RustPython/RustPython

parser/src/lexer.rs

(\u, \x and octals not supported.)

Add support for a escape sequence in string literals to lexer.

---

vm/src/import.rs

This allows modules to use builtins (such as print).  This fixes, for example, `cargo run -- -c 'import demo'`.
(Note that this is split in to two commits for easier reviewing; one changes the behaviour, and the second cleans up variable naming.)

 Use a scope (with builtins) for module import

---

parser/src/python.lalrpop

Allow Tests in function arguments (rather than just Expressions)

---

parser/src/lexer.rs
tests/snippets/strings.py

Implement triple-quotes for strings

---

tests/snippets/callables.py
vm/src/builtins.rs
vm/src/frame.rs
vm/src/objclass.rs
vm/src/pyobject.rs
vm/src/sysmodule.rs
vm/src/vm.rs

Implementing __call__ and then demoing the more interesting borrow_mut bug.

Callable 2

---

src/main.rs
tests/test_snippets.py
vm/src/builtins.rs
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/eval.rs
vm/src/import.rs
vm/src/sysmodule.rs
vm/src/vm.rs

Not the current working directory, which is the current behaviour.
Fixes #80.

Make imports relative to the importing file

---

vm/src/builtins.rs
vm/src/macros.rs
vm/src/objbool.rs
vm/src/objlist.rs
vm/src/stdlib/json.rs

This could be used in more places, but I wanted to get this PR up before I start work.

Introduce optional parameter support in arg_checks!

---

vm/src/bytecode.rs
vm/src/compile.rs
vm/src/vm.rs

The tuple constant will be used in my next kwargs branch, but I need to iterate on that a bit (whereas this is ready to merge and unblocks work on #105).

Add a tuple Constant (and fix some stack leakage)

---

tests/snippets/json_snippet.py
vm/src/pyobject.rs

Implement None == None

---

vm/src/bytecode.rs
vm/src/compile.rs
vm/src/exceptions.rs
vm/src/vm.rs

This should improve the usability of the exception mechanics.

Improve traceback of exception

---

tests/snippets/ast_snippet.py
vm/src/import.rs
vm/src/pyobject.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/mod.rs

This is an initial attempt at the ast builtin module. Comments or ideas are welcome!
Question I mostly have is how can you create classes in a module, and create instances of those classes.
Another topic is that I really feel a macro could come in handy here.

Initial attempt at ast builtin module

---

parser/src/parser.rs
parser/src/python.lalrpop
tests/snippets/assignment.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/vm.rs

First steps in this. Need to generalise to support other iterators not just tuples.

Assignment

---

vm/src/import.rs

This doesn't include any additional testing, because we can't currently modify `sys.modules` to test the caching (because we don't have the dict primitives).

Cache imported modules in sys.modules

---

parser/src/parser.rs
vm/src/compile.rs
vm/src/eval.rs
vm/src/import.rs
vm/src/obj/objsequence.rs
vm/src/obj/objstr.rs
vm/src/pyobject.rs
vm/src/stdlib/ast.rs
vm/src/vm.rs

Instead of allocated types, per [0].
[0] https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#ptr_arg

Accept slices to function calls

---

parser/src/ast.rs
parser/src/python.lalrpop
tests/snippets/with.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/vm.rs

This PR will add the with statement. The snippet is a simple example, and should pass.

With statement implementation

---

tests/snippets/builtin_abs.py
tests/snippets/builtin_divmod.py
vm/src/builtins.rs
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs
vm/src/vm.rs

Added abs and divmod built in functions and several methods on numeric types

Added builtins

---

tests/snippets/with.py
vm/src/compile.rs
vm/src/vm.rs

This is an attempt at handling exceptions within a context manager. I still feel there is something not quiet right here.

Add prototype of context manager handling during exceptions.

---

tests/snippets/import_name.py
tests/snippets/name.py
vm/src/builtins.rs
vm/src/import.rs

Adds `__name__` to scope. 
```bash
cargo run tests/snippets/name.py
```

Added name to scope

---

README.md
src/main.rs

My bad, I did not know it was on purpose :)

Restored the 5> in the repl prompt

---

tests/snippets/membership.py
vm/src/obj/objdict.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objstr.rs
vm/src/obj/objtuple.rs
vm/src/vm.rs

This PR brings the membership test for lists, strings, tuples, dicts and user defined objects.
I am pretty new to rust, so do no hesitate tell me if I do not follow usual good practices.

Basic membership implementation

---

tests/snippets/builtin_max.py
tests/snippets/builtin_min.py

Here is snippets for `min` and `max` testing most of the use case I could read in the python doc. Of course, they do not work yet :)
It could be a goal to reach for #152

max and min snippets

---

src/main.rs
tests/snippets/sysmod_argv.py
vm/src/sysmodule.rs

__Usage__:
```bash
> cargo run tests/snippets/sysmod_argv.py test
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/rustpython tests/snippets/sysmod_argv.py test`
['tests/snippets/sysmod_argv.py', 'test']
```

Adds args accessible via the sysmodule

---

vm/src/obj/objfloat.rs

Part of https://github.com/RustPython/RustPython/issues/166

Added __le__ for float

---

tests/snippets/builtin_bin.py
tests/snippets/builtin_hex.py
vm/src/builtins.rs

Implement `bin` and `hex` builtin functions

---

tests/snippets/floats.py
vm/src/obj/objfloat.rs

Part of https://github.com/RustPython/RustPython/issues/166

Added __ge__ to float

---

src/main.rs
tests/snippets/metaclasses.py
vm/src/builtins.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/obj/objbool.rs
vm/src/obj/objobject.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/vm.rs

This doesn't really work yet, because I'm running into my badly defined getattribute!
No test snippet yet either.

WIP - Specify metaclass and create class with correct type.

---

tests/snippets/class.py
vm/src/obj/objfunction.rs
vm/src/obj/objproperty.rs
vm/src/obj/objtype.rs
vm/src/vm.rs

type.__getattribute__ should be bound to type!

---

tests/snippets/subtraction.py
vm/src/obj/objint.rs
vm/src/vm.rs

Example of how to call attrs that exist.

Implement __sub__/__rsub__.

---

README.md

Hi @rmliddle, this is how the wasm build worked for me. Does it make sense or am I using npm in the wrong way?

Updated the wasm installation instruction

---

vm/src/vm.rs

This is to prevent code duplication. Based on https://github.com/RustPython/RustPython/pull/188

WIP: Added call_or_unsupported to vm.rs

---

.travis.yml

This travis config will build and deploy to the website repo. I'll setup the token in travis config

Auto build and deploy documentation to website repo

---

.travis.yml

@windelbouwman this should fix the python tests

Limit the gh-pages deployment step to only nightly build

---

wasm/app/index.html
wasm/app/index.js

I'll create submit another PR to make travis auto-update the page on gh-pages

Created a demo page so user can try their code online

---

wasm/app/index.html

Added fork me on github ribbon to demo page

---

.travis.yml
wasm/release.sh

I don't think Travis got everything it need, let me open a PR to test the build

CI build and deploy demo page on master branch

---

vm/src/obj/objstr.rs

I've added some of the missing methods, currently have isalnum, isnumeric, isdigit, title, swapcase, isalpha, replace, and center. The center method does center the string but I haven't found a way to fill in custom characters around it using format!() just yet

Added some of the missing str methods

---

tests/snippets/import.py
tests/snippets/import_star.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/pyobject.rs

This is a separate opcode in CPython so I added it as such here.

Add 'from x import *' syntax.

---

vm/src/stdlib/ast.rs
vm/src/stdlib/io.rs
vm/src/stdlib/json.rs
vm/src/stdlib/keyword.rs
vm/src/stdlib/pystruct.rs
vm/src/stdlib/re.rs
vm/src/stdlib/time_module.rs
vm/src/sysmodule.rs

Format module building in a more readable way

---

tests/snippets/list.py
vm/src/builtins.rs
vm/src/obj/objlist.rs

Also include IndexError in the __builtin__ module.

Add list.pop

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

Added the isdecimal method to the 'str' class

---

tests/snippets/bools.py
vm/src/obj/objbool.rs

This PR adds `bool.__doc__` with a test in tests/snippets/bools.py addressing #260.

Add bool.__doc__ (addresses #260)

---

tests/snippets/numbers.py
vm/src/obj/objint.rs

Adding int.__bool__ method

---

vm/src/exceptions.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs
vm/src/vm.rs

Separates os dependent builds to start to address the dependency related issues in #313

Factored OS Module for Windows Support, Unsafe Handling of Raw FileHandles and Descriptors

---

vm/src/exceptions.rs

Fix hierarchy or existing OS errors

Add OSError

---

tests/snippets/numbers.py
vm/src/obj/objint.rs

int type: Added __invert__

---

wasm/demo/src/index.html
wasm/lib/README.md
wasm/lib/src/lib.rs

Spellcheck

---

vm/src/obj/objobject.rs
vm/src/obj/objstr.rs
vm/src/obj/objtype.rs
vm/src/stdlib/math.rs

Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if

Fixed the 'collapsible_if' clippy warnings

---

vm/src/obj/objobject.rs

Added __doc__ atrribute for object

---

Cargo.lock
tests/snippets/builtin_range.py
vm/Cargo.toml
vm/src/lib.rs
vm/src/obj/objrange.rs

Add range.index

---

tests/snippets/numbers.py
vm/src/obj/objint.rs

 int type: Added __rxor__

---

vm/src/builtins.rs
vm/src/frame.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objdict.rs
vm/src/obj/objint.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objrange.rs
vm/src/obj/objset.rs
vm/src/obj/objstr.rs
vm/src/obj/objtuple.rs
vm/src/pyobject.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/io.rs
vm/src/stdlib/json.rs
vm/src/stdlib/os.rs
vm/src/stdlib/pystruct.rs
vm/src/sysmodule.rs
vm/src/vm.rs

There's a huge amount of repetition and work which can be made easy by moving the work inside new_int.

Eliminate repeated to bigint

---

vm/src/builtins.rs
vm/src/compile.rs
vm/src/format.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/obj/objbool.rs
vm/src/obj/objdict.rs
vm/src/obj/objlist.rs
vm/src/obj/objsequence.rs
vm/src/obj/objset.rs
vm/src/obj/objstr.rs
vm/src/obj/objtuple.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/io.rs
vm/src/vm.rs

Fixed various small clippy warnings

---

tests/snippets/builtin_range.py
vm/src/obj/objrange.rs

- Also fix range.index for negative steps
For #293

Add range.{__bool__, __contains__}

---

vm/src/obj/objbytearray.rs
vm/src/obj/objrange.rs
vm/src/stdlib/json.rs
vm/src/vm.rs

Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#if_same_then_else

Fix the 'if_same_then_else' clippy warnings

---

vm/src/dictdatatype.rs

This is an implementation of the dictionary datatype as is implemented in CPython and pypy.
Its not yet used in the code. This is another challenge.

Add dict data type.

---

tests/snippets/builtin_slice.py
vm/src/builtins.rs
vm/src/frame.rs
vm/src/obj/mod.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objrange.rs
vm/src/obj/objsequence.rs
vm/src/obj/objslice.rs
vm/src/obj/objstr.rs
vm/src/pyobject.rs

I have also made the following changes:
- Made slice payload to use big ints 
- Change return type of PySliceableSequence::get_pos to return None on out of bounds
- Remove unnecessary cloning of BigInt in RangeType::get
- Implement negative step handling

Add slice type

---

tests/snippets/builtin_divmod.py
tests/snippets/division_by_zero.py
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs

fix floordiv and divmod by zero for ints and floats

---

tests/snippets/set.py
vm/src/obj/objset.rs

This PR add comparison operations to set object.

Add set.{__eq__,__gt__,__ge__,__le__,__lt__,issubset,issuperset}

---

tests/snippets/membership.py
vm/src/obj/objbytes.rs

Add bytes.{__ge__, __gt__, __le__, __lt__}

---

vm/src/builtins.rs
vm/src/frame.rs
vm/src/obj/objdict.rs
vm/src/stdlib/json.rs
vm/src/sysmodule.rs

This implements some trivial refactors to prepare for proper dictionaries.

Change to more usage of VirtualMachine in anticipation of proper dicts

---

vm/src/exceptions.rs

Fixing assert second argument formatting

---

.travis.yml

added cargo clippy to travis

---

vm/src/vm.rs

I botched this in #433. :sweat_smile:

Fix typo in VirtualMachine::_and

---

tests/snippets/list.py
vm/src/obj/objlist.rs
vm/src/vm.rs

The `match` is quite messy with some `BigInt` to/from `usize` conversion. Any suggestion on how to make it more readable is very welcome.

Implemented list.insert()

---

src/main.rs

Replaced cluttered match statements with if let

---

tests/snippets/set.py
vm/src/obj/objset.rs

This add set.{union,intersection,difference,symmetric_difference}

Add set.{union,intersection,difference,symmetric_difference}

---

vm/src/compile.rs
vm/src/eval.rs

Remove return, use function without closure

---

parser/src/ast.rs
parser/src/parser.rs
tests/snippets/fstrings.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/stdlib/ast.rs

- Converts f-string parser to a state machine to make easier to reason about
- Adds support for format specs

Support format specs in f-strings

---

tests/snippets/builtin_enumerate.py
tests/snippets/list.py
vm/src/obj/objlist.rs

I'm trying implement remove method to `list`. For now my code find the element and remove it. But I don't know how handle when element not exists in the list. I'm new in the rust so can you please help me?

Add remvoe to list object

---

azure-pipelines.yml
tests/snippets/os_info.py

Add Windows CI via Azure Pipelines

---

.travis.yml
README.md
tests/.travis-runner.sh
tests/test_snippets.py

Attempt to bring code coverage

Code coverage for RustPython

---

parser/src/python.lalrpop
tests/snippets/decorators.py

Allow attributes to be used as decorators

---

tests/.travis-runner.sh
tests/snippets/inplace_ops.py
tests/snippets/list.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/obj/objlist.rs
vm/src/vm.rs

Support magic methods for in-place operations

---

README.md
vm/src/stdlib/io.rs

README: Added Azure Build Badge, Disclaimer 
IO: Minor Changes to Inheritance to follow [CPython](https://docs.python.org/3/library/io.html).

Readme Update + Inheritance Fix on IO

---

Cargo.toml
parser/Cargo.toml
parser/build.rs
parser/src/error.rs
parser/src/lexer.rs
parser/src/lib.rs
parser/src/parser.rs
py_code_object/Cargo.toml
py_code_object/python_compiler/Cargo.toml
vm/Cargo.toml
vm/src/import.rs
vm/src/stdlib/random.rs
vm/src/sysmodule.rs
wasm/lib/Cargo.toml

The following command was used from the project root for the migration:
```shell
$ cargo fix --all --edition-idioms --allow-dirty
```

Migrated the project to the Rust 2018 edition

---

tests/snippets/bytearray.py
vm/src/obj/objbytearray.rs

Also I fixed the bug with checking if bytearray is lower. The function `bytearray.islower()` returns alway true.

Add bytearray.{lower, upper}

---

tests/snippets/builtin_complex.py
vm/src/obj/objcomplex.rs
vm/src/obj/objint.rs

Adds the option to add complex number to ints, and also to create a new complex number just by
```
cmplx = 1 + 1j
```
instead of
```
cmplx = Complex(1, 1)
```

Complex and ints addition

---

tests/snippets/set.py
tests/snippets/testutils.py

As commented by @OddBloke and @windelbouwman  in #524

Add assertRaises context manager to testutils

---

tests/snippets/floats.py
vm/src/obj/objfloat.rs

Yet another two small and obscure additions to the float type.

Addred real property and is_integer function to float.

---

vm/src/bytecode.rs
vm/src/compile.rs
vm/src/error.rs

fix invalid break continue return yield

---

parser/src/lexer.rs

add lexer error

---

Cargo.lock
wasm/demo/src/main.js
wasm/lib/Cargo.toml
wasm/lib/src/browser_module.rs
wasm/lib/src/wasm_builtins.rs

Update the snippet on page load; insert spaces when tab is pressed.

Quality of life improvements for the demo.

---

tests/snippets/stdlib_socket.py
vm/src/stdlib/socket.rs

- socket.recv read amount of bytes asked
- Add validation to connect and bind address

Socket improvments

---

tests/snippets/getframe.py
vm/src/frame.rs
vm/src/obj/objframe.rs
vm/src/obj/objgenerator.rs
vm/src/pyobject.rs
vm/src/sysmodule.rs
vm/src/vm.rs

Finally think I've got this solved.
I've moved the mutability inside Frame using RefCell, and all need from mutable frames goes away. super should be easy enough now.

Framestack 2

---

wasm/lib/src/vm_class.rs

I'm not really sure about having it always be the same objects b/c they're created and stored outside the closure, but it seemed better than calling `self.with()` from the inside.

Add an `injectModule` method to WASMVirtualMachine

---

wasm/example/src/main.py

Use alert() for the WASM example crate

---

vm/src/pyobject.rs
vm/src/stdlib/socket.rs

pyobject.rs should not depend on stdlib module.

 Use PyObjectPayload::AnyRustValue for socket

---

vm/src/dictdatatype.rs
vm/src/macros.rs
vm/src/stdlib/io.rs
vm/src/stdlib/re.rs

It feels strange that I, after disliking some macros, now introduce a new macro. Well, you learn from your fellow developers! Thanks!

Introduce py_class macro to define classes.

---

tests/snippets/stdlib_socket.py
vm/src/stdlib/socket.rs

Add support in UDP for socket module. 
Also fixed the addr return in TCP accept on the way. Hope that is OK if not I will split to a different PR.

Socket UDP

---

vm/src/obj/objbool.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objfloat.rs
vm/src/obj/objiter.rs
vm/src/obj/objrange.rs
vm/src/pyobject.rs
vm/src/stdlib/io.rs

Convert more objects to `Any` payload

---

tests/snippets/builtin_dir.py
vm/src/obj/objtype.rs

This should fix the problem in #482.

Fix module dir

---

Cargo.lock
Cargo.toml
wasm/lib/README.md

Based on some discussion on the gitter.

Prepare the wasm crate for publishing on npm

---

parser/src/ast.rs
parser/src/parser.rs
parser/src/python.lalrpop
tests/snippets/type_hints.py
vm/src/compile.rs
vm/src/stdlib/ast.rs

First of a series of changes to support type annotations.

Add type annotations to parser.

---

vm/src/obj/objbytearray.rs

Bytearray hex formatting

---

vm/src/function.rs
vm/src/obj/objstr.rs

Mostly skipped the ones dealing with ints.

Convert a bunch of string methods to new-args-style.

---

tests/snippets/dict.py
vm/src/obj/objdict.rs

This implementation should be OK after changing the hashmap to use __hash__ ask key.
This is not yet in compliance with python as this is not a [dict view](https://docs.python.org/3.5/library/stdtypes.html?highlight=keys#dict-views).

Add dict.{keys,values,items}

---

vm/src/builtins.rs
vm/src/obj/objfilter.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/vm.rs
wasm/lib/src/browser_module.rs

implemented a From trait for PyFuncArgs, which helps in less verbose function calling.

Less explicit PyFuncArgs is better.

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

Also support out-of-range start/end params for some functions, and fixed some return values.

Convert most remaining string methods to implicit args

---

vm/src/obj/objdict.rs
vm/src/obj/objobject.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/vm.rs

Building on top of my other branch to avoid conflicting with myself.

Add PyClass.

---

vm/src/obj/objmodule.rs
vm/src/pyobject.rs
vm/src/vm.rs

This is the last of these I'm planning to do, btw.
I think there's another step in using PyList to construct automatically convert the list of elements into a python list that I couldn't figure out (return value of dir).

Replace PyObjectPayload::Module with PyModule.

---

vm/src/frame.rs
vm/src/obj/mod.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objframe.rs
vm/src/obj/objfunction.rs
vm/src/obj/objgenerator.rs
vm/src/pyobject.rs
vm/src/vm.rs

Convert function, method, builtin_*, frame, and generator to Any payload

---

vm/src/frame.rs
vm/src/obj/mod.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objbytes.rs
vm/src/obj/objdict.rs
vm/src/obj/objframe.rs
vm/src/obj/objfunction.rs
vm/src/obj/objgenerator.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objmemory.rs
vm/src/obj/objrange.rs
vm/src/obj/objsequence.rs
vm/src/obj/objset.rs
vm/src/obj/objslice.rs
vm/src/obj/objstr.rs
vm/src/obj/objtuple.rs
vm/src/pyobject.rs
vm/src/vm.rs

Based on #645 to avoid conflicts.

Convert memoryview and slice to Any payload

---

vm/src/obj/objstr.rs

add __doc__ to str

---

wasm/demo/package.json
wasm/demo/src/index.ejs
wasm/demo/src/index.js
wasm/demo/src/main.js

Add interactive shell to WASM demo

---

vm/src/stdlib/ast.rs
vm/src/stdlib/dis.rs
vm/src/stdlib/io.rs
vm/src/stdlib/json.rs
vm/src/stdlib/keyword.rs
vm/src/stdlib/math.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/os.rs
vm/src/stdlib/platform.rs
vm/src/stdlib/pystruct.rs
vm/src/stdlib/random.rs
vm/src/stdlib/re.rs
vm/src/stdlib/socket.rs
vm/src/stdlib/string.rs
vm/src/stdlib/time_module.rs
vm/src/stdlib/tokenize.rs
vm/src/stdlib/types.rs
vm/src/stdlib/weakref.rs
vm/src/sysmodule.rs
vm/src/vm.rs
wasm/lib/src/browser_module.rs

Rename mk_module to make_module.

---

wasm/demo/snippets/mandelbrot.py

I added a yield in the inner `x` loop, which removes *all* stuttering during the mandelbrot generation, but I'm also concerned that it may be too slow. Should it yield conditionally, or is it fine with one character at a time?

Use a generator for the mandelbrot demo snippet

---

tests/snippets/import.py
vm/src/builtins.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/vm.rs
wasm/lib/src/browser_module.rs
wasm/lib/src/convert.rs

I will add the builtin module as well so I can test overriding the `__import__`.

Add __import__

---

tests/snippets/property.py
vm/src/obj/objnone.rs
vm/src/obj/objproperty.rs
vm/src/pyobject.rs

Adds the following attributes/methods to property:
- fget
- fset
- fdel
- getter
- setter
- deleter

Implement property attributes and functions

---

vm/src/pyobject.rs

As discussed in #674.
My plan is:
* eliminate PyRef::new*
* move all/most calls to PyObject::new(...) to this interface.
* use this narrow interface to solve the which objects get attributes problem.
Pushing this push first to make sure we agree on the interface.

Py value into ref

---

vm/src/function.rs

Fixes bug found by @adrian17 
A function defined as:
```rust
fn list_sort(zelf: PyListRef, kwargs: KwArgs, vm: &mut VirtualMachine) -> PyResult {
```
was allowing: `[].sort(True)`
It is now rejected.

Handle unexpected positional argument in KwArgs

---

vm/src/function.rs

`FromArgs` currently takes an iterator of `PyArg`s, rather than having full access to `PyFuncArgs`. This isn't really necessary and is just unneeded complexity, so this removes it.

FromArgs: use PyFuncArgs instead of iterator

---

tests/snippets/class.py
vm/src/obj/objsuper.rs

Allow super to work in class methods.
I am not sure how fragile using "self" is but feel free to suggest something else.

super in class methods

---

vm/src/obj/objenumerate.rs
vm/src/obj/objgenerator.rs
vm/src/obj/objlist.rs
vm/src/obj/objmap.rs
vm/src/obj/objset.rs
vm/src/obj/objtuple.rs
vm/src/vm.rs

Continuing my project to refactor away direct use of PyObject.

More pyobject

---

vm/src/stdlib/json.rs
vm/src/stdlib/mod.rs
vm/src/vm.rs
wasm/lib/src/convert.rs

For some reason it was panicking when trying to import `json.{dumps,loads}`, so I just switched to using plain rust functions straight from `json.rs`.

Fix the WASM build

---

tests/snippets/attr.py
tests/snippets/property.py
vm/src/obj/objobject.rs
vm/src/obj/objproperty.rs

Also fixed property.__get__ owner parameter not being optional.

Implement calling __set__ and __delete__ magic methods

---

src/main.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/obj/objclassmethod.rs
vm/src/obj/objstaticmethod.rs
vm/src/stdlib/io.rs
vm/src/stdlib/re.rs
vm/src/sysmodule.rs
vm/src/vm.rs

First batch of my big change (breaking it up a bit for review friendliness).

Avoid attribute protocol

---

vm/src/import.rs

There is a format problem in master

Fix format

---

tests/snippets/class.py
vm/src/frame.rs
vm/src/obj/objsuper.rs

@windelbouwman already merged the previous PR but lets continue the discussion here. What do you guys think about this solution @coolreader18 @adrian17?

Use first argument in super

---

src/main.rs

Edit: this would resolve #626.

Make the REPL handle line continuation better

---

vm/src/obj/objbool.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objcode.rs
vm/src/obj/objcomplex.rs
vm/src/obj/objellipsis.rs
vm/src/obj/objenumerate.rs
vm/src/obj/objframe.rs
vm/src/obj/objlist.rs
vm/src/obj/objmemory.rs

This further increases the usage of the extend_class macro. This should help in refactoring set_attr.

Increase usage of extend_class macro.

---

src/main.rs
vm/src/builtins.rs
vm/src/compile.rs
vm/src/eval.rs
vm/src/function.rs
vm/src/import.rs
vm/src/obj/objcode.rs
vm/src/obj/objfilter.rs
vm/src/obj/objfloat.rs
vm/src/obj/objmemory.rs
vm/src/obj/objobject.rs
vm/src/obj/objproperty.rs
vm/src/obj/objsequence.rs
vm/src/obj/objslice.rs
vm/src/obj/objtype.rs
vm/src/obj/objzip.rs
vm/src/pyobject.rs
vm/src/stdlib/re.rs
vm/src/vm.rs
wasm/lib/src/browser_module.rs
wasm/lib/src/convert.rs
wasm/lib/src/vm_class.rs

To do this I replaced a few PyObject::new with PyValue::{into_ref, into_ref_with_type}.

Change PyObject.typ to PyClassRef

---

tests/snippets/types_snippet.py
vm/src/obj/objmodule.rs
vm/src/obj/objnone.rs
vm/src/obj/objobject.rs
vm/src/obj/objtuple.rs
vm/src/obj/objtype.rs
vm/src/obj/objweakref.rs
vm/src/pyobject.rs

Wanted to get a feel of the Weak stuff.

Type __subclasses__()

---

vm/src/stdlib/json.rs
vm/src/vm.rs

A couple more bits of dictionary clean up.

More dict cleanup

---

parser/src/ast.rs
parser/src/parser.rs
parser/src/python.lalrpop
tests/snippets/ast_snippet.py
tests/snippets/comparisons.py
vm/src/compile.rs
vm/src/stdlib/ast.rs

(the compiled bytecode is pretty much exactly the same as in CPython.)

Support chained comparisons

---

vm/src/macros.rs
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs
vm/src/obj/objstr.rs

See #771 for more details and discussion.

Add match_class! macro

---

vm/src/obj/objrange.rs

I underestimated my dislike of `Either`. This feels much nicer.

Add and use a RangeIndex type instead of Either

---

vm/src/frame.rs
vm/src/obj/objdict.rs
vm/src/obj/objmodule.rs
vm/src/pyobject.rs
vm/src/stdlib/json.rs
wasm/lib/src/browser_module.rs

First batch of small refactors left over after the big dictionary change.

Dict cleanup

---

tests/snippets/stdlib_os.py
vm/src/obj/objbytes.rs
vm/src/stdlib/os.rs

The test should be changed to create the file in some temp folder once we add `tempfile`. In case anyone has a simpler idea that will be more safe please suggest.

Add os.{read,write,remove,unlink}

---

vm/src/dictdatatype.rs

This is in preparation for using this to back set too.

Parameterise dictdatatype::Dict by value type.

---

tests/snippets/function_args.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/obj/objfunction.rs
vm/src/pyobject.rs
vm/src/vm.rs

Also, exposes the `__defaults__` and `__kwdefaults__` attributes on functions.

Implement keyword only argument defaults

---

vm/src/obj/objint.rs
vm/src/obj/objrange.rs
vm/src/obj/objstr.rs

First round of refactors after https://github.com/RustPython/RustPython/pull/799

int, str, range: take self by shared reference

---

tests/snippets/set.py
vm/src/obj/objset.rs

As suggested by @OddCoincidence in #765. I used `match_class` macro to avoid unwanted clones.

refactor objset using inner

---

tests/snippets/dict.py

Cleanup dict test snippet

---

tests/snippets/list.py
vm/src/obj/objlist.rs

what it says on the tin.
saw #766 and realized that this code had the same problem.

fix error related to #746 but for list.__delitem__

---

vm/src/function.rs
wasm/lib/src/vm_class.rs

Let's hope the checks go fine now.

Drop IntoPyNativeFunc impl to fix Nightly/Beta breakages.

---

parser/src/lexer.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/function.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objdict.rs
vm/src/obj/objint.rs
vm/src/obj/objrange.rs
vm/src/obj/objset.rs
vm/src/obj/objslice.rs
vm/src/obj/objsuper.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/stdlib/os.rs

Hopefully, both the rustfmt and clippy CI tasks will now pass.

Update code format and fix some clippy warnings

---

src/main.rs

I missed these usages of syntax error when I created `vm.new_syntax_error` function in #829.

Use new_syntax_error in main.rs

---

tests/snippets/global_nonlocal.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs

@cthulahoops I'm a bit confused about the load_cell name. Is it the same as the load_deref opcode in cpython?

Add nonlocal support.

---

Lib/os.py
tests/snippets/stdlib_os.py

This should allow us to extend filesystem tests.

 Use temp directory for os test

---

Cargo.lock
Cargo.toml
benchmarks/bench.rs
benchmarks/benchmarks/mandelbrot.py
benchmarks/benchmarks/minidom.py
benchmarks/benchmarks/nbody.py

Add benches

---

tests/snippets/stdlib_socket.py
vm/src/stdlib/socket.rs

I don't have a windows machine so I will test it using the CI.

Socket.fileno

---

src/main.rs
tests/snippets/dir_main/__main__.py

I tested this code by running `cargo run tests/snippets/dir_main` but no idea how to integrate it into current test system. Any idea?

Add __main__.py support

---

tests/snippets/math_basics.py
tests/snippets/math_module.py
vm/src/stdlib/math.rs

Add trunc, ceil, floor to math module

---

tests/snippets/try_exceptions.py
vm/src/bytecode.rs
vm/src/compile.rs
vm/src/frame.rs
vm/src/vm.rs

This resolves #867 and resolves [#837](https://github.com/RustPython/RustPython/pull/831#discussion_r275260542)

 Add exceptions stack to VirtualMachine

---

tests/snippets/builtin_range.py
vm/src/obj/objrange.rs

Fix range() to support negative index + Add range.__eq__

---

Lib/stat.py
tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs

- Add `DirEntry.stat`.
- Add Cpython `Lib/stat.py`
- Add tests for stat mode.

Extend os.stat

---

tests/snippets/builtin_complex.py
vm/src/obj/objcomplex.rs
vm/src/obj/objfloat.rs

Adding `__rmul__`, `__*div__`, `__*mod__`, `__[r]pow__`

PyComplex extend_class, uniform operand handling, missing methods + Complex64 IntoPyObject

---

tests/snippets/printing.py
vm/src/builtins.rs

Print file parameter

---

tests/snippets/bools.py
vm/src/obj/objbool.rs
vm/src/obj/objint.rs

Add bool methods

---

src/main.rs
vm/src/compile.rs

for #908 
I didn't handle the multiple expression case mentioned there.
Also, possibly not every Single-mode compilation should be returning expressions

Repl underscore

---

parser/src/ast.rs
parser/src/lexer.rs
parser/src/python.lalrpop
parser/src/token.rs
tests/snippets/test_async_stuff.py
vm/src/compile.rs
vm/src/stdlib/ast.rs
vm/src/symboltable.rs

The start of a debated syntax :)

Add async def and async for parsing.

---

tests/snippets/delete.py
vm/src/frame.rs
vm/src/vm.rs

Nameerror on bad del

---

tests/snippets/bytearray.py
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs

same thing as byte except a little change in partition/rpartition due to cpython "strange"  behaviour

add split, rsplit, partition, rpartition, expandtabs, spitlines, zfill,replace to bytearray

---

tests/snippets/bytearray.py
tests/snippets/bytes.py
vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs

More bytearray methods

---

tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs

os.{getcwd,chdir}

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs
vm/src/stdlib/mod.rs

After https://github.com/RustPython/RustPython/pull/948

Itertools repeat

---

benchmarks/bench.rs
src/main.rs
tests/snippets/builtins_module.py
vm/src/builtins.rs
vm/src/eval.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/pyobject.rs
vm/src/vm.rs
wasm/lib/src/vm_class.rs

This feature allows to expand `__builtins__` for program-global

Add __builtins__ to globals()

---

tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs

Add st_{a,m,c}time to os.stat

---

tests/snippets/strings.py
vm/src/builtins.rs
vm/src/function.rs
vm/src/obj/objstr.rs

Accept tuple for first arg in str.startswith and str.endswith

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

After https://github.com/RustPython/RustPython/pull/949

Itertools takewhile

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

Required for `Lib/collections/__init__.py`.

Add `itertools.starmap`

---

Lib/types.py
tests/snippets/stdlib_types.py
tests/snippets/sysmod.py
vm/src/macros.rs
vm/src/obj/mod.rs
vm/src/obj/objnamespace.rs
vm/src/pyobject.rs
vm/src/sysmodule.rs

Add SimpleNamespace and sys.implementation

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

Required for `Lib/collections/__init__.py`.

Add `itertools.chain`

---

Cargo.lock
tests/snippets/function_args.py
vm/Cargo.toml
vm/src/frame.rs
vm/src/function.rs
vm/src/pyobject.rs
wasm/lib/src/convert.rs

https://www.python.org/dev/peps/pep-0468/
Revives https://github.com/RustPython/RustPython/pull/560

Move PyFuncArgs.kwargs to IndexMap, implement PEP-468

---

tests/snippets/builtin_dir.py
vm/src/builtins.rs

Fix no-arg dir(), convert it to new args style

---

tests/snippets/stdlib_io.py
vm/src/stdlib/io.rs

This should be enough for #958.

RawIOBase inherits IOBase

---

Lib/reprlib.py

After https://github.com/RustPython/RustPython/pull/969

Lib reprlib

---

derive/src/lib.rs
derive/src/pyclass.rs
tests/snippets/sysmod.py
vm/src/obj/objtuple.rs
vm/src/sysmodule.rs

For #958. For this, I created a `pystruct_sequence` proc macro as there are quite a few of these 'struct sequences' throughout the c part of the standard library.

Add sys.flags

---

src/main.rs
vm/src/frame.rs
vm/src/stdlib/binascii.rs
vm/src/symboltable.rs
vm/src/vm.rs

Some cleanups, renames and typo fixes I've made in process of reading the codebase. I think they make code a bit easier to read.

Some cleanups and typo fixes

---

tests/snippets/strings.py
vm/Cargo.toml
vm/src/obj/objstr.rs

Implement `isprintable` function of `str` object

str.isprintable

---

Cargo.lock
tests/snippets/stdlib_os.py
vm/Cargo.toml
vm/src/builtins.rs
vm/src/exceptions.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs

I did not yet fixed the support in `FileIo` flags but I will do that at later stage.

Support more open flags

---

vm/src/obj/objstr.rs

Remove a mistakenly commited debug print

---

derive/src/pyclass.rs

This was something I added for #1039 but took out of that PR because it wasn't necessary anymore. I figured I'd make a PR for this, since we do have at least one classmethod in the codebase (`dict.fromkeys`).

Add #[pyclassmethod] to #[pyimpl]

---

tests/snippets/builtin_ord.py
vm/src/builtins.rs

add bytearray and bytes input types for ord()

---

vm/src/builtins.rs
vm/src/exceptions.rs

Also needed for enabling `.pyc` files

Add EOFError

---

tests/snippets/test_struct.py
vm/src/stdlib/pystruct.rs

xdrlib works now locally, but I first would like to merge this change to the struct module.

Add endianness support to struct module.

---

tests/snippets/tuple.py
vm/src/obj/objtuple.rs

Add tuple.__rmul__ and uncomment test snippet of __rmul__.

Add tuple.__rmul__

---

tests/snippets/sysmod.py
vm/src/sysmodule.rs

sys.byteorder: Implement sys.byteorder

---

tests/snippets/memoryview.py
vm/src/obj/objmemory.rs

memoryview support `__getitem__`

Memoryview slice

---

compiler/src/bytecode.rs
compiler/src/compile.rs
parser/src/ast.rs
parser/src/python.lalrpop
vm/src/frame.rs

As talked about in #1050 ([comment](https://github.com/RustPython/RustPython/pull/1050#discussion_r296472862))

Calculate import level at parsing

---

tests/snippets/builtin_complex.py
vm/src/obj/objcomplex.rs

Fix complex representation for negative imaginary number case.

---

bytecode/src/bytecode.rs
compiler/src/compile.rs
compiler/src/error.rs
parser/src/lexer.rs
vm/src/frame.rs
vm/src/stdlib/ast.rs
vm/src/vm.rs
wasm/lib/src/vm_class.rs

Change get_row() into row()

---

Cargo.lock
Cargo.toml
bytecode/Cargo.toml
compiler/Cargo.toml
derive/Cargo.toml
parser/Cargo.toml
parser/src/parser.rs
src/main.rs
vm/Cargo.toml
vm/src/builtins.rs
vm/src/import.rs
vm/src/lib.rs
vm/src/stdlib/mod.rs
vm/src/vm.rs
wasm/lib/Cargo.toml

Update authors field and package name in cargo.toml files.

Underscore2hyphen

---

src/main.rs
vm/src/import.rs
wasm/lib/src/vm_class.rs
wasm/lib/src/wasm_builtins.rs

We should change `browser_load_module` later as well.

Use importlib import in WASM

---

Cargo.lock
compiler/src/error.rs
compiler/src/symboltable.rs
parser/Cargo.toml
parser/src/ast.rs
parser/src/error.rs
parser/src/fstring.rs
parser/src/lexer.rs
parser/src/lib.rs
parser/src/location.rs
parser/src/python.lalrpop

This improves error messages coming from f-string parsing.
Also grouped all error types into the `error.rs` file, and created a `location.rs` file.

parser error handling improvements.

---

tests/snippets/exceptions.py
tests/snippets/json_snippet.py

make exceptions repr tests Python 3.7-friendly by eval-repr round-trip

---

.gitignore
Cargo.lock
Cargo.toml
src/main.rs
vm/Cargo.toml
vm/src/frame.rs
vm/src/import.rs
vm/src/lib.rs
vm/src/macros.rs
vm/src/pyobject.rs
vm/src/vm.rs

This is just an initial change to get the ball rolling for flame profiling, we can add more scopes later.

Add flamegraph profiling using flame and flamer

---

tests/snippets/try_exceptions.py
vm/src/frame.rs
vm/src/vm.rs

Fix exception stack

---

Lib/logging/__init__.py
Lib/logging/config.py
Lib/logging/handlers.py
Lib/traceback.py
vm/src/dictdatatype.rs
vm/src/obj/objdict.rs

Add logging and traceback python modules.

Add default argument to dict.pop. 

---

tests/snippets/test_logging.py
vm/src/obj/objframe.rs

Things to note:
- the traceback is difficult, since `f_back` is not working properly. @cthulahoops maybe you could have a look at the `f_back` operation?
- `sys.stderr` is not implemented. How should we tackle this?

Add testcase for logging module.

---

tests/snippets/builtin_range.py
vm/src/obj/objrange.rs

Implemented range methods lt, gt, le, ge

---

crawl_sourcecode.py
parser/src/ast.rs
parser/src/python.lalrpop
vm/src/stdlib/ast.rs

Add script to walk over AST of sourcecode.

Implement more nodes in the ast.

---

tests/snippets/sysmod.py
vm/src/sysmodule.rs

Currently without the traceback. I am not yet sure what to return there.

Add sys.exc_info

---

bytecode/src/bytecode.rs
compiler/src/compile.rs
compiler/src/symboltable.rs
parser/src/ast.rs
parser/src/python.lalrpop
vm/src/frame.rs
vm/src/stdlib/ast.rs

This does not yet account for the triple dot, but aligns the import AST nodes with cpython.

Simplify import AST in line with CPython.

---

vm/src/obj/objlist.rs
vm/src/pyobject.rs

Hello
This is my first time performing a pull request. I would appreciate any comments or advice.

Implemented list.__reversed__

---

vm/src/obj/objlist.rs

Implemented list.__rmul__

---

parser/src/lexer.rs

Since the REPL uses a check on end of file, my previous change broke the continuation function of the REPL. This change improves the lexer a tiny bit in that it does not emit extra newlines when this is not required.

Minor tweak on lexer to fix the REPL.

---

tests/snippets/ints.py
vm/src/obj/objint.rs

Adds properties to int objects:
- `numerator`
- `denominator`

Add int ratio properties

---

src/main.rs
vm/src/import.rs
vm/src/sysmodule.rs
vm/src/vm.rs

As talked about in #1090. This uses the git hash and not a hash of the only the bytecode but I will leave that for later stage.

Write bytecode

---

tests/snippets/strings.py
vm/src/obj/objstr.rs
vm/src/pyobject.rs

Hello,
I added iteration support for ```str```.

Implement str iterator support

---

tests/snippets/builtin_ascii.py
vm/src/builtins.rs

Implement builtin ascii API
close: #1179

builtins: Implement ascii builtin API

---

tests/snippets/builtin_ascii.py
vm/src/builtins.rs

Some range of Unicode characters should be specially handled

builtin: Fix hex format of ascii

---

Cargo.lock
tests/snippets/stdlib_os.py
vm/Cargo.toml
vm/src/builtins.rs
vm/src/stdlib/os.rs

os.getpid  [RUST STD]
os.getegid [UNIX]
os.getgid  [UNIX]
os.getsid  [UNIX]
os.getuid  [UNIX]
os.geteuid [UNIX]
os.getppid [UNIX]
os.getpgid [UNIX]
os.setgid  [UNIX]
os.setegid [UNIX]
os.setpgid [UNIX]
os.setuid  [UNIX]
os.seteuid [UNIX]

Implement several methods - os module

---

.travis.yml

https://travis-ci.community/t/skipping-a-deployment-with-the-pages-provider-because-this-branch-is-not-permitted/4493

Fix deployment

---

vm/src/stdlib/signal.rs

Fix signal on macos

---

Cargo.lock
tests/snippets/stdlib_socket.py
vm/Cargo.toml
vm/src/stdlib/mod.rs
vm/src/stdlib/os.rs
vm/src/stdlib/socket.rs

For #1176 Add socket method gethostname sethostname inet_aton . 
The convert_nix_error method is a common method, maybe it should be moved to exceptions.rs.

Extend Socket module

---

Cargo.lock
tests/snippets/stdlib_subprocess.py
vm/Cargo.toml
vm/src/stdlib/io.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/subprocess.rs

In CPython subprocess is actually a pure python lib that uses `os` functions but I think the [subprocess](https://docs.rs/subprocess/0.1.18/subprocess/index.html) library in rust fits better here.

Add subprocess

---

Lib/argparse.py
Lib/textwrap.py
src/main.rs
tests/snippets/generators.py
vm/src/builtins.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/function.rs
vm/src/obj/objstr.rs
vm/src/obj/objtype.rs
vm/src/stdlib/re.rs
vm/src/sysmodule.rs
vm/src/vm.rs

What's preventing `rustpython -m unittest.__main__` from working now is `sys.std{out,in,err}`, which I believe @yanganto is working on.

Fix a bunch of problems with getting argparse to actually work

---

compiler/src/compile.rs
compiler/src/symboltable.rs
examples/parse_folder.rs
parser/src/ast.rs
parser/src/lexer.rs
parser/src/parser.rs
parser/src/python.lalrpop
tests/snippets/assignment.py
tests/snippets/generators.py
vm/src/scope.rs
vm/src/stdlib/ast.rs

- Simplify grammar for comprehensions.
- Add capital J suffix for complex numbers.

Add variable annotation syntax.

---

tests/snippets/bools.py
vm/src/obj/objbool.rs

Fix pyobject truth value

---

tests/snippets/stdlib_subprocess.py
vm/src/obj/objbytes.rs
vm/src/obj/objtuple.rs
vm/src/stdlib/os.rs
vm/src/stdlib/subprocess.rs

Add Popen.{terminate, kill, communicate, pid}

Extend subprocess.Popen

---

bytecode/src/bytecode.rs
compiler/src/compile.rs
compiler/src/symboltable.rs
parser/src/ast.rs
parser/src/python.lalrpop
tests/snippets/short_circuit_evaluations.py
vm/src/frame.rs
vm/src/stdlib/ast.rs

This implements the boolean short circuit logic in line with cpython and micropython.

Improve the situation regarding boolean operations.

---

compiler/src/compile.rs
compiler/src/symboltable.rs
tests/snippets/function.py

gh-1212: Fix scope_for_name to catch NameError properly

---

.travis.yml
Cargo.toml
redox/comment-cargo.sh
redox/recipe.sh
redox/uncomment-cargo.sh
vm/src/stdlib/os.rs
vm/src/stdlib/socket.rs

[Redoxer](https://gitlab.redox-os.org/redox-os/redoxer/)

Add Redox OS compilation to Travis using Redoxer

---

compiler/src/compile.rs
compiler/src/symboltable.rs
crawl_sourcecode.py
vm/src/stdlib/symtable.rs

- Renamed SymbolScope to SymbolTable
- Add proper detection of a local variable

Improve symbol table processing.

---

README.md

Closes #1190 
Added commands to assist Python developers who are new to Rust.

Add minimal version and document check/update to README

---

Cargo.lock
vm/Cargo.toml
vm/src/stdlib/os.rs

Hi, I just implemented stdlib 'os.cpu_count()'.

Implemented stdlib function 'os.cpu_count()'

---

tests/snippets/stdlib_socket.py
vm/src/stdlib/socket.rs

For #1176
Add socket method htonl.

Impl socket htonl

---

vm/src/stdlib/os.rs

this fixes broken pytest on macos, which failed on `os.path.realpath(tmpdir)`

implement os.readlink()

---

tests/snippets/json_snippet.py
vm/src/stdlib/json.rs

Hello.
I am new for rust python.
I have added `json_dump` method. But it works only for StringIO.
Could you give me some advice? (Other IO,, what else)

Add `json.dump` and `json.load`

---

src/main.rs
vm/src/builtins.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/obj/objbool.rs
vm/src/obj/objdict.rs
vm/src/obj/objfilter.rs
vm/src/obj/objfloat.rs
vm/src/obj/objfunction.rs
vm/src/obj/objint.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objmap.rs
vm/src/obj/objnone.rs
vm/src/obj/objobject.rs
vm/src/obj/objproperty.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/stdlib/io.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/math.rs
vm/src/stdlib/signal.rs
vm/src/stdlib/thread.rs
vm/src/vm.rs
wasm/lib/src/browser_module.rs
wasm/lib/src/convert.rs

Fixes this [TODO](https://github.com/RustPython/RustPython/blob/master/vm/src/vm.rs#L526)

Make func_ref an &PyObjectRef

---

tests/snippets/builtin_complex.py
vm/src/obj/objcomplex.rs

complex: Implement __getnewargs__

---

tests/snippets/ellipsis.py
vm/src/obj/objellipsis.rs

Resolves #1254 
Add `__reduce__` method to `Ellipsis` class.

Add __reduce__ method to Ellipsis

---

tests/snippets/object.py
vm/src/obj/objobject.rs

https://docs.python.org/3/library/abc.html#abc.ABCMeta.__subclasshook__

object.__subclasshook__

---

Cargo.lock
tests/snippets/stdlib_io.py
vm/Cargo.toml
vm/src/stdlib/io.rs

stdlib_io: Implement fileIO.close

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

CPython returns "NotImplemented" string when arguments supplied.

Add str.__rmod__() method. #190

---

Cargo.lock
tests/snippets/math_module.py
vm/Cargo.toml
vm/src/stdlib/math.rs

- Implement factorial function with test case
- Deal with Negative input as a ValueError

Update factorial module of math

---

vm/src/obj/objint.rs

suggested by @windelbouwman  in #1274

Reduce payload occurrence of int

---

python_test.py
tests/snippets/math_module.py
vm/src/stdlib/math.rs

- Implement ldexp function with test case

Update ldexp module of math

---

vm/src/stdlib/os.rs

Tries to fix https://github.com/RustPython/RustPython/issues/1263
It's my first pull request ever on github. I'd love to have feedback.

[WIP]Implement os access

---

tests/snippets/class.py
vm/src/obj/objsuper.rs

Add \_\_str\_\_ \_\_repr\_\_ method for super type.

Add __str__ __repr__ for super

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

Implement itertools.filterfalse

itertools: Implement itertools.filterfalse

---

tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs

Added `os.chmod`, which works on unix platforms only.

Add os.chmod

---

Lib/datetime.py
tests/snippets/stdlib_datetime.py
tests/snippets/testutils.py

~#1301 is required for tests~ 
#1302 is a blocking issue for other tests

Datetime module

---

tests/snippets/ints.py
vm/src/obj/objint.rs

Fix panics with int()

---

tests/snippets/arraymodule.py
vm/src/macros.rs
vm/src/obj/objfloat.rs
vm/src/obj/objstr.rs
vm/src/stdlib/array.rs
vm/src/stdlib/mod.rs

Not all the methods for `array.array` are implemented, but the most relevant ones are.

Add the array module

---

tests/snippets/json_snippet.py
vm/src/stdlib/json.rs

`json.loads` and `json.load` should work for `bytes` and `bytearray`
mentioned #1255

Modify `json.loads` for bytes and bytearray

---

src/main.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/stdlib/signal.rs
vm/src/stdlib/time_module.rs
vm/src/vm.rs

This is based on #1311 for the PySyscallFunctions struct.

Raise a KeyboardInterrupt on a SIGINT

---

bytecode/src/bytecode.rs
compiler/src/compile.rs
vm/src/frame.rs

- Make subscript its own bytecode.
- Remove pass bytecode.
- Move complex bytecodes into seperate functions to reduce complexity of dispatch function.

Make subscript its own bytecode.

---

compiler/src/symboltable.rs
tests/snippets/global_nonlocal.py
vm/src/scope.rs

This leapt out at me while reviewing #1329. The code was was added recently.

load_global shouldn't load outermost locals.

---

compiler/src/compile.rs
compiler/src/symboltable.rs
vm/src/stdlib/ast.rs

- Add symboltable scope for comprehensions. 
- Add _ast module nodes for comprehensions.

Add symboltable scope for comprehensions. 

---

Cargo.lock
Cargo.toml
src/main.rs
vm/src/stdlib/os.rs
vm/src/stdlib/signal.rs

Use the `dirs` crate to find the config dir on non-unix; fix warnings.

Improve UX on windows

---

vm/src/stdlib/os.rs

add seek constants, resolves #1348

---

tests/snippets/sysmod.py
vm/src/sysmodule.rs

Add framework attribute in sys module

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

Modify panic! to Err for unsupported operand type of str problem
Fixes #1365

Fix unsupported operand type of str problem

---

Cargo.lock
parser/src/ast.rs
parser/src/error.rs
parser/src/function.rs
parser/src/lib.rs
parser/src/python.lalrpop
tests/snippets/function.py

Add Positional argument error to LexicalError

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

#1361 
This is an implementation of the Python standard library function `itertools.accumulate`. I also included a couple of very basic tests.

Implement itertools.accumulate

---

vm/src/obj/objcomplex.rs
vm/src/obj/objfloat.rs
vm/src/stdlib/math.rs

Same as in #1339 but for float.

Add IntoPyFloat

---

tests/snippets/builtin_range.py
vm/src/obj/objrange.rs

__eq__ compare length, start, step of range
Fixes #1389

Fix __eq__ of range

---

vm/src/function.rs
vm/src/macros.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objint.rs
vm/src/obj/objrange.rs
vm/src/obj/objsequence.rs
vm/src/obj/objset.rs
vm/src/stdlib/collections.rs
vm/src/stdlib/io.rs
vm/src/stdlib/json.rs
vm/src/stdlib/re.rs
vm/src/vm.rs

This is an implementation of #1237; already there's a ton better formatting inside the macro invocations!

Match an actual match expression in match_class!

---

tests/snippets/math_module.py
vm/src/stdlib/math.rs

- Implement copysign function with test case
- Add constants of `NAN`, `INF`, `NINF` on top of `math_module.py`

Update copysign module of math

---

vm/src/stdlib/pystruct.rs

Fix Typo in vm/src/stdlib/pystruct.rs

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

itertools.compress

---

Cargo.lock
tests/snippets/basic_types.py
vm/src/obj/objbyteinner.rs

Fix panic when using negative int for bytes()

---

Cargo.lock
parser/src/error.rs
parser/src/function.rs
tests/snippets/function_args.py

Add duplicate keyword argument error

---

tests/snippets/slice.py
vm/src/obj/objslice.rs

Add __repr__ of slice

---

vm/build.rs
vm/src/sysmodule.rs
vm/src/version.rs

#1358 will be fixed in this PR.

Add sys._git (#1358)

---

tests/snippets/slice.py
vm/src/obj/objslice.rs
vm/src/vm.rs

Compute `__eq__` and `__ne__` by comparing start,
stop and step of slice
Issue #1431

Implement __eq__, __ne__ of slice 

---

tests/snippets/ints.py
vm/src/obj/objint.rs

this is fix of #1408 and #1415.

Fix int type casting errors

---

parser/src/error.rs
parser/src/function.rs
parser/src/python.lalrpop
tests/snippets/function_args.py

Do not panic in parser

---

tests/snippets/types_snippet.py
vm/src/obj/objfunction.rs
vm/src/obj/objproperty.rs
vm/src/obj/objtype.rs
vm/src/types.rs

Fix properties on `type`

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

#1361
Hi, this is my first draft of `itertools.tee`. I also added some tests for it. Please review, and let me know if there are any bugs to be fixed, or improvements I can make. Thanks.

Implement itertools.tee

---

wasm/demo/package.json
wasm/demo/src/main.js

Using [wavesoft/local-echo](https://github.com/wavesoft/local-echo/)

Improve the demo terminal's navigation

---

tests/snippets/list.py
tests/snippets/tuple.py
vm/src/obj/objsequence.rs
vm/src/vm.rs

Fixed gt, lt comparison of sequence. Also, the values of
le and ge are calculated using the not operation of gt and lt
Fixes #1450

Fix sequence comparison

---

compiler/src/error.rs
parser/src/error.rs
parser/src/lexer.rs
tests/snippets/invalid_syntax.py
vm/src/builtins.rs
vm/src/exceptions.rs
vm/src/vm.rs

Implement TabError

---

tests/snippets/builtin_format.py
vm/src/format.rs

Fix #1476 Magnitude seperator format bug

---

tests/snippets/slice.py
vm/src/obj/objslice.rs

Add gt, ge, lt, le for slice
Issue #1431

Add comparison of slice

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

cpython compatible "".__repr__

---

tests/snippets/list.py
vm/src/obj/objlist.rs

When list iadd iterable value,
run iterator and add values to the list
Fixes #1475

Fixed list's __iadd__

---

tests/snippets/slice.py
vm/src/obj/objslice.rs

When hashing slice, raise TypeError
Issue #1431

Add __hash__ of slice

---

tests/snippets/builtin_thread.py
vm/src/stdlib/thread.rs

https://docs.python.org/ko/3/library/_thread.html#_thread.TIMEOUT_MAX

_thread.TIMEOUT_MAX

---

tests/snippets/builtin_range.py
vm/src/obj/objrange.rs
vm/src/obj/objtuple.rs

Calculate hash value of range through hash of tuple
Fixes #1482

Fixed __hash__ of range

---

Cargo.lock
Lib/os.py
tests/snippets/exit.py
vm/Cargo.toml
vm/src/builtins.rs
vm/src/stdlib/os.rs

Fixed builtin exit() method with SystemExit (can be tested without Lib).
Added os._exit() method and os.EX_* constants

Change something related to exit

---

tests/snippets/types_snippet.py
vm/src/obj/objtype.rs

Fixed to return the mro function 
to include its own class
Fixes #1490

Fixed to return the mro function

---

Cargo.lock
Lib/csv.py
tests/snippets/test_csv.py
vm/Cargo.toml
vm/src/stdlib/csv.rs
vm/src/stdlib/mod.rs

Added csv module and implemented reader function.

Added csv module

---

tests/snippets/builtin_range.py
tests/snippets/floats.py
tests/snippets/none.py
vm/src/obj/objfloat.rs
vm/src/obj/objnone.rs
vm/src/obj/objrange.rs

Add __ne__ for float, none and range

Add __ne__ methods

---

compiler/src/error.rs
parser/src/error.rs
parser/src/lexer.rs
parser/src/python.lalrpop
tests/snippets/invalid_syntax.py
vm/src/vm.rs

Implement IndentationError

---

tests/snippets/test_csv.py
vm/src/stdlib/csv.rs

Added kwarg parameters of csv.reader 'delimiter' and 'quotechar'

Add csv.reader options

---

DEVELOPMENT.md
README.md

~This PR is mutually exclusive with #1516.
That means if this PR is merged #1516 is needed to be dropped. On the other hand, if #1516 is merged this PR is needed to be dropped too.~

Change rustc version in markdown

---

tests/snippets/generators.py
vm/src/frame.rs
vm/src/obj/objframe.rs
vm/src/obj/objgenerator.rs
vm/src/obj/objiter.rs
vm/src/vm.rs

Now that this is working, I'm planning on implementing `async def` coroutines :)

Fix the `yield from` expression

---

vm/src/obj/objint.rs

Impl from @RobertBerglund 's comment, working on #304

`int.__sizeof__` from #1426

---

tests/snippets/stdlib_math.py
vm/src/stdlib/math.rs

- Implement fmod function with test case
- This PR includes commit of #1547

Update fmod module of math

---

tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

This implements `itertools.product` of standard library.
Related with #1361

Implement itertools.product

---

tests/snippets/floats.py
vm/src/obj/objfloat.rs

Fix float.__repr__()

---

vm/src/obj/objbytes.rs

Implemented bytes.__sizeof__

---

tests/snippets/basic_types.py
vm/src/obj/objbyteinner.rs

Fix panic when using non-collection in bytes()

---

tests/snippets/floats.py
vm/src/obj/objfloat.rs

Fix to receive a string value with '_' when creating a float value
Fixes #1527

Modify str to float

---

tests/snippets/strings.py
vm/src/obj/objdict.rs
vm/src/obj/objmappingproxy.rs
vm/src/obj/objstr.rs
vm/src/obj/objsuper.rs
vm/src/stdlib/time_module.rs

socket2 Part 1, some necessary but miscellaneous changes that aren't directly related to socket

---

Lib/linecache.py
tests/snippets/stdlib_traceback.py
vm/src/builtins.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/import.rs
vm/src/lib.rs
vm/src/obj/mod.rs
vm/src/obj/objtraceback.rs
vm/src/pyobject.rs
vm/src/traceback.rs
vm/src/types.rs

This PR change exception traceback to be with `traceback` object very similar to CPython.

Traceback object

---

Lib/_collections_abc.py
Lib/contextlib.py
Lib/types.py
bytecode/src/bytecode.rs
compiler/src/compile.rs
tests/snippets/async_stuff.py
tests/snippets/asyncio_slow.py
vm/src/builtins.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/obj/mod.rs
vm/src/obj/objcoroutine.rs
vm/src/types.rs
vm/src/vm.rs

Here's what I've done so far with this and what's left to do:

Make async def/await actually functional

---

tests/snippets/stdlib_math.py
vm/src/stdlib/math.rs

- Implement remainder function with test case

Update remainder module of math

---

tests/snippets/slice.py
vm/src/obj/objrange.rs
vm/src/obj/objslice.rs

Fixes #1431.
CPython equivalent method: https://github.com/python/cpython/blob/master/Objects/sliceobject.c#L373

Implement .indices(len) of slice

---

Lib/colorsys.py

I've been looking for a reason this wasn't in yet but haven't found it.

Colosys.py from the cpython standard lib

---

tests/snippets/bytes.py
vm/src/cformat.rs
vm/src/format.rs
vm/src/obj/objbytes.rs
vm/src/obj/objstr.rs

implement byte formatting with bytes or tuple of bytes #736

bytes.mod implement with CFormat

---

tests/snippets/bytearray.py
vm/src/obj/objbytearray.rs

- implement bytearray formatting with CFormat
- fix issue #1569

Implement bytearray.mod 

---

Lib/test/support/__init__.py
Lib/test/support/script_helper.py
Lib/test/support/testresult.py
Lib/test/test_bool.py

After this change you can run test_bool.py from CPython:
```
cargo run --release Lib/test/test_bool.py
Finished release [optimized] target(s) in 0.10s
Running `target/release/rustpython Lib/test/test_bool.py`
test_blocked (__main__.BoolTest) ... ok
test_boolean (__main__.BoolTest) ... ok
test_callable (__main__.BoolTest) ... ok
test_contains (__main__.BoolTest) ... ok
test_convert (__main__.BoolTest) ... ok
test_convert_to_bool (__main__.BoolTest) ... ok
test_fileclosed (__main__.BoolTest) ... ERROR
test_float (__main__.BoolTest) ... ok
test_format (__main__.BoolTest) ... ok
test_from_bytes (__main__.BoolTest) ... FAIL
test_hasattr (__main__.BoolTest) ... ok
test_int (__main__.BoolTest) ... ok
test_isinstance (__main__.BoolTest) ... ok
test_issubclass (__main__.BoolTest) ... ok …
```

Add test to Lib and allow test_bool.py to run

---

vm/src/import.rs

This will restore the functionality to before #1573.

Fix remove_importlib_frames

---

tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs

Specifically: 
- os.pipe
- os.pipe2
- os.get_blocking
- os.set_blocking
- os.get_inheritable
- os.set_inheritable
Sorry for adding so many on my first PR. I was just planning on doing pipe at first, and kinda got dragged into the rest for testing.
Regarding os.pipe (~line 1000), is it okay to ignore close(fd) failure? That's what CPython does, and I'm not otherwise sure how to appropriately handle that. 
Also, flake8 complains about stdlib_os.py a lot. Not my code, and I didn't want to run a linter and make my first PR seem bigger.

add some os stdlib functions

---

vm/src/stdlib/socket.rs

Add IPPROTO_NONE for android target

---

parser/src/lexer.rs

Rename LineContinationHandler -> LineContinuationHandler

---

src/main.rs
vm/src/eval.rs
vm/src/import.rs
vm/src/lib.rs
vm/src/vm.rs
wasm/lib/src/vm_class.rs

Provide `update_sysmodule` in vm to update sys when update_sysmodule
changed
Fix issue #1588

Update sys module when stdlib_inits is changed

---

Cargo.lock
tests/snippets/stdlib_binascii.py
tests/snippets/stdlib_os.py
vm/Cargo.toml
vm/src/obj/objbyteinner.rs
vm/src/stdlib/binascii.rs
vm/src/stdlib/errno.rs
vm/src/stdlib/io.rs
vm/src/stdlib/multiprocessing.rs
vm/src/stdlib/os.rs
vm/src/stdlib/socket.rs
vm/src/stdlib/winapi.rs

~~This might be a lot of miscellaneous changes, but I have a lot of other miscellaneous changes and I don't know the best way to split them all into PRs. If you're reviewing, I'd recommend going commit by commit.~~ I split it up

Fix some various issues with `os` and `binascii`

---

compiler/src/compile.rs
derive/src/compile_bytecode.rs
parser/src/function.rs
parser/src/lexer.rs
vm/src/builtins.rs
vm/src/cformat.rs
vm/src/format.rs
vm/src/frame.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objenumerate.rs
vm/src/obj/objfunction.rs
vm/src/obj/objmap.rs
vm/src/obj/objobject.rs
vm/src/obj/objrange.rs
vm/src/obj/objslice.rs
vm/src/obj/objsuper.rs
vm/src/obj/objtype.rs
vm/src/stdlib/dis.rs
vm/src/vm.rs

Fix clippy warnings

---

tests/snippets/strings.py
vm/src/obj/objstr.rs

Add str.format_map method

---

tests/snippets/strings.py
vm/src/format.rs
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs

Add support for the `%` format code for floats.

---

tests/snippets/strings.py
vm/src/format.rs

Implement the '%' string format code for integers

---

parser/src/parser.rs
tests/snippets/ints.py
vm/src/pyobject.rs
vm/src/stdlib/socket.rs

I didn't make any useful changes by these but they were derived during trying to solve other problems.

Small changes about parser, int test, new_bool and socket.has_ipv6

---

tests/generator/not_impl_methods_footer.txt
tests/not_impl_gen.py

example result:
```
bool.__init_subclass__
bool.__str__ (inherited)
bool.from_bytes (inherited)
bytearray.__alloc__
bytearray.__getattribute__ (inherited)
bytearray.__iadd__
bytearray.__init__ (inherited)
bytearray.__init_subclass__
bytearray.__ne__ (inherited)
bytearray.__reduce__ (inherited)
bytearray.__reduce_ex__ (inherited)
bytearray.__str__ (inherited)
bytearray.decode
bytes.__getattribute__ (inherited)
bytes.__getnewargs__
bytes.__init_subclass__
bytes.__ne__ (inherited)
bytes.__str__ (inherited)
complex.__format__ (inherited)
complex.__ge__ (inherited)
complex.__getattribute__ (inherited)
complex.__gt__ (inherited)
complex.__init_subclass__
complex.__le__ (inherited)
complex.__lt__ (inherited)
complex.__ne__ (inherited)
complex.__pos__
complex.__str__ (inherited)
dict.__doc__ …
```

whats_left prints inherited but unimplemented attrs + more types

---

.travis.yml
Lib/test/__main__.py
Lib/test/list_tests.py
Lib/test/seq_tests.py
Lib/test/test_bool.py
Lib/test/test_compare.py
Lib/test/test_decorators.py
Lib/test/test_list.py
vm/src/obj/objframe.rs

This change add the CPython tests suite to the travis CI.
In addition I added a few more test suites.

Run Cpython tests suite in travis CI

---

tests/snippets/stdlib_math.py
vm/src/stdlib/math.rs

https://docs.python.org/3.9/library/math.html#math.nextafter is introduced yesterday :)

math: Implement math.nextafter

---

vm/src/descriptor.rs
vm/src/function.rs
vm/src/lib.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objclassmethod.rs
vm/src/obj/objfunction.rs
vm/src/obj/objproperty.rs
vm/src/obj/objstaticmethod.rs
vm/src/obj/objsuper.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/vm.rs

It seems we need a pair of slot and method in most of cases.
Would adding a method pair by `pyslot` be helpful?

Use slot for descriptor get

---

Lib/test/test_bool.py
vm/src/obj/objint.rs

This fixes test_bool.test_math

objint __pos__ returns Int object

---

Lib/test/mapping_tests.py
Lib/test/test_dict.py

I will take this opportunity to talk about the `gc` module. Should we remove it from our tests or should we create a stub?
I believe removing it from the tests is the correct way.

Add Cpython test_dict

---

Cargo.lock
Lib/hmac.py
tests/snippets/stdlib_operator.py
vm/Cargo.toml
vm/src/stdlib/operator.rs

C implementation of timing safe compare that I used as reference: https://github.com/python/cpython/blob/master/Modules/_operator.c#L727

Add _operator._compare_digest

---

derive/src/pyclass.rs

Parsing in for loop is painful.
Doing with a hashmap is easier.

Utility ClassItemMeta for class item meta parsing

---

.github/workflows/ci.yaml
vm/src/stdlib/os.rs

As suggested in the chat by @dralley this is an initial configuration of Github actions. My suggestion is to first run this in parallel to the travis CI and once this is stable remove travis.
The windows CI fails on the snippets test. I have not yet discovered why...

GitHub actions

---

Cargo.lock
tests/snippets/stdlib_subprocess.py
vm/Cargo.toml
vm/src/stdlib/subprocess.rs

The new version of rust-subprocess supports timeout hniksic/rust-subprocess#30

Support timeout in Popen.communicate

---

Lib/test/test_types.py
vm/src/format.rs

And fixed crash when it is too long

parse_number can raise error about length

---

Cargo.lock
Lib/random.py
Lib/tempfile.py
tests/snippets/stdlib_random.py
vm/Cargo.toml
vm/src/stdlib/mod.rs
vm/src/stdlib/random.rs
vm/src/stdlib/random/mersenne.rs

Based off of @malkog's work in #1571. Closes #1571 and closes #1269.
cc @vks.

Implement _random.Random

---

azure-pipelines.yml

Bump up to python 3.7 for Azure Pipelines

---

derive/src/pyclass.rs
tests/snippets/types_snippet.py
vm/src/exceptions.rs
vm/src/obj/mod.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objclassmethod.rs
vm/src/obj/objcode.rs
vm/src/obj/objfloat.rs
vm/src/obj/objfunction.rs
vm/src/obj/objgetset.rs
vm/src/obj/objint.rs
vm/src/obj/objnone.rs
vm/src/obj/objobject.rs
vm/src/obj/objproperty.rs
vm/src/obj/objstaticmethod.rs
vm/src/obj/objsuper.rs
vm/src/obj/objtype.rs
vm/src/obj/objweakref.rs
vm/src/pyobject.rs
vm/src/slots.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs
vm/src/stdlib/pwd.rs
vm/src/stdlib/subprocess.rs
vm/src/types.rs
vm/src/vm.rs

- Add getset_descriptor
- Remove PyReadOnlyProperty
- #[pyproperty] now generates getset. PyProperty is only used for python code.

Add getset_descriptor

---

tests/snippets/exceptions.py
vm/src/exceptions.rs

I misunderstood the initial value behavior. Added tests and fix about them

Fix SyntaxError initial value

---

Lib/test/exception_hierarchy.txt
Lib/test/test_baseexception.py
Lib/test/test_int.py
Lib/test/test_int_literal.py
Lib/test/test_opcodes.py
Lib/test/test_pow.py
Lib/test/test_raise.py

- test_baseexception
- test_int
- test_int_literal
- test_opcodes
- test_pow
- test_raise

Add more CPython tests

---

Lib/test/test_set.py
vm/src/function.rs
vm/src/obj/objset.rs

Apparently we have some work to do on `set` and `frozenset`. I have started by adding the ability to receive multiple iterables as argument to needed methods.

Add CPython Set tests and support Args in methods

---

Lib/test/test_class.py
Lib/test/test_contains.py
Lib/test/test_tuple.py
Lib/test/test_with.py

- test_tuple
- test_with
- test_class
- test_contains

Add more CPython test

---

Lib/_sitebuiltins.py
Lib/platform.py
Lib/test/list_tests.py
Lib/test/test_dict.py
vm/src/builtins.rs
vm/src/stdlib/os.rs
vm/src/stdlib/subprocess.rs
vm/src/vm.rs

~~Just testing this on CI right now, I'm not sure if this will work.~~ Fixes #1753

Fix writing to stdio streams on Windows

---

Cargo.lock
Cargo.toml
src/shell.rs
src/shell/helper.rs
vm/Cargo.toml
vm/src/builtins.rs
vm/src/frame.rs
vm/src/lib.rs
vm/src/obj/objcoroutine.rs
vm/src/obj/objdict.rs
vm/src/obj/objgenerator.rs
vm/src/pyobject.rs
vm/src/readline.rs
vm/src/stdlib/os.rs
vm/src/vm.rs

Closes #1586, closes #1590, closes #1632

Implement input()

---

tests/snippets/generators.py
vm/src/frame.rs
vm/src/macros.rs
vm/src/obj/mod.rs
vm/src/obj/objcoroinner.rs
vm/src/obj/objcoroutine.rs
vm/src/obj/objgenerator.rs
vm/src/pyobject.rs

I wrote this a few months ago and then forgot about it; surprisingly there weren't many conflicts when I rebased it!

Deduplicate coroutine/generator code

---

Lib/pydoc.py
Lib/types.py
vm/src/obj/objframe.rs
vm/src/obj/objmodule.rs

`help()` sorta works now! Not really with any builtin stuff, since builtin functions don't have `__name__` attributes, but `help(pydoc)` looks pretty much the same as CPython's rendering.

Add pydoc stdlib module

---

LICENSE
LICENSE-logo
README.md

I figured CC-BY-4.0 for the logo would be fairly permissive (and I drew the logo 😏), but if anyone disagrees feel free to bring it up.

Add LICENSE-logo, update LICENSE to (c) 2020

---

src/main.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/msvcrt.rs
vm/src/stdlib/os.rs

`getpass` works on windows now.

Add the msvcrt stdlib module

---

Lib/test/test_grammar.py
bytecode/src/bytecode.rs
compiler/src/compile.rs
parser/src/ast.rs
parser/src/function.rs
parser/src/parser.rs
parser/src/python.lalrpop
vm/src/obj/objcode.rs

Partially add #1755 
This PR allows positional only parameter functions work but not disallow positional only parameter is passed by name.

PEP570 - positional only parameter support

---

Lib/functools.py
Lib/inspect.py
Lib/test/support/script_helper.py
Lib/test/test_typechecks.py
Lib/test/test_unary.py
Lib/zipfile.py

module inspect, functools, zipfile and test test_unary, test_typechecks

---

Lib/test/test_bytes.py
parser/src/lexer.rs

This actually fixes the current failures in test_bytes. In addition I simplified lexer by merging `lex_byte` into `lex_string`.

Escape octet in string

---

.github/workflows/ci.yaml
Cargo.lock
Lib/ipaddress.py
Lib/ssl.py
scripts/install-openssl.ps1
src/main.rs
src/shell.rs
vm/Cargo.toml
vm/src/obj/objbyteinner.rs
vm/src/obj/objset.rs
vm/src/obj/objstr.rs
vm/src/pyobject.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/socket.rs
vm/src/stdlib/ssl.rs

This is all VERY flaky, with many uses of unsafe. I'm not sure if this is a good idea at this point, but it does work, ~~albeit not certificate verification~~. EDIT: certificate verification does work, just not with `google.com`. @palaviv what's the deal? :smile:  
```py
from urlllib.request import urlopen
print(urlopen("https://rustpython.github.io").read().decode())
```

Add the ssl stdlib module

---

Lib/functools.py
vm/src/obj/objtype.rs

Call __set_name__ on descriptors when initializing types

---

Lib/test/support/__init__.py
Lib/test/support/testresult.py
Lib/test/test_iter.py

unittest test_iter

---

Lib/test/test_bytes.py
vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objstr.rs

Fix part of bytes find/count bugs

Refactor and fix bytes count/find

---

vm/src/builtins.rs

This allows e.g. `contextlib.redirect_stdout` to work with `print()`

Direct print() to sys.stdout

---

vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objcomplex.rs
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs
vm/src/pyobject.rs

I have also added the ThreadSafe trait to some trivial objects.

Convert ByteArray to thread safe

---

Cargo.lock
Lib/test/list_tests.py
vm/Cargo.toml
vm/src/builtins.rs
vm/src/frame.rs
vm/src/function.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objcoroinner.rs
vm/src/obj/objframe.rs
vm/src/obj/objiter.rs
vm/src/obj/objlist.rs
vm/src/obj/objmodule.rs
vm/src/obj/objobject.rs
vm/src/obj/objset.rs
vm/src/obj/objstr.rs
vm/src/obj/objtuple.rs
vm/src/obj/objweakref.rs
vm/src/pyobject.rs
vm/src/stdlib/faulthandler.rs
vm/src/stdlib/weakref.rs
vm/src/sysmodule.rs
vm/src/types.rs
vm/src/vm.rs
wasm/lib/src/vm_class.rs

Prep some things for threading

---

vm/src/obj/objbytearray.rs

This fixes the deadlock problem in #1821. The problem was with the `extend` method that held the lock while calling python code.

Fix PyByteArray locking issue

---

Lib/_codecs.py
Lib/test/test_unicode.py
vm/Cargo.toml
vm/src/stdlib/faulthandler.rs
vm/src/stdlib/msvcrt.rs
vm/src/stdlib/os.rs
vm/src/vm.rs

These fixes are pulled out from #1821, they're not really related to each other but there's not that much to review, I think.

Miscellaneous io-related fixes

---

Lib/test/string_tests.py
Lib/test/test_bytes.py
vm/src/obj/mod.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objstr.rs
vm/src/obj/pystr.rs
vm/src/pyobject.rs

~Failing test depends on #1855~

Fix str.split bytes.split

---

compiler/src/peephole.rs
compiler/src/peephole/optimizations.rs
tests/snippets/if_expressions.py

Disable the unpack optimization

---

derive/src/lib.rs
derive/src/pyclass.rs
derive/src/pymodule.rs
derive/src/util.rs
vm/src/obj/objtuple.rs
vm/src/stdlib/binascii.rs
vm/src/stdlib/collections.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/platform.rs
vm/src/stdlib/pystruct.rs
vm/src/stdlib/random.rs

Creating an inner module for every stdlib looks not ideal but i have no idea how to do without them

pymodule derive macro

---

Lib/test/string_tests.py
vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objstr.rs
vm/src/obj/pystr.rs

The failing tests depend on #1847

Fix bytes.{find,count} and simplify __contains__ implementation

---

vm/src/stdlib/tokenize.rs

Remove the arg_check! in the tokenize function. #1714

Remove arg_check! in tokenize

---

vm/src/stdlib/thread.rs

As title, remove the arg_check! macro

remove arg_check macro in thread mod

---

vm/src/obj/objstr.rs

Rust str is utf-8, so it doesn't match to CPython str very well.
Probably we would reimplement PyString as same as CPython, but this is a
temporal fix for easy speedup.
Before:
$ time cargo run --release Lib/test/test_unicode.py
13.56s user 0.16s system 88% cpu 15.487 total
After:
$ time cargo run --release Lib/test/test_unicode.py
10.02s user 0.10s system 88% cpu 11.448 total

Cache str.len()

---

Lib/test/string_tests.py
Lib/test/test_unicode.py
vm/src/obj/objbyteinner.rs
vm/src/obj/objstr.rs
vm/src/obj/pystr.rs

String test skip is not a regression but just further tests triggers crash

Fix find/index/count not to crash for bigint start/end arguments

---

vm/src/stdlib/os.rs

Add umask support

---

vm/src/stdlib/io.rs
vm/src/stdlib/pystruct.rs
vm/src/stdlib/zlib.rs

This lets you run `rustpython -m zipfile` operations that decompress zip files!

Add zlib.decompressobj()

---

README.md

Related commit: 5f6c7152b39162926571272caf79f9eaff049564

standard library is set by default by 5f6c715

---

vm/src/stdlib/os.rs

As title, `getpgrp` support in os module in UNIX only

add getpgrp support in os mod

---

vm/src/stdlib/os.rs

As title, add getresuid support in os module. 
Note: macos is not supported in libc

add support for getresuid

---

vm/src/stdlib/os.rs

As title. 
Note: macos not supported

add_getresgid_support

---

vm/src/stdlib/os.rs

As tite, add setregid support in os module

support setregid in os module

---

vm/src/stdlib/os.rs

As title.
Note, mac os is not supported

support initgroups in os module

---

Cargo.lock
Lib/_rp_thread.py
Lib/_weakrefset.py
Lib/importlib/_bootstrap.py
Lib/test/lock_tests.py
Lib/test/support/__init__.py
Lib/test/test_thread.py
Lib/threading.py
tests/snippets/test_threading.py
vm/Cargo.toml
vm/src/function.rs
vm/src/obj/objweakref.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/thread.rs
vm/src/vm.rs

~~Dependent on #1933 and #1935~~

Add _thread.start_new_thread

---

Lib/test/test_argparse.py
tests/snippets/builtin_complex.py
tests/snippets/floats.py
vm/src/exceptions.rs
vm/src/obj/objcomplex.rs
vm/src/obj/objfloat.rs
vm/src/stdlib/io.rs

Can't believe argparse have so many tests...

Add CPython argparse test

---

Lib/test/test_errno.py
Lib/test/test_exception_hierarchy.py
Lib/test/test_module.py
Lib/test/test_operator.py

Add some tests from CPython 3.8.3

---

README.md

I was trying to find the best place. Feel free to suggest other options.

Add link to home page

---

Lib/test/seq_tests.py
Lib/test/string_tests.py
Lib/test/test_bytes.py
Lib/test/test_list.py
Lib/test/test_memoryview.py
Lib/test/test_unicode.py
tests/snippets/index_overflow.py
vm/src/obj/objbytearray.rs
vm/src/obj/objbyteinner.rs
vm/src/obj/objbytes.rs
vm/src/obj/objlist.rs
vm/src/obj/objsequence.rs
vm/src/obj/objstr.rs
vm/src/stdlib/thread.rs
vm/src/stdlib/time_module.rs

I fixed a compile error and then a few tests that depended on oom-catching.
cc @aurelien-m

32 bit support

---

vm/src/stdlib/os.rs

As title, support setgroups
MACOS is not supported.

support setgroups in os module

---

vm/src/stdlib/os.rs

as title.
Note: a tiny change also made to setregid to keep the return type consistent

Support setresgid in os module

---

vm/Cargo.toml
vm/src/function.rs
vm/src/obj/objdict.rs
vm/src/pyobject.rs
vm/src/stdlib/os.rs

@coolreader18 is spliting non-subprocess part form #1962 ok?
@palaviv

non-subprocess stuff from #1962

---

bytecode/src/bytecode.rs
compiler/src/compile.rs
tests/snippets/class.py
vm/src/frame.rs

Fix #1980 
Add setup annotation for compile class

Add annotation setup

---

Cargo.lock
Lib/shutil.py
Lib/tarfile.py
Lib/test/test_shutil.py
derive/src/from_args.rs
vm/Cargo.toml
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs
vm/src/stdlib/posixsubprocess.rs
vm/src/stdlib/winapi.rs

Implement os.get_terminal_size

---

.gitpod.Dockerfile
.gitpod.yml
.theia/launch.json
.theia/settings.json

This PR provides the configuration files and updates the existing ones to allow launching and debugging in VS Code and Gitpod/Theia.

Config files for debugging and launch for VS Code and Gitpod

---

Lib/test/test___future__.py

cpython's test passes without any problems, so it seemed that it'd be okay to add the whole file.

Added CPython 3.8.3's test___future__.py.

---

.github/workflows/ci.yaml

 skip platform independent tests for macOS 

---

.github/workflows/ci.yaml
Cargo.toml

https://doc.rust-lang.org/cargo/reference/profiles.html#overrides

Build dependencies with opt-level 3 always

---

Lib/test/test_urlparse.py

Add CPython urlparse test

---

Lib/test/test_cmd.py

Add CPython 3.83 test test_cmd.py

---

vm/src/function.rs
vm/src/obj/objfloat.rs
vm/src/obj/objmodule.rs
vm/src/pystr.rs
vm/src/stdlib/io.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/random.rs
vm/src/stdlib/select.rs

by following std::option::Option
https://doc.rust-lang.org/std/option/enum.Option.html#method.flatten

flat_option -> flatten

---

derive/src/pymodule.rs
derive/src/util.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs

This PR re-cluster os module with 3 submodules `posix`, `nt` and `minor`.
I think current result is not the ideal state but this was limit for me due to lack of windows dev enviroment.

Reorganize os module

---

vm/src/stdlib/os.rs

This PR implements os.waitpid using MSVCRT's [`_cwait`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/cwait) function.

Implement os.waitpid on Windows

---

vm/src/stdlib/os.rs

This fixes some broken test CPython cases on Windows.

Implement os.chmod on Windows

---

common/src/hash.rs
examples/mini_repl.rs
vm/src/bytesinner.rs
vm/src/dictdatatype.rs
vm/src/frame.rs
vm/src/obj/objdict.rs
vm/src/obj/objfunction.rs
vm/src/obj/objset.rs
vm/src/obj/objstr.rs
vm/src/obj/objsuper.rs
vm/src/py_serde.rs
vm/src/pyobject.rs
vm/src/stdlib/dis.rs
vm/src/stdlib/errno.rs
vm/src/stdlib/os.rs
vm/src/stdlib/thread.rs
wasm/lib/src/convert.rs
wasm/lib/src/vm_class.rs

This patch make DictKey used in more natural manner - except for `&str` case.

Refactor DictKey

---

vm/src/macros.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objclassmethod.rs
vm/src/obj/objint.rs
vm/src/obj/objrange.rs
vm/src/obj/objstaticmethod.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/hashlib.rs
vm/src/stdlib/io.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/marshal.rs
vm/src/stdlib/os.rs
vm/src/stdlib/zlib.rs

We can leverage From trait for synthesize.

Use From::from for PyValues instead of new

---

Lib/asynchat.py
Lib/asyncore.py
Lib/test/test_os.py

Copy test_os.py from CPython 3.8.3

---

vm/src/stdlib/os.rs

I thought there was no function dealing with non-Unix errno, but as turns out there is and I didn't notice it.

Use errno_err on Windows waitpid

---

Lib/test/test_set.py
tests/snippets/set.py
vm/src/obj/objset.rs
vm/src/pyobject.rs
vm/src/types.rs

related https://github.com/RustPython/RustPython/issues/1652
I just fixed @dralley 's implementaion a little.

Support pysetiterator.

---

Cargo.lock
bytecode/Cargo.toml
common/Cargo.toml
common/src/float_ops.rs
common/src/hash.rs
compiler/Cargo.toml
vm/Cargo.toml
vm/src/format.rs
vm/src/obj/objbool.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objcomplex.rs
vm/src/obj/objfloat.rs
vm/src/obj/objint.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/stdlib/re.rs

A few parts might be just a preference. Tell me if anyone think there are unnessessary editing.

Small edits

---

derive/src/pyclass.rs
derive/src/pymodule.rs
derive/src/util.rs
vm/src/pyobject.rs
vm/src/sysmodule.rs

I finished `pystruct_sequence` work but not about pyclass.

Implement tp_name and derive support

---

Lib/test/list_tests.py
Lib/test/test_tuple.py
vm/src/obj/objsequence.rs

Minor error message fix in objsequence.get_item.

Fix error message in objsequence.get_item

---

Lib/test/test_symtable.py
compiler/src/symboltable.rs
vm/src/stdlib/symtable.rs

Fix symtable is_nested test and optimized test.
Reference:
[is_nested](https://github.com/python/cpython/blob/master/Python/symtable.c#L83)
[is_optimized](https://github.com/python/cpython/blob/3.8/Lib/symtable.py#L76)

Add nested and optimized for symtable

---

Lib/_codecs.py
Lib/asyncio/tasks.py
vm/src/frame.rs

Relate to issue  #978
Continue to https://github.com/RustPython/RustPython/pull/2076 
Some changes to compile and pass the tests

Support __all__

---

Lib/test/support/__init__.py
Lib/test/test_complex.py
vm/src/obj/objcomplex.rs

https://docs.python.org/3/library/functions.html#complex
Complex numbers can be arguments of complex()

Allow complex numbers as arguments of complex()

---

tests/snippets/bytearray.py
tests/snippets/stdlib_array.py
vm/src/bytesinner.rs
vm/src/macros.rs
vm/src/obj/objbytearray.rs
vm/src/stdlib/array.rs

Added `__ne__` methods to array and bytearray.
#1442

Implement __ne__ methods for array, bytearray

---

vm/src/obj/objtype.rs

I am not sure this is correct way, but it seems passing tests anyway

call_tp_new uses single iterator

---

vm/src/stdlib/os.rs

https://github.com/python/cpython/blob/master/Modules/posixmodule.c#L11911
https://docs.python.org/3/library/os.html#os.abort

Implement os.abort

---

Lib/test/test_long.py
vm/src/obj/objint.rs

It seems kinda rough code though, it passes the tests.
I'd like to get advice to improve this code.

Test lshift of zero

---

Lib/test/test_grammar.py
compiler/src/symboltable.rs

Fix nonlocal incompatibility

---

Lib/test/test_dict.py
vm/src/obj/objdict.rs

Modified inner_eq to inner_cmp so that dict_iterator can use and added rich comparison for dict_iterator.

Add rich comparison for dict_iterator

---

derive/src/pyclass.rs
vm/src/macros.rs
vm/src/obj/objbuiltinfunc.rs
vm/src/obj/objfunction.rs
vm/src/obj/objobject.rs
vm/src/obj/objtype.rs
vm/src/obj/objweakref.rs
vm/src/pyobjectrc.rs
vm/src/slots.rs
vm/src/stdlib/io.rs
vm/src/stdlib/json.rs
vm/src/vm.rs

slot optimization 2

---

benchmarks/bench.rs
benchmarks/benchmarks/pystone.py
bytecode/src/bytecode.rs
vm/src/frame.rs
vm/src/obj/objdict.rs
vm/src/obj/objframe.rs
vm/src/obj/objfunction.rs
vm/src/obj/objmodule.rs
vm/src/obj/objobject.rs
vm/src/obj/objsuper.rs
vm/src/obj/objtype.rs
vm/src/pyobject.rs
vm/src/scope.rs
vm/src/slots.rs
vm/src/stdlib/thread.rs
vm/src/types.rs
vm/src/vm.rs

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `./rustpython-norm pystone.py 50000` | 9.068 ± 0.422 | 8.567 | 10.075 | 1.14 ± 0.06 |
| `./rustpython-opt pystone.py 50000` | 7.934 ± 0.155 | 7.724 | 8.179 | 1.00 |

getattro slot

---

vm/src/stdlib/thread.rs
vm/src/vm.rs

Add vm.start_thread() and related functions

---

wasm/demo/src/index.ejs
wasm/notebook/src/index.js
wasm/notebook/src/parser.js
wasm/notebook/src/sample.txt
wasm/notebook/webpack.config.js

Add proper syntax highlighting for wasm notebook

---

vm/src/stdlib/pystruct.rs

https://github.com/rust-lang/rustfmt/issues/4462

Fix clippy error

---

Lib/pickle.py
Lib/test/test_array.py
Lib/test/test_bytes.py
Lib/test/test_memoryview.py
Lib/test/test_os.py
Lib/test/test_struct.py
derive/src/pyclass.rs
extra_tests/snippets/memoryview.py
extra_tests/snippets/stdlib_struct.py
extra_tests/snippets/stdlib_xdrlib.py
vm/src/bytesinner.rs
vm/src/byteslike.rs
vm/src/obj/objbytearray.rs
vm/src/obj/objbytes.rs
vm/src/obj/objint.rs
vm/src/obj/objlist.rs
vm/src/obj/objmemory.rs
vm/src/obj/objtuple.rs
vm/src/pyobject.rs
vm/src/sliceable.rs
vm/src/slots.rs
vm/src/stdlib/array.rs
vm/src/stdlib/io.rs
vm/src/stdlib/marshal.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/pystruct.rs
vm/src/vm.rs

I add a slot for implement the buffer protocol, more or less like what CPython doing. I am not sure is the right way for RustPython. Also I am confusing about the slots seem do not inherit from the base? So how we control the behavour of the subclass?

Implement Buffer Protocol

---

Lib/random.py

This change makes random._os, found by whats_left.sh.

Update random.py with CPython 3.7 version.

---

common/src/static_cell.rs
derive/src/pyclass.rs
vm/src/pyobject.rs
vm/src/stdlib/socket.rs

Also made some tweaks to socket

Make StaticCell less complex to use

---

Lib/shutil.py
Lib/test/test_os.py
Lib/test/test_shutil.py
extra_tests/snippets/stdlib_os.py
extra_tests/snippets/stdlib_socket.py
vm/src/function.rs
vm/src/stdlib/os.rs
vm/src/stdlib/socket.rs

Add socket function that sends all content of a file through the socket.

Add socket sendfile function

---

vm/src/builtins/dict.rs
vm/src/builtins/function.rs
vm/src/builtins/pytype.rs
vm/src/function/mod.rs
vm/src/stdlib/signal.rs

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `./rustpython-norm benchmarks/pystone.py 50000` | 6.816 ± 0.653 | 6.029 | 7.630 | 1.06 ± 0.11 |
| `./rustpython-opt benchmarks/pystone.py 50000` | 6.410 ± 0.294 | 5.937 | 6.853 | 1.00 |

Replace FuncArgs.insert with prepend_arg, optimize check_signals

---

vm/src/stdlib/ast.rs

Add NamedExpression AST class

---

extra_tests/snippets/builtin_slice.py
extra_tests/snippets/bytearray.py
vm/src/sliceable.rs

use unsigned abs to avoid overflow

---

ast/src/ast.rs
parser/src/fstring.rs
parser/src/parser.rs
parser/src/python.lalrpop

Tested with `cargo test` in `ast`, `parser` and `compiler` directory (as `cargo test --all` would fail to compile for wasm...)

Implements AST Customization (#2388)

---

extra_tests/not_impl_gen.py

There are a number of modules that weren't being checked by the script such as `zlib`, it's actually missing a bunch of constants. This adds 877 more lines to the output of `whats_left.sh` (see this txt: [new_whats_new.txt](https://github.com/RustPython/RustPython/files/5859617/new_whats_new.txt))
These are the modules `ModuleScanner` finds that `pkgutil` doesn't.
```py
['_abc', '_ast', '_bisect', '_blake2', '_codecs', '_collections', '_csv', 
'_datetime', '_elementtree', '_functools', '_heapq', '_imp', '_io', 
'_locale', '_md5', '_operator', '_peg_parser', '_pickle', 
'_posixsubprocess', '_random', '_sha1', '_sha256', '_sha3', '_sha512', 
'_signal', '_socket', '_sre', '_stat', '_statistics', '_string', 
'_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', 
'_weakref', 'array', …
```

Detect modules that aren't python files or directories in whats_left

---

Lib/test/test_slice.py

Hello,
I've set the tests that fail as "expectedFailure", and skipped the test raising an AssertionError.
Hope that's OK! :man:

adding test: test_slice from 3.8.7

---

vm/src/builtins/weakref.rs
vm/src/stdlib/thread.rs

Noticed using changes in #2411

Format IDs as hex

---

Lib/codeop.py
Lib/test/test_codeop.py

This pull request will:
- Update the `codeop` module to the one found in [Python 3.9](https://github.com/python/cpython/tree/3.9)

Upgrade codeop

---

Cargo.lock
Lib/test/test_re.py

Just checking that all tests pass/are there any that are fixed

Update sre-engine dependency

---

vm/src/stdlib/os.rs

Implement `os.getlogin`.
This is still marked as draft, because right now in case of an error, an empty string is returned. However, when testing in a Docker container without a defined login name, I noticed that calling `os.getlogin()` on CPython returns an `OSError` instead:
> OSError: unable to determine login name
I'll fix that tomorrow.
Refs #1175.

Implement os.getlogin

---

bytecode/src/lib.rs
compiler/src/ir.rs

This should fix the CI issue from 3f36dcd.

Run rustfmt

---

vm/src/stdlib/os.rs

Implemented `os.getpriority` and `os.setpriority`.
Ref: #1175

Implement os.getpriority and os.setpriority

---

vm/src/builtins/range.rs

This avoids unnecessary operations, such as clone, multiplication, and division.
For the following microbenchmark, the current master would take time `3.41s, 0.73s, 3.69s`, and it takes `2.27s, 0.50s, 2.60s` after applying this patch.
```python
import time
t0 = time.time()
for i in range(10000000):
pass
t1 = time.time()
print(t1 - t0)
t0 = time.time()
for i in range(0, 10000000, 5):
pass
t1 = time.time()
print(t1 - t0)
t0 = time.time()
for i in range(10000000, 0, -1):
pass
t1 = time.time()
print(t1 - t0)
```
Previously, the `PyRange::get` function takes 30% of the time, and it takes only 10% of execution time after this optimization.
Currently, 34% of the time is spent on `PyDict::inner_itemset_fast` (a lot of time spent on dropping the old value), and about 10% is spent on `BigInt` …

Optimize builtins/range

---

Lib/test/test_subclassinit.py
compiler/src/compile.rs
extra_tests/snippets/class.py
vm/src/builtins/make_module.rs
vm/src/builtins/pytype.rs
vm/src/function.rs

Fixes #2435, and also fixes #2436
@Zomatree, could you verify that your example works now?

Handle splat args in bases/kwargs for __build_class__

---

.github/workflows/ci.yaml
Lib/test/test_asyncgen.py
Lib/test/test_exceptions.py
Lib/test/test_raise.py
vm/src/coroutine.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/iterator.rs
vm/src/sysmodule.rs
vm/src/vm.rs

Also with this change, it'll be easier to unify the except/finally frame block types, if we want to do that.

Rework the vm exception stack to handle errors better

---

Lib/test/test_charmapcodec.py
Lib/test/testcodec.py

with associated support file `testcodec.py`

Add test_charmapcodec from CPython 3.8.7

---

Lib/test/test_enum.py

This adds close to 200 tests that (should) already pass.

Add test_enum from CPython 3.8.7

---

Lib/test/cfgparser.1
Lib/test/cfgparser.2
Lib/test/cfgparser.3
Lib/test/test_configparser.py

This adds over 300 tests that (should) already pass.

Add test_configparser from CPython 3.8.7

---

Lib/test/test_enum.py

Should alleviate the CI failure seen in #2485.

Fix other test_enum unexpected success on Windows

---

Lib/test/test_os.py
vm/src/stdlib/os.rs

`closerange` use `close` internally
Pass 3 more tests in `Lib/test/test_os.py`
Refs #1175.

Implement os.closerange

---

Cargo.lock
vm/src/stdlib/errno.rs
vm/src/stdlib/os.rs
vm/src/stdlib/signal.rs
vm/src/stdlib/socket.rs

Fix compilation on freebsd

---

Cargo.lock
vm/Cargo.toml
vm/src/stdlib/os.rs

Now pass `test_posix.py PosixTester.test_open_dir_fd`
Implement **dir_fd** in
`make_path` and `os.open(path, flags, mode=0o777, *, dir_fd=None)`

Implement dir_fd in os.open

---

extra_tests/not_impl_gen.py

some modules will print something to stdout when imported

remove noise from importing modules in whats_left

---

.github/workflows/cron-ci.yaml

Try running cron-ci benchmarks with cargo-criterion

---

vm/src/stdlib/os.rs

os: Implement copy_file_range

---

Cargo.lock
Lib/test/test_re.py

Upgrade sre-engine

---

bytecode/src/lib.rs
common/src/float_ops.rs
derive/src/compile_bytecode.rs
vm/src/vm.rs

As described in #2522, it's nice to get some documentation going.
This is my first crack at it, mostly focused on the bytecode crate. I'd really appreciate any feedback on it!
I've left some TODOs that can either be fixed in this PR or be left for future ones. In particular I believe concrete examples would help a lot but I don't think I can construct realistic example scenarios, maybe there are some suggestions?

Documentation of VM & Bytecode

---

README.md

Replaces defunct 'codingworkshops' project

Add Robot Rumble to use cases

---

Lib/test/test_zlib.py
vm/src/stdlib/zlib.rs

- Pass data chunks on a slice-by-slice basis to compression API
- decompress method: Amend error message
This is my first PR in Rust :grin:
Please let me know if I've made any mistakes / if there's anything I could improve on!

Change data chunk passing in Rust zlib compression

---

Lib/test/test_array.py
Lib/test/test_class.py
Lib/test/test_index.py
Lib/test/test_memoryio.py
Lib/test/test_range.py
Lib/test/test_zlib.py
vm/src/builtins/int.rs
vm/src/pyobject.rs

- add a special_retrieve fudge function to the PyValue trait
- define the special_retrieve function for PyInt
- remove blocks on successful tests to reflect effect of changes

Type checking for __index__-defined integers

---

.github/workflows/ci.yaml
Cargo.lock
vm/Cargo.toml
vm/src/stdlib/mod.rs
vm/src/stdlib/scproxy.rs

on the way to go to `--install-pip` for macos

module _scproxy

---

Lib/test/test_os.py
vm/src/stdlib/os.rs

os: implement `repr` for `DirEntry`

---

vm/src/stdlib/socket.rs
vm/src/stdlib/ssl.rs

Update _ssl to use select()/poll() to handle sockets w/ timeouts

---

Cargo.toml
Lib/_codecs.py
Lib/importlib/_bootstrap.py
Lib/test/test_configparser.py
Lib/test/test_fileio.py
Lib/test/test_importlib/test_open.py
Lib/test/test_importlib/test_read.py
Lib/test/test_io.py
Lib/test/test_memoryio.py
Lib/test/test_regrtest.py
Lib/test/test_runpy.py
common/src/str.rs
extra_tests/snippets/stdlib_sys.py
vm/Cargo.toml
vm/pylib-crate/Cargo.toml
vm/src/builtins/pystr.rs
vm/src/byteslike.rs
vm/src/import.rs
vm/src/stdlib/io.rs
vm/src/vm.rs

Properly implement TextIOWrapper using codecs

---

Lib/test/subprocessdata/fd_status.py
Lib/test/subprocessdata/input_reader.py
Lib/test/subprocessdata/qcat.py
Lib/test/subprocessdata/qgrep.py
Lib/test/subprocessdata/sigchild_ignore.py
Lib/test/test_subprocess.py

This one's a doozy, and it may contain flaky tests.

Add test_subprocess from CPython 3.8

---

.github/workflows/ci.yaml
.github/workflows/cron-ci.yaml
extra_tests/test_snippets.py
vm/src/stdlib/io.rs
vm/src/stdlib/select.rs

Fix install-pip regressions

---

vm/src/stdlib/os.rs

Follow-up to #2654, cc @fanninpm

Cache stat result in DirEntry to fix spurious CI failures

---

README.md

Correct documentation link

---

Lib/bisect.py
Lib/test/test_bisect.py
vm/src/stdlib/bisect.rs
vm/src/stdlib/mod.rs

Adds bisect functionality implemented in Rust.

Add Rust accelerator module for bisect.

---

vm/src/builtins/make_module.rs
vm/src/frame.rs
vm/src/vm.rs

Add after binops in `vm.rs` and handle them in a similar fashion. Update frame and `abs` to forward calls to them.

Refactor unary ops.

---

Lib/shelve.py
Lib/test/test_shelve.py

Add shelve.py from CPython 3.8

---

Lib/test/test_posix.py

Help developers to find failure by better documenting it.

test: add reason of failure for tests

---

vm/src/stdlib/io.rs

The name is a "pun" on `usize` - `s/u/Utf8`

Use a Utf8size struct to represent the {bytes,chars} pairs in textio

---

Lib/test/test_uu.py

@coolreader18 is this module really necessary?

Add test_uu from CPython 3.8

---

vm/src/builtins/set.rs

Previously, `zelf.keys` was called for every invocation of `next`resulting in an unfortunate quadratic runtime. This pr just grabs keys and makes them part of the iterator instead. As a result, iterating through a set iterator is now linear.
This should speed up the test-suite by, I'm hoping, at least a minute or two. Specifically `test_itertools` has improved _a lot_ since it has many calls of the form `sorted(set_instance)` with large sets.

Make set iteration linear

---

Lib/test/test_os.py
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs

os: fix fdopen invalid file descriptor

---

extra_tests/snippets/builtins_module.py
extra_tests/snippets/name.py
vm/src/builtins/make_module.rs

Fixes #2757 
Can be tested with:
```
cargo run --release extra_tests/snippets/name.py
```

Fix builtins.__name__

---

common/src/boxvec.rs
vm/src/builtins/function/jitfunc.rs
vm/src/stdlib/ssl.rs
wasm/lib/src/js_module.rs
wasm/lib/src/lib.rs

Clippy's suggestion isn't working (and going through `self.iter` causes `importlib` to seemingly hang locally) so I'm just `allow`ing it for this case.

clippy: Fix remaining issues

---

Lib/test/test_reprlib.py
extra_tests/snippets/builtin_type.py
vm/src/builtins/builtinfunc.rs

Adds correct `__repr__` to `PyBuiltinMethod`

---

Lib/test/test_deque.py

hello I have added test_deque.py from CPython 3.8.7 
if there is any issue plz let me know
I will fix it asap
thanks in prior

added test_deque.py from CPython 3.8.7

---

extra_tests/snippets/builtin_type.py
vm/src/builtins/builtinfunc.rs

Adds `__qualname__` to `PyBuiltinFunction`

---

Lib/test/test_exception_hierarchy.py
Lib/test/test_socket.py
vm/src/stdlib/socket.rs

There is one todo that is waiting for hstrerror to land in libc crate.
For now it shows the same error as cpython when hstrerror is not
available.

socket: impl herror

---

Lib/test/test_math.py
vm/src/stdlib/math.rs

I implemented `math.comb` function.
As I am new to Rust, if there is any other suggestions, please give me some advice :)

Add math.comb function

---

extra_tests/snippets/builtin_exceptions.py
vm/src/exceptions.rs

Fixes infinite recursion on `raise e from e`

---

extra_tests/snippets/builtin_type.py
vm/src/builtins/function.rs

Fixes `repr` of functions defined in classes

---

Lib/test/test_float.py
extra_tests/snippets/stdlib_math.py
vm/src/builtins/float.rs

Originally pull requested by @fanninpm [#2456]

Add __floor__ and __ceil__ to float w/ tests

---

Lib/test/test_deque.py
vm/src/stdlib/collections.rs

resolve #2838 
add `deque.__iadd__` method

add deque __iadd__ method

---

vm/src/frame.rs

Fixed unwrapping in frame.rs

---

extra_tests/snippets/dict_union.py
vm/src/builtins/dict.rs

closes #2832
with proper test cases

Fix make dict.{__or__,__ror__,__ior__} with other types return NotImplemented

---

vm/src/builtins/object.rs
vm/src/builtins/pytype.rs
vm/src/slots.rs
vm/src/vm.rs

this was the last typeslot with mismatching name

tp_cmp -> tp_richcompare

---

extra_tests/snippets/bytes.py
extra_tests/snippets/strings.py
vm/src/builtins/pystr.rs

`id()` for `str` stays the same after `* 1`

---

vm/src/builtins/classmethod.rs
vm/src/builtins/complex.rs
vm/src/builtins/range.rs
vm/src/builtins/slice.rs
vm/src/exceptions.rs
vm/src/stdlib/hashlib.rs
vm/src/stdlib/re.rs

Follow up to:
- https://github.com/RustPython/RustPython/pull/2863
- https://github.com/RustPython/RustPython/pull/2861

Cleans up `pyproperty` definitions

---

Lib/test/test_iterlen.py
Lib/test/test_list.py
vm/src/builtins/list.rs

Refactor common functionality of `__reduce__` and `__setstate__` in functions.

Fix pickling, length hint, iteration for reverse list iterators. 

---

Lib/test/test_os.py
vm/src/stdlib/os.rs

Fix os sendfile

---

Lib/test/test_set.py
vm/src/builtins/set.rs

Also fixes a minor issue with `set.__new__`'s signature.
I added an `elements` method for inner for this that just exposes the underlying `keys`.

Add reduce for set, frozenset.

---

Lib/test/test_deque.py
Lib/test/test_iterlen.py
vm/src/stdlib/collections.rs

Add reverse deque iterator.

---

Lib/test/test_math.py
Lib/test/test_statistics.py
vm/src/stdlib/math.rs

I implemented math.prod function and enabled its tests.
However, I have a problems to deal with the test which I commented below.
Please suggest better solution for this if there is an nice idea :)

Add math.prod function and enable its tests

---

vm/src/pyobject.rs

add_slot_wrappers must be called up to once
