vm/src/frame.rs
This pull request resolves #2799.
Because the implementation of [`ItemProtocol<T>.set_item(…)` for `PyDictRef`][itemprotocol-setitem-for-pydictref] can return `Err` having `TypeError` when `key` implemented [`Unhashable`][unhashable], it should not call `unwrap`. So, this pull request removed calling `unwrap` and used `?` operator.
[itemprotocol-setitem-for-pydictref]: https://github.com/RustPython/RustPython/blob/53b8067acd1af79c2081e9eb56586fa8955749fd/vm/src/builtins/dict.rs#L527-L534
[unhashable]: https://github.com/RustPython/RustPython/blob/53b8067acd1af79c2081e9eb56586fa8955749fd/vm/src/slots.rs#L219-L228
=> Fix incorrect unwrapping

extra_tests/snippets/builtin_type.py, vm/src/builtins/pytype.rs
Closes #2762
Now it matches the CPython behavior: 
Changes:
- now `__prepare__` is a `classmethod`
- first argument can be any object, not just `str`
- all arguments are optional
https://docs.python.org/3/reference/datamodel.html#preparing-the-class-namespace
=> Makes args of `type.__prepare__` optional

Lib/test/test_index.py, vm/src/builtins/range.rs
This revision fix **RangeTestCase.test_range** test in [test_index.py](https://github.com/RustPython/RustPython/blob/master/Lib/test/test_index.py#L248)
`TryFromObject` implementation for `RangeIndex` enum did not cover classes
that override `__index__` operator which cpython implementation is currently providing
(https://docs.python.org/3.8/library/operator.html#operator.__index__)
I add codes that cover the above case using `vm.to_index` method.
```rust
impl TryFromObject for RangeIndex {
fn try_from_object(vm: &VirtualMachine, obj: PyObjectRef) -> PyResult<Self> {
match_class!(match obj {
i @ PyInt => Ok(RangeIndex::Int(i)),
s @ PySlice => Ok(RangeIndex::Slice(s)),
obj => Err(vm.new_type_error(format!(
"sequence indices be integers or slices, not '{}'",
obj.class().name,
))),
})
}
} …
```
=> Add __index__ operator overriding class support for RangeIndex

derive/src/pyclass.rs, extra_tests/snippets/builtin_type.py, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/getset.rs, vm/src/builtins/property.rs, vm/src/builtins/pytype.rs, vm/src/exceptions.rs, vm/src/pyobject.rs, vm/src/stdlib/pyexpat.rs, wasm/lib/src/js_module.rs, wasm/lib/src/wasm_builtins.rs
In the next PR I will also fix the `repr` of `getset` as well.
Changes:
- New `class` field on `PyGetSet`
- New arguments to `new_getset` and `new_readonly_getset`
- Fixed how `derive` is constructing types
- Fixes all `.new_getset` and `.new_readonly_getset` calls
- Also fixes recent `class` argument order in `new_method` from #2770 to be consistent: name, class, functions
CPython impl: https://github.com/python/cpython/blob/635bfe8162981332b36cc556bac78e869af579c2/Objects/descrobject.c#L572-L599
Closes #2790
=> Adds `class` field to `PyGetSet` to fix `__qualname__`

vm/src/slots.rs
Noticed this while working on #2814. Doesn't appear this trait is used anywhere yet (`rg Desctuctor` returned nothing else in the repo), so it was a simple fix.
=> typo in slots.rs: SlotDesctuctor -> SlotDestructor

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
Closes #2813.
I am assuming that the way this trait is structured (the struct must implement `Hashable`, which is then overruled by the implementation of `Unhashable`) is required by how Rust checks for trait implementations? Like the hash function wouldn't work otherwise.
=> implement Unhashable for collections.deque

extra_tests/snippets/builtin_type.py, vm/src/builtins/pytype.rs
Implementation now matches CPython: https://github.com/python/cpython/blob/cee67fa66129b5d1db5c8aa3884338f82f0da3de/Objects/typeobject.c#L5380-L5384
Closes #2794
=> Adds `__subclasshook__` to `type`

Lib/test/test_index.py, vm/src/sliceable.rs
This revision fix three test cases in [test_index.py](https://github.com/RustPython/RustPython/blob/master/Lib/test/test_index.py)
* `SeqTestCase.test_index`
* `SeqTestCase.test_wrappers`
* `ListTestCase.test_setdelitem`
All these three cases' failures were caused by not supporting classes
that override `__index__` operator when indexing sequence type.
This commit implement almost same routine with PR(#2807) which also did not
support classes that override `__index__` operator in range indexing.
=> Add __index__ operator overriding class support for SequenceIndex

derive/src/pyclass.rs
Using `rustpython_common` results in lookup errors in `pymodule/pyclass` macros when using rustpython as a dependency.
=> Use rustpython_common via public name.

src/lib.rs
This pull request resolves #2822.
For testing, please see #2822 's testcases. 🙏🏻 
I tried to code like [CPython `add_main_module` does](https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Python/pylifecycle.c#L1612-L1658).
=> Add missing `__annotations__`  variable into main module

Lib/test/test_math.py, vm/src/stdlib/math.rs
Added `math_perm` method.
Unfortunately, test only fails when `k` is `None`.
=> Add `math_perm` method

Lib/test/test_bytes.py, vm/src/builtins/bytearray.rs, vm/src/bytesinner.rs
- `__alloc__` differs from CPython's `bytearray.__alloc__` due to the difference in the underlying storage used.
- `__init__` now controls actual initialization instead of `__new__`. `__new__` now also accepts `*args, **kwargs` as required.
=> Add __alloc__ to bytearray and fix its __init__ issues.

Lib/test/seq_tests.py, vm/src/builtins/tuple.rs
Refs #2840
Reference: https://github.com/python/cpython/blob/c0ab59f7de1906feee21c057ad433fad924d1e38/Objects/tupleobject.c#L560-L567
=> Fixes that `id()` of `tuple` was changing on `* 1`

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
Closes #2834
Note: at the moment almost all collections are missing `MemoryError` corner case, like here: https://github.com/python/cpython/blob/d1ae57027fc39ff60dcfc1b63881400e5ca3ce56/Modules/_collectionsmodule.c#L709-L711
I guess that this is out of scope of this task, related:
- https://github.com/RustPython/RustPython/issues/1750
- https://github.com/RustPython/RustPython/pull/1779
I think that some tests in `test_deque` might hang because of that.
=> Adds `__rmul__` to `collections.deque`

extra_tests/snippets/bytes.py, vm/src/builtins/bytes.rs
Refs #2840
Only `str` is left.
=> `id()` for `bytes` stays the same after `* 1`

Lib/test/test_iterlen.py, vm/src/builtins/dict.rs
All the iterators misreported their length after exhaustion.
=> Fix length hint for dictionary iterators.

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
before: 
when idx >= len it doesn't insert the element to the end
it inserted to index len-1
after:  
when idx >= len it inserts the element to the end of the deque
=> support deque.insert when idx is gte to len

Lib/test/test_deque.py, extra_tests/snippets/stdlib_collections.py, vm/src/stdlib/collections.rs
before: RustPython hangs when
d = deque('a')
d.extend(d)
after: it extends to the copy of it
I'll fix the temporary change in deque.__iadd__ with another PR
=> support deque.extend recursive call

vm/src/stdlib/itertools.rs
Only a single `pyclassmethod` was invalid 🎉 
I think that this is the last PR in this series: https://github.com/RustPython/RustPython/pull/2867
All other usages like `pyattr` and `pyslot` are fine 👍
=> Cleans up `pyclassmethod` definition

vm/src/stdlib/os.rs, vm/src/stdlib/posixsubprocess.rs
Commit https://github.com/RustPython/RustPython/commit/ca5c07b9f35f0bbc7d697f1d9d8810a12bfdc85e introduces a number of `cargo` warnings about unused imports. This is a naive attempt to solve its warnings.
=> Removes unused imports

.vscode/launch.json, .vscode/tasks.json
vscode's auto-generated lldb doesn't catch the exception.
I edited it a bit using `preLaunchTask`
this template will be helpful for people who want to use debugger
=> vscode lldb configuration template

Lib/test/test_set.py, vm/src/builtins/set.rs
If the item passed to a sets `{remove, discard, contains}` is a set/set subclass, retry the operation after converting it to a frozenset.
=> Retrying contains, remove, discard with a frozenset.

vm/src/buffer.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/make_module.rs, vm/src/builtins/memory.rs, vm/src/bytesinner.rs, vm/src/byteslike.rs, vm/src/cformat.rs, vm/src/lib.rs, vm/src/pyobject.rs, vm/src/slots.rs, vm/src/stdlib/array.rs, vm/src/stdlib/binascii.rs, vm/src/stdlib/codecs.rs, vm/src/stdlib/fcntl.rs, vm/src/stdlib/io.rs, vm/src/stdlib/marshal.rs, vm/src/stdlib/multiprocessing.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/os.rs, vm/src/stdlib/pyexpat.rs, vm/src/stdlib/pystruct.rs, vm/src/stdlib/socket.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/ssl.rs, vm/src/stdlib/zlib.rs, wasm/lib/src/convert.rs
TryFromBorrowedObject reduces unnessessary cloning.
PyBuffer is a trait for buffer protocol but hidden in memory view codes. Giving it a sole module will be a guideline for future protocols.
renamed `PyBytesLike`, `PyRwBytesLike` and `BufOrStr` into `ArgBytesLike`, `ArgMemoryBuffer` and `ArgStrOrBytesLike` by following the description of `getarg.c`. Let's keep `Py` prefixes only for actual python objects.
closes #2854
=> give an own module for buffer protocol + TryFromBorrowedObject

Lib/test/test_enum.py, vm/src/builtins/pytype.rs
This pull request resolves #2869.
```
>>>>> class A: ...
>>>>> A.__new__
<bound method __new__ of <class '__main__.A'>>
>>>>> object.__new__
<bound method __new__ of <class 'object'>>
>>>>> A.__new__ == object.__new__
False
```
```
>>>>> class A: ...
>>>>> A.__new__
<bound method __new__ of <class 'object'>>
>>>>> object.__new__
<bound method __new__ of <class 'object'>>
>>>>> A.__new__ == object.__new__
True
```
=> Remove unnecessary slot wrapper addition

Lib/test/test_set.py, vm/src/builtins/set.rs
This revision fixes issue #2877
implementation referenced on `imul` method of `PyList`.
```python
>>>>> f = frozenset(range(1000))
>>>>> f2 = f.copy()
>>>>> f is f2
False
```
```python
>>>>> f = frozenset(range(1000))
>>>>> f2 = f.copy()
>>>>> f is f2
True
```
=> Fix frozenset copy to return self

Lib/test/test_math.py, vm/src/stdlib/math.rs
add two conditions to raise ValueError for input values
case 1: NaN, when both input values are finite, and base is negative and exponent is non-integer
case 2: divde by zero, when base is 0 exponent is negative value
=> Fix failed test pow in test_math

Lib/test/test_syntax.py, compiler/src/symboltable.rs
This revision fixes `test_global_parap_err_first` test in
[test_syntax.py](https://github.com/RustPython/RustPython/blob/master/Lib/test/test_syntax.py#L678) and implement the other syntax errors detection as cpython 3.8 provided for global symbol.
* name {} is parameter and global
```python
>>>>> def test(a):
.....   global a
.....
SyntaxError: name 'a' is parameter and global at line 2 column 2
global a
```
* annotated name {} can't be global
```python
>>>>> def test():
.....   a: int
.....   global a
.....
SyntaxError: annotated name 'a' can't be global at line 3 column 2
global a
```
* name {} is assigned to before global description
```python
>>>>> a = 100
>>>>> def test():
.....   a = 10
.....   global a
.....
SyntaxError: name 'a' is assigned to before global declaration at line 3 …
```
=> Add syntax error detection routine for global symbol

Lib/test/lock_tests.py, Lib/test/test_importlib/test_locks.py
Temporarily so that other PRs don't get stalled until its fixed. Note that these don't hang consistently, they do hang often, though.
=> Skip tests that cause RustPython to hang.

Lib/test/test_iter.py, vm/src/builtins/pystr.rs
This revision implements the missing `PyTuple` reverse iterator and methods for `PyStrIterator` and `PyReverseIterator`
```python
>>>>> t = reversed(tuple('hello'))
>>>>> t.__reduce__()
(<built-in function iter>, (('h', 'e', 'l', 'l', 'o'),), 4)
>>>>> t.__setstate__(2)
>>>>> t.__reduce__()
(<built-in function iter>, (('h', 'e', 'l', 'l', 'o'),), 2)
>>>>> operator.length_hint(t)
3
>>>>> list(t)
['l', 'e', 'h']
```
```python
>>>>> s = 'hello'
>>>>> s = iter('hello')
>>>>> s.__reduce__()
(<built-in function iter>, ('hello',), 0)
>>>>> s.__setstate__(2)
>>>>> s.__reduce__()
(<built-in function iter>, ('hello',), 2)
>>>>> operator.length_hint(s)
3
>>>>> list(s)
['l', 'l', 'o']
```
```python
>>>>> s = reversed('hello')
>>>>> s.__reduce__()
(<built-in function reversed>, ('hello',), 4)
>>>>> …
```
=> Implement missing Iterator & ReverseIterator and its methods

vm/src/builtins/builtinfunc.rs, vm/src/builtins/object.rs, vm/src/builtins/pytype.rs, vm/src/pyobject.rs, vm/src/slots.rs
This pull request tries to resolve #2410 
This pull request does:
- Fill 'object' type's missing docstrings 0b52d0c 
- Introduce new `__text_signature__` property to `PyType`, `PyBuiltinMethod`, `PyBuiltinFunction`. 40ab1c4 
```python
print(object.__str__.__text_signature__)  # expected `($self, /)`
print(object.__text_signature__)  # expected `()`
print(type.__text_signature__)  # expected `None` (no output)
```
- parse `__text_signature__` logic: https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Objects/typeobject.c#L183-L203
=> Introduce `__text_signature__` property

Lib/test/test_dict.py, vm/src/builtins/dict.rs, vm/src/dictdatatype.rs
dict entries was changed due to remain order even when delete any element. #2902 
in this PR, i only adjust dict reverse iterator next function to this new dict entries structure.
however, there remains some issue about detecting the change while iteration.
before, the size change was equivalent to the change of the dictionary entries, so it was easy to detect it
however, making deletion not to erase entries, and insertion occurs on next_new_entry_idx, it is hard to detect change during iteration.
all iterators with dict may have this issue.
=> adjust dict reverse iterator next to new dict entries structure

Lib/importlib/_bootstrap_external.py, vm/src/builtins/dict.rs, vm/src/builtins/float.rs, vm/src/builtins/set.rs, vm/src/frame.rs, vm/src/function.rs, vm/src/import.rs, vm/src/pyobject.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/imp.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/pystruct.rs, vm/src/stdlib/signal.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/time.rs, vm/src/stdlib/winapi.rs, vm/src/sysmodule.rs, vm/src/vm.rs
I used `codespell -L crate,struc,ser,ans,numer -w vm/`
https://github.com/codespell-project/codespell
=> Fixes typos in vm/

Lib/typing.py, vm/src/builtins/object.rs, vm/src/builtins/pytype.rs, vm/src/pyobject.rs
(Eventually, if this ends up getting merged, this will close #2622 and close #2658.)
I haven't gotten this module to import cleanly if I mostly take it from CPython 3.8 sources:
```none
>>>>> import typing
File "~/Documents/GitHub/RustPython/vm/pylib-crate/Lib/typing.py", line 1572, in <module>
class SupportsAbs(Protocol[T_co]):
TypeError: '_ProtocolMeta' object is not subscriptable
```
Line 1572 is the first occurence of a class inheriting from `Protocol[T_co]` rather than `Protocol`. Did the syntax change between CPython 3.6 and CPython 3.7?
Let me know how we can get around this.
=> Update typing to CPython 3.8

Lib/test/test_genericclass.py, vm/src/builtins/make_module.rs, vm/src/builtins/object.rs, vm/src/builtins/pytype.rs, vm/src/pyobject.rs
Because it was treating `__class_getitem__` as a special method, subscripting a type from `typing` would just always return `type` instead of some sort of `_GenericAlias`
=> Fix __class_getitem__ slightly

vm/src/builtins/dict.rs, vm/src/dictdatatype.rs
in #2915, there was a comment to use only fetch_add, not using load & store to maintain atomic operation.
since dict iterator has this load & store, change to use fetch_add.
=> make dict iterator use atomic operation

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
resolve deque deadlock while iteration
by using CPython method, added state property to PyDeque.
by using state, RustPython can detect mutation while iterating.
=> resolve deque deadlock using state

extra_tests/snippets/list.py, vm/src/builtins/list.rs
This revision fix #2919 in some part.
Current `count`, `contains`, `remove` and `index` methods in `PyList` implementation does not unlock the read guard before entering loop.
If there is something try to lock the write guard while iterating loops, rustpython die.
With this fix, there is no more deadlock, but resulting values from that methods slightly incompatible with cpython.
```python
class test:
def __eq__(self, other):
self.d.pop()
return True
t = test()
d = [1,2,t,3,4]
t.d = d
d.count(4) 
```
=> Fix list entering deadlock in several methods

extra_tests/snippets/stdlib_collections.py, vm/src/stdlib/collections.rs
=> Fix deque repr hang if element __repr__ mutates.

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
before: `deque.index` only work when start and end was not given. 
after: this function now can handle when start and end is given
=> support deuqe.index using start, end index

Lib/enum.py, Lib/test/test_enum.py, Lib/test/test_httplib.py, vm/src/builtins/mappingproxy.rs
Currently, there is a bug to find a key from itself and the base types not only its attributes. If there was user defined class named `A`, `"__setattr__" in A.__dict__` returns `True` because `object` has `__setattr__` though `A` class doesn't.
```python
>>>>> "__setattr__" in type.__dict__
True
>>>>> "__setattr__" in object.__dict__
True
>>>>> class A: ...
>>>>> "__setattr__" in A.__dict__
True
```
```python
>>>>> "__setattr__" in type.__dict__
True
>>>>> "__setattr__" in object.__dict__
True
>>>>> class A: ...
>>>>> "__setattr__" in A.__dict__
False
```
=> Find key from only its attributes

src/shell/helper.rs
Closes #2925.
The panic appeared in debug builds but, even in release mode, the behavior was wrong. (tab wasn't inserted in REPL).
=> Fix panic (debug), no indend (release) in REPL.

Lib/test/test_deque.py, vm/src/stdlib/collections.rs
this PR resolves `deque.rotate` panics when abs(mid) is larger than deque length
=> resolve deque.rotate panic

extra_tests/snippets/stdlib_array.py, vm/src/stdlib/array.rs
Fixes a panic when an empty array was indexed. Uses `PySliceableSequence::wrap_index` as other collections do.
=> Fixes panic when empty array is indexed.

vm/src/stdlib/os.rs
this implements `os.nice` (which linked to a unix system call, changing process priority) function. 
with this commit, rustpyhton works as below. 
```python 
>>>>> import os
>>>>> os.nice(0)
0
>>>>> os.nice(-1)
-1
>>>>> os.nice(-10)
-11
>>>>> os.nice(10)
-1
>>>>> os.nice(20)
19
>>>>> os.nice(20)
19
>>>>> os.nice(-20)
-1
>>>>> os.nice(-12)
-13
>>>>> os.nice(-100)
-20
```
=> os: implement os.nice 

extra_tests/snippets/bytes.py, vm/src/builtins/bytes.rs
This revision implement `bytes.__bytes__` in cpython 3.11 for typing module.
* https://docs.python.org/3.11/whatsnew/3.11.html#other-cpython-implementation-changes
* https://bugs.python.org/issue24234
=> Implement `bytes.__bytes__`

extra_tests/snippets/complex.py, vm/src/builtins/complex.rs
This revision implement `complex.__complex__` which will be added in cpython 3.11 for `typing` module.
* https://docs.python.org/3.11/whatsnew/3.11.html#other-cpython-implementation-changes
* https://bugs.python.org/issue24234
=> implement `complex.__complex__`

Lib/test/test_deque.py, extra_tests/snippets/deque.py, vm/src/stdlib/collections.rs
add `__new__` function to deque iterator, and reverse deque iterator
this allows to create iterator instance using type instance. for example,
```
klass = type(iter(deque()))
a = klass(deque('abcd'))
```
creates a deque iterator instance
=> add __new__ method to deque iterator and reverse iterator

Lib/test/test_array.py, Lib/test/test_bytes.py, Lib/test/test_list.py, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/list.rs, vm/src/builtins/pystr.rs, vm/src/builtins/tuple.rs, vm/src/bytesinner.rs, vm/src/sequence.rs, vm/src/stdlib/array.rs, vm/src/stdlib/collections.rs, vm/src/vm.rs
This add the checking required to detect *most* of the `MemoryError`s during `repeat`. In addition to that, I've renamed most arguments for the repeat value to `value` to match CPython's and made the internal multiplication functions take `usize`'s since the conversion can be performed earlier.
=> Check for MemoryErrors when repeating sequences.

Lib/test/test_array.py, vm/src/stdlib/array.rs
Test cases:
UTF32 related work will be done later in a dedicated PR.
whitespace-ignoring review link: https://github.com/RustPython/RustPython/pull/2937/files?w=1
=> Implement `array::_array_reconstructor`

Lib/test/test_typechecks.py, Lib/test/test_typing.py, vm/src/builtins/mappingproxy.rs
When we run the Python code like below:
```python
class A: ...
print(A.__dict__.items())
print(A.__dict__.get("__hash__", "NONE"))
```
We can't find `__hash__` anywhere and will see `NONE` output because there is no `__hash__` method.
Let's see the output from the execution result of CPython implementation.
```
dict_items([('__module__', '__main__'), ('__dict__', <attribute '__dict__' of 'A' objects>), ('__weakref__', <attribute '__weakref__' of 'A' objects>), ('__doc__', None)])
NONE
```
But RustPython implementation fetches the `object.__hash__` method though it doesn't have.
```
dict_items([('__dict__', <getset_descriptor object at 0x556b113c8460>), ('__module__', '__main__'), ('__qualname__', 'A'), ('__doc__', None)])
<method '__hash__' of 'object' objects>
```
So this pull request …
=> Fix `PyMappingProxy::get`

Lib/test/test_iterlen.py, Lib/test/test_set.py, extra_tests/snippets/set.py, vm/src/builtins/set.rs
Uses the underlying `Dict` to perform the iteration similar to how the dictionary iterators do. This leads to a slight improvement since the elements Vec isn't constructed (which was constructed to temporarily avoid the previous `O(N**2)` implementation of set iteration).
=> Improve set iteration, add __reduce__

Lib/test/test_reprlib.py, vm/src/builtins/object.rs
Before this pull request, there was a bug where `object`'s repr message is not compatible with CPython implementation.
When you run the below code:
```python
class A:
def a(self):
class C:
...
print(repr(C()))
print(repr(A()))
A().a()
```
CPython implementation prints the following lines:
```
<__main__.A object at 0x7f9411fca7f0>
<__main__.A.a.<locals>.C object at 0x7f9411fca790>
```
But RustPython implementation does:
```
<A object at 0x555d487e75c0>
<C object at 0x555d487bdc20>
```
It was because `object.__repr__` used only `__name__` without `__module__`, `__qualname__`. 😢 
https://github.com/RustPython/RustPython/blob/f1e81c991e3a0eec3708110075e6bb5a3c280e72/vm/src/builtins/object.rs#L185-L189
- [`object.__repr__` CPython implementation](https://github.com/python/cpython/blob/7e246a3a7 …
=> Correct `object.__repr__` format

Lib/test/test_iterlen.py, vm/src/iterator.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/itertools.rs, vm/src/vm.rs
Length hint is called on the object passed to `extract_elements` and not on its iterator.
In addition, `get_all` was removed since the context in which it is used can be replaced with `extract_elements` (which also has better runtime performance).
=> Call `__length_hint__` before extracting elements

ast/src/location.rs
I think the error message has unnecessary linebreak.
When we execute `eval("1.0e_1")`
* in CPython
```bash
>>> eval("1.0e_1")
File "<string>", line 1
1.0e_1
^
SyntaxError: unexpected EOF while parsing
```
* in RustPython
```bash
>>>>> eval("1.0e_1")
SyntaxError: Invalid Syntax at line 1 column 4
1.0e_1
↑
```
=> Remove unnecessary linebreak

Lib/test/test_dataclasses.py, Lib/test/test_reprlib.py, vm/src/builtins/object.rs, vm/src/builtins/pytype.rs
This pull request fixes `object.__repr__` implementation.
- [`object_repr` implementation](https://github.com/python/cpython/blob/f9242d50b18572ef0d584a1c815ed08d1a38e4f4/Objects/typeobject.c#L4518-L4544)
=> Correct `object.__repr__`

vm/src/codecs.rs
Thanks to @coolreader18 for pointing this out [here.](https://github.com/RustPython/RustPython/pull/3002#discussion_r706352084)
=> Fix comparison in codecs.rs that always failed

Lib/test/test_cmath.py, vm/src/builtins/complex.rs, vm/src/stdlib/cmath.rs, vm/src/stdlib/mod.rs
The minimum structure needed for the tests to be able to execute. The functions that remain can be good first issues for anyone interested.
I've purposely not used macros similar to `math.rs` since we can't capture docs for them (though that could be an easy fix) and we don't generate the signature for them in they aren't marked as `pyfunction`s.
=> Add cmath module.

common/src/float_ops.rs, vm/src/anystr.rs, vm/src/builtins/pystr.rs, vm/src/bytesinner.rs, vm/src/stdlib/cmath.rs, vm/src/stdlib/math.rs, vm/src/stdlib/sre.rs, vm/src/sysmodule.rs
Replace occurrences of module constants with associated constants since the latter will be deprecated at some point as per their docs. Only change not made is in `math_remainder` since #3037 will take care of that.
=> Use associated constants instead of module constants.

Lib/test/test_math.py, vm/src/stdlib/math.rs
add conditions for below rules (specified in test codes)
1. remainder(x, inf) is x, for non-NaN non-infinite x
2. According to IEEE 754-2008 7.2(f)
2-1. remainder(x, 0) for non-NaN x is invalid operation
2-2. remainder(infinity, x) for non-NaN x is invalid operation
=> Fix failed test remainder in test_math

Cargo.lock, Cargo.toml, build.rs
add precommit to RustPython
it runs `cargo clippy` / `cargo fmt --all` /  `git add -u` before commit
by running `cargo clean && cargo build`, it adds git hooks to the project.
=> add precommit which runs  clippy & fmt

Cargo.toml
cc @eldpswp99 
I found this is breaking partial commit workflow at all.
`cargo clean` and rerunning will regenerate pre-commit.
=> revert git-add from precommit

derive/src/pyclass.rs, derive/src/pymodule.rs, derive/src/util.rs
This just allows builtin functions to use the same machinery, a number of enhancements are still required after this, though.
=> Try to generate a text signature template for both methods and functions

vm/src/sysmodule.rs
`warnoptions` is initialized further down (correctly) using the `warnopts` variable.
=> Remove duplicate entry for warnoptions.

Lib/test/exception_hierarchy.txt, derive/src/lib.rs, derive/src/pyclass.rs, derive/src/pymodule.rs, derive/src/util.rs, extra_tests/snippets/builtin_exceptions.py, vm/src/builtins/make_module.rs, vm/src/exceptions.rs
So, I've decided to go with the simplest `extend_exception!` I can think of.
Why?
1. It solves the problem
2. It is flexible enough to write any code we want
2. We already had something similar in `pub fn extend(ctx: &PyContext)`
3. We don't actually need exception structs
4. We cannot write fancy things with module level declarations, because we don't have `ctx` yet
---
**Update**: it was really hard to make it work with subclasses ad custom `__new__` and `__init__` in mind.
So, I've switched to a more complex `struct`-based macro.
Closes #2973 
Refs #2960
Refs #2897
=> All exceptions are now modified with `extend_exception!` macro

Cargo.lock, derive/Cargo.toml, derive/src/pyclass.rs, derive/src/pymodule.rs, derive/src/util.rs
Make signature errors show the funciton signature instead of macro attribute
=> better error message when pymethod/pyproperty signature is wrong

Lib/test/test_ast.py, Lib/test/test_collections.py, Lib/test/test_configparser.py, Lib/test/test_enum.py, Lib/unittest/test/test_discovery.py, vm/src/builtins/pytype.rs, vm/src/slots.rs
`HEAPTYPE` isn't set for built-in types, instead only used for dynamically created types. (see `<bltin_type>.__flags__ & (1 << 9)`)
The errors that appear now are a result of this, `copyreg` doesn't know how to `__reduce__` types that don't have the `HEAPTYPE` flag so any builtins that lack it require an implementation of `__reduce__` (currently, `Exception` types and types defined in `_ast` it seems).
=> Remove HEAPTYPE flag from builtins.

Lib/test/test_cmath.py, vm/src/stdlib/cmath.rs
Relates to #3039
Added `cmath.log()` and `cmath.log10()`
=> Add cmath log() and log10() methods

Lib/test/test_syslog.py, vm/src/builtins/pystr.rs, vm/src/stdlib/mod.rs, vm/src/stdlib/os.rs, vm/src/stdlib/socket.rs, vm/src/stdlib/ssl.rs, vm/src/stdlib/syslog.rs, vm/src/utils.rs
=> Implement `syslog` module for unix

vm/src/stdlib/os.rs
Targets such as i686-unknown-linux-gnu have a [c_long definition of i32](https://docs.rs/libc/0.2/i686-unknown-linux-gnu/libc/type.c_long.html), so assuming that [`libc::pathconf`](https://docs.rs/libc/0.2.102/i686-unknown-linux-gnu/libc/fn.pathconf.html) returns an i64 will cause a compilation error on such platforms.
This patch fixes that by adding a cast to i64, which is valid as `c_long` is only ever i32 or i64, meaning this is either a no-op or a sign extension.
=> Fix compilation on unix platforms with i32 c_long

Lib/test/test_os.py, vm/src/builtins/int.rs, vm/src/stdlib/os.rs
Implement tp_new for `stat_result`
To unpack args, this PR implement a `flatten_args` closure to
unpack args like
```
args = (1, 2, 3, 4, 5, 6)
args = ((1, 2, 3, 4, 5, 6))
args = (((1, 2, 3, 4, 5, 6)))  # from pickle load
```
=> os: fix stat_result test

Lib/test/test_types.py, Lib/types.py, vm/src/builtins/genericalias.rs, vm/src/builtins/list.rs, vm/src/builtins/mod.rs, vm/src/types.rs
- Introduce `types.GenericAlias` type.  [7790ecb]
- Add `list.__class_getitem__` method.  [057a748]
- Bump `types` module to CPython 3.9.7 [ea53510, b9cf020]
This pull request will resolve #3079.
This pull request introduces `types.GenericAlias` type, introduced in CPython 3.9, and is the type of `list[int]` or `dict[str, int]`. It can be accessed from `types` module. And there are some features not been implemented yet.
As more description, this `types.GenericAlias` type has a test named `test.test_genericalias` but the test requires `contextvars`:
```python
File "Lib/test/test_genericalias.py", line 12, in <module>
from contextvars import ContextVar, Token
ModuleNotFoundError: No module named 'contextvars'
```
And `contextvars` requires `_contextvars`: …
=> Introduce `types.GenericAlias` type

derive/src/lib.rs, derive/src/pyvalue.rs, vm/src/stdlib/array.rs, vm/src/stdlib/ast.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/csv.rs, vm/src/stdlib/hashlib.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/json.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/os.rs, vm/src/stdlib/pyexpat.rs, vm/src/stdlib/pystruct.rs, vm/src/stdlib/random.rs, vm/src/stdlib/re.rs, vm/src/stdlib/select.rs, vm/src/stdlib/socket.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/ssl.rs, vm/src/stdlib/symtable.rs, vm/src/stdlib/thread.rs, vm/src/stdlib/unicodedata.rs, vm/src/stdlib/winreg.rs, vm/src/stdlib/zlib.rs, wasm/lib/src/browser_module.rs, wasm/lib/src/js_module.rs
This seems a big change but actually it is a simple macro that will produce the following implementation
```rust
impl ::rustpython_vm::PyValue for #ty {
fn class(_vm: &VirtualMachine) -> &PyTypeRef {
Self::static_type()
}
}
```
=> impl `#[derive(PyValue)]` for static_type

src/shell/helper.rs, vm/src/anystr.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/dict.rs, vm/src/builtins/iter.rs, vm/src/builtins/list.rs, vm/src/builtins/make_module.rs, vm/src/builtins/pystr.rs, vm/src/builtins/set.rs, vm/src/bytesinner.rs, vm/src/exceptions.rs, vm/src/function.rs, vm/src/function/argument.rs, vm/src/pyobject.rs, vm/src/stdlib/array.rs, vm/src/stdlib/csv.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/math.rs, vm/src/stdlib/os.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/ssl.rs, vm/src/stdlib/thread.rs, wasm/lib/src/browser_module.rs, wasm/lib/src/js_module.rs
which were not a python object but just argument helper
=> Rename Py{Callable, Iterable} to Arg{..}

derive/src/pymodule.rs
```rust
#[pymodule]
mod module_name {
#[pyclass(module="overriden_name")]
struct T { .. }
}
```
Previous behavior: `T.__module__` is `module_name`
Changed behavior: `T.__module__` is `overriden_name`
=> pyclass module priors to umbrella pymodule name

vm/src/stdlib/mod.rs
`io` and `signal` are used elsewhere in the crate so limit their visibility there.
=> Don't export stdlib modules.

vm/src/builtins/make_module.rs, vm/src/builtins/map.rs, vm/src/builtins/set.rs, vm/src/builtins/zip.rs, vm/src/function.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/math.rs, vm/src/stdlib/pystruct.rs, vm/src/stdlib/re.rs, vm/src/stdlib/sre.rs, vm/src/sysmodule.rs, wasm/lib/src/js_module.rs
split from #3104 
`vm::function::Args` needs to be exposed to define functions, but `Args` is too common name.
=> vm::function::{Args -> PosArgs}

vm/src/builtins/function.rs, vm/src/builtins/object.rs, vm/src/builtins/pytype.rs, vm/src/macros.rs, vm/src/pyobject.rs
this issue was first mentioned in #2974 
This makes tp_new to be called by `object.__new__`
for example, with `tuple.__new__`
before: `<bound method __new__ of <class 'tuple'>>`
after: `<bound method object.__new__ of <class 'tuple'>>`
well, i have problem with controlling the new with pysuper, i remain this as draft now
I would be thankful for any advice!
=> make magic method new to follow cpython way

vm/src/builtins/asyncgenerator.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/coroutine.rs, vm/src/builtins/dict.rs, vm/src/builtins/enumerate.rs, vm/src/builtins/filter.rs, vm/src/builtins/generator.rs, vm/src/builtins/iter.rs, vm/src/builtins/list.rs, vm/src/builtins/map.rs, vm/src/builtins/pystr.rs, vm/src/builtins/range.rs, vm/src/builtins/set.rs, vm/src/builtins/tuple.rs, vm/src/builtins/zip.rs, vm/src/slots.rs, vm/src/stdlib/array.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/csv.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/os.rs, vm/src/stdlib/pystruct.rs, wasm/lib/src/js_module.rs
Adaptable for any kind of iterable/iterator with new machanism.
So now `io::_IOBase` also can implement `Iterable` and `PyIter`
This is the same strategy with `Hashable` and `Unhashable`
=> Universal mechanism for Iterator slots

vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/memory.rs, vm/src/byteslike.rs, vm/src/cformat.rs, vm/src/lib.rs, vm/src/protocol/buffer.rs, vm/src/protocol/mod.rs, vm/src/slots.rs, vm/src/stdlib/array.rs, vm/src/stdlib/io.rs, vm/src/stdlib/os.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/winreg.rs
I also renamed `PyBufferInternal` to `BufferInternal` because it is not a CPython type or concept.
replacement of similar work in #3104
=> rustpython_vm::protocol to hold protocols

derive/src/pymodule.rs, src/lib.rs, vm/src/import.rs, vm/src/macros.rs, vm/src/vm.rs, wasm/lib/src/vm_class.rs
This tries to resolve a part of #3101.
This pull request does:
- Use document from the database (i.e. `derive/docs.json`) for modules derived with `rustpython_vm::macros::pymodule` (i.e. `rustpython_derive::pymodule::impl_pymodule`).
But this pull request doesn't achieve the purpose for modules derived with `rustpython_vm::macros::py_module` (though it seems equal with `rustpython_derive::pymodule::impl_pymodule`, maybe it seems left by historical(?) reason 🤔 . You can check this through `_csv` module.
=> Sync some modules' doc with database

Lib/test/test_fileio.py, Lib/test/test_urllib.py, vm/src/exceptions.rs, vm/src/stdlib/os.rs, vm/src/stdlib/posix.rs
Implement OSError members `filename` and `filename2` by adding a new
struct `IOErrorWithFilename` will implement `IntoPyException`.
This PR will *NOT* pass more CPython test(*) but will allow user to
access `attr:filename` in OSError exception which IMO is a important
feacture.
The reason why CPython test failed before is `AttributeError: 'FileNotFoundError' object has no attribute 'filename'`
After this PR the reason will become `AssertionError: ...`
This is because CPython check the identity of `err.filename` to equal the input `filename` which means the only to pass this test is to store the `filename` object directly into `PyPathLike` or `PathOrFd` and return *the* `filename` if error which is how CPython deal with this with `path_t->object`.
=> OSError with filename and filename2

vm/src/builtins/enumerate.rs, vm/src/builtins/genericalias.rs, vm/src/builtins/int.rs, vm/src/builtins/make_module.rs, vm/src/builtins/memory.rs, vm/src/builtins/module.rs, vm/src/stdlib/bisect.rs, vm/src/stdlib/codecs.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/nt.rs, vm/src/stdlib/os.rs, vm/src/stdlib/posix.rs, vm/src/stdlib/posix_compat.rs, vm/src/stdlib/signal.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/ssl.rs, vm/src/stdlib/winreg.rs
Since it implies them being handled as `positional_or_keyword`. Alternatively, an argument without a `pyarg` attribute should be disallowed.
=> Clean up bare occurunces of `[pyarg(any)]`

derive/src/pyclass.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/code.rs, vm/src/builtins/dict.rs, vm/src/builtins/frame.rs, vm/src/builtins/genericalias.rs, vm/src/builtins/getset.rs, vm/src/builtins/list.rs, vm/src/builtins/module.rs, vm/src/builtins/object.rs, vm/src/builtins/property.rs, vm/src/builtins/pytype.rs, vm/src/builtins/range.rs, vm/src/builtins/set.rs, vm/src/builtins/slice.rs, vm/src/exceptions.rs, vm/src/macros.rs, vm/src/pyobject.rs, vm/src/slots.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/hashlib.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/os.rs, vm/src/stdlib/socket.rs, vm/src/stdlib/sys.rs, vm/src/stdlib/thread.rs, vm/src/stdlib/time.rs, vm/src/version.rs
`tp_` prefix is originated from CPython code, which conventionally use those kind of type prefixes for member fields.
RustPython is not following the naming policy, so it doesn't give any meaning to readers.
Renaming it will give more clear meanings about the type `PyTypeSlots` and slot implementation methods name.
=> tp_ -> slot_

Lib/test/test_cmath.py, vm/src/stdlib/cmath.rs
This implement `asinh` in #3039
**Before**
```python
>>>>> import cmath
>>>>> cmath.asinh(2)
AttributeError: module 'cmath' has no attribute 'asinh'
```
**After**
```python
>>>>> import cmath
>>>>> cmath.asinh(2)
(1.4436354751788103+0j)
```
=> Add `asinh` function to `cmath`

Lib/test/test_cmath.py, vm/src/stdlib/cmath.rs
This implement `atan` and `atanh` in #3039
**Before**
```python
>>>>> import cmath
>>>>> cmath.atan(1)
AttributeError: module 'cmath' has no attribute 'atan'
>>>>> cmath.atanh(1)
AttributeError: module 'cmath' has no attribute 'atanh'
```
**After**
```python
>>>>> import cmath
>>>>> cmath.atan(2)
(1.1071487177940904+0j)
>>>>> cmath.atanh(2)
(0.5493061443340549-1.5707963267948966j)
```
=> Add `atanh` and `atan` to `cmath`

vm/src/protocol/iter.rs, vm/src/stdlib/builtins.rs
This revision may resolve #3176 
Add `check` method in `PyIter` as static method and use it at the proper location.
It can be also used in pickle, sqlite, etc (which is not yet implemented in RustPython).
=> Implement `PyIter_Check`

Lib/binhex.py, Lib/test/test__osx_support.py, Lib/test/test_binhex.py, Lib/test/test_cmd_line_script.py, Lib/test/test_codeccallbacks.py, Lib/test/test_trace.py, Lib/test/test_zipapp.py, Lib/test/tracedmodules/__init__.py, Lib/test/tracedmodules/testmod.py, Lib/trace.py, Lib/zipapp.py
This revision add six missing tests from cpython 3.8
* `test_zipapp.py`
* `test_trace.py`
* `test_binhex.py`
* `test_codeccallback.py`
* `test_cmd_line_script.py`
* `test__osx_support.py`
=> Add missing tests from cpython 3.8

common/src/encodings.rs, vm/src/stdlib/codecs.rs
~~Based on the PyPy implementation. The encoding function needs some work with respect to error handling.~~ **EDIT**: Now based on @coolreader18's `ascii` codec.
Requesting @coolreader18 as a potential reviewer, as they wrote the architecture for the `encodings` module and the error handling function(s).
=> Implement latin_1 in Rust

Lib/test/test_cmd_line_script.py
These unexpected successes were created due to the collision of #3158 and #3180.
Unfortunately, due to the timing, this PR won't make the cut for the weekly cron job.
=> Unmark passing tests in `test_cmd_line_script`

bytecode/src/lib.rs
Instead of calling write! with an explicit newline character at the end,
prefer its alternative, writeln!.
Signed-off-by: Tony Jinwoo Ahn <tony.jinwoo.ahn@gmail.com>
=> Replace write! with writeln!

Lib/test/test_dataclasses.py, Lib/test/test_pprint.py, vm/src/builtins/mappingproxy.rs
This revision implements `repr` method of `mappingproxy` type.
There are two case of `repr` in mapping proxy. 
``` python
>>> mappingproxy = type(type.__dict__)
>>> mappingproxy({"ASCII": 256})
mappingproxy({'ASCII': 256})
>>> int.__dict__
mappingproxy({'__repr__': <slot wrapper '__repr__' of 'int' objects>, '__hash__': <slot wrapper '__hash__' of 'int' 
objects>, '__getattribute__': <slot wrapper '__getattribute__' of 'int' objects>, '__lt__': <slot wrapper '__lt__' of 'int' objects>, '__le__': 
<slot wrapper '__le__' of 'int' objects>, '__eq__':  .........(skip).......... })
```
But original rustpython just print `<mappingproxy object at 0x55dc213e7eb0>`.
With this fix, rustpython also print like cpython.
```python
>>>>> mappingproxy = type(type.__dict__)
>>>>> …
```
=> Add missing `repr` for `mappingproxy`

Lib/test/test_base64.py, Lib/test/test_buffer.py, Lib/test/test_zipfile.py, vm/src/stdlib/pystruct.rs
This revision fix the incompatibility behaviour in `pystruct` and add `test_buffer.py` from cpython 3.8.
There exists incompatibility when overflow occurred in `struct.pack`. Here is example
```python
>>> import struct
>>> struct.pack('b', (1<<128)-1)
struct.error: argument out of range
```
```python
>>>>> import struct
>>>>> struct.pack('b', (1<<128)-1)
OverflowError: Python int too large to convert to Rust i8
```
This minor difference make `test_buffer.py` stalled in this lines.
```python
try:
struct.pack(fmt, (1<<exp)-1)
break
except struct.error:
pass
```
`test_buffer.py` is use `struct` and `_testbuffer` module which is not yet implemented. …
=> Fix pystruct incompatibility and Add `test_buffer.py` from cpython 3.8

Lib/test/test_compile.py
@DimitrisJim requested this in https://github.com/RustPython/RustPython/pull/3203#issuecomment-932813341. Most of the failures are because either the `dis` module or the `_ast` module is incomplete.
=> Add test_compile from CPython 3.8

DEVELOPMENT.md
Hey, thanks for creating/maintaining RustPython!
This PR updates the currently failing unit testing instructions on DEVELOPMENT.md and adds instructions to run only specific tests.
Should close #2240
=> Update unit tests instructions, explain how to run them individually

Lib/test/test_named_expressions.py, parser/src/error.rs
This is my first PR. Really excited about this project!
I left the fine-grained error message (E.g., "Got unexpected token ...") because I thought this was helpful to users. This is different than Python 3.8's error message, but still conforms to the unittest expectations (contains "invalid syntax"). LMK if you would prefer the RustPython and CPython to be more consistent. Happy to make any changes.
RustPython:
Python 3.8
=> Fix error message for named expression syntax errors

vm/src/stdlib/sre.rs
For readability, replace exclusive range with inclusive range.
=> Modify range in sre.rs

vm/src/stdlib/collections.rs
This fixes `PyDeque.repr` in #3217 
**before**
```python
>>>>> from collections import deque
>>>>> class MyDeque(deque): pass
>>>>> MyDeque()
deque([])
```
**after**
```python
>>>>> from collections import deque
>>>>> class MyDeque(deque): pass
>>>>> MyDeque()
MyDeque([])
```
=> Fix deque `repr` to print correct format

Lib/test/test_builtin.py, vm/src/stdlib/builtins.rs
`test_chr` used to fail on `chr(-1)` because it would fail to convert the -1 to u32 in `try_to_primitive`, raising an OverflowError.
By changing the received value to a `BigInt`, we're able to match [chr's docs](https://docs.python.org/3.8/library/functions.html#chr) and always raise a `ValueError` if the value is out of range. Note that CPython in turn may raise an `OverflowError` if the argument is too high (platform dependent as it depends on int size), even if it's not documented anywhere.
Another option would be to change the received value to `i32`.
=> Fix test_chr by raising a ValueError on chr(-1) instead of OverflowError

compiler/src/compile.rs
Addresses https://github.com/RustPython/RustPython/issues/2979.
According to [the docs][1], `__debug__` is treated as a constant by the interpreter.
This patch adds some checks to bring RustPython's behaviour in line with cpython's.
[1]: https://docs.python.org/3/library/constants.html#built-in-constants
=> fix: forbid stores to the __debug__ builtin

Lib/test/test_pprint.py, Lib/test/test_set.py, extra_tests/snippets/bytearray.py, extra_tests/snippets/deque.py, extra_tests/snippets/set.py, vm/src/builtins/bytearray.rs, vm/src/builtins/set.rs
Addresses: https://github.com/RustPython/RustPython/issues/3217
This patch changes the `set`, `frozenset`, `deque` and `bytearray`
collections to use the subclass name in `__repr__`, if they are
subclassed.
=> fix: __repr__ use collection subclass name

Lib/test/test_builtin.py, vm/src/builtins/zip.rs
This revision implements optional length-checking to `zip` and its related new methods (`__reduce__`, `__setstate__`).
This is new features in cpython 3.10 stable-release.
If `strict=True` option is given to `zip`, all the iterators to be zipped must have same length.
```python
>>>>> a = [1,2,3]
>>>>> b = (4,5)
>>>>> for k in zip(a,b,strict=True):
.....   print(k)
..... 
(1, 4)
(2, 5)
ValueError: zip() argument 2 is shorter than argument 1
>>>>> for k in zip(b,a,strict=True):
.....   print(k)
..... 
(4, 1)
(5, 2)
ValueError: zip() argument 2 is longer than argument 1
```
also implement `__setstate__` and `__reduce__` for the `strict` parameter in …
=> Add length check, `reduce`, `setstate` on zip from cpython 3.10

stdlib/src/array.rs, stdlib/src/bisect.rs, vm/src/builtins/int.rs, vm/src/stdlib/builtins.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/itertools.rs
by using `try_to_primitive`. There's probably other cases where the error is explicitly handled yet.
=> Clean up overflow cases.

stdlib/src/json.rs, stdlib/src/select.rs, stdlib/src/syslog.rs, stdlib/src/termios.rs, vm/src/builtins/pytype.rs, vm/src/codecs.rs, vm/src/exceptions.rs, vm/src/function.rs, vm/src/pyobject.rs, vm/src/slots.rs, vm/src/stdlib/ast.rs, vm/src/stdlib/io.rs, vm/src/stdlib/os.rs, vm/src/stdlib/time.rs, vm/src/vm.rs
as counterpart of TryFromObject::try_from_object
This is useful when the type to infer is known
=> PyObjectRef::try_into_value

extra_tests/snippets/dict_union.py
Fixes #3212, or at least I believe. Let me know if anything is wrong.
After this PR, running 
```
pytest snippets/dict_union.py
```
in the "extra_tests" folder does not give any error.
The expected outcomes of the tests was computed with CPython 3.9.7 as follows:
```
[frazar@hostname extra_tests]$ python
Python 3.9.7 (default, Aug 31 2021, 13:28:12)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> d={1:2}
>>> d.__ior__('FooBar')
ValueError: dictionary update sequence element #0 has length 1; 2 is required
>>> d.__ior__(42)
TypeError: 'int' object is not iterable
>>> d.__ior__([36])
Traceback (most …
```
=> Align dict union test outcomes with CPython 3.9

vm/src/exceptions.rs
In CPython, `__str__` and `__repr__` for `OSError` show different results.
This PR try to match this behavior but without the part after the
message (in following example is "'123' -> '456'").
```
In : exc.__repr__()
Out: "FileNotFoundError(2, 'No such file or directory')"
In : exc.__str__()
Out: "[Errno 2] No such file or directory: '123' -> '456'"
In : exc.args
Out: (2, 'No such file or directory')
```
=> Implement __str__ for OSError

stdlib/src/csv.rs, stdlib/src/ssl.rs, stdlib/src/zlib.rs
This pull request fixes typo of types manually created. You can check these changes are valid fixups through the below lines:
```python
import _csv, zlib, _ssl
print(_csv.Error, zlib.error, _ssl.SSLError, _ssl.SSLCertVerificationError, _ssl.SSLZeroReturnError, _ssl.SSLWantReadError, _ssl.SSLWantWriteError, _ssl.SSLSyscallError, _ssl.SSLEOFError)
```
`python3 test.py`
```
<class '_csv.Error'> <class 'zlib.error'> <class 'ssl.SSLError'> <class 'ssl.SSLCertVerificationError'> <class 'ssl.SSLZeroReturnError'> <class 'ssl.SSLWantReadError'> <class 'ssl.SSLWantWriteError'> <class 'ssl.SSLSyscallError'> <class 'ssl.SSLEOFError'>
```
`cargo run --features=ssl -- test.py`
```
<class 'Error'> <class 'error'> <class 'SSLError'> <class 'SSLCertVerificationError'> <class 'SSLZeroReturnError'> <class …
```
=> Correct typo of types manually created

Lib/test/test_format.py, vm/src/cformat.rs
Fixing up string formatting only required fixing how %a was handled, and a tweak to exception text.
Bytes formatting appears to have been based on the string formatting code, so didn't capture where CPython behaves differently between bytes and str formatting, and didn't handle bytearrays at all: the changes there are a little more involved.
I've made atomic commits, so reviewing commit-wise should work.
=> cformat.rs: fixes to get two test_format.py tests passing

benches/README.md
Correct the file location of the index.html file. 
Found this while tinkering with the benches. HTH.
=> Fix typo in benches readme.

Lib/test/test_genericalias.py, extra_tests/snippets/test_typing.py, vm/src/builtins/genericalias.rs
This revision fix some misworking functions
* Fix original `make_parameters` & `subs_tvars`
* `test_parameters` and `test_parameter_chaining` tests now going success
I removed `extra_tests/snippets/test_typing.py` which I added in #3374, that I had been thought there are no tests for
using `TypeVar` with `GenericAlias`. It is actually covered by `test_parameter_chaining` in `test_genericalias.py`
@moreal Could you review this [commit](https://github.com/RustPython/RustPython/commit/59a2ade1cb3f3677e6c4c50b287f70548f76b333)? As you originally added this commit, I'd be a pleasure if you review this one 😊
In cpython, only they push parameters if they are not already exist. I fixed that mismatch between rustpython.
=> Fix `GenericAlias` parameter chaining

extra_tests/snippets/stdlib_binascii.py, extra_tests/snippets/stdlib_socket.py, extra_tests/snippets/stdlib_struct.py, extra_tests/snippets/stdlib_termios.py, stdlib/src/binascii.rs, stdlib/src/socket.rs, stdlib/src/termios.rs, vm/src/macros.rs, vm/src/pyobject.rs, vm/src/stdlib/pystruct.rs
In CPython's PyErr_NewException[0], the dotted "module.name" passed in is
split on that dot: the content before the dot is set as __module__ in
the created exception class, and the content after it is set as
__name__.
This commit mirrors that behaviour, by introducing a `module` argument
to `PyContext.new_class`: if Some("module_name") is passed, it will be
set as `__module__`.  All exception-creating uses of `new_class` are
updated to pass in their module and class names separately.
[0] https://github.com/python/cpython/blob/main/Python/errors.c#L1082-L1087
=> correctly set __module__ and __name__ for builtin exceptions

Lib/test/test_posix.py, Lib/test/test_tarfile.py, vm/src/exceptions.rs
As was: "FileNotFoundError: [Errno 2] No such file or directory (os error 2)"
To be: "FileNotFoundError: [Errno 2] No such file or directory (os error 2): 'filename' -> 'filename2'"
Reference CPython implementation
```
if (self->filename) {
if (self->filename2) {
return PyUnicode_FromFormat("[Errno %S] %S: %R -> %R",
OR_NONE(self->myerrno),
OR_NONE(self->strerror),
self->filename,
self->filename2);
} else {
return PyUnicode_FromFormat("[Errno %S] %S: %R",
OR_NONE(self->myerrno),
OR_NONE(self->strerror),
self->filename);
}
}
if (self->myerrno && self->strerror)
return PyUnicode_FromFormat("[Errno %S] %S",
self->myerrno, self->strerror);
```
=> os: implement os-error-str according to CPython

whats_left.sh
Hi! 👋
First of all, thanks a lot for this project. This is my first PR, don't hesitate to tell me if I'm completely off the topic! 
I wanted to see where I could help so I run `whats_left.sh` (on MacOS Monterey). Unfortunately Black was not able to find the generated file `not_impl.py`.
```
Usage: black [OPTIONS] [SRC]...
Try 'black -h' for help.
Error: Invalid value for '[SRC]...': Path 'extra_tests/snippets/not_impl.py' does not exist.
```
I found out that this file was generated inside `extra_tests/` directory and not in `extra_tests/snippets/` so I just fixed the path in `whats_left.sh`.
After this little fix, it works as expected. 
Have a good day,
Matthieu.
=> fix `not_impl.py` path for black in `whats_left.sh`

vm/src/builtins/genericalias.rs
@Snowapril a review would be great if you could.
=> Disallow kwargs from genericalias `__new__`.

vm/src/builtins/range.rs
`Unconstructible` handles forbidding instantiation.
=> Remove slot_new for longrange_iterator.

Lib/test/test_format.py, Lib/test/test_types.py, common/src/float_ops.rs, vm/src/cformat.rs, vm/src/format.rs
With one exception, which I'll comment on inline. Otherwise, commits are atomic.
=> cformat.rs: fix remaining test_format.test_common_format failures

Lib/test/test_positional_only_arg.py, vm/src/builtins/function.rs
Fix a error message which appears when a number of positional arguments are less than expected. 
This fix is to pass some test cases in `Lib/test/test_positional_only_arg.py`
=> fix error message for checking number of positional arguments

derive/src/pymodule.rs, derive/src/util.rs, stdlib/src/binascii.rs, stdlib/src/csv.rs, stdlib/src/socket.rs, stdlib/src/ssl.rs, stdlib/src/termios.rs, stdlib/src/zlib.rs, vm/src/pyobject.rs, vm/src/stdlib/pystruct.rs
This revision implements below
*  with procedural-macro, auto-wrapping `#[pyattr(once)]` attached functions with static_cell! codes
*  refactor duplicated codes in several functions with `#[pyattr]` attached.
*  add `new_exception_type` method for creating module-level exceptions.
=> Refactor duplicated codes in exception creations

extra_tests/not_impl_gen.py
https://github.com/RustPython/RustPython/issues/2410 was resolved by #2904. So this pull request removes the staled lines from `extra_tests/not_impl_gen.py`
=> Remove staled comments

ast/src/location.rs
in windows, arrow is not shown
and crahsed.
changed to another arrow that's
compatible
=> arrow crash in windows

vm/src/builtins/pytype.rs
Address issue #3419
Guided by @youknowone in PyCon APAC 2021 sprint
=> Allow writing union types as X | Y

Lib/test/test_base64.py, vm/src/builtins/memory.rs
This pr is to fix [test_base64.py](https://github.com/24seconds/RustPython/blob/dd773b3413017955db8639968b0a286adfa05e61/Lib/test/test_base64.py) test failure. Turned out most of them are related to `memoryview`'s `cast` function.
In the Cpython,  `cast` function's argument `shape` seems to support `list` and `tuple` type.
https://github.com/python/cpython/blob/af9ee57b96cb872df6574e36027cc753417605f9/Objects/memoryobject.c#L1367-L1418  
But RustPython currently supports `list` only. 
So this pr did those below
- Change `CastArgs` shape field type to `OptionalArg<PyObjectRef>`
- Check shape type is one of list or tuple
- convert shape properly
Because many `test_base64.py` tests are related to this problem, most of them are resolved after fix.
For the check, I ran these. If there is …
=> Support tuple type also for memoryview shape arg

Lib/test/test_hashlib.py, stdlib/src/hashlib.rs
This PR is related to #3467 
I add "usedforsecurity" as a optional keyword argument to hash functions in hashlib.
I also copy test_hashlib.py from CPython v3.9.9 and mark some tests expectedFailure
=> feat(hashlib): add usedforsecurity kwarg to hash functions

vm/src/stdlib/builtins.rs
According to `whats_left.sh` printing, that `True`, `False`, `None` constants must be registered at builtins
=> Register `True`, `False`, `None` to builtins

Lib/test/support/import_helper.py
`frozen_modules` requires non-trivial changes in import (`imp.rs`)
and from the doc it is deprecated since 3.3 which makes this feacture
unlikely to be support on this project.
So instead of implementing this feature, I make `frozen_modules` to
raise exception if `frozen` is required. Other than that, all implementation
is just like the upstream version (except one TODO comment to remind
us there is something not fully supported)
=> import_helper: refactor `frozen_modules`

vm/src/builtins/genericalias.rs
While making #3497 work, I found `types.GenericAlias.__getitem__` wasn't exposed. This pull request just makes it 
You can run the below lines to test.
```
import typing
type(list[int]).__getitem__(list[typing.T], ...)  # expect list[...]
```
Before this pull request, you can see:
```
>>>>> import typing
>>>>> type(list[int]).__getitem__(list[typing.T], ...)
AttributeError: type object 'GenericAlias' has no attribute '__getitem__'. Did you mean: '__setattr__'?
```
=> Expose `types.GenericAlias.__getitem__`

Lib/inspect.py, Lib/test/test_abc.py, vm/src/builtins/classmethod.rs, vm/src/builtins/property.rs, vm/src/builtins/staticmethod.rs
Includes a minor departure from CPython implementation of `inspect.isabstract` because TPFLAGS_IS_ABSTRACT is not set in `obj.__flags__`. Not sure if this is a problem but happy to revert this change if it is.
=> Fix __isabstractmethod__ for class/static methods and properties

Lib/test/test_decorators.py, Lib/test/test_shlex.py, derive/src/pyclass.rs, derive/src/util.rs, vm/src/builtins/builtinfunc.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/pystr.rs, vm/src/builtins/staticmethod.rs
**What this PR does / why we need it:**
This PR added `staticmethod` in macros. And apply it to `maketrans` and changed `staticmethod` to be callable.
- Change `staticmethod` to be callable as in 3.10.x 
- Apply `staticmethod` to maketrans 
- Remove unexpected successes in `test_shlex`
See
- https://docs.python.org/3.10/library/stdtypes.html?highlight=maketrans#str.maketrans
- https://docs.python.org/3/whatsnew/3.10.html#other-language-changes
AS-IS
```python
$ target/debug/rustpython
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> def abc():
.....   print('hello')
..... 
>>>>> staticmethod(abc)()
TypeError: 'staticmethod' object is not callable
```
TO-BE
```python
$ target/debug/rustpython
Welcome …
```
=> Add staticmethod in macros and apply it to maketrans

Lib/filecmp.py, Lib/test/test_filecmp.py, Lib/test/test_genericalias.py
Copy `filecmp` module and tests from cpython v3.10.2
Enable `filecmp` in Lib/test/test_genericalias.py
Run the tests:
```
$ cargo run --release -- -m test test_filecmp -v
== RustPython 3.9.0alpha (heads/module-filecmp:7b7378509, Jan 23 2022, 21:05:31) [rustc 1.58.1]
== macOS-11.6.1-x86_64-64bit little-endian
== cwd: /private/var/folders/fv/652pf8d94lg8fmxym5m8g9xh0000gn/T/test_python_607
== CPU count: 8
== encodings: locale=UTF-8, FS=utf-8
Run tests sequentially
0:00:00 load avg: 8.81 [1/1] test_filecmp
test_cmpfiles (test.test_filecmp.DirCompareTestCase) ... ok
test_default_ignores (test.test_filecmp.DirCompareTestCase) ... ok
test_dircmp (test.test_filecmp.DirCompareTestCase) ... ok
test_dircmp_subdirs_type (test.test_filecmp.DirCompareTestCase)
Check that dircmp.subdirs respects …
```
=> Add the filecmp module from cpython v3.10.2

Lib/test/test_typing.py, Lib/typing.py, vm/src/builtins/pytype.rs
In CPython implementation, immutable types (usually bulletins types) doesn't allow `type.__name__` setter but heap types allow `<TYPE>.__name__` setter. For example, there is `typing.io`. You can see also the 2733202 commit.
So this pull request does:
- Allow heap types' `__name__` setter.
- Don't split the name if it is heap type.
```python
>>> type.__name__ = "foo"
TypeError: cannot set '__name__' attribute of immutable type 'type'
>>> class io: ...
... 
>>> io.__name__ = "typing.io"
>>> io.__name__
'typing.io'
```
```python
>>>>> type.__name__ = "foo"
TypeError: cannot set '__name__' attribute of immutable type 'type'
>>>>> class io: ...
>>>>> …
```
=> Allow heap types' `__name__` setter

vm/src/stdlib/itertools.rs
=> Allow kwargs in itertools.combinations() signature

Lib/test/libregrtest/runtest_mp.py
Running the Python unit tests `cargo run --release -- -m test` with `-j <n>` failed, because of a missing import.
=> Fix: parallel execution of python unit tests

Lib/test/test_typing.py, Lib/typing.py
After #3527, `typing.re` initialization also became able to be corrected. This pull request does it.
=> Correct `typing.re` initialization

extra_tests/snippets/fstrings.py, parser/src/fstring.rs, parser/src/snapshots/rustpython_parser__fstring__tests__fstring_parse_selfdocumenting_format.snap, parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_nested_spec.snap, parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_not_nested_spec.snap
I was using CPython 3.9's `Lib/test/test_fstring.py` as an implementation guide to track my progress, but there's still a long way to go, particularly w/r/t escape sequences.
Should fix #3531.
=> Fix f-string format spec

Lib/test/test_complex.py, vm/src/builtins/complex.rs
This revision removes below special method from `complex` class
* `__int__`
* `__float__`
* `__floordiv__`
* `__mod__`
* `__divmod__`
* `__rfloordiv__`
* `__rmod__`
* `__rdivmod__`
According to [Cpython 3.10 changes](https://docs.python.org/3.10/whatsnew/3.10.html#removed), these special methods of complex class are removed as **they always raise `TypeError`**.
reference : https://bugs.python.org/issue41974
=> Remove several special method of complex class

Lib/test/test_threading.py, common/src/cmp.rs, derive/src/pyclass.rs, derive/src/pymodule.rs, stdlib/src/socket.rs, vm/src/builtins/slice.rs, vm/src/cformat.rs, vm/src/stdlib/io.rs
Clippy lints fixed:
- [`let_underscore_lock`](https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_lock)
- [`unnecessary_lazy_evaluations`](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations)
- [`unwrap_or_else_default`](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_else_default)
- [`needless_late_init`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_late_init)
=> Fix Clippy lints introduced in Rust 1.59

Lib/test/test_zlib.py, stdlib/src/zlib.rs
In this revision, 
* Arguments wrapping has been done in both zlib `compress` and `decompress` functions .
* In `test/test_zlib.py`, test_keywords unit test is completed.
=> Arguments wrapping in zlib functions

Lib/test/test_exception_hierarchy.py, stdlib/src/select.rs
`builtins::PyTypeRef` added
Added `socket error` to `select`
=> Add select.error

Lib/test/test_posix.py, vm/src/stdlib/os.rs
In CPython this error message is constructed by path_converter in
posixmodule.c[0].
[0] https://github.com/python/cpython/blob/main/Modules/posixmodule.c#L1260
=> stdlib/os.rs: update wrong-type exception text for __fspath__

vm/src/frame.rs
RustPython doesn't check the return type of `__format__` in f-string, and will panic when `__format__` not returning `str`
```python
class A:
def __format__(self, format_spec):
return 0
a = A()
print(f'{a}')
```
It should raise `TypeError: __format__ must return a str, not int` instead, as what `format(a, '')` and `'{}'.format(a)` are doing.
=> Add __format__ type check in f-string

Lib/contextvars.py, Lib/test/test_context.py, stdlib/src/contextvars.rs, stdlib/src/lib.rs
This is currently scaffolding for the `contextvars` module introduced in CPython 3.7 (see PEP 567).
I'm welcome to any suggestions on how to flesh this out.
=> Add contextvars from CPython 3.8

Lib/test/test_asyncgen.py, vm/src/stdlib/builtins.rs
the caller is expected to make sure that the passed in object does in
fact supports the protocol
relates #3609
=> implement aiter

.github/workflows/cron-ci.yaml
Follow-up from #3640. Related to #3588.
- Install `llvm-tools-preview` on stable in cron-ci
- Update codecov-action to v3
- Tweak lcov commands to not delete everything
=> Fix coverage cronjob

vm/src/builtins/type.rs
I have changed the drain(..) to into_inter() as discussed in #3660 .
=> Changed the drain into into_iter on types.rs

vm/src/builtins/genericalias.rs, vm/src/builtins/module.rs, vm/src/builtins/object.rs, vm/src/builtins/super.rs, vm/src/builtins/union.rs, vm/src/protocol/object.rs, vm/src/stdlib/thread.rs, vm/src/types/slot.rs, vm/src/vm/mod.rs
This revision does the below things.
* Relocate `generic_setattr` from `builtins::object` into `protocol::object`
* Relocate `generic_getattr`, `generic_getattr_opt` from `vm` into object protocol
* Remove duplicate `generic_getattr` in `builtins::object`
ref #3244 
https://docs.python.org/3/c-api/object.html
=> Relocate `PyObject_Generic*` into object protocol

ast/asdl_rs.py
As #3651 replace `PyContext` into `Context`, `asdl_rs.py` also need to reflect it.
refer https://github.com/RustPython/RustPython/commit/a63ad27cd424c63a8a35e651de743e2321b68b51
=> Fix `PyContext` into `Context` in `asdl_rs.py`

Lib/test/test_long.py, vm/src/builtins/int.rs
A BigUint is represented as a vector of BigDigits and it seems that in Rust no allocations can have a size larger than `isize::MAX`. `usize::MAX` is sufficient for shifting purposes here.
Guided by @youknowone in PyCon APAC 2022 spring sprint
=> Fix test_long::test_huge_rshift

extra_tests/snippets/stdlib_array.py, stdlib/src/array.rs
Resolves #3612 
The issue is
> The name of array.array iterator has to be array_iterator but arrayiterator in RustPython.
but it is "The name of array.array iterator has to be **arrayiterator** but **array_iterator** in RustPython", right?
and I also changed also PyArray's name, 
because it looks different from [CPython's](https://github.com/python/cpython/blob/3.8/Modules/arraymodule.c#L2838).
=> Changed pyclass name of PyArray and PyArrayIter #3612

stdlib/src/socket.rs, vm/src/object/ext.rs
See https://github.com/RustPython/RustPython/pull/3716#discussion_r875374802
=> Revert "PyResult<T, E> instead of PyResult<T>"

.github/workflows/ci.yaml
Once 1.62 is relased, we can switch back to stable.
=> Switch clippy to beta

derive/src/pyclass.rs, vm/src/builtins/object.rs, vm/src/class.rs, vm/src/types/slot.rs
I had a look at `object.__sizeof__`. @moreal opened a pull request (#3421) on it last year, but it never got finished.
CPython uses `tp_basicsize`, `tp_itemsize`, and `ob_size` in `__sizeof__`. The intended use of `tp_basicsize` and `tp_itemsize` can be seen, e.g., at  https://docs.python.org/3/extending/newtypes_tutorial.html#defining-new-types. Since new types are implemented different in RustPython we don't need `tp_itemsize` (and `ob_size`).
If merged, this should be the last point for #2898.
Can you give me some feedback? Thanks!
=> Add `object.__sizeof__`

Lib/test/test_deque.py, Lib/test/test_set.py, vm/src/builtins/weakproxy.rs
After a  weakReference and str() call, the two values were different in comparison, resulting in an error
I found it, "weakproxy object" is not have "\_\_str__()" so calling by "parent object" in "\_\_str__()" 
So I added in "weakproxy. rs"  made it and "str()"method is work normally
=> Add weak proxy str

Lib/test/test_builtin.py, vm/src/bytesinner.rs
FileName: `test_builtin.py`
FunctionName: `test_bytearray_translate`
Error: RustPython was throwing wrong `Error`, RustPython was throwing `TypeError`
=> Fixed `test_bytearray_translate` Error

compiler/porcelain/src/lib.rs, compiler/src/compile.rs, compiler/src/mode.rs, vm/src/stdlib/ast.rs, vm/src/vm/mod.rs
This is helpful to evaluate python code and get expression back
example: https://github.com/RustPython/RustPython/pull/3667/commits/718b013201423b6d2b5e7afddaf95d85303eb256
=> Add compile::Mode::BlockExpr

vm/src/vm/context.rs
Add Context::empty_bytes like empty_tuple in [issue](https://github.com/RustPython/RustPython/issues/3765)
closes #3765
=> Add Context::empty_bytes

derive/src/compile_bytecode.rs, extra_tests/snippets/stdlib_dir_module.py, vm/src/vm/mod.rs
Assume we have a directory structure like this:
```
test
nested_test_1
nested_test_2
```
Expected module names are:
```
nested_test_1
nested_test-1.nested_test-2
```
However in the actual result was:
```
nested_test_1
nested_test-1nested_test-2
```
the '.' separator missing
=> Fix broken module_names in compile_dir for sub-directories

extra_tests/snippets/syntax_decimal.py, parser/src/lexer.rs
Try to fix #3796 
In cpython:
```
>>> 0.E
File "<stdin>", line 1
0.E
^
SyntaxError: invalid decimal literal
```
After this patch , RustPython:
```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> 0.E
SyntaxError: Invalid decimal literal at line 1 column 4
0.E
^
```
=> fix panic when parsing invalid decimal, close #3796

stdlib/src/array.rs, stdlib/src/mmap.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/builtins/list.rs, vm/src/builtins/str.rs, vm/src/builtins/tuple.rs, vm/src/sliceable.rs
closed #3786
* rename `get_item_by_index` to `getitem_by_index`
* rename `get_item_by_slice` to `getitem_by_slice`
* rename `set_item_by_index` to `setitem_by_index`
* rename `set_item_by_slice` to `setitem_by_slice`
=> rename for name consistency

Lib/test/list_tests.py, vm/src/builtins/list.rs
* change <code>fn iadd</code>, <code>fn inplace_concat</code> to raise error when non iterable object has passed.
-----------
result of test_list.py
```
e
.................x..................s.................
Ran 54 tests in 0.878s
OK (skipped=1, expected failures=1)
```
=> add list iadd, inplace_concat TypeError for non iterable object

.github/workflows/ci.yaml, Lib/test/test_ntpath.py, Lib/test/test_script_helper.py, Lib/test/test_socket.py, Lib/test/test_socketserver.py, Lib/test/test_strtod.py, Lib/test/test_urllib2_localnet.py, Lib/test/test_xmlrpc.py, Lib/test/test_yield_from.py
The extra flags come from the `buildbottest` rule in CPython's Makefile.
This will enable checking the tests we've been skipping by default (such as network-based tests). This will also report the top 10 slowest tests and will mark a test as failed if it altered the execution environment.
=> Run test suites like how CPython runs theirs

Lib/test/seq_tests.py, extra_tests/snippets/stdlib_collections_deque.py, vm/src/builtins/tuple.rs, vm/src/stdlib/collections.rs
Fix OverflowError when an integer value larger than Rust's isize is entered in the index method of deque.
and add test case for checking this error
before
```
>>>>> from collections import deque
>>>>> deq = deque()
>>>>> deq.index(92233720368547758090,0,11111111111111111111111111111111111111)
OverflowError: Python int too large to convert to Rust isize
```
after
```
>>>>> from collections import deque
>>>>> deq = deque()
>>>>> deq.index(92233720368547758090,0,11111111111111111111111111111111111111)
ValueError: 92233720368547758090 is not in deque
```
=> Fix OverflowError at collections.rs

vm/src/stdlib/itertools.rs
c.f. https://github.com/python/cpython/blob/cf1732619a61f7b7b5223ebaf6be6455d28257f2/Modules/itertoolsmodule.c#L4178-L4182
=> Fix error type in itertools.count constructor

Lib/test/test_socket.py, stdlib/src/socket.rs
The following constants may be missing from either rust's `libc` or the `winapi` crate (as of 4 July 2022):
- `AF_AAL5`
- `NETLINK_SKIP`
- `NETLINK_W1`
- `NETLINK_TCPDIAG`
- `NETLINK_ARPD`
- `NETLINK_ROUTE6`
- `NETLINK_TAPBASE`
- `AF_QIPCRTR`
- `BLUETOOTH_PROTO_L2CAP`
- `BLUETOOTH_PROTO_HCI`
- `SOL_HCI_RAW`
- `SO_HCI_RAW_FILTER`
- `HCI_TIME_STAMP`
- `HCI_DATA_DIR`
- `BLUETOOTH_PROTO_RFCOMM`
- `BTPROTO_SCO`
- `PACKET_HOST`
- `PACKET_BROADCAST`
- `PACKET_MULTICAST`
- `PACKET_OTHERHOST`
- `PACKET_OUTGOING`
- `PACKET_LOOPBACK`
- `PACKET_FASTROUTE`
- `TIPC_ADDR_NAMESEQ`
- `TIPC_ADDR_NAME`
- `TIPC_ADDR_ID`
- `TIPC_ZONE_SCOPE`
- `TIPC_CLUSTER_SCOPE`
- `TIPC_NODE_SCOPE`
- `TIPC_IMPORTANCE`
- `TIPC_SRC_DROPPABLE`
- `TIPC_DEST_DROPPABLE`
- `TIPC_CONN_TIMEOUT`
- `TIPC_LOW_IMPORTANCE`
- …
=> Add `_socket` constants from CPython 3.10

stdlib/src/array.rs
* Change `PyArrayIter` struct to `PyArrayIterator`
=> Refactor: change PyArrayIter name

Lib/test/test_types.py, vm/src/builtins/genericalias.rs, vm/src/builtins/singletons.rs, vm/src/builtins/type.rs, vm/src/builtins/union.rs
I'm focusing on fixing `test_types::UnionTests::test_union_args`.
Modifying or Adding operator or(|) function for python's `Lib/typing.py`.
It fails, however, when the very last check procedures proceed.
The problem is `NoneType` has no `__args__` function.
I tried making that function, but I cannot guess how to do it
cuz I completely don't know how `PyNone` struct works.
Anyway I got pass at least for the previous check routines.
Thx.
=> Fix union args

Lib/test/ann_module5.py, Lib/test/ann_module6.py, Lib/test/test_typing.py, Lib/typing.py
This pull request updates the `typing` module to 3.10.5 in CPython.
=> Update `typing` module to 3.10.5

vm/src/format.rs
Because precision is not allowed in integer format specifier:
In this revision, 
* Precision error handling has been done in `format_int` function. 
Before:
```
>>>>> print('{:.2}'.format(200))
200
```
After:
```
>>>>> print('{:.2}'.format(200))
ValueError: Precision not allowed in integer format specifier
```
=> format_int precision error handling

Lib/test/test_itertools.py, vm/src/stdlib/itertools.rs
#3890 Allows the itertools module mentioned in this issue to be treated as a basetype.
=> Add basetype flag to itertools module

vm/src/builtins/set.rs
This pull request tries to improve `frozenset`'s debug representation. But there is a comment *"implement more detailed, non-recursive Debug formatter`"* 🤔. So if this pull request's change can occur errors, please let me know it 🙏🏻 
For `frozenset([1, 2, "str"])` object, it is represented as `PyFrozenSet {[PyObject PyInt { value: 1 }], [PyObject PyInt { value: 2 }], [PyObject PyStr { value: "str", kind: Ascii, hash: -845154580267954013 }]}`
For `frozenset(['a', frozenset(['a'])])`, it is represented as `PyFrozenSet {[PyObject PyStr { value: "a", kind: Ascii, hash: -1579463412027138821 }], [PyObject PyFrozenSet {[PyObject PyStr { value: "a", kind: Ascii, hash: -1579463412027138821 }]}]}`.
=> Improve frozenset debug representation

Lib/test/test_bytes.py, vm/src/builtins/bytes.rs
`b = b'python'`
`b['a']`
TypeError: bytes indices must be integers or slices or classes that override __index__ operator, not 'str'
=> TypeError: byte indices must be integers or slices or classes that override __index__ operator, not 'str'
=> Fix byte indices must be integers or slices, error message

vm/src/builtins/function.rs, vm/src/builtins/getset.rs, vm/src/stdlib/io.rs
This pull request tries to resolve #3897, #3899. You can run the below code in the main branch (before this pull request) and you'll see the result message like below:
```
>>>>> import sys
>>>>> frame = sys._getframe()
>>>>> del frame.f_trace
AttributeError: attribute 'f_trace' of 'frame' objects is not writable
```
But after this pull request, it became deletable.
```
>>>>> import sys
>>>>> frame = sys._getframe()
>>>>> del frame.f_trace
>>>>> frame.f_trace = "a"
>>>>> frame.f_trace
'a'
>>>>> del frame.f_trace
>>>>> frame.f_trace
```
=> Remove `PyGetSet.deleter`

Lib/test/test_weakref.py, vm/src/builtins/weakproxy.rs
Resolve `test_weakref::ReferencesTestCase::test_basic_proxy`
fix: #3909
=> Fix weakref richcompare

Lib/collections/_defaultdict.py, Lib/test/test_defaultdict.py
Fixes #3933.
cpython's `defaultdict` implementation: https://github.com/python/cpython/blob/3.10/Modules/_collectionsmodule.c#L2160-L2190
=> Add `or`, `ror` and`ior` to `defaultdict`

Lib/test/test_range.py, vm/src/builtins/range.rs
* Check if start + step is greater than sys.maxsize
Close #3936 
An attempt was made to implement the pickle-related function of the range iter, but the implementation was already completed.
The real problem is the difference in behavior with cpython.
In cpython, even if only start + step of range exceeds the range of int, longrange_iter is returned, but in rustpython, only start, stop, and step exceed the range of int.
=> Fix: `range` beyond the isize range

vm/src/stdlib/io.rs
fix #3896 
- python3
```
>>> import io
>>> io.TextIOBase.encoding
<attribute 'encoding' of '_io._TextIOBase' objects>
```
- RustPython
```
>>>>> import io
>>>>> io.TextIOBase.encoding
AttributeError: 'TextIOBase' object has no attribute 'encoding'
```
=> implement TextIOBase encoding attribute

vm/src/stdlib/pwd.rs
In `getpwnam()`, a function used to find user information based on name, name cannot contain null characters.
However, this has not been verified in tests.
=> Fix: check if name contains null byte

extra_tests/snippets/builtin_float.py, vm/src/builtins/float.rs
Fixes #3978.
```
>>>>> import math
>>>>> a = float(math.nan)
>>>>> b = float(math.nan)
>>>>> a is b
>>>>> true
```
- https://github.com/python/cpython/blob/main/Objects/abstract.c#L1633-L1635
- https://github.com/RustPython/RustPython/blob/main/vm/src/builtins/int.rs#L258-L264
=> Fix `PyFloat::py_new` always returning new float object issue

Lib/test/test_float.py, common/src/float_ops.rs, vm/src/cformat.rs, vm/src/format.rs
In this revision, 
* Bugs about precision handling malfunction are fixed.
---
Before:
```
>>>>> print('{:.2}'.format(math.pi))
3.141592653589793
```
After:
```
>>>>> print('{:.2}'.format(math.pi))
3.1
```
---
RUSTPython:
```
print('{}'.format(60.0)) // 60 
print('{}'.format(120.0)) // 120 
```
CPython:
```
print('{}'.format(60.0)) // 60.0
print('{}'.format(120.0)) // 120.0
```
---
RUSTPython:
```
print('{}'.format(math.pi)) // 3.14159
```
CPython:
```
print('{}'.format(math.pi)) // 3.141592653589793
```
---
RUSTPython:
```
print('{:.2}'.format(math.pi)) // 3.1
print('{:.2}'.format(math.pi * 10)) // 31
print('{:.2}'.format(math.pi * 100)) // 3.1e+02
```
CPython:
```
print('{:.2}'.format(math.pi)) // 3.1
print('{:.2}'.format(math.pi * 10)) // 3.1e+01
print('{:.2}'.format(math.pi * 100)) // …
```
=> Precision bug fix when `FormatType` is `None`

stdlib/src/socket.rs
Change the run result msg of 'socket.timeout'
`socket.timeout` ->`TimeoutError`
=> Modify timeout print message

Lib/test/test_base64.py, Lib/test/test_binascii.py, stdlib/src/binascii.rs
Originally, `binascii.unhexlify` raised `ValueError` when odd-length string came. But it should raise `binascii.Error` type error. This pull request does it.
=> Correct `binascii.unhexlify` error type

whats_left.py
With greeting #2448 patch, meta file's location for comparison is moved to `extra_tests/snippets`.
As we registered `extra_tests/not_impl.py` to `.gitignore`, need to relocate it.
=> Relocate generated file location in `whats_left.py`

Cargo.lock, stdlib/Cargo.toml, stdlib/src/lib.rs, stdlib/src/uuid.rs
- Add _uuid module
- Add _uuid function generate_time_safe()
- uuid v1 = generate_time_safe
- Return mac address to node_id if you have mac address or return random generated bytes to node_id if you do not have mac address
=> Add: _uuid module

Lib/test/list_tests.py, Lib/test/test_deque.py, Lib/test/test_list.py, Lib/test/test_userlist.py, vm/src/sequence.rs
This code is tested based on `list_tests.py::CommonTest::test_remove`,
except for lines `352~358` that seem related to `str` test.
=> Update `_mut_iter_equal_skeleton` method

Lib/test/test_sys.py, vm/src/stdlib/sys.rs, vm/src/stdlib/thread.rs
Implementation - `sys.thread_info` 
close: #4014
=> Feature: sys.thread_info

vm/src/stdlib/sys.rs
Remove `stdlib::self` in `sys.rs` and refactoring.
```
warning: unused import: `self`
[151](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:152)
--> vm/src/stdlib/sys.rs:15:18
[152](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:153)
|
[153](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:154)
15 |         stdlib::{self, builtins},
[154](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:155)
|                  ^^^^
[155](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:156)
|
[156](https://github.com/RustPython/RustPython/runs/7802998224?check_suite_focus=true#step:5:157)
= note: …
```
=> Refactor: sys.rs CI problem

Lib/test/test_super.py, vm/src/builtins/type.rs, vm/src/stdlib/builtins.rs, vm/src/vm/context.rs
When a class object is created with metaclass, the following operation is performed.
[https://docs.python.org/3/reference/datamodel.html?highlight=__classcell__#:~:text=CPython implementation detail%3A In,a RuntimeError in Python 3.8](https://docs.python.org/3/reference/datamodel.html?highlight=__classcell__#:~:text=CPython%20implementation%20detail%3A%20In,a%20RuntimeError%20in%20Python%203.8).
**CPython implementation detail:** In CPython 3.6 and later, the `__class__` cell is passed to the metaclass as a `__classcell__` entry in the class namespace. If present, this must be propagated up to the `type.__new__` call in order for the class to be initialised correctly. Failing to do so will result in a [RuntimeError] in Python 3.8.
1. Error handling when `__class__` (the class it belongs …
=> Fix metaclass check classcell

.github/workflows/ci.yaml
Currently, the `cargo clippy` or the CI `Check Rust code with rustfmt and clippy` job failed.
It warns `clippy::derive_partial_eq_without_eq` as unknown lints but it exists in 1.63.0 release. You can see it through https://rust-lang.github.io/rust-clippy/master/.
At the #4046, it updated the toolchain's version to `1.62.1` from `stable` and the `stable` version was `1.63.0`.
But I see the pull request description while writing this pull request's description:
> I need time to check if the failure is our bug or rust regression.
I don't know its context so it may be intended and if then, this pull request should be closed.
=> Update CI toolchain to stable

Lib/test/test_cmd_line.py, Lib/test/test_subprocess.py, extra_tests/snippets/syntax_non_utf8.py, vm/src/stdlib/builtins.rs
It isn't a full perfect solution for `eval` implementation but it fixes:
- `eval` became to receive `bytes` also.
- `eval` raises `ValueError` when there is `null` (`\x00`) character before compiling.
You can see also:
- [`_Py_SourceAsString`](https://github.com/python/cpython/blob/b5e3ea286289fcad12be78480daf3756e350f69f/Python/pythonrun.c#L1820-L1867)
- https://github.com/python/cpython/blob/b5e3ea286289fcad12be78480daf3756e350f69f/Python/bltinmodule.c#L961
```
str = _Py_SourceAsString(source, "eval", "string, bytes or code", &cf, &source_copy);
```
p.s. The message says like it should receive `string` or `bytes` or `code` but it also receives `bytearray` well. 🤔
=> Raise `ValueError` if `\x00` character exists for `eval` argument

stdlib/src/ssl.rs
This PR associated with #4000.
I added `libaray` and `reason` attribute to ssl.SSLError like CPython.
=> Add 'library', 'reason' Attribute to ssl.SSLError

Lib/test/test_threading.py, vm/src/signal.rs, vm/src/stdlib/signal.rs, vm/src/stdlib/thread.rs
Additionally I ran the test below, and it was successful.
```py
from time import sleep
from threading import Thread
from _thread import interrupt_main
import sys
def task():
sleep(3)
print('Interrupting main thread now')
interrupt_main()
thread = Thread(target=task)
thread.start()
try:
print('Main thread waiting...')
sleep(7)
except KeyboardInterrupt:
print('Main interrupted! Exiting.')
sys.exit()
``` 
Close: #3922
=> Feature: _thread.interrupt_main

extra_tests/snippets/syntax_generator.py, parser/python.lalrpop, parser/src/parser.rs, parser/src/snapshots/rustpython_parser__parser__tests__parse_generator_comprehension.snap, parser/src/snapshots/rustpython_parser__parser__tests__parse_if_else_generator_comprehension.snap, parser/src/snapshots/rustpython_parser__parser__tests__parse_named_expression_generator_comprehension.snap
See: #4108.
I noticed this when trying to parse the CPython codebase itself, which has this test (on which `RustPython` throws a syntax error):
```
def test_named_expression_scope_in_genexp(self):
a = 1
b = [1, 2, 3, 4]
genexp = (c := i + a for i in b)
self.assertNotIn("c", locals())
for idx, elem in enumerate(genexp):
self.assertEqual(elem, b[idx] + a)
```
=> Allow named expressions in generator comprehensions

Lib/concurrent/futures/_base.py, Lib/concurrent/futures/process.py, Lib/concurrent/futures/thread.py, Lib/test/test_thread.py, Lib/test/test_threadedtempfile.py, Lib/test/test_threading.py, Lib/test/test_threading_local.py, Lib/threading.py
```
======================================================================
ERROR: test_interrupt_main_invalid_signal (test.test_threading.InterruptMainTests)
File "/Users/user/Projects/RustPython/vm/pylib-crate/Lib/test/test_threading.py", line 1692, in test_interrupt_main_invalid_signal
self.assertRaises(ValueError, _thread.interrupt_main, -1)
AttributeError: module '_thread' has no attribute 'interrupt_main'
```
=> Update thread/threading/concurrent from CPython 3.10.5

compiler/parser/src/fstring.rs, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__fstring_parse_selfdocumenting_base.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__fstring_parse_selfdocumenting_base_more.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__fstring_parse_selfdocumenting_format.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_empty_fstring.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_equals.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_nested_spec.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_not_equals.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_not_nested_spec.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_selfdoc_prec_space.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_selfdoc_trailing_space.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_yield_expr.snap, compiler/parser/src/string.rs, demo.py
Per discussion in #4097, we can now avoid creating a `JoinedStr` entirely when parsing f-strings, and instead return the vector of values.
=> Avoid creating unused JoinedStr in FStringParser

Lib/test/test_builtin.py, vm/src/stdlib/builtins.rs, vm/src/stdlib/sys.rs
- Add built-in `breakpoint` function
```
>>>>> breakpoint()
--Return--
> /Users/igyubong/Desktop/RustPython/Lib/bdb.py(336)set_trace()->None
-> sys.settrace(self.trace_dispatch)
(Pdb) 
```
- [Python breakpoint documentation](https://docs.python.org/3.7/library/functions.html#breakpoint)
- [cpython breakpoint implementation](https://github.com/python/cpython/blob/main/Python/sysmodule.c#L499-L582)
=> Add built-in `breakpoint` function

Lib/test/test_rlcompleter.py, derive/src/pyclass.rs, derive/src/util.rs, vm/src/builtins/descriptor.rs, vm/src/builtins/function.rs, vm/src/builtins/mod.rs, vm/src/builtins/type.rs, vm/src/object/core.rs, vm/src/types/slot.rs, vm/src/types/zoo.rs, vm/src/vm/context.rs
This pull request tries to implement `__slots__` feature with `member_descriptor`.
This pull request doesn't contain `mebmer_descriptor.slots.descr_get` yet and it'll be implemented in the next pull request because I worried that this pull request becomes too big to review.
=> Implement `__slots__` with `member_descriptor`

Lib/test/test_ioctl.py, stdlib/src/fcntl.rs
#4070 
- add `test_ioctl.py`.
- update `fn ioctl` can take others having `fileno` method not only Integer.
=> update ioctl first arg

Lib/test/test_fcntl.py, stdlib/src/fcntl.rs
As specified in Python official documentation
(https://docs.python.org/3.10/library/fcntl.html)
> All functions in this module take a file descriptor fd as their first
> argument. This can be an integer file descriptor, such as returned by
> sys.stdin.fileno(), or an io.IOBase object, such as sys.stdin itself,
> which provides a fileno() that returns a genuine file descriptor.
And clarified more in fcntl.fcntl function:
> Perform the operation cmd on file descriptor fd (file objects
> providing a fileno() method are accepted as well).
All function in fcntl modules should accept either int fd or object with
fileno() function which returns int fd.
This was already implemented with for `fcntl.fcntl` function with
`io::Fildes` newtype helper which extracted either int fd or called
fileno() …
=> Allow fcntl functions to accept objects with fileno() function

compiler/core/src/location.rs
I'm finding this useful when using RustPython as a library, though if you don't it in RustPython I can just use my own wrapper type.
=> Add PartialOrd to Location

Lib/test/test_math.py, stdlib/src/math.rs
Python documentation says `The special cases pow(0.0, -inf) and pow(-0.0, -inf) were changed to return inf instead of raising ValueError, for consistency with IEEE 754`
- [Python documentation](https://docs.python.org/ko/3.11/library/math.html#math.pow)
- [Python 3.11 change log](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.11.rst#math)
- https://github.com/python/cpython/pull/26606
=> Fix edge case of `math.pow(0.0, -inf)`, `math.pow(-0.0, -inf)`

Lib/operator.py, Lib/test/test_operator.py, vm/src/stdlib/operator.rs
Add `operator.call` implemented in cpython 3.11
* Python codes are copy-pasted from CPython.
- [Cpython change log](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.11.rst#operator)
-  https://github.com/python/cpython/pull/27888
- https://github.com/python/cpython/pull/29110
=> Add `operator.call`

Lib/test/test_math.py, stdlib/src/math.rs
`math.cbrt` returns the cube root of x
* Python codes are copy-pasted from CPython.
- https://github.com/python/cpython/pull/26622
- [Python documentation](https://docs.python.org/ko/3.11/library/math.html#math.cbrt)
=> Add `math.cbrt` implemented in cpython 3.11

Lib/test/test_iter.py, vm/src/vm/vm_ops.rs
- [Related CPython implementation](https://github.com/python/cpython/blob/main/Objects/abstract.c#L2173-L2254)
=> Fix `bool_eq` argument order of `_membership_iter_search` for compatibility with cpython

Lib/test/test_functools.py, derive/src/pyclass.rs, vm/src/builtins/descriptor.rs, vm/src/builtins/type.rs, vm/src/object/core.rs, vm/src/vm/context.rs
This pull request implements `MemberDescrObject`'s setter.
---
I'll implement the setter macro in the next PR with `Frame.f_trace_lines` member.
- Support `T_BOOL` member type.
- Implement `Frame.f_trace_lines` member.
- Implement `#[pymember(setter)` macro.
=> Implement `MemberDescrObject` setter

Lib/test/test_isinstance.py, vm/src/protocol/object.rs
This PR resolves 2 tests by applying `with_recursion` in `abstract_issubclass`
* `test_infinite_recursion_via_bases_tuple`
* `test_infinite_cycle_in_bases`
=> Fix `test_infinite_recursion_via_bases_tuple`, `test_infinite_cycle_in_bases`

.github/workflows/ci.yaml
You can skip unnecessary ci actions through the `skip:ci` tag.
The default pull_request action trigger does not include labeled or unlabeled, so when the label is modified, the trigger is modified to reactivate the action.
=> ci: Support for ci skip through tag

compiler/codegen/src/compile.rs, extra_tests/snippets/code_co_consts.py
Always insert `None` at `code_stack.constants`
```py
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dis
>>> def g():
...     return 1
... 
>>> dis.dis(g)
2           0 LOAD_CONST               1 (1)
2 RETURN_VALUE
>>> g.__code__.co_consts
(None, 1)
```
```py
>>>>> import dis
>>>>> def g():
.....     return 1
..... 
>>>>> dis.dis(g)
2           0 LoadConst            (1)
1 ReturnValue
>>>>> g.__code__.co_consts
(1,)
```
```py
>>>>> import dis
>>>>> def g():
.....     return 1
..... 
>>>>> dis.dis(g)
2           0 LoadConst            (1)
1 ReturnValue
>>>>> g.__code__.co_consts
(None, 1)
```
- [What is none doing in the code objects co consts …
=> Always insert `None` at `code_stack.constants`

Lib/test/test_dataclasses.py, vm/src/protocol/object.rs
```
>>> class NoHash(object):
...   __hash__ = None
... 
>>> hash(NoHash())
TypeError: unhashable type: 'NoHash'
```
```
>>>>> class NoHash(object):
.....   __hash__ = None
..... 
>>>>> hash(NoHash())
TypeError: 'NoneType' object is not callable
```
This PR fixes RustPython's error message when `hash` method is `None`
```
>>>>> class NoHash(object):
.....   __hash__ = None
..... 
>>>>> hash(None)
TypeError: unhashable type: 'NoHash'
>>>>>
=> Fix `hash`'s error message when `hash` method is `None`

Lib/datetime.py
Added `UTC` alias added in cpython 3.11
By the way, It seems maybe the `Lib/test/datetimetester.py` tests are missing, I'm wondering if this is intended.
```
>>>>> datetime.UTC
datetime.timezone.utc
```
* Python codes are copy-pasted from CPython.
- https://github.com/python/cpython/pull/91973
- [Python change log](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.11.rst#datetime)
=> Add `datetime.UTC` alias for `datetime.timezone.utc`

Lib/test/test_structseq.py, vm/src/types/structseq.rs, vm/src/vm/context.rs
This PR treat __match_args__ without n_*_fields
refs: #4063
=> match args without n_*_fields

Lib/pprint.py, Lib/test/test_pprint.py
This is a change of cpython 3.10
Python codes are copy-pasted from CPython.
`pprint.pprint` function displays integer with underscores.
* https://github.com/python/cpython/pull/24864
=> Update `pprint` lib and tests from CPython v3.12.0a0

Lib/opcode.py, Lib/test/test_code.py, vm/src/builtins/code.rs
Add `co_names` to `PyCode`
CPython document says `co_names` is a *tuple of names other than arguments and function locals*
https://github.com/python/cpython/blob/main/Doc/library/inspect.rst#types-and-members
```
>>>>> a = 3
>>>>> b = 5
>>>>> c = 7
>>>>> def f(k, l, m):
.....   d = 9
.....   return a + k
..... 
>>>>> f.__code__.co_names
1
('a',)
>>>>> 
```
=> Add `co_names` to `PyCode`

Lib/test/test_statistics.py, vm/src/builtins/int.rs
This PR is trying to fix #4198.
```
>>>>> 576460752303423488.0/12009599006321323.0
47.99999999999999
>>>>> 576460752303423488/12009599006321323
48.0
```
=> Fix `int.inner_truediv`

Lib/test/test_exception_hierarchy.py, Lib/test/test_fileio.py, Lib/test/test_subprocess.py, extra_tests/snippets/builtin_exceptions.py, vm/src/exceptions.rs
Tested by removing expected failure and commenting everything but OSError in Lib/test/test_exceptions.py::testAttributes::exceptionList, WindowsError and pickling part of the test.
fixes : #4193
=> Fill OSError attributes

extra_tests/snippets/stdlib_itertools.py, vm/src/stdlib/itertools.rs
The test `def test_dropwhile(self):` of Lib/test/test_itertools.py is not activated because the line `self.assertRaises(TypeError, next, dropwhile(10, [(4,5)]))` fails.
The bytes against which the pickling is compared in stdlib_itertools.py are generated with CPython
This is part of #3611
=> Add dropwhile.__reduce__

Lib/unittest/runner.py, Lib/unittest/test/test_runner.py
I think updating unittest runner could be useful because it shows unexpected success info without the `--verbose` flag.
=> Update `unittest/runner.py` from CPython v3.12.0a0

compiler/parser/src/fstring.rs, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_nested_spec.snap
There's still a problem with this rework where 
```
arg_list = 'hits, misses, maxsize, currsize'
f'lambda _cls, {arg_list}: _tuple_new(_cls, ({arg_list}))
```
returns 
`lambda _cls, {'hits, misses, maxsize, currsize'}: _tuple_new(_cls, ({'hits, misses, maxsize, currsize'}))`
instead of 
`lambda _cls, hits, misses, maxsize, currsize: _tuple_new(_cls, (hits, misses, maxsize, currsize))`
closes: #4102
=> Refactor fstrings

derive/src/pyclass.rs, vm/src/builtins/descriptor.rs, vm/src/builtins/frame.rs, vm/src/frame.rs, vm/src/vm/context.rs
This pull request's purpose is to implement `Frame.f_trace_lines` (in `vm/src/builtins/frame.rs`).
-----
This may not be the best structure to handle members 😞 But it works. 🔨
=> Implement `Frame.f_trace_lines`

README.md
I hate to be self-promotional but RustPython powers Ruff's AST parser. If you want to include in the README, feel free! But also fine if not :)
=> Add Ruff as a use-case in the README

vm/src/builtins/type.rs
In this revision,
- #4085 has been fixed by removing remark and
- [Updating `docs.inc.rs` file in `RustPython/__doc__`](https://github.com/RustPython/__doc__/pull/1/files)
close: #4085
=> class-doc-fixed

compiler/parser/src/lexer.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_class.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_kwargs.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_print_2.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_print_hello.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_string.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_1.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_2.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_3.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_string_concat.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_string_concat_1.snap
The same as #4220, but for simple strings. E.g., right now `"foo"` starts at column 2, instead of column 1.
=> Start simple string at quote mark

stdlib/src/bisect.rs, stdlib/src/cmath.rs, stdlib/src/zlib.rs, vm/src/builtins/bool.rs, vm/src/builtins/dict.rs, vm/src/builtins/filter.rs, vm/src/builtins/float.rs, vm/src/builtins/int.rs, vm/src/builtins/list.rs, vm/src/builtins/map.rs, vm/src/builtins/property.rs, vm/src/builtins/range.rs, vm/src/builtins/set.rs, vm/src/builtins/str.rs, vm/src/builtins/tuple.rs, vm/src/stdlib/builtins.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/posix.rs, vm/src/stdlib/symtable.rs
In this revision,
- Remove most of unnecessary remarks about `__doc__`, that already exist in [`Rustpython/__doc__/docs.inc.rs`](https://github.com/RustPython/__doc__/blob/main/docs.inc.rs)
- Not everything, like some remarks in `vm/src/builtins/str.rs` methods. They are not still added to docs.inc.rs.
--- 
Effected files are:
=> remove most of old __doc__ remarks

compiler/codegen/src/compile.rs, extra_tests/snippets/scope_lambda.py
This PR trying to fix #3934.
I think the compile context of the lambda expression should be resolved as `Function` after executing `enter_function` like in the `compile_function_def`.
The detailed explanations are in the above issue's comments.
Example code:
```
>>>>> class X:
.....   v = 999
.....   f = lambda x=v:x
..... 
>>>>> 
```
Example code's bytecodes:
```
1           0 LoadGlobal           (0, __name__)
1 StoreLocal           (1, __module__)
2 LoadConst            ("X")
3 StoreLocal           (2, __qualname__)
4 LoadConst            (None)
5 StoreLocal           (3, __doc__)
2           6 LoadConst            (999)
7 StoreLocal           (4, v)
3           8 LoadNameAny          (4, v)
9 BuildTuple           (1, false)
10 LoadConst            (<code object <lambda> at ??? file …
```
=> Fix lambda expression's  unexpected `UnboundLocalError`

compiler/parser/src/parser.rs
I'm using this in [Ruff](https://github.com/charliermarsh/ruff) where it's useful to be able to generate the token stream once upfront, use it in a few places, then pass it to the parser without re-tokenizing the entire stream.
=> Expose a method to parse AST from tokens directly

Lib/test/test_builtin.py, vm/src/stdlib/builtins.rs
This was as simple as fixing the error messages produced when zero arguments are passed.
Part of #1671. It was a great first issue to work on!
=> Fix compatibility bug for min/max builtins

Lib/test/test_dataclasses.py, Lib/test/test_pickle.py, Lib/test/test_pickletools.py, Lib/test/test_typing.py, compiler/codegen/src/compile.rs
Fix #3993 
This pr tries to fix the compile time issue for `global` declaration.
Since lots of the tests under `Lib/test` used `global SomeClass` inside their test methods, this fix might help in the future.
e.g. Test `test_dataclasses_pickleable` has passed because the global classes are pickleable after this fix.
---
Take the following code snippet as example:
```python
def test_c_methods():
global Subclass
class Subclass(tuple):
class Nested(str):
pass
test_c_methods()
```
The result before this pr:
```
>>>>> Subclass.__qualname__
'test_c_methods.<locals>.Subclass'
>>>>>
>>>>> Subclass.Nested.__qualname__
'test_c_methods.<locals>.Subclass.Nested'
```
The result after fix:
```
>>> Subclass.__qualname__
'Subclass'
>>>
>>> Subclass.Nested.__qualname__
'Subclass.Nested'
```
=> Fix `global` behavior on class

Lib/test/test_itertools.py, vm/src/stdlib/itertools.rs
Hello!
I tried to implement the `reduce` method for `PyItertoolsChain` (issue #3611) but got stuck. I used the [CPython implementation](https://github.com/python/cpython/blob/9608bef84afd797ba6d16ec97439909f2f0d1095/Modules/itertoolsmodule.c#L2276) as a reference. The implementation seems to work just fine with simple arrays etc. but fails the `test_chain_reducible` test. Any suggestions on why?
The error message:
```
ERROR: test_chain_reducible (test.test_itertools.TestBasicOps)
File "/home/dan/Projects/RustPython/pylib/Lib/test/test_itertools.py", line 187, in test_chain_reducible
self.assertEqual(list(oper(it)), list('abcdef'))
File …
```
=> Chain reduce

compiler/parser/python.lalrpop, compiler/parser/src/context.rs, compiler/parser/src/lib.rs, compiler/parser/src/snapshots/rustpython_parser__context__tests__ann_assign_name.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_attribute.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_for.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_list.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_list_comp.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_name.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_named_expr.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_set_comp.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_starred.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_subscript.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_tuple.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_with.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__aug_assign_attribute.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__aug_assign_name.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__aug_assign_subscript.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__del_attribute.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__del_subscript.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_dict_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_double_list_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_generator_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_if_else_generator_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_list_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_named_expression_generator_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_tuples.snap
It looks like the parser is _almost_ always setting `ast::ExprContext::Load`. This PR attempts to set `ast::ExprContext::Store` and `ast::ExprContext::Del` in the right places, based on playing around with CPython's own behavior.
I'm not familiar enough with LALRPOP to know if there's a way to do this within the parser itself -- so, instead, I had to "rewrite" the expression tree in the right places.
=> Add expression context parsing

Lib/test/test_long.py, Lib/test/test_math.py, stdlib/src/math.rs
This also fixes a bug in the `log2()` implementation, where very large negative integer arguments would not raise an exception (and instead would turn into NaNs).
Follow-up to #4241. Part of #1671.
=> Use improved log2() implementation for log10()

Lib/test/test_math.py
It looks like these were accidentally left in the codebase after #2773.
=> Clean up a few obsolete TODOs in test_math.py

Lib/test/test_ast.py, Lib/test/test_fstring.py, Lib/test/test_support.py, compiler/codegen/src/symboltable.rs, compiler/core/src/location.rs, compiler/parser/python.lalrpop, compiler/parser/src/error.rs, compiler/parser/src/fstring.rs, compiler/parser/src/parser.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_class.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_if_elif_else.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_named_expression_generator_comprehension.snap, vm/src/format.rs
The test_fstring.py file comes from CPython
This improve coverage as of #1671.
=> Improve string fstring coverage

Lib/test/test_math.py, stdlib/src/math.rs
This uses the improved-accuracy hypotenuse algorithm from Borges 2019, see https://arxiv.org/abs/1904.09481.
Part of #1671.
=> Implement a more accurate hypot()

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_equals.snap, compiler/parser/src/snapshots/rustpython_parser__fstring__tests__parse_fstring_not_equals.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_double_list_comprehension.snap
Right now, `1 == 2` has a start location at the first `=`. This PR changes the parser such that start location is equivalent to the start of the `left` item (i.e., the `1`).
=> Set comparator start location to beginning of comparison

jit/src/instructions.rs, jit/tests/int_tests.rs
👋 Hey,
This PR implements a few more ops in the JIT.
I noticed that shifting by negative numbers raises an exception, I've modeled this as a trap, with the hopes that some day we'll catch that custom trap code and do proper exception handling.
Are there any other cases of special values in these ops that python treats differently?
=> Implement a few more ops in the JIT

vm/src/dictdatatype.rs
This as_mut doesn't fail in most condition, although if you actually impl a garbage collect, there is a very small chances(three in 200,000, edited: more like 20 in 200000) that this following as_mut can fail due to change in dict:
https://github.com/RustPython/RustPython/blob/1a92399349704d2a49ae57539f308c5f91a1d436/vm/src/dictdatatype.rs#L252
```rust
/// Store a key
pub fn insert<K>(&self, vm: &VirtualMachine, key: &K, value: T) -> PyResult<()>
where K: DictKey + ?Sized,
{
let hash = key.key_hash(vm)?;
let _removed = loop {
let (entry_index, index_index) = self.lookup(vm, key, hash, None)?;
let mut inner = self.write();
if let Some(index) = entry_index.index() {
// Update existing key
if let Some(entry) = inner.entries.get_mut(index) {
// this `as_mut` might fail
let entry = entry …
```
=> Allow retry if `as_mut` fail when insert Dict

README.md
GreptimeDB use RsutPython for simple embedded scripting, so I think we can add this use case here?: https://docs.greptime.com/developer-guide/datanode/python-coprocessor
=> doc: add greptimedb's use case to README

compiler/parser/src/lexer.rs
I slightly made some changes to the lexer for better organization of the struct
- Changed `Vec<IndentationLevel>` into a new struct `Indentations` and limited its methods just for `pop`, `push`, `is_empty`, and `current`: Checking empty semantics is different from normal vectors in that `is_empty()` should return when the length is one, rather than zero because of the default indentation level.
- Made a struct for `chr0, chr1, chr2`, which is `CharWindow<const N: usize>`
- Changed condition expression in if statements. For example `if x == Some(1) || x == Some(2) { ... }` changed into `if matches!(x, Some(1 | 2))`
- Shortcircuited an if statement to reduce indentation level.
- Add a new test for `123_45_67_890` which was missing in `lexer.rs` tests module
=> Re-organizing lexer struct

Cargo.lock, compiler/parser/Cargo.toml, compiler/parser/src/function.rs, compiler/parser/src/string.rs
I tend to benchmark the parser by parsing all of CPython in [Ruff](https://github.com/charliermarsh/ruff). This involves (1) disabling Ruff's linting pass, then (2) running `cargo build --release && hyperfine --warmup 10 --runs 50 -i "./target/release/ruff resources/test/cpython --no-cache"`.
Prior to this change:
```
Benchmark 1: ./target/release/ruff resources/test/cpython --no-cache
Time (mean ± σ):     265.2 ms ±   4.6 ms    [User: 2260.7 ms, System: 83.1 ms]
Range (min … max):   259.0 ms … 281.1 ms    50 runs
Benchmark 1: ./target/release/ruff resources/test/cpython --no-cache
Time (mean ± σ):     268.4 ms ±   4.2 ms    [User: 2268.1 ms, System: 83.5 ms]
Range (min … max):   262.5 ms … 283.6 ms    50 runs
Benchmark 1: ./target/release/ruff resources/test/cpython --no-cache
Time (mean …
```
=> Implement some minor performance optimizations

src/lib.rs, vm/src/vm/setting.rs
Running flame it works now as described in the profiling section:
```bash
echo "print('hello!')" >> script.py
cargo run --release --features flame-it script.py
```
or:
```bash
cargo run --release --features flame-it -- -c "print('hello world')"
```
to generate the flamescope (by default) which can be uploaded to speedscope.
ref #4289
=> Fix issues with flame-it.

compiler/parser/src/lexer.rs
I refactored following lexer functions.
* `lex_number`
* ~~`take_number`~~
* `at_exponent`
* `is_identifier_continuation`
What I have done are as follows.
* using match expression instead of if expression
* reducing the nesting of match expression
=> Refactor lexer functions

examples/call_between_rust_and_python.py, examples/call_between_rust_and_python.rs
Add an example which illustrates how to call between rust and python. Most importantly there no examples which illustrate how to call rust from python and it is not obvious how to do this.
I never figured out if there was a way to nicely call a constructor of a rust struct since all methods in python require the self parameter I assumed that this was not possible and that construction should be done via a standalone function.
If it is encouraged or idiomatic to use a python constructor from rust for some reason then perhaps that should be added to the example.
Previous opened issue: https://github.com/RustPython/RustPython/issues/4124
=> Add example for calling between rust and python

stdlib/Cargo.toml
The test runner for ubuntu was recently bumped from 20.04 to 22.04, this appears to have caused some linking errors in openssl. Bumping it to the most recent version appears to clear things up.
=> Bump openssl

Lib/test/test_ast.py, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_1.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_2.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_3.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_string_concat.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_f_string_concat_1.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_f_string_concat_2.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_string_concat_1.snap, compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_string_concat_2.snap, compiler/parser/src/string.rs
```
"hello" "world"
^
end_location
```
```
"hello" "world"
^
end_location
```
=> Fix the end location of an implicitly-concatenated string

Lib/test/test_ensurepip.py, compiler/parser/python.lalrpop, compiler/parser/src/lib.rs, compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap, compiler/parser/src/with.rs
Since the upstream grammar for this is not LR(1), we abuse LALRPOP macros and the `Into`/`TryInto` traits to build a cover grammar that converts to either tuples or `with` items after additional validation. It’s annoying and ugly, but something like this is basically our only option short of switching to a more powerful parser algorithm.
Fixes #4145.
(Cc @charliermarsh, who I know is working on a more powerful parser algorithm in charliermarsh/ruff#286. But this may be a useful stopgap.)
=> Parse Python 3.9+ parenthesized context managers

Lib/test/test_ast.py, compiler/parser/python.lalrpop, compiler/parser/src/parser.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_class.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_if_elif_else.snap, compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap
For example, `FunctionDef` currently ends at where `DEDENT` occurs:
```python
def f1():
pass
def f2():
^ here
pass
```
but it should end at the final statement in the function body:
```python
def f1():
pass
^ should end here
def f2():
pass
```
=> Fix end location of compound statements

compiler/ast/asdl_rs.py, compiler/ast/src/ast_gen.rs, compiler/parser/python.lalrpop, compiler/parser/src/function.rs, compiler/parser/src/with.rs
It seems unnecessary to box the children of an ASDL product type for the same reason that it’s unnecessary to box the elements of a `Vec`.
(Refs #2399, where the ASDL converter was introduced.)
=> Remove unnecessary boxing of ASDL product children

compiler/codegen/src/symboltable.rs, extra_tests/snippets/syntax_comprehension.py
https://github.com/RustPython/RustPython/issues/4319#issuecomment-1356117387
What I have done are as follows.
* Replace symbol scope from Local to Cell.
* Add test in `syntax_comprehension.py`.
=> Fix panic about warlus operator inside mutiple comprehensions.

Lib/test/test_ast.py, compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_attribute.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_for.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_list.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_list_comp.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_name.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_set_comp.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_starred.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_subscript.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_tuple.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__aug_assign_attribute.snap, compiler/parser/src/snapshots/rustpython_parser__context__tests__aug_assign_subscript.snap, compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap
This PR fixes the start and end locations of `Tuple`.
```
(1, 2, 3)
^-----^
doesn't include ()
```
```
(1, 2, 3)
^-------^
includes ()
```
=> Fix the start and end locations of `Tuple`

jit/src/instructions.rs, jit/tests/misc_tests.rs
I mostly just wrote this limited implementation to test out the performance of a simple iterative fibonacci implementation that I found. https://pythonistaplanet.com/fibonacci-sequence-iterative/
I modified the code to avoid calling print. For testing I also started at a higher number so the call overhead from python to the jitted code is reduced.
| no jit | jit |
| -------|-----|
| f(79) = 14472334024676221 | f(79) = 14472334024676221 |
| time: 0.0044 s |  time: 0.00048 s |
<details>
<summary>code</summary>
```python
import time
def f(n: int):
a = 0
b = 1
c = 0
while (n - 1):
c = a + b
a,b = b,c
n = n - 1
return c
start = time.time()
for i in range(50, 80):
print(f"f({i}) = {f(i)}")
print("time: {:.2} s".format(time.time() - start))
print("__jit__()", f.__jit__())
start = time.time()
for …
```
=> Support variable exchange (aka basic tuple support)

Lib/test/test_symtable.py, vm/src/stdlib/symtable.rs
To make `test_globals` in `test_symtable.py` pass, I've done following fix about `PySymbol`.
I referenced the following CPython code.
https://github.com/python/cpython/blob/main/Lib/symtable.py#L247-L251
I referenced the following CPython code.
https://github.com/python/cpython/blob/main/Lib/symtable.py#L257-L260
=> make `test_globals` pass

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_if_else_generator_comprehension.snap, compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap
This PR fixes the `IfExp` location.
```python
x if y else z
^
x if y else z
^
```
---
```python
import ast
code = "x if y else z"
print(ast.dump(ast.parse(code), include_attributes=True, indent=2))
```
prints out:
```
Module(
body=[
Expr(
value=IfExp(
test=Name(
id='y',
ctx=Load(),
lineno=1,
col_offset=5,
end_lineno=1,
end_col_offset=6),
body=Name(
id='x',
ctx=Load(),
lineno=1,
col_offset=0,
end_lineno=1,
end_col_offset=1),
orelse=Name(
id='z',
ctx=Load(),
lineno=1,
col_offset=12,
end_lineno=1,
end_col_offset=13),
lineno=1,
col_offset=0,
end_lineno=1,
end_col_offset=13),
lineno=1,
👇👇👇👇👇👇👇👇
col_offset=0,
end_lineno=1,
end_col_offset=13)],
type_ignores=[])
```
=> Fix `IfExp` location

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap
Because the `with` item grammar disallows named expressions, CPython parses `with (a := 0, b := 1):` as a tuple rather than two `with` items.
=> Fix parsing of tuple with named expression as context manager

Lib/test/test_importlib/source/test_source_encoding.py, compiler/parser/src/lexer.rs
#4353 
I've added BOM check in `Lexer`.
With this fix, the following tests now pass.
So I've removed the decorators.
* `test_bom`
* `test_bom_and_utf_8`
=> Add BOM check

examples/atexit_example.py, vm/src/stdlib/sys.rs
This PR aims to fix #4318. In order to do that,  I changed the exception type, of which the unraisable must be a subtype, to [`base_exception_type`](https://github.com/RustPython/RustPython/blob/d1811c72e72c51b849b0ad7b3f0efb2814a16bf2/vm/src/exceptions.rs#L324), because the [`SystemExit`](https://docs.python.org/3/library/exceptions.html#SystemExit) exception is not a subtype of  `Exception` (as [pointed out](https://github.com/RustPython/RustPython/issues/4318#issuecomment-1345354962) by @DimitrisJim). 
In addition,  I changed the error message printed  by the unraisable hook to print the exception type to match the behavior of CPython. The error message printed at `SystemExit` (generated by the `atexit_example.py` script included in this PR) does now look as follows:
```shell
cargo run …
```
=> Fix assertion error at unraisable exception

Lib/test/test_exceptions.py, vm/src/suggestion.rs
=> Fix unwrap issue causing panic

compiler/parser/src/lexer.rs
Currently, `Lexer` always resets the start location but it should not.
=> Fix `make_tokenizer_located`

Lib/test/test_builtin.py, vm/src/frame.rs
#4375
I've fixed `LoadNameAny` opecode to return exception occured in local.
With this fix, following test now pass.
* test_eval
=> `eval` doesn't raise correct exception

Lib/test/test_binascii.py, extra_tests/snippets/stdlib_binascii.py, stdlib/src/binascii.rs
This pull request resolves https://github.com/RustPython/RustPython/issues/4336.
Those lines to throw the `base64::DecodeError::InvalidLastSymbol{ .. }` are the below lines.
```rust
// https://github.com/marshallpierce/rust-base64/blob/10b73f67c4b19dc7fc1f4c4ae250558cba90c8d8/src/engine/fast_portable/decode_suffix.rs#L141-L147
if !decode_allow_trailing_bits && (leftover_bits & mask) != 0 {
// last morsel is at `morsels_in_leftover` - 1
return Err(DecodeError::InvalidLastSymbol(
start_of_leftovers + morsels_in_leftover - 1,
last_symbol,
));
}
```
And it provides an option, `decode_allow_trailing_bits`, to pass the check. This pull request uses the config option.
You can copy the below line and run the RustPython build on the `main` branch and on this pull request.
```python
import base64; …
```
=> Allow trailing bits while decoding base64

Lib/test/test_syntax.py, compiler/parser/src/error.rs, compiler/parser/src/function.rs
CPython prohibits `f(**kwargs, *args)`; we should too.
=> Prohibit starred arguments after double-starred arguments

Lib/test/test_compile.py, Lib/test/test_positional_only_arg.py, compiler/parser/python.lalrpop, compiler/parser/src/error.rs, compiler/parser/src/function.rs
- Add lex error `DuplicateArgumentError` 
The codes below will now yield `SyntaxError` due to duplicate arguments in function definition
```python
def f(a, a): pass
def f(a, *a): pass
def f(*a, **a): pass
lambda a,a: 0
lambda a,*a: 0
```
Example error message
```
SyntaxError: duplicate argument in function definition at line 2 column 9
def f(a, a): pass
^
```
- Add lex error for `named arguments must follow bare *`
1. The code below will now yield `SyntaxError` if no kw arguments follow bare asterisk
```python
def f(a, b, *): pass
```
Example error message
```
SyntaxError: named arguments must follow bare * at line 2 column 12
def f(a, b, *): pass
^
```
2. The code below works fine as expected
```python
def f(a, b, *, c): pass
```
=> add lex error for function args

compiler/parser/src/error.rs, compiler/parser/src/function.rs
Output before:
```
>>>>> def foo(**kwargs): pass
>>>>> foo(k=10, k=20)
SyntaxError: keyword argument repeated at line 1 column 10
foo(k=10, k=20)
^
```
Output after:
```
>>>>> def foo(**kwargs): pass
>>>>> foo(k=10, k=20)
SyntaxError: keyword argument 'k' repeated at line 1 column 10
foo(k=10, k=20)
^
```
=> arg name to be written upon duplicate kwargs error #4381

extra_tests/snippets/builtin_format.py, vm/src/format.rs
Conversion from decimal to prefixed hex is incorrect.
```
>>>>> f"{255:#X}"
'0xFF'
```
The output should be `0XFF`.
I've fixed hex prefix.
=> Fix hex prefix

Lib/test/test_named_expressions.py, compiler/parser/python.lalrpop
`a[b := c]` and `{a := b for c in d}` are valid Python.
=> Allow named expression in subscript and set comprehension

extra_tests/snippets/builtin_format.py, vm/src/format.rs
In CPython, integer can be converted to character.
```
>>> f"{65:c}"
'A'
```
But in RustPython, ValueError is raised.
```
>>>>> f"{65:c}"
ValueError: Unknown format code 'c' for object of type 'int'
```
I've fixed to convert an integer to character.
I referenced the following source code.
https://github.com/python/cpython/blob/79c10b7da84f52999dc483fc62c8e758ad3eff23/Python/formatter_unicode.c#L864
=> Fix character format

extra_tests/snippets/builtin_format.py, vm/src/format.rs
Prefixed format with padding doesn't work correctly.
```
>>>>> f"{256:#010x}"
'000000x100'
```
the output should be `0x00000100`
I've fixed format function.
=> Prefix format with padding doesn't work correctly.

wasm/notebook/snippets/python-markdown-math.txt
`[google](google.com)` → `[google](https://google.com)`
URLs without `https://` are relative.
If you run it in [the demo notebook](https://rustpython.github.io/demo/notebook/), then `google.com` becomes `https://rustpython.github.io/demo/notebook/google.com`.
=> Fix the markdown URL in the sample notebook

compiler/parser/src/string.rs
Removes unreachable code in `compiler/parser/src/string.rs`.
=> Remove unreachable code in `compiler/parser/src/string.rs`

compiler/parser/src/error.rs, src/shell.rs
Fixes #3892  #4400 
Removed the automatic continuing logic that was in place for code that needs multiple lines in the shell to parse correctly. Now we check if full_code can be parsed after each line of input given, but ignoring specific EOF and IndentationLevel errors.
I am working on a way to do this without modifying errors.rs, if I should not be modifying that.
Edit: I think my edits to errors.rs may have improved EOF error handling.
=> Fix IndentationError works differently with cpython in interective shell

compiler/parser/src/string_parser.rs
Use `drain` to simplify `compiler/parser/src/string_parser.rs`.
=> Use `drain` to simplify `compiler/parser/src/string_parser.rs` 

compiler/parser/src/error.rs, compiler/parser/src/string_parser.rs
Removes incorrect `EmptyExpression` in `StringParser.parse_formatted_value`.
=> Remove incorrect `EmptyExpression` in `StringParser.parse_formatted_value`

Lib/test/test_types.py, common/src/format.rs, extra_tests/snippets/builtin_format.py, vm/src/builtins/int.rs
Integer Format validation is not implemented.
```
>>>>> f"{4096:,o}"
'1,0000'  # Should be raised `ValueError`
>>>>> f"{123456:_n}"
'123_456' # Should be raised `ValueError`
```
I've implemented format validation.
With this fix, following tests now pass.
* `test_format_spec_errors` in `test_types.py`
* `test_int__format__` in `test_types.py`
=> Implement integer format validation

common/src/format.rs, extra_tests/snippets/builtin_format.py, vm/src/builtins/float.rs
Float Format validation is not implemented.
```
>>>>> f"{1.0:,o}"
ValueError: Unknown format code 'o' for object of type 'float'
```
The output should be raised `ValueError: Cannot specify ',' with 'o'.`
I've implemented format validation.
=> Implement float format validation

Lib/test/test_tokenize.py, common/src/format.rs, common/src/str.rs, extra_tests/snippets/builtin_format.py, vm/src/builtins/str.rs
If multibyte character exists in string, f-string padding doesn't work correctly.
For example:
```py
f'{"🐍":4}'
```
On CPython, The result of this code is below.
```py
'🐍   '
```
But on RustPython, The Result is different.
```py
'🐍'
```
I've fixed the character counting method.
With this fix, the following tests now pass.
* `test_non_ascii_identifiers`
* `test_unicode`
=> Fix f-string padding

common/src/format.rs, extra_tests/snippets/builtin_format.py, vm/src/builtins/str.rs
String Format validation is not implemented.
```
>>>>> f'{"abc":,}'
'abc'
```
The output should be raised `ValueError: Cannot specify ',' with 's'.`
I've implemented format validation.
=> Implement string format validation

compiler/core/src/location.rs, compiler/parser/src/lexer.rs, compiler/parser/src/string_parser.rs
I think the default location for `Location` should be (1, 0), not (0, 0).
=> Implement `Default` for `Location`

common/src/format.rs, vm/src/builtins/float.rs, vm/src/builtins/int.rs, vm/src/builtins/str.rs
Fix return type of `FormatSpec::parse`.
With this fix, Method chain can be used.
=> Fix `FormatSpec::parse`.

common/src/format.rs, common/src/str.rs
Panic occured when formatted from integer to multibyte characater.
```
>>>>> f"{0x1f5a5:c}"
thread 'main' panicked at 'assertion failed: s.is_ascii()', common/src/str.rs:75:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I've implemented the check whether string contains multibyte character.
=> Fix integer format

common/src/format.rs, extra_tests/snippets/builtin_format.py, vm/src/builtins/float.rs, vm/src/builtins/int.rs, vm/src/builtins/str.rs, vm/src/format.rs
#4387
I've fixed to raise `OverflowError`.
```
>>>>> f"{-1:c}"
OverflowError: %c arg not in range(0x110000)
```
=> `PyInt.format` only raises `ValueError`

vm/src/vm/mod.rs
This pull requests fixes exitcode of `KeyboardInterrupt`. You can run the below code with CPython and RustPython(before/after). (in unix target os)
```
cargo run -- -c "raise KeyboardInterrupt"
echo $?  # before = 1 / after = 130
python3 -c "raise KeyboardInterrupt"
echo $?  # 130
```
- ~~windows~~
- https://docs.rs/winapi/latest/winapi/um/winnt/constant.STATUS_CONTROL_C_EXIT.html
- ~~wasm~~
- https://github.com/python/cpython/blob/8b1f1251215651c4ef988622345c5cb134e54d69/Modules/main.c#L666
=> Correct exitcode of KeyboardInterrupt

.devcontainer/devcontainer.json
Github has recently a new feature called [Codespaces](https://github.com/features/codespaces). A codespace is basically a development VM that can be preconfigured to support certain environment. I've found this feature while working on my first contribution to RustPython, so I would like to suggest to add this configuration to the main repo. This PR adds an official Rust feature image supported by Github team, currently it has Rust 1.66.0.
Codespaces in forks are paid by the fork owner, so RustPython org won't be billed for anything.
- Docs: https://docs.github.com/en/codespaces/overview
=> [RFC] Add Github Codespaces configuration (devcontainer.json)

.gitignore, compiler/parser/build.rs, compiler/parser/src/python.rs
docs.rs failed to build the documentation of the recently released rustpython-parser 0.2.0 because the build.rs script couldn't write the parser.rs file because docs.rs builds the documentation in a sandbox with a read-only filesystem.
This commit fixes this by writing the parser.rs file to the cargo output directory instead, as recommended by the docs.rs documentation.[1]
Fixes #4436.
[1]: https://docs.rs/about/builds#read-only-directories
=> Fix docs.rs build for rustpython-parser

compiler/parser/src/lexer.rs, compiler/parser/src/parser.rs, compiler/parser/src/token.rs
This token is completely ignored by the parser, but it's useful for other users of the lexer, such as the Ruff linter. For example, the token is helpful for a "trailing comma" lint.
The same idea exists in Python's `tokenize` module - there is a NEWLINE token (logical newline), and a NL token (non-logical newline).
Fixes #4385.
=> lexer: Add `NonLogicalNewline` token

common/src/format.rs
[String::split_at](https://doc.rust-lang.org/std/string/struct.String.html#method.split_at) panics if `mid` is not on a UTF-8 code point boundary, changed to use [`String::char_indices`](https://doc.rust-lang.org/std/string/struct.String.html#method.char_indices) instead of `String::chars().enumerate()` to fix it.
See also https://github.com/charliermarsh/ruff/issues/1845
=> Fix panic when parsing a format spec with multi-byte character

Cargo.lock, compiler/codegen/src/compile.rs, compiler/codegen/src/ir.rs, compiler/codegen/src/snapshots/rustpython_codegen__compile__tests__nested_double_async_with.snap, compiler/core/Cargo.toml, compiler/core/src/bytecode.rs, compiler/src/lib.rs, jit/src/instructions.rs, jit/tests/common.rs, vm/src/frame.rs
This gives a slight speedup and I have to imagine much better memory usage, but I don't think we have a way to profile the latter.
=> Switch from 64-bit instruction enum to out-of-line arg values

compiler/parser/src/parser.rs
Fixup for commit e64faa781c1faa9052a9d57c00d29830d2f11850. I only updated `parse()` to ignore `NonLogicalNewline`, didn't notice it's also needed in `parse_tokens()`. Now I've ran the full Ruff test suite, and it passes (except for a couple intended fixes for the new token).
=> Fixup parse_tokens after "Add NonLogicalNewline token"

common/src/float_ops.rs, common/src/format.rs
I've fxied to hold `float_ops::Case` in the following `FormatType` value.
* Hex
* Exponent
* GeneralFormat
* FixedPoint
=> Refactor `FormatType`

compiler/parser/src/context.rs, compiler/parser/src/parser.rs
This PR removes useless `String::from` in tests
=> Remove useless `String::from` in tests

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_if_elif_else.snap
Since we parse an `elif:` block as an `If` node, its location should include its `orelse` node like it would for an `if:` block.
=> Fix end location for elif blocks

Lib/test/test_runpy.py, Lib/test/test_signal.py, vm/src/vm/interpreter.rs, vm/src/vm/mod.rs
This pull request fixes exitcode of `SIGINT` (i.e., `KeyboardInterrupt`) when running through `subprocess.run`.
You can run the below script.
```python
import sys, subprocess; subprocess.run([sys.executable, "-c", "raise KeyboardInterrupt"])
```
```python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, subprocess; subprocess.run([sys.executable, "-c", "raise KeyboardInterrupt"])
File "<string>", line 1, in <module>
KeyboardInterrupt
CompletedProcess(args=['/opt/homebrew/opt/python@3.10/bin/python3.10', '-c', 'raise KeyboardInterrupt'], returncode=-2)
```
```python
>>>>> import sys, subprocess; subprocess.run([sys.executable, …
```
=> Correct exitcode when running through `subprocess.run`

Lib/test/test_locale.py, common/src/cformat.rs, vm/src/cformat.rs
This PR extends `cformat.rs` to handle lone-dot cases, like `"%.f" % 123.456`. Previously, RustPython used six decimal places for this case, treating it equivalently to `"%f" % 123.456`. This differs from CPython, which treats `"%.f"` as "remove the decimal point". Similarly, CPython treats `"%.s"` as a full string truncation.
=> Implement lone-dot semantics for %-style format strings

vm/src/stdlib/builtins.rs, vm/src/vm/mod.rs
Related to #4316
This pull request allows the `compile` function to initialize the `ast` module before the compilation.
I am not sure if this is the correct way to initialize the module. But it seems to solve the problem.
=> Initialize ast when calling compile function

extra_tests/snippets/stdlib_array.py, stdlib/src/array.rs
CPython implements `array.__contains__` but RustPython doesn't implement it yet. This pull request implements it.
```python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> array.array('B').__contains__
<method-wrapper '__contains__' of array.array object at 0x1051ce700>
```
```python
Welcome to the magnificent Rust Python 0.2.0 interpreter 😱 🖖
>>>>> import array
>>>>> array.array('B').__contains__
AttributeError: 'array' object has no attribute '__contains__'
```
```python
Welcome to the magnificent Rust Python 0.2.0 interpreter 😱 🖖
>>>>> import array
>>>>> array.array('B').__contains__ …
```
=> Implement `array.array.__contains__`

Lib/test/test_array.py, stdlib/src/array.rs
This pull request registers `array.array` to `collections.abc.MutableSequence._abc_registry` and it makes `isinstance(array.array("<type>"), collections.abc.MutableSequence)` as `true`.
There is an issue that it cannot load `MutableSequence` from `collections.abc`, so I bypassed it by loading `MutableSequence` from `_collections_abc` directly. But it should be fixed or note comments about specific reason.
You can run the below code to test these changes:
```python
import array, collections.abc; print(isinstance(array.array('B'), collections.abc.MutableSequence))
```
- https://github.com/python/cpython/blob/bd7903967cd2a19ebc842dd1cce75f60a18aef02/Modules/arraymodule.c#L3075-L3088
=> Register `array.array` to `collections.abc.MutableSequence`

Cargo.lock, compiler/parser/Cargo.toml
string_cache is still using phf_shared 0.10.0 though.
=> Bump phf to 0.11 series

src/settings.rs, vm/src/stdlib/signal.rs, vm/src/vm/setting.rs
which is similiar to pyo3's `prepare_freethreaded_python()`, will not raise the `KeyboardInterrupt` exception, this will be benefit when embedding RustPython in other application(Which might want to set their own Interrupt)
=> feat: allow not to set SIGINT handler

compiler/parser/src/lexer.rs
Mainly by matching on `'a'..='z'` and `'A'..='Z'` which are the most common identifier characters (avoiding the calls to `is_xid_start` and `is_xid_continue`). Apart from that makes `IndentationLevel` slightly smaller and adds some sensible capacities.
Testing locally, this results in tokenizing the stdlib around ~20% faster (mainly, the `match` change yields that), I'll probably add that benchmark and one for the parser since its nice to have lying around).
=> Minor lexer optimizations

.github/workflows/ci.yaml
an attempt to see if the tests can run fine w/o the ssl feature (i'm under the impression they might)
=> Skip linking ssl on mac runner.

.cspell.json, compiler/parser/python.lalrpop, compiler/parser/src/parser.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__generator_expression_argument.snap
Given the following:
```py
" ".join(
sql
for sql in (
"LIMIT %d" % limit if limit else None,
("OFFSET %d" % offset) if offset else None,
)
)
```
The `GeneratorExp` was using the range of the `sql` token on the second line, as opposed to the entire range of the actual generator.
=> Use entire range for generators-as-arguments

vm/src/builtins/complex.rs, vm/src/builtins/dict.rs, vm/src/builtins/int.rs, vm/src/builtins/set.rs, vm/src/builtins/tuple.rs, vm/src/bytesinner.rs, vm/src/object/core.rs, vm/src/object/ext.rs, vm/src/stdlib/builtins.rs
=> Optimize Py<PyDict>::to_attributes() to reuse PyRefExact

vm/src/builtins/bytearray.rs, vm/src/builtins/bytes.rs, vm/src/bytesinner.rs
Hi!
Here is a solution proposal to #4497. I was not quite sure what the optimization part of #4496 was (I assumed it was the if-else part).
=> Optimize bytes-like (l|r)strip

vm/src/builtins/bytes.rs
One unnecessary `to_vec()` was not removed in #4500.
=> Remove unnecessary to_vec() in bytes.rs

.cspell.json, .github/workflows/ci.yaml, stdlib/src/ssl.rs, vm/src/builtins/type.rs, whats_left.py
This Pull Request is fixing the charmap error when running Python over the script whats_left.py as shown below:
```python
λ python.exe -I whats_left.py
test_sqlite3: testing with version '2.6.0', sqlite_version '3.39.4'
File "[REDACTED]\IdeaProjects\RustPython\whats_left.py", line 445, in <module>
f.write(output + "\n")
File "[REDACTED]\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u03c0' in position 76582: character maps to <undefined>
```
The line responsible of this behaviour is:
```python
with open(GENERATED_FILE, "w") as f:
``` …
=> Fixed UTF-8 encoding for `whats_left.py` and type mismatching in `stdlib/src/ssl.rs`

Cargo.lock, Lib/test/test_unicodedata.py, extra_tests/snippets/builtin_str_unicode.py, stdlib/Cargo.toml, stdlib/src/unicodedata.rs
Closes https://github.com/RustPython/RustPython/issues/4522
~~This PR is a draft for further discussion.~~
Update: In this PR, we've adopted `ucd` crate to implement `unicodedata.east_asian_width` using database v9.0.0, while leaving `unicodedata.ucd_3_2_0.unidata_version` referring to `unicodedata.east_asian_width` as is for now.
https://docs.python.org/3/library/unicodedata.html#unicodedata.east_asian_width
```
>>> import unicodedata
>>> unicodedata.unidata_version
'14.0.0'
>>> unicodedata.east_asian_width('\u231a')
'W'
>>> unicodedata.ucd_3_2_0.unidata_version
'3.2.0'
>>> unicodedata.ucd_3_2_0.east_asian_width('\u231a')
'N'
```
- `unicodedata.east_asian_width` is supported by using `ucd` crate
- `unicodedata.ucd_3_2_0.east_asian_width` is **not working** due to 9.0 change as in test …
=> Add unicodedata.east_asian_width

Lib/test/test_urllib2.py, stdlib/src/socket.rs
The `gethostbyname_ex` function of the `socket` module is only supposed to return IPv4 address as per the documentation: https://docs.python.org/3/library/socket.html#socket.gethostbyname_ex
This can also be seen in the CPython code: https://github.com/python/cpython/blob/c00faf79438cc7f0d98af2679c695f747e4369a3/Modules/socketmodule.c#L5882
This commit replace `AF_UNSPEC` with `AF_INET` so that only IPv4 are returned. This also fixes the test issue I had in PR #4526 .
I don't know if the test will pass on other platforms so I'm opening this PR to see the test results 🙂
=> Ensure socket.gethostbyname_ex only returns IPv4 addresses

compiler/parser/python.lalrpop, compiler/parser/src/parser.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__star_index.snap
This PR implements the behavior defined in [PEP 646](https://peps.python.org/pep-0646/#change-1-star-expressions-in-indexes).
See: #4479.
=> Allow starred expressions in subscripts

Cargo.lock, Lib/hmac.py, Lib/test/test_hashlib.py, Lib/test/test_hmac.py, stdlib/Cargo.toml, stdlib/src/hashlib.rs
Hi!
This is a bit of a rabbit hole but:
- I noticed the function `digest()` was missing from the `hmac` module so I updated `hmac.py` to the version from CPython 3.11
- I noticed `test_hmac.py` was missing from `Lib/test` so I also imported `test_hmac.py` from CPython 3.11
- I saw some test were failing because the `update` method of the `PyHasher` struct was taking the wrong argument type so I fixed that.
- I saw some other tests were failing because the `PyHasher` struct was not implementing the python `copy` method so I fixed that as well.
- Finally running `test_hmac.py` I noticed that two tests (`test_sha384_rfc4231` and `test_sha512_rfc4231`) are returning incorrect output so I marked them as expected failure.
The incorrect output probably need some more digging to see why that hmac …
=> Update hmac.py to CPython 3.11 and integrate test_hmac.py tests

compiler/ast/Python.asdl, compiler/ast/src/ast_gen.rs, compiler/codegen/src/compile.rs, compiler/codegen/src/symboltable.rs, compiler/parser/python.lalrpop, compiler/parser/src/parser.rs, compiler/parser/src/snapshots/rustpython_parser__parser__tests__try.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__try_star.snap, vm/src/stdlib/ast/gen.rs
This PR implements the `TryStar` spec documented [here](https://docs.python.org/3/reference/compound_stmts.html#except-star).
Note that this PR merely adds support to the parser and AST representation, rather than the runtime itself.
See: #4479.
=> Implement except* syntax

Lib/test/test_hmac.py, stdlib/src/hashlib.rs
Following PR #4526, I decided to investigate the two failing tests.
The `PyHasher` implementation was missing the `block_size` attribute which is used by the `hmac.py` code. This code was generating a warning and defaulting to an arbitrary block size: https://github.com/RustPython/RustPython/blob/ef873b4b606f0a58e3640b6186416631fdeead26/Lib/hmac.py#L84-L95
This caused the `sha2_384` and `sha2_512` HMAC to use  an incorrect block size and generate incorrect outputs.
In the process of implementing the block size property, I also simplified the `HashWrapper` constructor to use a generic type parameter.
=> Implemented the block_size attribute for PyHasher

Lib/test/test_time.py, extra_tests/snippets/stdlib_datetime.py, vm/src/stdlib/time.rs
Chrono panics in case of unsupported formats, this patch handles such cases and returns supplied format as a result.
=> Return arg in case of invalid param in strftime

compiler/parser/src/lexer.rs, compiler/parser/src/lib.rs, compiler/parser/src/parser.rs, compiler/parser/src/soft_keywords.rs
In Ruff, we often generate token streams outside of the parse step. Right now, that's causing failures for lint rules in certain cases that rely on the token stream rather than the AST. This PR always wraps the lexer in the soft keyword transformer. The primary downside is that we now have to thread through the `Mode` to all lexer calls.
=> Always wrap token streams in `SoftKeywordTransformer`

vm/src/version.rs
forgot to update when changing CI in #4517
=> Mark RustPython as Python 3.11

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__parser__tests__match.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__match_as_identifier.snap, compiler/parser/src/snapshots/rustpython_parser__parser__tests__patma.snap
Similar to other compound statements, this PR ends the match statement at the end of the last statement within the body.
=> Limit match range to end of last statement

Lib/test/test_compile.py, compiler/codegen/src/compile.rs
The final case from #2979 that wasn't handled.
=> Always load __debug__ as a const.

compiler/parser/python.lalrpop, compiler/parser/src/snapshots/rustpython_parser__parser__tests__patma.snap
This was an oversight in the initial implementation: I used the `MatchValue` location for _all_ sub-expressions (so, e.g., if you had `case -0j`, we used the range of `-0j` for the sub-expressions `0j`, which is incorrect). Now, we use the correct ranges for every sub-expression in the match.
=> Use proper locations for sub-expressions in constant matches

stdlib/src/array.rs
Thanks to @youknowone 's suggestion, I was able to fix the bug I reported. Thank you so much!
=> Satisfy safety conditions for std::slice::from_raw_parts. Fixes #4575.

Lib/test/test_syntax.py
And also allow the doctests to run for checking the edgecases.
=> Update test_syntax from CPython 3.11.0

compiler/codegen/src/compile.rs, extra_tests/snippets/syntax_forbidden_name.py
More edgecases, `def f(*__debug__): pass` and `def f(**__debug__): pass` were not handled correctly.
=> Disallow __debug__ as args, kwargs name.

Cargo.lock, compiler/Cargo.toml, compiler/codegen/Cargo.toml, compiler/codegen/src/compile.rs, compiler/codegen/src/error.rs, compiler/codegen/src/ir.rs, compiler/core/Cargo.toml, compiler/core/src/bytecode.rs, compiler/core/src/error.rs, compiler/core/src/lib.rs, compiler/core/src/location.rs, compiler/core/src/marshal.rs, compiler/parser/Cargo.toml, compiler/parser/src/parser.rs, compiler/src/lib.rs, vm/Cargo.toml, vm/src/builtins/code.rs, vm/src/builtins/complex.rs, vm/src/builtins/dict.rs, vm/src/builtins/float.rs, vm/src/builtins/function.rs, vm/src/builtins/function/jitfunc.rs, vm/src/builtins/traceback.rs, vm/src/exceptions.rs, vm/src/frame.rs, vm/src/lib.rs, vm/src/macros.rs, vm/src/stdlib/marshal.rs, wasm/lib/Cargo.toml
Switch from bincode to a custom marshal format. This totally removes `serde` as a dependency from the rustpython binary, improving compile times and also enabling a follow-up change I'm working on that deserializes from the marshal data straight into a `CodeObject<rustpython_vm::builtins::code::Literal>`, without the intermediary `CodeObject<bytecode::ConstantData>`.
Supersedes and
closes #4125 
closes #3563
=> Custom marshal enc/decoding impl

Cargo.lock, Cargo.toml
This avoids the `Updating git repository `https://github.com/youknowone/unicode_names2.git`` on every Cargo command.
=> Pin `youknowone/unicode_names2` to a specific revision

Cargo.lock, compiler/core/Cargo.toml, compiler/core/src/location.rs, compiler/parser/Cargo.toml
I mostly followed the way that Rome does this in [`rome_rowan`](https://github.com/rome/tools/blob/main/crates/rome_rowan/Cargo.toml), which presumedly comes from Rowan initially.
=> Add optional serde dependency

Lib/test/test_baseexception.py
=> Update test_baseexception.py from cpython 3.11.2

Lib/test/test_hashlib.py, stdlib/src/hashlib.rs
I implemented support for hashlib shake_128 and shake_256.
Going through the code I made some refactoring to better match CPython behavior.
There is one test I had to disable however. The test was enabled but didn't execute any code because shake implementation were missing: https://github.com/RustPython/RustPython/blob/a7c985685146ca401011eb0c25c0b2805a767ce7/Lib/test/test_hashlib.py#L311-L312
But also I'm not sure we want to match openssl length size limitations in our implementation.
=> Implementing shake_128 and shake_256 in the hashlib module

vm/src/stdlib/sys.rs, vm/src/version.rs
Resolve #4550
With this patch, I got the same string as with CPython's `sys.winver`.
=> Add sys.winver

Lib/test/test_with.py
#4564
Tests related to python/cpython#26809 have been marked as failing tests.
=> Update test/test_with.py from CPython 3.11.2

Lib/test/test_contextlib.py
=> Update test/test_contextlib.py from CPython 3.11.2

Lib/test/test_collections.py, Lib/test/test_typing.py, derive-impl/src/pyclass.rs, derive-impl/src/util.rs, vm/src/builtins/bytearray.rs, vm/src/builtins/dict.rs, vm/src/builtins/list.rs, vm/src/builtins/set.rs, vm/src/builtins/slice.rs, vm/src/builtins/type.rs, vm/src/class.rs, vm/src/stdlib/collections.rs, vm/src/types/slot.rs
In CPython:
- If a type is marked as unhashable on the native side (i.e. `PyObject_HashNotImplemented` is assigned to hash slot), then `__hash__` attribute of the type dict is set to None so that the type is considered as unhashable on Python side too.
- If a type is created at runtime and `"__hash__": None` is given as the type dict (like `type('C', (object,), {'__hash__': None})`), then the hash slot is filled with PyObject_HashNotImplemented.
In RustPython, Unhashable trait exists to mark a type as unhashble. But there is no way to check if a type implements Unhashable trait at runtime, so it is hard to follow the CPython's mechanism.
So I've added `unhashable_wrapper` function similar to PyObject_HashNotImplemented, and used that as a marker for unhashable on the native side.
--- …
=> Update to pass test for unhashable collections

Lib/test/test_contextlib.py, Lib/test/test_with.py, vm/src/frame.rs
This patch does not cover all cases of `test_contextlib.py`
`bytecode::Instruction::SetupWith` and `BeforeAsyncWith` raise a TypeError instead of an AttributeError.
It relates to #4650
=> Change error type for bad objects in "with" and "async with"

Cargo.toml
it will be better than only showing it on README and getting continuous same issues.
=> Pin our toolchain to Rust version 1.67.1

compiler/core/src/bytecode.rs, compiler/core/src/marshal.rs, derive-impl/src/compile_bytecode.rs, jit/tests/common.rs, pylib/src/lib.rs, src/interpreter.rs, vm/src/builtins/code.rs, vm/src/frozen.rs, vm/src/import.rs, vm/src/stdlib/imp.rs, vm/src/vm/mod.rs, wasm/lib/src/vm_class.rs
Now frozen modules are stored as lz4-compressed in static memory until they are imported, which should help with memory usage in a freeze-stdlib environment (and the size increase from less efficient(?) compression due to potentially less dict-sharing(?? i have no clue how compression algorithms actually work) should hopefully not be too bad)
=> Rework frozen modules and directly deserialize to CodeObject<Literal>

Lib/test/test_pickle.py, vm/src/exceptions.rs, vm/src/stdlib/builtins.rs
Add BaseExceptionGroup that is introduced in Python 3.11. ExceptionGroup still needs to be implemented.
#4628 
[1]: https://docs.python.org/3/library/exceptions.html#exception-groups
=> Add BaseExceptionGroup

Lib/test/test_types.py
[#4564](https://github.com/RustPython/RustPython/issues/4564)
Changes from CPython v3.11.2 produce a single failure on a new test `test_dunder_get_signature`. There seems to be no signature found in builtin method `__get__` of 'method_descriptor' objects, so it raises a ValueError. I added the `expectedFailure` decorator to that function.
=> Update test/test_types from CPython 3.11.2

compiler/core/Cargo.toml, compiler/parser/Cargo.toml
The Serde-enabled paths actually rely on this -- it was just missing. (Ruff was fine with this, since Ruff's Serde includes this feature, but attempting to compile outside of Ruff was causing an error.)
From `compiler/parser`, run `cargo test --all-features`.
Before:
```
error: cannot find derive macro `Serialize` in this scope
--> compiler/core/src/location.rs:6:38
|
6 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
|                                      ^^^^^^^^^
|
note: `Serialize` is imported here, but it is only a trait, without a derive macro
--> compiler/core/src/location.rs:2:26
|
2 | use serde::{Deserialize, Serialize};
```
After: success.
=> Include Derive feature with optional Serde dependency

Lib/_compression.py, Lib/gzip.py, Lib/test/test_gzip.py, extra_tests/snippets/stdlib_zlib.py, stdlib/src/zlib.rs
Updated `_compression.py` to match  CPython v3.11.2. I didn't see any immediate unit test for this, so it seemed fit to test using a library that relies on `_compression.py`. I updated `gzip.py` / `test_gzip.py` and accounted for the unexpected failures on `test_gzip.py`. 
The failures were primarily wbit errors tracing to `stdlib/src/zlib.rs`, but I am not familiar enough with this module in rust to correct the issues.
=> Update _compression, gzip, and test_gzip for CPython v3.11.2

.github/workflows/ci.yaml
Attempting to add #4665, but I don't know if this is right.
Needed to install `gcc-aarch64-linux-gnu` to get this to check locally.
=> Add an architecture with libc::c_char == u8 build to CI

Lib/test/test_string.py
#4564 update test_string.py from Cpython v3 with expectedFailure
=> Update test_string.py from Cpython v3.11.2

Lib/test/test_sort.py, vm/src/iter.rs
modified `richcompare` fn in `iter.rs` to #4564 resolve unittest error in `test_sort.py`
removed TODO mark in `test_sort.py`
=> resolve unittest error in test_sort.py

Lib/test/test_bytes.py, vm/src/cformat.rs
This is a follow-up of the following PR
https://github.com/RustPython/RustPython/pull/4746
It addresses the failing test case for test_mod, where,
```
b'...%(foo)b...' % {b'foo':b"abc"}
```
caused invalid key error for 'foo'
The cause of this issue was that individual tokens in bytesinner were converted to string before being used for string formatting, but the token being addressed was expected to be in bytes.
It was addressed by making sure that it is treated as bytes.
=> Fix issue with cformat converting bytes to string for bytesinner

Lib/test/test_builtin.py
#4564 update test_builtin.py from cpython v3.11.2
=> update test_builtin.py from cpython v3.11.2

Lib/test/test_bytes.py, common/src/cformat.rs, vm/src/cformat.rs
More details can be found here
https://github.com/RustPython/RustPython/issues/4762
It was the last issue that made test_mod to fail, so I also removed the expectedFailure flag from that test.
=> Allow try_update_quantity_from_tuple to set left alignment when needed

Lib/test/string_tests.py, vm/src/builtins/str.rs, vm/src/bytesinner.rs
I update string_tests.py from python 3.11.2. And then I found that the test case in string_tests was failing because rustpython returns b'' when executing the statement b''.replace('', 'A', 100), whereas cpython returns b'A'. 
After investigating, I discovered that there was no handling for cases where both the self and the first argument are empty strings, so I fixed it.
=> update string_tests and solve failing test

Lib/test/test_descr.py
While working on unary & ternary function behaviour in number protocol, I found there is `test_descr` in cpython. 
There are a lot of tc which makes failure or internal crash. It will be helpful for our slot & descriptor works
=> Add test_descr from cpython v3.11.2

common/src/os.rs, stdlib/src/posixsubprocess.rs, stdlib/src/socket.rs, stdlib/src/sqlite.rs, stdlib/src/ssl.rs, vm/src/function/fspath.rs, vm/src/function/mod.rs, vm/src/stdlib/io.rs, vm/src/stdlib/nt.rs, vm/src/stdlib/os.rs, vm/src/stdlib/posix.rs, vm/src/stdlib/posix_compat.rs
FsPath work to support #4773 
cc @ilp-sys 
`PyPathLike` is defined in `posixmodule` as `path_t`.
But FsPath is more common concept.
`PyPathLike` also is not a python object. We don't prefix non-python object with `Py` anymore without good reasons
=> relocate FsPath from stdlib::os and rename PyPathLike to OsPath

whats_left.py
I added a check that whats_left is being run with CPython 3.11 or newer, as suggested here https://github.com/RustPython/RustPython/pull/4255#issuecomment-1298014225 and also put one signature under the other to make them easier to compare
=> Don't run whats_left with older CPython versions

extra_tests/snippets/syntax_del.py, vm/src/stdlib/sys.rs
This PR aims to handle panic in `unraisablehook`
and thus fixes panic issue as mentioned in https://github.com/RustPython/RustPython/issues/4863
Note: It doesn't fixes underlying issue, as I am not sure what is expected in given scenario (cpython hangs if inputs as per as #4863 ).
Also, I am not sure what to put as default in unwrap_or_else.
=> handle panic if str is not defined in unraisablehook

stdlib/src/sqlite.rs, vm/src/builtins/str.rs, vm/src/exceptions.rs, vm/src/frame.rs, vm/src/stdlib/io.rs, vm/src/vm/context.rs
The goal of this commit is to convert Context::empty_str to &'static PyStrInterned and to fix #4869
Summary of what I did:
- In `vm/src/vm/context.rs`, I changed empty_str to `&'static PyStrInterned`
- Anywhere that has `empty_str.clone()` I changed it to `empty_str.to_owned()` as suggested by rustc. 
This is my first time contributing to this project, and I appreciate your feedback.
=> Convert Context::empty_str to &'static PyStrInterned

stdlib/src/array.rs, stdlib/src/contextvars.rs, stdlib/src/socket.rs, vm/src/builtins/code.rs, vm/src/builtins/function.rs, vm/src/builtins/slice.rs, vm/src/exceptions.rs, vm/src/stdlib/collections.rs, vm/src/stdlib/io.rs, vm/src/stdlib/itertools.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/os.rs, vm/src/stdlib/posix.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/thread.rs, wasm/lib/src/js_module.rs
I implemented the tp_repr slot for most types except tuples (c.f. #4653).
Implementing it for tuples turns out to be quite tricky and will probably require quite some refactoring.
=> Implemented tp_repr slots for more types

.github/workflows/ci.yaml
Fixes https://github.com/RustPython/RustPython/issues/4915 by setting correct dir path
=> fix wrong directory name for openssl setup

Lib/test/test_sqlite3/test_hooks.py, stdlib/src/sqlite.rs
```python
>>>>> import sqlite3; sqlite3.connect(':memory:').create_collation('X', 42)
```
(no output)
```python
>>> import sqlite3; sqlite3.connect(':memory:').create_collation('X', 42)
TypeError: parameter must be callable
```
```python
>>>>> import sqlite3; sqlite3.connect(':memory:').create_collation('X', 42)
TypeError: parameter must be callable
```
- https://github.com/python/cpython/blob/dc328d398d8f65ec6d2fa493e16ceee75f6d774a/Modules/_sqlite/connection.c#L2078-L2081
=> sqlite: Throw `TypeError` when `callable` is not callable

.github/workflows/ci.yaml, Lib/site.py, Lib/sysconfig.py, Lib/test/test_site.py
This work should resolves https://github.com/RustPython/RustPython/issues/4911
Aim
Note: Instead of having both python and rustpython, I am including only one as venv/lib/rustpython3.11/site-packages, as venv/lib/python3.11/ severs no purpose and create confusion.
=> Ensure correct site packages are visible to rustpython

Cargo.lock, Lib/hashlib.py, Lib/test/test_enum.py, Lib/test/test_hashlib.py, Lib/test/test_hmac.py, stdlib/Cargo.toml, stdlib/src/blake2.rs, stdlib/src/hashlib.rs, stdlib/src/lib.rs, stdlib/src/md5.rs, stdlib/src/sha1.rs, stdlib/src/sha256.rs, stdlib/src/sha3.rs, stdlib/src/sha512.rs
1) split hashlib and _hashlib
2) add libraries: _md5, _sha1, _sha3, _sha256, _blake2
3) add tests for hashlib
=> Update test_hashlib.py from Cpython v3.11.2 & refactor hashlib

derive-impl/src/pymodule.rs, derive-impl/src/util.rs, stdlib/src/ssl.rs, vm/src/builtins/mod.rs, vm/src/builtins/module.rs, vm/src/stdlib/builtins.rs, vm/src/stdlib/imp.rs, vm/src/stdlib/io.rs, vm/src/stdlib/nt.rs, vm/src/stdlib/os.rs, vm/src/stdlib/posix.rs, vm/src/stdlib/posix_compat.rs, vm/src/stdlib/sys.rs, vm/src/stdlib/time.rs, vm/src/vm/mod.rs, vm/src/vm/vm_new.rs
The first commit is #4898 
- Adding `PyModuleDef` for static module definition.
- Adding `#[pymodule(with(...))]` and `#[pymodule(sub)]` to support module composition better. It works like trait composition of `#[pyclass]`
=> PyModuleDef and #[pymodule(with(...))]

vm/src/builtins/descriptor.rs, vm/src/builtins/type.rs, vm/src/types/zoo.rs, vm/src/vm/context.rs
- PyMemberDef: Matches to CPython name and similar naming as `PyMethodDef`. `PyMehtodDef` is a python object in CPython
- PyMemberDescrObject -> PyMemberDescriptor
- we don't use -Object suffix
- we avoid abbr as much as possible
=> Rename method/member types

compiler/parser/python.lalrpop
This PR changes the `python.lalrpop` to use `Located::new` over the struct initializer syntax. 
This change is motivated to ease upstream contribution from Astral's RustPython fork. Astral's fork uses `Located::end_location: Location` over `Located::end_location: Option<Location>` [[PR](https://github.com/astral-sh/RustPython/pull/4)].
Using `Located::new` has the added benefit that it requires slightly less code because the `custom` field can be omitted, and `end_location` doesn't need to be wrapped in `Some`
=> Use `Located::new` over struct initializer

compiler/ast/asdl_rs.py, compiler/ast/src/ast_gen.rs, compiler/parser/python.lalrpop, compiler/parser/src/function.rs
This is a follow-up to #4192 and is motivated by the discussions in https://github.com/astral-sh/RustPython/pull/4
The PR adds the`start` and `end` methods to `Located` that return a node's start or end location. The `end` method falls back to returning `location` if `end_location` is `None`. 
The PR further implements `Deref` for `Located` so that the node's fields and methods can be accessed directly: You can write `located.field` instead of `located.node.field`
=> Add `Located::start`, `Located::end` and impl `Deref`

wasm/lib/src/vm_class.rs
Fix #4931
`rustpython-wasm` crate doesn't have `stdlib` feature
=> Fix wasm build stdlib

stdlib/src/array.rs, stdlib/src/bisect.rs, stdlib/src/contextvars.rs, stdlib/src/math.rs, stdlib/src/mmap.rs, stdlib/src/pyexpat.rs, stdlib/src/pystruct.rs, stdlib/src/sqlite.rs, stdlib/src/ssl.rs, stdlib/src/syslog.rs, vm/src/builtins/function.rs, vm/src/builtins/memory.rs, vm/src/builtins/str.rs, vm/src/builtins/weakref.rs
@discord9 could you check this is safe?
In my opinion, *Args object never be referenced by any object but they instantly removed after a function call.
They will not have chance to be called by traverse.
=> Remove Traverse from FromArgs

compiler/codegen/src/compile.rs, compiler/codegen/src/symboltable.rs
=> more location -> start()

vm/src/stdlib/time.rs
#4938
It now creates an overflow error with the message described in the issue. 
Output: 
```
Welcome to the magnificent Rust Python 0.2.0 interpreter
>>>>> import time
>>>>> time.mktime((88,)*9)
OverflowError: mktime argument out of range
```
=> Report overflow error

Lib/uuid.py
cc @lastmjs
https://github.com/python/cpython/pull/104397
=> Allow uuid on wasm32 and wasi

Lib/test/test_trace.py, vm/src/protocol/callable.rs
#4906
trace_func and profile_func now set to none if errors are encountered
Working with the example code:
```
import sys
def trace(frame, event, arg):
raise NameError
return trace
sys.settrace(trace)
print("fail here")
try:
a = 1/0
except:
print("not allowed")
```
RustPython now correctly will print:
fail here
not allowed
=> Set trace_func / profile_func to none on error

Cargo.lock, Cargo.toml
https://github.com/RustPython/Parser/pull/35 
cc @lastmjs The binary size goes 100k smaller and hopefully function `__reduce` can be smaller.
=> Reduce parser size and Avoid copying elements when parsing

Lib/subprocess.py, Lib/test/test_subprocess.py, stdlib/src/posixsubprocess.rs
Some args to `fork_exec` were missing which are currently unused. Hopefully, Windows doesn't mind too much.
=> Update subprocess to CPython 3.11

Lib/abc.py, Lib/test/test_abc.py
Was poking around abc and noticed it wasn't updated!
abc.py [from cpython](https://github.com/python/cpython/blob/3.11/Lib/abc.py)
test_abc.py [from cpython](https://github.com/python/cpython/blob/3.11/Lib/test/test_abc.py)
#4564
=> Update abc.py from Python 3.11

Lib/test/test_abc.py, Lib/test/test_dataclasses.py, extra_tests/snippets/stdlib_abc.py, vm/src/builtins/object.rs
Print the names of abc and the abstract methods, instead of a generic message when trying to instantiate abc. 
Allows remaining test_abc.py tests to pass.
Also noticed a snippet in extra_tests that I think was just forgotten.
=> Fix abc error message

.github/workflows/ci.yaml
Temporarily skip testing the configparser for Mac until #4995 is resolved.
=> Temporarily skip configparser.

Lib/test/test_itertools.py, vm/src/stdlib/itertools.rs
Add accumulate.__reduce__ implementation for #3611.
Publishing as a draft to collect initial feedback. Behaviour seems to be identical to CPython's, but I'm still testing.
- https://github.com/python/cpython/blob/main/Modules/itertoolsmodule.c#L3858-L3894
=> Implement itertools.accumulate.__reduce__ and __setstate__

extra_tests/snippets/syntax_non_utf8.py, vm/src/stdlib/builtins.rs
Can't find anything in Python's changelogs but it appears eval now returns a SyntaxError in this case, lets see what the tests think.
=> Return SyntaxError with null byte input in eval.

.github/workflows/ci.yaml, .github/workflows/cron-ci.yaml
It seems that the Mac CI sometimes targets 3.11.3, sometimes 3.11.4 and this is becoming very annoying. Pin the Python version to a specific major.minor.micro. Ideally, we'd like to target major.minor in the future.
=> Pin Python version to 3.11.4 in CI runs.

Lib/_collections_abc.py, Lib/test/test_collections.py, Lib/test/test_typing.py
#4564 updating _collections_abc.py to 3.11.2 for Python
=> updated _collections_abc.py and test_collections.py to CPython 3.11.2

Cargo.lock, Cargo.toml, compiler/codegen/src/compile.rs, compiler/codegen/src/symboltable.rs, vm/src/stdlib/ast/gen.rs
Part of https://github.com/RustPython/RustPython/issues/4996
- Adds generated content using the latest Python ASDL
- Bumps RustPython/Parser to the latest version
- Adds stubs for handling generic type parameters and type alias statements
I know more will need to be done to actually _use_ PEP 695, I'd like to address these in separate pull requests if feasible.
=> Add parser support for PEP 695

src/lib.rs
When compiling to WASI the the current directory is set to `/` on boot. That's a bit unfortunate and it means that if you'd list files in `.` it would read the root directory. This PR allows to initialize the current working directory from the `PWD` environment variable. I have added a `target` check to only do this for WASI.
=> Add ability to initialize cwd from PWD when targeting WASI

pylib/build.rs, vm/src/vm/mod.rs
=> Fix `freeze-stdlib` + `Interpreter::without_stdlib`

src/shell.rs
This PR prints the same initial messages that you'd expect in the CPython shell, at least to some extend.
=> Print version and info text when executing the shell

Lib/platform.py, Lib/test/test_platform.py, Lib/test/test_sysconfig.py, vm/src/stdlib/sys.rs
=> Update platform from CPython 3.11.5

.github/workflows/ci.yaml
We added the `--check` flag directly to cargo fmt some time back, so when I stumble across cases of the older more verbose versions I open these types of PRs to increase awareness.
Additionally, when `cargo fmt` is invoked in the root of a workspace it will automatically format all the workspace members (you can see that `cargo fmt --all --check -- --verbose` will enumerate the same files as `cargo fmt --check -- --verbose`).
Our `--all` flag is a bit dated compared to other tools, and is only necessary with `cargo fmt` in some more edge type cases (e.g. wanting to format packages that aren't explicit workspace members, or when invoking from certain subdirectories)
=> simplify rustfmt invocation in CI

jit/src/instructions.rs, jit/tests/float_tests.rs
Implemented Binary operations (ADD, SUB, MUL, DIV for now) for allowing mixed type calculations with integers and floating point numbers
1. I assume that division by zero is yet to be handled in current JIT implementation.
2. Added necessary tests
=> [JIT]  Binary operations for integers and floating-point numbers allowing mixed type calculations

vm/src/protocol/object.rs
Hi!
I noticed that there was an error in my earlier pull request (#5091 ). `fast_isinstance()` should be called by `self` instead of `self.class()` in `type_check`. Sorry for the inconvenience.
=> fix type_check

vm/src/builtins/function.rs, vm/src/frame.rs
We need this fake one to make Python 3.12 functools work
=> Fake PEP-0695 with empty __type_params__

README.md
The `rustpython-*` crates have been published since this message was added.
=> Remove outdated info about yanked crates

stdlib/Cargo.toml
This pull request updates the `puruspe` library from version 0.1.5 to 0.2.0. The API syntax remains unchanged, ensuring full backward compatibility. The new version provides a critical bug fix in the gamma function, enhancing the library's reliability and accuracy.
=> Update puruspe version from 0.1.5 to 0.2.0

Lib/ast.py, Lib/test/support/ast_helper.py, Lib/test/test_ast.py
One of testcases contains`match-case` statement which is not supported so I commented it out.
#5104
=> Update ast, test_ast from CPython 3.12.0

Lib/test/test_slice.py, extra_tests/snippets/builtin_slice.py, vm/src/builtins/slice.rs
related to #5101.
This PR implemented slice hash based on [sliceobject.c](https://github.com/python/cpython/blob/main/Objects/sliceobject.c#L653) and updated cooresponding tests.
It seems that the hash results for many objects are different from CPython's, e.g. `hash(None)`.
=> Support slice hash

Cargo.lock, Cargo.toml
Without 'std' I can't compile for 'wasi'. It seems that random state has to be supplied when 'has_std' is false and somehow indexmap thinks there is no 'std' in 'wasi'.
Also bumped indexmap to match lock file.
```
error[E0107]: struct takes 3 generic arguments but 2 generic arguments were supplied
--> /workspaces/aici/RustPython/vm/src/function/argument.rs:65:17
|
65 |     pub kwargs: IndexMap<String, PyObjectRef>,
|                 ^^^^^^^^ ------  ----------- supplied 2 generic arguments
|                 |
|                 expected 3 generic arguments
|
note: struct defined here, with 3 generic parameters: `K`, `V`, `S`
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-1.9.3/src/map.rs:76:12
|
76 | pub struct IndexMap<K, V, S> {
|            ^^^^^^^^ -  -  - …
```
=> enable std feature in indexmap

extra_tests/snippets/builtin_none.py, vm/src/builtins/singletons.rs
This was changed in Python 3.12. Closes #5103
=> None.__ne__(None) should be NotImplemented

Lib/test/test_complex.py, vm/src/builtins/complex.rs
Addressing issue #5138, this PR adds another check on the `inner_pow` function to raise error when the real number part of power number is negative
=> Raise error on power with negative number

Cargo.lock, Lib/test/test_long.py, vm/src/builtins/int.rs
The [docs](https://docs.python.org/3/library/functions.html#round) specify that calling `round` with a negative precision removes significant digits, so that `round(12345, -2) == 12300`. The implementation was simply returning the original integer.
Additionally, `round(a, b)` is implemented as `(a / 10^b) * 10^b`, using half-even rounding during the division.
=> Fix integer rounding

Lib/test/test_binascii.py, Lib/test/test_codecs.py, Lib/test/test_uu.py, stdlib/src/binascii.rs
- Fix logic bug in both `binascii.a2b_uu` and `binascii.b2a_uu`.
- Use correct error type by `new_binascii_error` instead of `new_value_error`.
- Pass three more unit tests: `test_uu`, `test_returned_value` and `test_unicode_a2b`.
[Edit]
- Pass more related unit tests in `test_uu` and `test_codecs`.
=> Fix bug in `binascii` `uu` encoding. Pass more related unit tests.

Cargo.lock, Cargo.toml, benches/execution.rs, benches/microbenchmarks.rs
The benchmarks seem to have been broken since Python 3.10 deprecated the API
they were using to parse and execute CPython baselines. Since then
rust-cpython has been deprecated in favor of pyo3.
- Replace `cpython` and `python3-sys` dependencies with `pyo3`.
- Add `html_report` feature to `criterion`, it will be required in a
future release.
- Remove `anyhow`. It was unused and cargo cleaned it up automatically.
- Use `compile` and `exec` from within the CPython context to
compile and execute benchmarks. There's probably more overhead to that than
the internal API had, but that overhead should be consistent per
benchmark.
If anyone cares about hyperoptimizing benchmarks then they can optimize
the harness as well.
Fixes #3498
=> Fix benchmarks by replacing rust-cpython with pyo3

Lib/test/test_collections.py, vm/src/builtins/dict.rs, vm/src/builtins/list.rs, vm/src/builtins/str.rs, vm/src/dictdatatype.rs
Python does not define `list().__bool__`, `dict().__bool__`, and `str().__bool__`, and some tests were failing because they were defined.
I could not find any references to them and deleting them doesn't seem to break anything.
=> Removed unused __bool__ methods

Lib/test/test_collections.py, Lib/test/test_set.py, benches/microbenchmarks/frozenset.py, common/src/hash.rs, vm/src/builtins/set.rs, vm/src/types/slot.rs, vm/src/utils.rs
The original hash algorithm just XOR'd all the hashes of the elements of the set, which can be problematic. The CPython algorithm is required to pass the tests.
- Replace `PyFrozenSet::hash` with CPython's algorithm
- Remove unused `hash_iter_unorded` functions
- Add `frozenset` benchmark
- Enable tests
- Lower performance expectations on effectiveness test
- Adjust `slot::hash_wrapper` so that it doesn't rehash the computed hash value in the process of converting PyInt to PyHash
=> Use CPython hash algorithm for frozenset

Lib/code.py, Lib/test/test_code.py
```log
ssssssxxsxxxxx..xxxxxsxxxx..
Ran 28 tests in 0.958s
OK (skipped=8, expected failures=16)
```
The current tests have passed, and the new version has added several test functions, among which three functions have failed. I have marked them as TODO. For details,
please check commit 572053df82a6ad1b09e00be3d4cb130eb8eba762.
#5104
=> Update code.py and test_code.py from CPython v3.12 

Lib/copy.py, Lib/test/test_copy.py
```log
...........x.............................x..................................
Ran 76 tests in 0.223s
OK (expected failures=2)
```
#5104
=> Update `copy.py` and `test_copy.py` from CPython v3.12 

Lib/_collections_abc.py, Lib/collections/__init__.py, Lib/test/test_collections.py, Lib/test/test_ordered_dict.py, Lib/test/test_typing.py
Update `_collections_abc.py` and `test_collections.py` to 3.12.2
`test_Buffer` is disabled pending #5179
This should check off `_collections_abc.py` and `test/test_ordered_dict.py`. from #5104. I'm unsure what else would be required to check off `collections`.
=> Update `_collections_abc.py` and `test_collections.py` to 3.12.2

Lib/csv.py, Lib/test/test_csv.py, stdlib/src/csv.rs
I've updated `csv.py` and `test_csv.py`, but version 3.12 has changed the import options, and `__version__` now needs to be imported from `_csv.c` (which is now `csv.rs`). It seems that `csv.rs` has not yet aligned with the behavior of `cpython` upstream. Should we consider updating `csv.rs` or postponing this commit? Due to this reason, I'm still unable to test `test_csv`.
=> 【Need Update csv.rs】Update csv.py and test_csv.py from CPython v3.12 

Lib/test/test_cmd_line.py, Lib/test/test_format.py, Lib/test/test_socket.py
Fix some easy test failures.
There are more failing tests, but they don't fail when run individually, and so are much harder to debug. See #5190
=> Fix convenient failing tests

Lib/test/test_cmd_line.py
After you suggestion in https://github.com/python/cpython/issues/116504#issuecomment-1999239012 I went to take a look at `test_cmd_line` in RustPython (it was so long ago I contributed to this amazing project, so may thing had changed!), and I've noticed this.
This is a problem, here' the simplest demo:
```python
import unittest
class TestMe(unittest.TestCase):
@unittest.expectedFailure
def test_me(self):
def run():
raise ValueError
with self.subTest(run=run):
run()
if __name__ == '__main__':
unittest.main()
```
This works as expected:
```
» ./python.exe ex.py
x
Ran 1 test in 0.001s
OK (expected failures=1)
```
This does not:
```python
import unittest
class TestMe(unittest.TestCase):
def test_me(self): …
```
=> Remove incorrect `@expectedFailure`s from `test_cmd_line`

Lib/test/test_os.py
This test was marked as an expected failure. Because the garbage collector is missing, that meant that the `os.scandir` object went unclosed. This object was squatting on the file descriptors of all the files contained in the test directory, which was breaking test_zipfile.
=> Skip TestScandir.test_uninstantiable

vm/src/frame.rs
Context managers have an `__exit__` function that returns a boolean-like object. If the object is truthy, then exceptions are suppressed.
If an exception was thrown while resolving that boolean, it would leak and live on in the error stack, getting tacked on to all future exceptions. This caused several mysterious test failures which would only trigger after this very specific event was tested in `test_with`.
The solution is to move a call to `vm.set_exception()` before attempting the `try_to_bool()` which threw the error.
Minimal example to reproduce the bug:
```py
import sys
import traceback
class cm(object):
def __init__(self):
pass
def __enter__(self):
return 3
def __exit__(self, a, b, c):
class Bool:
def __bool__(self):
1 // 0
return Bool()
try:
with cm():
raise Exception("Should NOT …
```
=> Reset exception in WithCleanupFinish

Lib/test/test_typing.py
See https://github.com/RustPython/RustPython/issues/5190#issuecomment-2010535802
I suspect that upgrading typing to 3.12 will resolve this, but I am not sure, and it would be a lot of work. For now, disabling this test should fix the related test failures.
=> Skip typing test which causes other failures

Lib/test/test_os.py, Lib/test/test_zipfile.py
See https://github.com/RustPython/RustPython/pull/5204#discussion_r1534119326
Thanks @fanninpm , did not know that
I wound up finding at least three other tests that were also leaving unclosed file descriptors lying around and causing this test to fail. Rather than continue hunting them all down, I think it's easier to just increase the threshold so that they don't impact this test.
I suspect this is not an issue for CPython because it has a working garbage collector, and it has very few tests that are expected to fail.
=> Increase threshold for zipfile test_many_opens 

Lib/test/test_itertools.py, vm/src/stdlib/itertools.rs, vm/src/stdlib/sre.rs
Adds the itertools.batched function new in python 3.12
https://docs.python.org/3/library/itertools.html#itertools.batched
=> Add itertools.batched Support

examples/call_between_rust_and_python.rs, examples/package_embed.rs, src/lib.rs, stdlib/src/array.rs, stdlib/src/sqlite.rs, vm/src/builtins/module.rs, vm/src/builtins/object.rs, vm/src/builtins/tuple.rs, vm/src/frame.rs, vm/src/import.rs, vm/src/stdlib/codecs.rs, vm/src/stdlib/io.rs, vm/src/stdlib/operator.rs, vm/src/stdlib/sre.rs, vm/src/stdlib/sys.rs, vm/src/stdlib/warnings.rs, vm/src/vm/compile.rs, vm/src/vm/mod.rs, vm/src/warn.rs
Simplify `vm.import` call and provide another version for from_list
=> split vm.import and vm.import_from

vm/src/import.rs, vm/src/vm/interpreter.rs, vm/src/vm/mod.rs, vm/src/vm/vm_object.rs, wasm/lib/src/browser_module.rs
fix #5041 #5177
We already had almost same function `rustpython_vm::import::import_file`. This new function only skip to set `__file__` attribute of the new module.
=> rustpython_vm::import::import_source

Lib/test/test_opcache.py, derive-impl/src/pyclass.rs, vm/src/builtins/object.rs
This pull request is related with https://github.com/RustPython/RustPython/issues/5105. The error was raised when executing the below lines:
```python
if not six.PY2:
class RequestModule(sys.modules[__name__].__class__):
def __call__(self, *args, **kwargs):
"""
If user tries to call this module directly urllib3 v2.x style raise an error to the user
suggesting they may need urllib3 v2
"""
raise TypeError(
"'module' object is not callable\n"
"urllib3.request() method is not supported in this release, "
"upgrade to urllib3 v2 to use it\n"
"see https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html"
)
sys.modules[__name__].__class__ = RequestModule  # HERE.
```
I thought it is because RustPython doesn't allow update even if the `value` is module's subclass. This pull request just …
=> Allow update `__class__` for mutable types or module subclasses

.github/workflows/ci.yaml, Lib/test/test_builtin.py, extra_tests/snippets/builtin_none.py, vm/src/builtins/singletons.rs
This pull request is related with https://github.com/python/cpython/issues/112125, https://github.com/RustPython/RustPython/issues/5103, https://github.com/RustPython/RustPython/pull/5124.
In Python 3.12, `None.__ne__` behavior was changed but it was a bug. According to the GitHub issue, the bug was fixed in *3.12.1* version and deployed. When I run `None.__ne__(None)` in `3.12.2` CPython, it returns `False`.
=> Fix `None.__ne__` bug

Lib/test/test_descr.py, Lib/test/test_importlib/test_lazy.py, vm/src/builtins/object.rs
This pull request continues from #5225 PR. In that PR, I missed to downcast `value` to `PyType` type when evaluating `both_module` value. So `cargo run -- --install-pip get-pip` was still failed in the same reason.
This pull request downcasts `value` to `PyRef<PyType>` when `value` is module type. Also it checks `value` is `PyType` first, once.
This pull request doesn't resolve an issue, *get-pip doesn't work*, completely. After this pull request, it should bump `Lib/shutil` to Python 3.12 version's.
=> Check `value` is `PyType` first

Cargo.lock, Lib/shutil.py, Lib/test/test_shutil.py, stdlib/Cargo.toml, vm/Cargo.toml, vm/src/stdlib/os.rs, vm/src/stdlib/winapi.rs
This PR is a PR for successful pip installation along with #5227, #5225 PR. Since `get-pip.py` needs `shutil.rmtree`'s `onexc` parameter, I bumped the module to _3.12.3_. And I checked that it can install pip and execute pip.
But I'm not sure the `DirEntry.is_junction` implementation is correct. I just used the code the below parts. It may need more research and confirmation.
https://github.com/RustPython/RustPython/blob/b1c3c9a9d6145bbb1872feb383e0fdd7c0dd10d4/vm/src/stdlib/os.rs#L444-L446
```
% cargo run --features=ssl -- --install-pip get-pip                                                                                                                           
Compiling rustpython-stdlib v0.3.1 (/Users/moreal/github/RustPython/RustPython/stdlib)
Compiling rustpython v0.3.1 …
```
=> Bump shutil to 3.12.3

Lib/test/test_class.py, Lib/test/test_hash.py, Lib/test/test_weakset.py, vm/src/builtins/type.rs
enables the test: testHashStuff in test_class.py
If a class defines its own `__eq__` but not `__hash__`, then CPython sets `__hash__` to None for that class (otherwise it inherits hash from `object`). So this PR re-creates that behavior.
[https://docs.python.org/3/reference/datamodel.html#object.\_\_hash\_\_](https://docs.python.org/3/reference/datamodel.html#object.__hash__)
=> compat fix for testHashStuff in test_class.py

Lib/test/test_baseexception.py, Lib/test/test_exceptions.py, vm/src/frame.rs
Added logic to ensure only BaseExceptions or its subclasses can be used in an except block. Checks and handles tuples of Exceptions too. 
Fix for `test_catch_non_BaseException` in `pylib/Lib/test/test_baseexception.py`
=> unit test fix - only allow catching exceptions - test_catch_non_BaseException

Lib/test/test_bool.py, vm/src/builtins/int.rs
added a check that `int.__new__` cannot be used to construct `bool`
=> fix for test test_bool.BoolTest.test_subclass

Lib/test/test_builtin.py, vm/src/stdlib/ast.rs, vm/src/stdlib/builtins.rs
Code changes to make the test `BuiltinTest.test_compile` in `test_builtin.py` work.
I've made a draft PR as this unit test has multiple different incompatibility issues that all need to be fixed for this to fully work, and so feedback can be given on the first issues while I work on the latter ones. 
Issues:
=> test_builtin.py test_compile unit test fix

.github/workflows/ci.yaml, Lib/filecmp.py, Lib/genericpath.py
The only remaining use of dummy_os is import_pypi. which might be also okay, but not tested.
=> Remove dummy_os import and update filecmp from CPython 3.12.2

Lib/test/test_builtin.py, compiler/codegen/src/compile.rs
Addresses the last todo item of #5251
Optimize=2 removes doc strings, so I added code to do that. 
The unit tests will most likely fail as the main branch commit this branch is based on doesn't pass all the tests.
=> filter out doc strings with opt level 2 as final step to enable test_builtin.py test_compile

Cargo.lock, Cargo.toml, Lib/test/test_future_stmt/test_future.py
Enabled test from PR https://github.com/RustPython/Parser/pull/121 and bumped version of the parser used forward by 4 commits to include the PR.
close #5317
=> Fix for test future.py  test annotations

Lib/test/test_builtin.py, vm/src/builtins/type.rs
test_builtin.py: test_type_qualname fix by checking type of `__qualname__` to be str
=> test_builtin.py: test_type_qualname fix

Lib/test/test_class.py, vm/src/builtins/type.rs
adjusted error message to match expectation when deleting non-existant attributes, e.g. `del A.x` where A has no attr x.
=> test_class.py: testTypeAttributeAccessErrorMessages fix

Lib/test/test_builtin.py, Lib/test/test_descr.py, Lib/test/test_posix.py, vm/src/builtins/type.rs
This revision implements `itemsize` slots and fix `best_base` implementation to select proper base class when generating class.
=> Fix `best_base` to select proper base class

Lib/test/test_descr.py, vm/src/builtins/super.rs, vm/src/builtins/type.rs, vm/src/object/core.rs
Assigning `__bases__` allows you to alter the class inheritance tree at any point. The updated `typing.py` uses this feature when constructing `NamedTuples`, for reasons unknown to me.
I had to make `PyType.bases` and `PyType.mro` mutable behind a `PyRwLock` in order to enable this feature.
Assigning `__bases__` has several features I wasn't sure how to implement. I left TODOs for these:
* Making sure the new method resolution order is actually a tree, i.e. it contains no cycles
* Removing the modified class from any `__subclass__` lists it used to belong to
* Removing any slots that no longer apply (not sure if this is required?)
=> Make `__bases__` mutable

Cargo.lock, stdlib/Cargo.toml
This lets you define `LIBSQLITE3_SYS_USE_PKG_CONFIG=1` in your profile, which cuts out building `libsqlite` from source.
=> Bump libsqlite3-sys

common/src/fileutils.rs, stdlib/src/ssl.rs, vm/src/function/method.rs, vm/src/intern.rs, vm/src/stdlib/os.rs
Fix `missing_transmute_annotations`, `legacy_numeric_constants` added in Rust 1.79.0 clippy
=> Fix `missing_transmute_annotations`, `legacy_numeric_constants` added in Rust 1.79.0 clippy

vm/src/vm/thread.rs
This makes it much easier to store a `ThreadedVirtualMachine` somewhere and run it as many times as we want in another thread.
After looking at the code, I see the way things are set up with the current `run` it's not best to change it from taking `self`. However I might suggest renaming it into `into_run` or similar (along with `into_spawn_func`) as it makes the fact it takes ownership clearer. That'd leave us with being able to name the shared run function simply `run`. However these would be breaking changes, so I left the core implementations the same.
For now I've just made a simple `shared_run` instead which accomplishes this without breaking changes.
I am sure this might require quite a bit of discussion about how we really want it and some refactoring, so let me know your …
=> Make a shared run function in ThreadedVirtualMachine

Lib/test/test_copyreg.py
This PR for a ``copyreg.py`` module.
* ``Lib/copyreg.py`` needs an update
* ``Lib/test/test_copyreg.py`` needs to be created
=> Add ``Lib/test/test_copyreg.py`` from 3.12

Lib/test/test_cmd_line.py, vm/src/vm/setting.rs
A basic fix, which changes sys.flags.int_max_str_digits to `4300` instead of `-1` so it behaves the same as the cpython implementation. Fixes #5139
PS: this is my first issue and I am new here, do let me know if I missed anything.
=> changed int_max_str_digits from -1 to 4300 to be more cpython complient

vm/src/vm/interpreter.rs
Don't let Interpreter::run silently ignore result value
=> Less confusing Interpreter::run 

vm/src/vm/vm_object.rs
which is mainly for rustpythonv-vm users' casual debugging
=> Add vm.print

vm/src/builtins/function.rs, vm/src/frame.rs
WIP
this adds getter and setter for the `doc`, `module` and `annotations` magic attributes for the python function objects.
`module` and `annotations` work without trouble. `doc` is different. The getter and setter were never called until i commented the line `class.set_attr(identifier!(ctx, __doc__), ctx.new_str(doc).into());` in `vm/src/class.rs`.
This will probably break other stuff. But it gets me closer to the goal.
Details
see this python code
```python
def foo():
"""doc string"""
print(foo.__dict__)
```
Output:
- CPython: `{}` - empty dict
- before PR: `{'__doc__': 'doc string', '__module__': '__main__', '__annotations__': {}}`
- without "fix" in `vm/src/class.rs`: `{'__doc__': 'doc string'}`
- with "fix": `{}` - empty dict
Any ideas how to fix this correctly?
=> Add get/set methods for function doc/module/annotations

Lib/test/test_re.py
It recently started to fail.
A bit worrying because 0.1 is already very greater than 0.0003
https://github.com/RustPython/RustPython/actions/runs/10748560557
https://github.com/RustPython/RustPython/actions/runs/10760680587
=> less strict time bound for test_re.test_search_anchor_at_beginning

Lib/test/test_complex.py, Lib/test/test_decimal.py, Lib/test/test_float.py, stdlib/src/math.rs
This allows enabling test_constructor_negative_nans_from_string
=> Fix copysign behavior for NaNs

Lib/test/test_long.py, vm/src/protocol/number.rs
Looking at the to-do, it was supposed to be uncommented when switching the target to python 3.11 but was missed.
=> Deprecate delegating int() to __trunc__

Lib/test/test_weakset.py, vm/src/builtins/set.rs
The previous implementation had multiple bugs:
- self intersection would result in nil set (#3881, #3992 )
- Intersecting {1, 2, 3} in {1} and {2} would result in {1} instead of {}.
The new implementation uses the approach chosen by [cpython](https://github.com/python/cpython/blob/5f011115943933ff36adf997c886d73ea88003fb/Objects/setobject.c#L1481-L1495), i.e., create a normal intersection and then replace `self` with the result.
Allows turning on one test in `test_weakset`. The equivalent test in `test_set` still fails due to some of the other set operations also being buggy on self application.
=> Fix set intersection_update implementation

vm/src/builtins/set.rs, vm/src/dictdatatype.rs
Adds a `try_fold_keys` method to `Dict` which allows performing common operations on all elements without needing to create a `Vec` first.
This sped up the `test_hash_effectiveness` test for FrozenSet from 4.5s to 3.2s on my machine.
=> Avoid allocating a vector of elements when hashing frozenset

Lib/_pydecimal.py, Lib/test/test_decimal.py
Rustpython includes the test added in https://github.com/python/cpython/pull/65, but not the behavior, leading to the test being disabled. This patches RustPython with the above pr  to update `from_float` behavior when passed an int in order to pass the test.
=> Fix inconsistent behavior of Decimal.from_float

Cargo.lock, stdlib/Cargo.toml
`uuid-macro-internal` is only relevant when using `uuid!` macro to parse uuids at compile time. RustPython doesn't do that so it's unnecessary.
=> Remove dependency on uuid-macro-internal

Cargo.lock, Cargo.toml
This dependency is only useful when modifying the crate name of `num_enum` crate (https://github.com/illicitonion/num_enum/blob/86d359f430ecd12be4d544f55bc68c27a3cda82f/num_enum_derive/src/parsing.rs#L545-L550). RustPython doesn't do that so it's unnecessary.
Gets rid of some transitive dependencies like `toml_edit`, `toml_datetime` and `nom8` as well.
=> Remove dependency on proc-macro-crate

Lib/test/test_set.py, vm/src/builtins/set.rs
Adds a hash field to the `PyFrozenSet` data type in order to avoid recomputing the hash of an immutable object.
Similar to the way it's done in [cpython](https://github.com/python/cpython/blob/5f011115943933ff36adf997c886d73ea88003fb/Objects/setobject.c#L761-L774) but the hash value is stored in the PyFrozenSet struct instead of the inner Set datatype.
Massively speeds up the `test_hash_effectiveness` test and allows using the same limit of 2**18 elements on the test as cpython.
RustPython is still about 5x slower than python at running this test (0.5s vs 2.5s on my machine).
Of course, in practical use cases repeatedly hashing the same frozenset is not common so I doubt this is a performance win in general. Just adding this to be consistent with cpython.
Fixes #5167
=> Cache hash value for FrozenSets

vm/src/frame.rs, vm/src/protocol/callable.rs
While trying to fix https://github.com/RustPython/RustPython/issues/5355, I stumbled upon a compile error when the `vm-tracing-logging` feature is enabled.
This PR fixes the above mentioned compile error.
One other thing that came up, is that [/vm/src/protocol/object.rs#L172 ](https://github.com/RustPython/RustPython/blob/98d09e781623ccec64643cf5412453cc78ba4f18/vm/src/protocol/object.rs#L172) generates very long traces and I think that it would be a good idea to use another format since it prints all the data of `self` and `value`.
=> Fix compile error when using `vm-tracing-logging`

common/src/boxvec.rs, common/src/linked_list.rs, common/src/lock/immutable_mutex.rs, common/src/lock/thread_mutex.rs, jit/src/lib.rs, stdlib/src/posixsubprocess.rs, stdlib/src/sqlite.rs, stdlib/src/ssl.rs, vm/src/object/ext.rs, vm/src/ospath.rs, vm/src/protocol/iter.rs, vm/src/protocol/number.rs, vm/src/py_serde.rs, vm/src/recursion.rs, vm/src/stdlib/codecs.rs, vm/sre_engine/src/engine.rs, vm/sre_engine/src/string.rs
Since new version of rust 1.83 released, clippy lint rules are also updated. 
It makes CI broen. 
Most of them is related to 
1. Some lifetimes are newly elided.
2. c str literal is recommended. 
I think there are various change of result in test, I will try them later. 
This PR is only for lint problem.
=> Resolve lint fails w rust 1.83 clippy

src/lib.rs
This exposes `shell::run_shell` as per issue discussion
fixes #5432
=> expose run_shell

.github/workflows/release.yml
Add Release Pipeline for RustPython. Pipeline is currently configured to cut a new release on every merge to main.
Sample Release: https://github.com/theshubhamp/RustPython/releases/tag/2024-12-07-gh-rel-rustpython-11
Sample Build: https://github.com/theshubhamp/RustPython/actions/runs/12212320619
Validated to run on Linux / Fedora:
Issue #5440
=> Add GitHub Binary Release Pipeline for RustPython

Cargo.lock, vm/Cargo.toml
Removes one more reason to have `syn` 1.0 as a dependency. After this, the only dependency still using `syn` 1.0 is `syn-ext` used by `rustpython-derive-impl`.
=> Bump result-like to 0.5.0

extra_tests/snippets/operator_arithmetic.py, vm/src/builtins/bool.rs, vm/src/vm/vm_ops.rs
PyNumber methods are expected to type check both arguments.
Dispatch is not done by inverting parameter order for __r<op>__ (example __ror__) when calls are handled via PyNumberMethods
Other changes:
- Add tests to assert a TypeError is raised when either of the parameter types boolean & other is not convertible to int (str or float for example)
- Sync binary operator order comment with actual implementation
Fixes: #5460
=> Check operand types in bool or, and, xor to be PyInt

.github/workflows/release.yml
Release creation fails with this error:
```
HTTP 422: Validation Failed (https://api.github.com/repos/RustPython/RustPython/releases)
body is too long (maximum is 125000 characters)
Error: Process completed with exit code 1.
```
Most likely because there's no previous release to diff of from.
Disabling, getting a green release & enabling back might fix this.
=> Temporarily disable release notes generation

.github/workflows/release.yml
Self-explanatory: adds a job before releasing that builds and uploads the wasm artifact
=> Build wasm on release

.github/workflows/release.yml
Introduce Weekly Pre-Release + Manual Release for RustPython binaries
Weekly Scheduled release @ Monday 9AM UTC defaults to Pre-Release. Regular Releases can be done using the same workflow by deselecting Mark "Pre-Release" checkbox.
Summary of Changes:
1. Support both Release & Pre-Release in Release Workflow
2. Schedule Pre-Release on Monday 9AM UTC
3. Re-enable Release Notes Generation
Workflow can be run manually. Pre-release of not can be selected at the time of run:
Sample Release: https://github.com/theshubhamp/RustPython/releases/tag/2025-01-03-gh-release-22
Sample Pre-Release: https://github.com/theshubhamp/RustPython/releases/tag/2025-01-03-gh-release-21
=> Introduce Weekly Pre-Release + Manual Release for RustPython binaries

Cargo.lock, vm/Cargo.toml
The latest version prebuilds the table (https://github.com/unicode-rs/rust-caseless/pull/21) thus removing the build step and dependency on regex. RustPython still has regex as a dev dependency but it's no longer part of normal builds, speeding them up.
=> Bump rust-caseless to 0.2.2

README.md
This repo is monorepo so we should use `cargo install --git https://github.com/RustPython/RustPython rustpython` instead
=> docs(readme): fix installation command for cargo

.github/workflows/release.yml
Handle pre-release flag being empty for schedule triggers in release workflow
GitHub workflow_dispatch input variables are always empty for other triggers
=> Handle pre-release flag being empty for schedule triggers in release workflow

vm/src/stdlib/signal.rs
If `install_signal_handlers` is false (due to embedding), the VM still inits the signal stdlib and installs a lot of signal-handling, including touching *ever* signal, including SIGINT.
When running multiple concurrent interpreters with varying inits at varying times, this can break the hosting application's signal-handling so lovingly
set up before starting anything with RustPython.
=> guard signal-handling init more broadly

jit/src/instructions.rs, jit/src/lib.rs, jit/tests/common.rs, jit/tests/misc_tests.rs, vm/src/builtins/function.rs, vm/src/builtins/function/jitfunc.rs
Support recursion in JIT-ed functions
JIT implementation today is experimental & doesn't support calling out (globals, other functions etc.). This PR adds support for recursion.
Summary of Changes:
1. Added a new JitType FuncRef that stores an id-reference to functions imported for use
2. For recursion, a self import is done & passed down to Bytecode Compiler
3. Recursion only works when return type is annotated
On a "non-scientific" benchmark, JIT-ed function appears to be faster than rustpython/intereprted (expected) and cpython 3.13.1
Source of fib.py:
```python
import time
import sys
target = int(sys.argv[1])
def fib(n: int) -> int:
if n == 0 or n == 1:
return 1
fib = 0
return fib(n-1) + fib(n-2)
start_time = time.perf_counter_ns()
val = fib(target)
time_taken = …
```
=> Support recursion in JIT-ed functions

Lib/ctypes/test/test_numbers.py, Lib/test/support/__init__.py, Lib/test/test_float.py, Lib/test/test_list.py, Lib/test/test_listcomps.py, Lib/test/test_unary.py
This pr updates the following tests to 3.12.8:
- ~~test_int~~ (Fails on wasm, so is not included in this PR)
- test_float
- test_unary
- test_numbers
- test_list
- test_listcomps
=> Update tests for builtin objects to python 3.12.8

compiler/codegen/src/compile.rs, compiler/codegen/src/symboltable.rs, compiler/core/src/bytecode.rs, vm/src/frame.rs, vm/src/stdlib/typing.rs
This pull request complements compiler, vm logics related [PEP-0695](https://peps.python.org/pep-0695/).
=> Complement vm logics related with `ParamSpec` and `TypeVarTuple`

Cargo.lock, stdlib/src/ssl.rs
I don't think we were actually affected, but better safe than sorry: https://github.com/sfackler/rust-openssl/security/advisories/GHSA-rpmj-rpgj-qmpm
close #5498
=> Update openssl to fix possible vulnerability

Lib/_colorize.py, Lib/test/test__colorize.py, vm/src/stdlib/nt.rs
Needed for #5517. I added a dummy for `nt._supports_virtual_terminal` which can be fixed later, but I can't think of a scenario where it'd be false.
=> Add _colorize at 3.13.2

Cargo.lock, extra_tests/snippets/builtins_ctypes.py, vm/Cargo.toml, vm/src/stdlib/ctypes.rs, vm/src/stdlib/ctypes/base.rs, vm/src/stdlib/mod.rs
Replacement of #5516.
The following code (adapted from the start of the `ctypes` module) runs:
```python
from _ctypes import sizeof
from _ctypes import _SimpleCData
from struct import calcsize as _calcsize
def _check_size(typ, typecode=None):
from struct import calcsize
if typecode is None:
typecode = typ._type_
actual, required = sizeof(typ), calcsize(typecode)
if actual != required:
raise SystemError("sizeof(%s) wrong: %d instead of %d" % \
(typ, actual, required))
class c_short(_SimpleCData):
_type_ = "h"
_check_size(c_short)
class c_ushort(_SimpleCData):
_type_ = "H"
_check_size(c_ushort)
class c_long(_SimpleCData):
_type_ = "l"
_check_size(c_long)
class c_ulong(_SimpleCData):
_type_ = "L"
_check_size(c_ulong)
if _calcsize("i") == _calcsize("l"):
c_int = c_long
c_uint = c_ulong
else: …
```
=> Initial _ctypes implementation

.github/workflows/ci.yaml
Thanks to #5323 `datetime` now works on windows.
=> test datetime on windows

derive-impl/src/pyclass.rs, derive/src/lib.rs
Originally, this would ignore the `magic`, which is counterintuitive, so it now just throws an error (nothing relies on this, so I think a hard error should be fine). I also documented `pyclass` and `pymodule` with API docs which cover almost everything.
The docs here are mostly just highly specific documentation for every argument and use case. https://github.com/RustPython/RustPython/wiki/Python-Attributes is currently a high level overview and can now be more geared towards that.
It would be nice if the docs for the main branch could be deployed using github pages to display them for users, since the current docs.rs content is highly out of date.
=> Ensure pymethod cannot be both magic and named simultaneously + macro documentation

.github/workflows/ci.yaml, Lib/test/test_importlib/frozen/test_loader.py, Lib/test/test_importlib/resources/test_files.py, Lib/test/test_importlib/resources/test_open.py, Lib/test/test_importlib/source/test_finder.py, vm/src/exceptions.rs
This makes it so that failing tests on windows are explicitly marked on CI, and considered platform dependent, and non-failing ones are re-enabled. This also fixes a few bugs to unblock tests and fix broken ones.
=> Windows testing

.github/workflows/ci.yaml, vm/src/codecs.rs
Fixes #5542; error introduced by #5502. Adds some debug assertions that are also in cpython.
This will help allow test_argparse to work for windows.
=> Fix unicode decode bug on surrogate error mode

.gitattributes, Lib/test/test_random.py, stdlib/src/random.rs, vm/src/stdlib/os.rs
I removed the `StdRng` variant since it was kinda more trouble than it's worth, and there's no clear way to access its state for `getstate`/`setstate`.
=> Fix a bunch of `random` tests

Cargo.toml, stdlib/Cargo.toml, stdlib/build.rs, stdlib/src/ssl.rs, vm/src/stdlib/os.rs, vm/src/utils.rs
`std::env::{set,remove}_var()` are unsafe in rust2024 due to raciness issues, and this PR treats them as such and also switches away from `openssl_probe::init_openssl_env_vars()`, which also uses `set_var` and is now marked unsafe.
=>  Use non-env-var methods from openssl_probe

Cargo.toml, common/src/int.rs, compiler/codegen/src/compile.rs, derive-impl/src/pytraverse.rs, derive-impl/src/util.rs, jit/src/lib.rs, stdlib/src/csv.rs, stdlib/src/json/machinery.rs, stdlib/src/mmap.rs, stdlib/src/socket.rs, stdlib/src/syslog.rs, vm/src/builtins/iter.rs, vm/src/builtins/mappingproxy.rs, vm/src/coroutine.rs, vm/src/frame.rs, vm/src/function/argument.rs, vm/src/stdlib/ast.rs, vm/src/stdlib/ctypes/base.rs, vm/src/stdlib/os.rs, wasm/lib/src/vm_class.rs
Open to suggestions for a better "euphemism" for `gen` - could always just go with `gen_` or even `r#gen`, but `jen` felt like it fit in the tradition of `klass` and `zelf`.
=> Enable rust2024-incompatible pat and keyword-ident lints

.github/workflows/ci.yaml, .github/workflows/cron-ci.yaml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, stdlib/Cargo.toml, stdlib/src/zlib.rs
This is a rust-only reimplementation of the `libz-sys` api, which I discovered [from this blog post](https://trifectatech.org/blog/zlib-rs-is-faster-than-c/). It can build without any C toolchain, which makes it a good pick for us when we're targeting windows and wasm, and the performance isn't anything to scoff at (see blog post). Also, the `zlib` feature now enables the entire `zlib` module, which I feel like just makes more sense.
=> Switch to libz-rs-sys for zlib implementation

Cargo.toml, vm/sre_engine/Cargo.toml
Follow-up to #5560. Also adds `lints.workspace = true` in `vm/sre_engine`
=> Remove redundant lints now that we're on edition2024

.devcontainer/devcontainer.json
See: https://stackoverflow.com/questions/78216235/cargo-not-found-after-installing-in-a-devcontainer
=> fix devcontainer.json

Cargo.lock, extra_tests/snippets/builtins_ctypes.py, vm/Cargo.toml, vm/src/stdlib/ctypes.rs, vm/src/stdlib/ctypes/base.rs, vm/src/stdlib/ctypes/function.rs, vm/src/stdlib/ctypes/library.rs, vm/src/stdlib/mod.rs
Here comes the meat of the code and the hardest part implementation-wise.
The main goal is to implement (atleast partially) `CFuncPtr`. By partially, I mean that not supporting arguments to functions is probably fine. At any rate the cpython implementation can be used as a reference since they use libffi. The main challenge is determining the return type of the loaded function from the `cvoid` it'll return (unless we don't have to do that for some reason).
The next pr can probably just do some cleanup on this and get the basics for struct and union return types working.
- Arguments cause errors to be thrown
- Return type of functions is `c_int` and cannot be changed
- Error handling isn't great.
- `import ctypes` fails
- creating string buffers is broken
=> _ctypes pt. 3

.github/workflows/cron-ci.yaml
The workflow also triggers itself if the file changes to prevent any bug like this from taking to long to identify.
=> Fix what is left data upload to website

Cargo.lock, Cargo.toml, Lib/test/test_cmd_line.py, examples/dis.rs, examples/parse_folder.rs, src/lib.rs, src/settings.rs, vm/src/version.rs
Supercedes #5414 -- the python CLI is really not that complicated, and it turns out it's not that hard to just do the flag handling ourselves, with a little help from [`lexopt`](https://docs.rs/lexopt). This actually cuts down on the number of lines of code we have in the codebase!
=> Use lexopt for argument parsing

.gitattributes
This was causing git to refuse to even attempt to merge Cargo.lock, leading to oftentimes changes to Cargo.lock being completely overwritten in a merge.
=> Remove -merge from Cargo.lock gitattributes

Lib/test/test_class.py, whats_left.py
- Copy `Lib/test/test_clsss.py` from Cpython 3.13.2
- Introduce new cpython_only test api `_testlimitedcapi`
=> Update test class to cpython 3.13.2

common/src/cformat.rs, common/src/format.rs, vm/src/anystr.rs, vm/src/builtins/str.rs, vm/src/bytesinner.rs, vm/src/cformat.rs, vm/src/dictdatatype.rs
Pulled from #5587. This makes the "Make cformat wtf8-compatible" commit there much smaller. The commit for str.format is already pretty find-and-replace str->wtf8, so I just pulled this out.
=> Refactor cformat in prep for wtf8

Cargo.lock, Lib/_pycodecs.py, Lib/test/test_charmapcodec.py, Lib/test/test_codeccallbacks.py, Lib/test/test_logging.py, common/Cargo.toml, common/src/encodings.rs, common/src/str.rs, common/src/wtf8/mod.rs, vm/src/codecs.rs, vm/src/exceptions.rs, vm/src/function/buffer.rs, vm/src/stdlib/codecs.rs, vm/src/stdlib/io.rs, vm/src/vm/vm_new.rs
This rejiggles some stuff around so that the situation is now:
* `{En,De}codeContext` owns the input data and defines the error type.
* `{En,De}codeErrorhandler` is passed the context and just encapsulates the error handling behavior.
* standard error handlers are now defined in the `rustpython_common::encodings::errors` module.
=> Refactor codecs

Cargo.lock, jit/Cargo.toml
Removes `hashbrown 0.14` from our dependencies, so now everything just uses `hashbrown 0.15` (except for a proc macro pulled in by tcl :unamused: )
=> Bump cranelift to 0.118

Lib/test/test_time.py, derive-impl/src/pystructseq.rs, vm/src/stdlib/time.rs, vm/src/types/structseq.rs
Fixes #4982 
Implements the missing`tm_gmtoff` and `tm_zone` fields in PyStructTime struct. 
The original issue's code example does not work in python 3.12. I used this instead for testing:
```py
import datetime
sgtTimeDelta = datetime.timedelta(hours=5)
sgtTZObject = datetime.timezone(sgtTimeDelta,
name="EST")
print(datetime.datetime(3001, 1, 19, 7, 59, 59, 999999, sgtTZObject).astimezone())
```
=> 4982 - Implement tm_gmtoff and tm_zone

Cargo.lock, Cargo.toml, common/Cargo.toml, common/src/hash.rs, common/src/lib.rs, common/src/rand.rs, compiler/Cargo.toml, stdlib/Cargo.toml, stdlib/src/random.rs, stdlib/src/uuid.rs, vm/Cargo.toml, vm/build.rs, vm/src/import.rs, vm/src/version.rs, vm/src/vm/mod.rs
Specifically, `rand` and `rustc_version` - we actually use very little of these dependencies' capabilities, and it's quite simple to swap them out with a 2-3 line function.
=> Remove some unncessary dependencies

compiler/codegen/src/compile.rs, compiler/core/src/bytecode.rs, extra_tests/snippets/builtin_list.py, vm/src/frame.rs
Enforce left-to-right evaluation with list/tuple/set expressions and positional arguments in calls.
We cannot iterate through the `*`-unpacked iterables after evaluating all given expressions. This PR fixes the problem by temporarily collecting the unpacked iterable into a tuple before moving on to the next element.
Fixes #5566 
(`**`-unpacking with `dict`s and keyword arguments seem to be more buggy; working on a fix.)
=> Fixes evaluation order in expression lists

whats_left.py
Since we target 3.13 now, we don't need to exclude the PEP 594 modules, as they have been removed.
Also adds a features flag to specify which features should be built.
=> Cleanup whats_left.py

extra_tests/snippets/stdlib_pwd.py, vm/src/stdlib/pwd.rs
Given,
```
hbina085@akarin-thinkpad ~/g/RustPython (main) [1]> cat ggg_nonexisten_user.py                                                                                                                                        (base) 
import pwd
fakename = 'fakeuser'
while pwd.getpwnam(fakename):
fakename += '1'
```
Currently, in CPython,
```
hbina085@akarin-thinkpad ~/g/RustPython (main)> python ggg_nonexisten_user.py                                                                                                                                         (base) 
File "/home/hbina085/git/RustPython/ggg_nonexisten_user.py", line 4, in <module>
while pwd.getpwnam(fakename):
^^^^^^^^^^^^^^^^^^^^^^
KeyError: "getpwnam(): name not found: 'fakeuser'"
```
Whereas, …
=> Fix not throwing the same error as CPython in test_pathlib.test_expanduser

common/src/static_cell.rs, common/src/str.rs, vm/src/stdlib/thread.rs, wasm/lib/src/vm_class.rs
Apparently this was stabilized in 1.59 and I didn't even realize.
=> Switch to const-initialized thread_local variables where appropriate

.github/workflows/release.yml
I can't seem to find a clean way to download the wix toolset and it's currently breaking CI. If I find a way to fix this in the future I'll submit another PR.
=> Remove packaging from release

Cargo.lock, compiler/codegen/Cargo.toml, compiler/codegen/src/compile.rs, compiler/codegen/src/error.rs, compiler/codegen/src/snapshots/rustpython_codegen__compile__tests__match.snap, compiler/codegen/src/snapshots/rustpython_codegen__compile__tests__match.snap.new, compiler/core/src/bytecode.rs, extra_tests/snippets/syntax_match.py, vm/src/frame.rs
Retains all match statement functionality, but rewrites all the match statement code to reduce bugs and mirror cpython. Also, it adds support for the rest of the patterns (hopefully).
Also this re-enables the codegen tests that the ruff port disabled.
Fixes: #5628 and #5491
=> Match statements rewrite

Lib/test/test_os.py
Was randomly running `test_os` and found an unexpected success.
=> Minor mark

Lib/test/test_float.py, Lib/test/test_winapi.py
- `test_winapi`
- Update `test_float` to 3.13.3
This is a test run of #5695.
From the looks of it, it is very efficient.
Seems to work pretty well, I'll see what happens on module/test pairs in a different pr.
=> Add/update various tests at 3.13.3

Lib/tarfile.py, Lib/test/test_shutil.py
cc @arihant2math: that's the reason the tests in `test_shutil` were failing; `shutil.py` was from a newer python version than `tarfile.py` and it was trying to use a kwarg that our version didn't have. I chose this version because that's what our `shutil.py` is from.
=> Update tarfile to 3.12.3

common/src/lib.rs, stdlib/src/lib.rs, vm/src/lib.rs
No longer needed; redoxer has a recent enough version of rustc.
=> Remove cfg_attr features for redox

.github/workflows/cron-ci.yaml
This fixes the output on the website, and correctly shows `_sqlite3` as implemented.
=> Collect whats_left data for website with sqlite feature

Lib/test/test_poll.py, stdlib/src/select.rs
I asked github copilot chat to find one of easy to fix `TODO: RUSTPYTHON` in the test files and try to fix one of them.
The result with minor edits is the first commit.
Next, I asked to refactor them with:
```
By looking current changes, I found the eventmask parsing is repeated in both functions. Rather than that, please add `PyEventMask` type as `pub struct PyEventMask(u16)` to retrieve the pattern.
How `Fildes` is doing with `impl TryFromObject for Fildes`  will be helpful to understand how to handle the pattern.
```
The result with minor edits is the second commit.
=> Fix test_poll::test_poll3

Lib/test/test_httplib.py, stdlib/src/ssl.rs
This isn't how cpython does it, but it should work just fine.
It can be updated/expanded as needed for tests.
=> Fix openssl error reasons

stdlib/src/math.rs
Use Rust native `ln_1p` to increase numerical precision matching what is expected by `test_mtestfile`.
=> Increase numerical precision of log1p

compiler/codegen/src/compile.rs, compiler/codegen/src/error.rs, compiler/codegen/src/ir.rs, compiler/codegen/src/lib.rs
Replacement of #5555. That attempted to just make it an error. But the main issue is that panicking leads to no source code or even file location. This simply outputs that before the panic (if the appropriate function is called). All the main places I have seen panics have been patched.
=> Cleaner panic output for codegen errors

.gitignore
~Fix the path for better usability.~ We can clean the `__pycache__` directory instead of using the downloaded one. It can sometimes cause errors
=> gitignore, folder fix, like __pycache__ 

.github/workflows/ci.yaml
The current version is pretty dated, so let's get back to being near latest.
```
RustPython on  rl/upgrade-ruff [?] via 🐍 v3.13.2 via 🦀 v1.86.0 
❯ uvx --from "ruff==0.11.8" ruff check extra_tests wasm examples  --exclude='./.*',./Lib,./vm/Lib,./benches/ --select=E9,F63,F7,F82
All checks passed!
```
=> chore: upgrade to `ruff==0.11.8`

stdlib/src/zlib.rs
After running `uv run python -I whats_left.py`, I saw `zlib.__version__` and thought it'd be easy to implement.
```
RustPython on  rl/zlib-easy via 🐍 v3.13.2 via 🦀 v1.86.0 
❯ cargo run --release
Compiling radium v1.1.0 (https://github.com/youknowone/ferrilab?branch=fix-nightly#4a301c3a)
Compiling rustpython-common v0.4.0 (/Users/rexledesma/Documents/projects/RustPython/common)
Compiling rustpython-vm v0.4.0 (/Users/rexledesma/Documents/projects/RustPython/vm)
Compiling rustpython-stdlib v0.4.0 (/Users/rexledesma/Documents/projects/RustPython/stdlib)
Compiling rustpython v0.4.0 (/Users/rexledesma/Documents/projects/RustPython)
Finished `release` profile [optimized] target(s) in 22.71s
Running `target/release/rustpython`
Welcome to the magnificent Rust Python 0.4.0 interpreter 😱 🖖 …
```
=> feat: implement `zlib.__version__`

README.md, whats_left.py
I was looking to contribute to the project and saw this script as the starting point for contributors. However, when running it locally, I realized it required Python 3.13.
[`uv` allows scripts with Python dependencies](https://docs.astral.sh/uv/guides/scripts/#running-a-script-without-dependencies), so this should be taken care by users who already have `uv` installed.
Ran `./whats_left.py` and `uv run python -I whats_left.py`. Got the same result.
=> chore: allow `uv run python -I whats_left.py`

compiler/literal/src/float.rs, vm/src/stdlib/io.rs
Rust 1.76 changed the internal format of precision values to be `u16` instead of `usize`.
=> Fix panic with high precision

Cargo.lock, wasm/lib/Cargo.toml, wasm/wasm-unknown-test/Cargo.toml, wasm/wasm-unknown-test/src/lib.rs
Now that no transitive non-build deps depend on getrandom 0.2, we can remove it from our deps.
=> Remove getrandom 0.2 from dependencies

Lib/codeop.py, Lib/test/test_baseexception.py, Lib/test/test_pickle.py, compiler/src/lib.rs, src/shell.rs, vm/src/compiler.rs, vm/src/exceptions.rs, vm/src/stdlib/ast.rs, vm/src/stdlib/builtins.rs, vm/src/vm/vm_new.rs
This PR adds support for incomplete parsing both in the native REPL and in the stdin REPL (in particular multiline input support is expanded for to allow more cases such as multiline strings). The implementation adds compatibility for cpython's `PY_CF_ALLOW_INCOMPLETE_INPUT` compile flag and adds a new exception type similar to python 3.14.
=> Support incomplete parsing

Lib/test/test_importlib/source/test_file_loader.py
reference
- pep451: https://peps.python.org/pep-0451/#attributes
- magic number: https://github.com/ever0de/RustPython/blob/b25fcefe75a826846ef64879ceac87de31e5ec64/vm/src/import.rs#L46-L56
=> Enable bad bytecode tests for PEP451 loaders
