RustPython/RustPython

Cargo.lock

Right now our CI is failing with https://github.com/RustPython/RustPython/runs/3339677749

Attempt to fix the failing CI

---

Lib/pprint.py
Lib/test/test_pprint.py

Add `sort_dicts` parameter to several functions and new `pp` function.
Also, enable related tests.

Update pprint module to Python3.8

---

vm/src/dictdatatype.rs

remove double-get from DictDataType::pop_back

---

vm/src/dictdatatype.rs

Further clarify pop_back using iterator adaptors

---

Lib/test/test_math.py
vm/src/stdlib/math.rs

I implemented `math.dist` function and enabled its tests.

Add math.dist function and enabled its tests

---

Lib/test/test_array.py
Lib/test/test_io.py
Lib/test/test_ntpath.py
Lib/test/test_re.py
Lib/test/test_strtod.py
Lib/test/test_traceback.py
Lib/test/test_unicode.py
vm/src/builtins/memory.rs
vm/src/builtins/pystr.rs
vm/src/stdlib/array.rs
vm/src/stdlib/pystruct.rs

Support unicode array type.

---

benches/benchmarks/pystone.py
bytecode/src/lib.rs
compiler/src/symboltable.rs
parser/src/lexer.rs
pdc.sh

Fixes typos in all other files

---

vm/src/builtins/function.rs

This revision fix issue #2939
Add `self.code.obj` field in error message for remove incompatibility with cpython.

Fix error message incompatibility

---

Lib/test/test_copy.py
Lib/test/test_enum.py
vm/src/builtins/float.rs
vm/src/builtins/int.rs

Fix regressions from #2932 
cc @moreal

Fix int/float enum pickle

---

Lib/test/test_deque.py
vm/src/stdlib/collections.rs

add deque __bool__ method

---

Lib/test/test_deque.py
vm/src/stdlib/collections.rs

add `deque.__copy__` method same to deque.copy.

add deque.__copy__

---

vm/src/stdlib/array.rs

Follow up to #2955, cleans up the rest of the usages of `Either` in `array`.

Use SequenceIndex instead of Either.

---

vm/src/builtins/dict.rs

The extensions for each type can be added into empty `#[pyimpl]` later
preparing #2898

prepare extension for each dict iterator types

---

derive/src/lib.rs
derive/src/pyclass.rs
derive/src/pymodule.rs
derive/src/util.rs
extra_tests/snippets/builtin_exceptions.py
vm/src/builtins/dict.rs
vm/src/exceptions.rs
vm/src/vm.rs

Closes #2771
I've changed a single exception to show my progress. If this is ok, then I can change all of them.

Adds better exception macro

---

Lib/test/test_deque.py
vm/src/stdlib/collections.rs

Deque is pretty unique with this approach.

Return subclass on deque copy.

---

.gitattributes

Subfolders were not ignored.
Docs: https://github.com/github/linguist/blob/0c7f82f88a2fb482db3a02812cbb4b8aab7308d1/docs/overrides.md#vendored-code

Make this a Rust project once again

---

vm/src/builtins/map.rs

it's for #2680
Signed-off-by: Tony Jinwoo Ahn <tony.jinwoo.ahn@gmail.com>

Add documentation for a pymethod in map.rs

---

Cargo.lock
Lib/test/test_long.py
ast/Cargo.toml
bytecode/Cargo.toml
common/Cargo.toml
parser/Cargo.toml
vm/Cargo.toml

Fixes a compilation error with the latest nightlies.

Update num_bigint to 0.4.2

---

Lib/test/test_unicode.py
common/src/encodings.rs

Signed-off-by: Tony Jinwoo Ahn <tony.jinwoo.ahn@gmail.com>

Fix range of "invalid start byte" for UTF-8

---

vm/src/stdlib/time.rs

This revision add four methods, `thread_time`, `thread_time_ns`, `process_time` and `process_time_ns`
* https://docs.python.org/3.8/library/time.html#time.process_time
* https://docs.python.org/3.8/library/time.html#time.thread_time
* https://docs.rs/libc/0.2.92/libc/fn.clock_gettime.html
* https://docs.rs/libc/0.2.92/libc/constant.CLOCK_PROCESS_CPUTIME_ID.html
* https://docs.rs/libc/0.2.92/libc/constant.CLOCK_THREAD_CPUTIME_ID.html
* https://docs.rs/winapi/0.3.9/winapi/um/processthreadsapi/fn.GetProcessTimes.html
* https://docs.rs/winapi/0.3.9/winapi/um/processthreadsapi/fn.GetThreadTimes.html

Add thread_time, process_time in `time` module

---

Lib/codecs.py
Lib/encodings/__init__.py
Lib/encodings/aliases.py
Lib/encodings/punycode.py
Lib/encodings/uu_codec.py
Lib/test/test_codecs.py
vm/src/codecs.rs
vm/src/stdlib/binascii.rs

A considerable portion of the Rust code needs to be iterated upon in order for this to work correctly.

Update codecs.py to CPython 3.8

---

vm/src/stdlib/select.rs
vm/src/stdlib/time.rs

cc @Snowapril 
review link: https://github.com/RustPython/RustPython/pull/3009/files?w=1

pymodule for time module

---

Lib/test/test_time.py

import CPython's time test 
Reference:
https://github.com/python/cpython/blob/main/Lib/test/test_time.py

Add time test file

---

compiler/src/compile.rs

Raise syntax error when saving a value to __debug__.

---

vm/src/stdlib/collections.rs

Closes #2839
Add `deque.__imul__()` method

Add deque __imul__ method

---

examples/freeze/main.rs

Just a simple drive-by fix for the wording in the freeze example

Examples Wording Issue - relative <=> relevant

---

vm/src/stdlib/os.rs

Add support for class `bytearray` and `memoryview`
Noted that clippy is not happy with the `Vec::from` part (warning: redundant closure). 
However when I change the code as clippy suggested, it fail to build with [error: implementation of `FnOnce` is not general enough].
It could be an issue in clippy implementation.

os: scandir add argument support

---

Lib/test/test_base64.py
Lib/test/test_binascii.py
vm/src/stdlib/binascii.rs

I adapted these exceptions from the `termios.rs` module.

Add binascii.Error and binascii.Incomplete

---

vm/src/stdlib/os.rs

implementation comments for os utility

---

vm/src/builtins/dict.rs
vm/src/builtins/enumerate.rs
vm/src/builtins/make_module.rs
vm/src/builtins/pybool.rs
vm/src/builtins/pystr.rs
vm/src/stdlib/math.rs
vm/src/stdlib/sre.rs

Cleans up a couple more instances of matching on Optional by using `Option` methods.

Clean up more instances of matching on Optional.

---

.vscode/tasks.json

not very useful and making trouble for windows users

remove '--features=ssl' from debugger config

---

Lib/test/test_cmath.py
vm/src/stdlib/cmath.rs

This is my first time working with rust, pls tell me if my code is wrong, i ran the test but couldnt unserstand the output

Implemented sqrt for cmath

---

Lib/test/test_uu.py
vm/src/stdlib/binascii.rs

This code is the beginnings of proper uuencoding/decoding, but it can be further refined.

Add uuencoding/decoding code to binascii.rs

---

Lib/test/test_super.py

import CPython's super test
reference:
https://github.com/python/cpython/blob/3.8/Lib/test/test_super.py

Add super test

---

extra_tests/snippets/class.py

type test for __new__

---

derive/src/pyclass.rs
derive/src/pymodule.rs
derive/src/util.rs

I.e just how methods have `$self` at the start of the sig, functions have `$module`.

Add $module for function text signatures.

---

Lib/test/test_httplib.py
Lib/test/test_io.py
vm/src/buffer.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/memory.rs
vm/src/byteslike.rs
vm/src/cformat.rs
vm/src/slots.rs
vm/src/stdlib/array.rs
vm/src/stdlib/io.rs
vm/src/stdlib/marshal.rs
vm/src/stdlib/os.rs
vm/src/stdlib/sre.rs

resembled CPython Py_buffer, less access to internal through vtable

Refactor PyBuffer

---

.github/workflows/ci.yaml
README.md
bytecode/src/lib.rs
compiler/src/compile.rs
compiler/src/lib.rs
compiler/src/symboltable.rs
derive/src/lib.rs
extra_tests/snippets/stdlib_imghdr.py
parser/src/lib.rs
vm/src/builtins/function.rs
vm/src/exceptions.rs
vm/src/lib.rs
wasm/README.md
wasm/lib/Cargo.toml
wasm/lib/README.md
wasm/notebook/src/index.ejs

Replace `master` with `main`

---

vm/src/builtins/pysuper.rs

possibly related to #3057 but didn't solve the problem itself

revise PySuper::getattro same as CPython super_getattro

---

Lib/test/test_cmath.py
vm/src/stdlib/cmath.rs

Implemented cmath.acosh function and uncommented test

Implement cmath.acosh

---

vm/src/stdlib/os.rs

This PR contains implementation of `os.sched_param` class.
You can check the interface of `sched_param` here :  
https://docs.python.org/3/library/os.html#os.sched_param 
With this code, RustPython works as below : 
```python 
>>>>> import os
>>>>> os.sched_param(1)
posix.sched_param(sched_priority = 1)
>>>>> os.sched_param('hi')
posix.sched_param(sched_priority = 'hi')
``` 
```python 
>>>>> import os 
>>>>> a = os.sched_param(1)
>>>>> a.sched_priority
1
>>>>> b = os.sched_param('hello')
>>>>> b.sched_priority
'hello'
```

posix : implement sched_param class

---

Lib/test/test_cmath.py
vm/src/stdlib/cmath.rs

Add tan() and tanh() for cmath
Related issue: #3039

Add tan() and tanh() for cmath

---

vm/src/crt_fd.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs

Fix x86 build

---

vm/src/stdlib/multiprocessing.rs
vm/src/stdlib/os.rs
vm/src/stdlib/winapi.rs
vm/src/stdlib/winreg.rs
vm/src/sysmodule.rs

Modify some codes as clippy advised.

Solve clippy warnings in window

---

Cargo.lock
benches/microbenchmarks.rs
vm/Cargo.toml
vm/src/builtins/dict.rs
vm/src/builtins/pystr.rs
vm/src/builtins/pytype.rs
vm/src/builtins/set.rs
vm/src/codecs.rs
vm/src/dictdatatype.rs
vm/src/py_io.rs
vm/src/pyobject.rs
vm/src/stdlib/ast/gen.rs
vm/src/stdlib/sre.rs
vm/src/stdlib/ssl.rs
vm/src/stdlib/string.rs
vm/src/sysmodule.rs
vm/src/utils.rs
vm/src/vm.rs

ref:
https://github.com/RustPython/RustPython/pull/3066#issuecomment-922493702

Fix PyStr operations to be safe

---

vm/src/stdlib/cmath.rs

as was done for math ones in #3119

Refactor cmath constants.

---

vm/src/stdlib/math.rs

diff is an unfortunate royal mess. moves stuff into a `pymodule`.

Refactor math.rs into module.

---

.cargo/config.toml

fix #2881
could anyone using windows test if this change works?

increase stack size for windows

---

vm/src/stdlib/posix.rs

move #3089 implements to posix.rs

posix : implement sched_set/getscheduler and sched_set/getparam

---

Lib/test/test_os.py
vm/src/stdlib/posix.rs

os: fix execv argument type

---

vm/src/builtins/int.rs
vm/src/stdlib/fcntl.rs
vm/src/stdlib/zlib.rs

move int::bigint_unsigned_mask to PyInt::as_u32_mask

---

vm/src/stdlib/socket.rs
vm/src/stdlib/ssl.rs

I moved `io::Read` and `io::Write` for PySocketRef to ssl. If they are implemented for `PySocket`, it would be member of socket. But the `PyRef<PySocket>` requirement is decided by `ssl::SslStream`. not by socket itself. So I moved it to ssl to make them specific to ssl requirement.
part of #3104

Refactor ssl module

---

vm/src/builtins/pytype.rs
vm/src/stdlib/io.rs
vm/src/stdlib/ssl.rs
vm/src/types.rs

pytype::new -> PyType::new

---

Cargo.lock
Cargo.toml
build.rs

I added precommit to reduce fmt ci failure
but this pre-commit tool raised some problems such as(#3122). so i removed the precommit.

remove precommit

---

vm/src/lib.rs
vm/src/signal.rs
vm/src/stdlib/signal.rs
vm/src/vm.rs

`vm/src/signal.rs` is used for rustpython-stdlib 
part of #3104

Refactor signal with pymodule

---

vm/src/stdlib/posixsubprocess.rs
vm/src/stdlib/pyexpat.rs
vm/src/stdlib/select.rs
vm/src/stdlib/ssl.rs

clean up use statements

---

extra_tests/not_impl_gen.py

Fix what's left issue

---

vm/src/exceptions.rs
vm/src/stdlib/ssl.rs

remove exception_slots

---

vm/src/stdlib/mod.rs
vm/src/stdlib/os.rs
vm/src/stdlib/socket.rs

FsPath public API

---

vm/src/stdlib/array.rs

array buffer internal with original type

---

vm/src/stdlib/ssl.rs

Build with
cargo ndk -t arm64-v8a -p 23 build --release --features freeze-stdlib,ssl,ssl-vendor
Then push rustpython to /data/local/tmp/python
run /data/local/tmp/python with code:
import urllib.request
print(urllib.request.urlopen('https://httpbin.org/ip').read().decode('ascii'))
check if https connection successful

android SSL support system certs

---

vm/src/stdlib/os.rs
vm/src/stdlib/posix.rs

Add OSError with filaname(2) support for `os.rename`, `os.readlink`, `os.link` and `os.chroot`
Follow up for #3150

OSError with filename2

---

Cargo.lock
Cargo.toml
Lib/distutils/command/install.py
Lib/distutils/sysconfig.py
Lib/test/test_zipfile.py
Lib/tokenize.py
Lib/zipfile.py
src/lib.rs
vm/src/builtins/dict.rs
vm/src/builtins/function.rs
vm/src/frame.rs
vm/src/function.rs
vm/src/stdlib/sys.rs
vm/src/vm.rs

Fix pip warnings about inconsistency between distutils' sysconfig and the actual sysconfig; fix error when installing package it would say something like `__env_pip__.zip is not a file`

Miscellaneous pip fixes

---

vm/src/builtins/complex.rs
vm/src/builtins/dict.rs
vm/src/builtins/float.rs
vm/src/builtins/int.rs
vm/src/builtins/object.rs
vm/src/builtins/tuple.rs
vm/src/macros.rs
vm/src/pyobject.rs
vm/src/stdlib/builtins.rs
vm/src/vm.rs

Arithmatic -> Arithmetic.

---

README.md

Something is broken on windows

Add RUSTPYTHONPATH note for windows users.

---

.cargo/config.toml

Fix windows stack size again

---

Lib/test/test_cmath.py

Enable exp() for cmath test for #3039

Enable exp() for cmath test

---

Lib/test/test_bytes.py
extra_tests/snippets/iterations.py
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/dict.rs
vm/src/builtins/enumerate.rs
vm/src/builtins/iter.rs
vm/src/builtins/list.rs
vm/src/builtins/pystr.rs
vm/src/builtins/range.rs
vm/src/builtins/set.rs
vm/src/builtins/tuple.rs
vm/src/dictdatatype.rs
vm/src/protocol/iter.rs
vm/src/stdlib/collections.rs

This should also garentee the multi-thread iteration as long as the iter object is not changed.

General logic for positional iterator

---

vm/src/sliceable.rs

close #3167
I thought there is more things but there wasn't

Remove impl TryFromObject for SequenceIndex

---

vm/src/builtins/int.rs
vm/src/builtins/iter.rs
vm/src/cformat.rs
vm/src/iterator.rs
vm/src/stdlib/builtins.rs

Use PyInt::try_to_primitive.

---

vm/src/builtins/int.rs
vm/src/stdlib/os.rs

which implicitly cost BigInt clone
introduced in #3088

Remove TryFromBorrowedObject for BigInt

---

.github/workflows/ci.yaml
.github/workflows/cron-ci.yaml
DEVELOPMENT.md
README.md
extra_tests/snippets/dict_union.py
extra_tests/snippets/imp.py
vm/src/version.rs

This PR is not intended to be merged.
Just to check the CI result - at least at the moment.
related issue for disabled test: #3212

bump up reference CPython to 3.9

---

vm/src/builtins/dict.rs

to essentially call `dict.update`, needed for #3230

Fix dict __ior__

---

stdlib/src/array.rs
vm/src/builtins/bytearray.rs
vm/src/protocol/buffer.rs
vm/src/protocol/mod.rs
vm/src/stdlib/io.rs

to distinguish which type implements it by name

ResizeGuard -> BufferResizeGuard

---

Lib/test/test_time.py
vm/src/stdlib/time.rs

This adds some needed functionality for running perf scripts on unix based platforms, windows is unfortunately pending since I haven't got a machine.

Time mod additions

---

Lib/test/test_importlib/source/test_finder.py
Lib/test/test_shutil.py
Lib/test/test_subprocess.py
Lib/test/test_tempfile.py
vm/src/exceptions.rs
vm/src/stdlib/os.rs

Implement `raw_os_error_to_exc_type` to reduce duplication of errno to
exception type.

Refactor OSError

---

Lib/test/test_time.py
vm/src/stdlib/time.rs

Closes #3382 
This revision implements some function of time module for windows
* `get_clock_info`
* `monotonic` / `monotonic_ns`
* `perf_counter` / `perf_counter_ns`

Time mod additions for Window

---

vm/src/stdlib/operator.rs

Uses `Callable` and `Constructor` instead of directly using `slot_*`.

Clean up slots in operator.

---

Lib/test/test_random.py
stdlib/src/random.rs

Allow any object as an argument for random.seed

---

vm/src/builtins/pystr.rs

This pull request tries to resolve the part of https://github.com/RustPython/RustPython/issues/3244.
> `Mapping` trait to provide type slot `as_mapping`
P.S. maybe it should be `AsMapping` trait 🤔

Implement `AsMapping` for `PyStr`

---

.github/workflows/ci.yaml

Recent PRs (#3422, #3426) should now make the check succeed.

Add a check for freeBSD.

---

vm/src/stdlib/time.rs

https://github.com/rust-lang/libc/pull/2496

Enable `clock_settime` for macOS.

---

vm/src/stdlib/posix.rs

`os.urandom` use the crate [getrandom](https://crates.io/crates/getrandom) to generate random but unfortunately that crate doesn't provide the needed `flags` according to [python doc](https://docs.python.org/3/library/os.html?highlight=os%20getrandom#os.getrandom). This PR implement `os.getrandom` by using `libc` binding.

os: implement getrandom

---

vm/src/lib.rs
vm/src/signal.rs
vm/src/stdlib/signal.rs
vm/src/vm.rs

Allow sending custom signals to a vm

---

.github/workflows/ci.yaml
Lib/test/test_collections.py
Lib/test/test_dict.py
vm/src/builtins/dict.rs
vm/src/builtins/set.rs
vm/src/stdlib/posix.rs
vm/src/stdlib/time.rs

I will also add sub, xor and and operations later.

fixed set.__ror__ operator to behave according to type

---

Lib/test/test_dictviews.py
extra_tests/snippets/builtin_dict.py
vm/src/builtins/dict.rs
vm/src/builtins/set.rs

Addresses part of issue #2898.
After this and pull request #3421 are merged, issue #2898 will be resolved.

Dict keys isdisjoint

---

Lib/test/test_math.py

* update `test_math.py` to cpython 3.10
* fix failed test, `testFactorialNonIntegers`

Update test_math.py to cpython 3.10

---

Lib/test/test_slice.py
vm/src/builtins/slice.rs

* implement `reduce` method to `PySlice`
* fix `test_pickle` in `test_slice`

implement `reduce` method to `PySlice`

---

Lib/test/test_enumerate.py
vm/src/builtins/enumerate.rs

add reduce in enumerate

---

Lib/test/test_bytes.py
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs

* delete unnecessary doc in `bytearray.rs` and `bytes.rs`
* fixed `test_doc` in `test_bytes.py`

Fix `bytearray` and `bytes` docs

---

vm/src/builtins/slice.rs

fix #3468 SaturatedSliceIter overflow

---

Lib/dis.py

This pull resolves Issue: #2889 
**Steps to Test This Pull Request**
```
$ target/debug/rustpython -m dis ./demo.py
0 LoadNameAny          (0, print)
1 LoadConst            ("Hello, RustPython!")
2 CallFunctionPositional (1)
3 Pop
4 LoadConst            (None)
5 ReturnValue
```

feat(Lib): print the disassembled info

---

Lib/test/test_dict.py
Lib/test/test_iter.py
vm/src/builtins/dict.rs

This fixes test_iter_dict testcase.

Implement reduce() for dict iterators

---

Lib/test/test_functools.py
Lib/test/test_positional_only_arg.py
Lib/test/test_typing.py
vm/src/builtins/function.rs

Also fix newly introduced failing functions in #3449 and #3455

allow passing a named argument to varkwargs function

---

Cargo.toml
common/src/boxvec.rs
common/src/linked_list.rs
compiler/src/compile.rs
derive/src/util.rs
jit/src/lib.rs
vm/src/codecs.rs
vm/src/exceptions.rs
vm/src/format.rs
vm/src/pyobjectrc.rs
vm/src/vm.rs

- Fix doc comment for Interpreter
- Fix doctests in ci

Fix doctests in ci

---

Lib/random.py
Lib/test/test_random.py
stdlib/src/random.rs
vm/src/builtins/int.rs

I wonder how many other things this will break and/or fix…

Update test_random.py to CPython 3.9

---

vm/src/stdlib/posix.rs

Use syscall instead of the getrandom libc function

---

.github/workflows/ci.yaml

Disable install-pip test

---

.github/workflows/ci.yaml

@youknowone Today I learned that you can't have more than one `if` statement in a process.

Fix syntax error in `ci.yaml`

---

Lib/pickletools.py
Lib/test/pickletester.py
Lib/test/support/warnings_helper.py
Lib/test/test_pickletools.py

This includes other support files.

Add test_pickletools from CPython 3.9

---

Lib/random.py
Lib/test/test_long.py
Lib/test/test_random.py
stdlib/src/random.rs
vm/src/builtins/int.rs
vm/src/stdlib/os.rs

This revision do follow things
*  Update `random.py` and `test_random.py` to cpython 3.10
*  Fix `os.urandom` and `random.getrandbits` to check input sign
*  Remove `random.randbytes` as it is already on `Random` class in `random.py` and python-side code never reach there

Update `random` module and fix some issues

---

Lib/pickle.py
Lib/test/test_bytes.py
Lib/test/test_pickle.py

This also updates `pickle.py` to CPython 3.10.

Add test_pickle from CPython 3.10

---

Lib/test/support/__init__.py
Lib/test/support/hashlib_helper.py
Lib/test/test_tarfile.py
Lib/test/test_urllib2_localnet.py

Requesting @deantvv as a reviewer.

Add test/support/hashlib_helper from CPython 3.10

---

Lib/test/support/import_helper.py

Requesting @deantvv as a reviewer.

Align test/support/import_helper with CPython 3.10

---

Lib/test/support/script_helper.py

Requesting @deantvv as a reviewer.

Update test/support/script_helper to CPython 3.10

---

Lib/test/support/__init__.py
Lib/test/support/os_helper.py
Lib/test/test__osx_support.py
Lib/test/test_genericpath.py
Lib/test/test_ntpath.py
Lib/test/test_pathlib.py
Lib/test/test_socketserver.py
Lib/test/test_tarfile.py
Lib/test/test_tempfile.py

Requesting @deantvv as a reviewer.

Align test/support/os_helper with CPython 3.10

---

Lib/statistics.py
Lib/test/test_statistics.py
stdlib/src/lib.rs
stdlib/src/statistics.rs

This also adds an accelerator module.

Update statistics.py to CPython 3.10

---

vm/src/stdlib/errno.rs

Some constants have also been reordered to reflect the order in the original C source.

Update errno module to CPython 3.10

---

Lib/codecs.py
Lib/test/test_codecs.py
vm/src/codecs.rs
vm/src/stdlib/codecs.rs

There might be a few regressions.

Update codecs.py to CPython 3.10

---

Lib/test/test_complex.py
vm/src/builtins/complex.rs

Enable 2 test cases for test_complex
- test_repr_roundtrip
- test_negative_zero_repr_str

Fix complex repr

---

Lib/test/test_bool.py
vm/src/stdlib/marshal.rs

Test: import marshal; assert marshal.loads(marshal.dumps(True)) == True
Test: import marshal; assert marshal.loads(marshal.dumps(False))== False

Fix bool un/marshaling

---

vm/src/builtins/list.rs
vm/src/builtins/set.rs
vm/src/builtins/tuple.rs
vm/src/stdlib/collections.rs
vm/src/utils.rs

Implement an helper functions to for repr function of the collections including list, tuple, set and deque.

refactor: add a repr helper function for the collections

---

Lib/test/test_dict.py
Lib/test/test_enum.py
vm/src/builtins/dict.rs

add `reduce` method to reverse_iter and obliterated the failure that was foreseen by it

Add `Reduce` method in reverse_iter

---

Lib/test/test_genericalias.py
vm/src/builtins/genericalias.rs

Modify `list[]` to print `list[()]` when executing `list[()]`

modify empty tuple (genericalias repr)

---

vm/src/builtins/pysuper.rs

add thisclass to the original typ

add thisclass to the original typ

---

Lib/test/test_builtin.py
Lib/test/test_enum.py
Lib/test/test_typing.py
vm/src/builtins/pytype.rs

See individual commits for details.

Get (most of) test_type_name passing

---

.github/workflows/ci.yaml
Cargo.toml
src/shell/helper.rs
vm/src/exceptions.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs
vm/src/stdlib/thread.rs

Fix wasm32 build

---

.github/workflows/ci.yaml

Plan to add tests for `wasm32-wasi` using [wasmer](https://github.com/wasmerio/wasmer)

ci: add test for wasm32-wasi

---

.github/workflows/cron-ci.yaml
scripts/codecoverage-rustc-wrapper.sh

Switch instrument coverage to stable

---

stdlib/src/lib.rs
stdlib/src/statistics.rs

Closes #3251
Not sure if this needs a test, or if you run the python ones in `Lib/test/test_statistics.py` is enough

Add `_statistics` module containing `_normal_dist_inv_cd`

---

Lib/test/test_asyncgen.py

This should get merged before #3646.

Update test_asyncgen.py to CPython 3.10

---

Lib/test/test_faulthandler.py

Most of these tests do not currently pass.

Add test_faulthandler.py from CPython 3.10

---

Lib/test/test_builtin.py
vm/src/format.rs
vm/src/frame.rs
vm/src/stdlib/builtins.rs

This pull request tries to resolve #3619.

Refactor `__format__` calling

---

vm/src/builtins/type.rs

Hello!
This is my first pull request, I am very eager to star contributing to this project. 
I believe I have addressed #3607, at least all the tests seem to pass since I made the changes.
Thank you :)

Changed PyAttributes type to IndexMap

---

Lib/bdb.py
Lib/test/test_bdb.py

Add test_bdb.py from CPython 3.10

---

Lib/test/test_configparser.py
Lib/test/test_exceptions.py
Lib/unittest/test/test_discovery.py
vm/src/exceptions.rs

Addresses three items in #3611.
cc @Snowapril

Add BaseException.__reduce__

---

stdlib/src/termios.rs

Note: includes constants that are missing and/or have incomplete platform coverage.

Add some platform-dependent constants to termios

---

extra_tests/snippets/builtin_super.py
vm/src/builtins/super.rs

This is the PR for #3610. I hope this time is everything ok, if not please let me know so I can change.  
Related to #3683

Pysuper types

---

README.md

Add document for wasi

---

vm/src/object/core.rs

call_slot_del is cold

---

Lib/test/string_tests.py
vm/src/builtins/str.rs
vm/src/exceptions.rs
vm/src/frame.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/io.rs
vm/src/vm/context.rs

PyStr::mul optimization for i=0 or str=''

---

vm/src/builtins/str.rs
vm/src/intern.rs
vm/src/object/core.rs
vm/src/object/ext.rs

more str AsRef<str>  

---

compiler/src/compile.rs

Compared to previous version of `compile_program_single`, below two
codes are skipped when an empty body is given.
```rust
self.emit_constant(ConstantData::None);
self.emit(Instruction::ReturnValue);
```
Fix #3704

Add missing emits for empty statement body in `compile_program_single`

---

Lib/test/test_int.py
extra_tests/snippets/builtin_int.py
vm/src/builtins/int.rs

Fixed int.real, int.numerator etc. returns wrong value when it's int type.

---

Lib/test/test_pickle.py
Lib/test/test_pickletools.py
vm/src/builtins/singletons.rs

Add NotImplemented.__reduce__()

---

extra_tests/snippets/builtin_memoryview.py
vm/src/builtins/memory.rs

when call "__delitem__()" error message did not match, So add "__delitem__()" function and matched it with cPython

add __delitem__() funtion

---

Lib/test/test_long.py
vm/src/bytesinner.rs

Issue: `int.from_bytes("", 'big')` It have to return `TypeError` but it did return `AssertionError: TypeError not raised by from_bytes` so fixed it `bytes_from_object` function that it returns Error

Fixed `bytes_from_object`

---

vm/src/stdlib/itertools.rs

Add count.reduce()

---

Lib/bisect.py
Lib/test/test_bisect.py
stdlib/src/bisect.rs

#3693
I modified `stdlib\src\bisect.rs`, 
and updated `Lib/test/test_bisect.py` and `Lib/bisect.py` to the version 3.10.
https://github.com/python/cpython/blob/3.10/Lib/bisect.py
https://github.com/python/cpython/blob/3.10/Lib/test/test_bisect.py

Optional key argument for bisect functions

---

Lib/test/test_reprlib.py

Update test_reprlib.py to CPython 3.10

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

Add `filterfalse.__reduce__`

---

Cargo.lock
benches/benchmarks/fannkuch.py
derive/Cargo.toml
derive/src/pyclass.rs
stdlib/src/array.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/dict.rs
vm/src/builtins/genericalias.rs
vm/src/builtins/iter.rs
vm/src/builtins/list.rs
vm/src/builtins/mappingproxy.rs
vm/src/builtins/memory.rs
vm/src/builtins/range.rs
vm/src/builtins/set.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/builtins/union.rs
vm/src/function/protocol.rs
vm/src/protocol/mapping.rs
vm/src/protocol/object.rs
vm/src/protocol/sequence.rs
vm/src/stdlib/collections.rs
vm/src/stdlib/sre.rs
vm/src/types/slot.rs

3% from pystone
3.5% from fannkuch
```
+-----------+-----------------+------------------------+------------------------+
| Benchmark | rustpython_orig | mapping                | mapping+sequence        |
+===========+=================+========================+========================+
| fannkuch  | 3.79 sec        | 3.67 sec: 1.03x faster | 3.65 sec: 1.04x faster |
+-----------+-----------------+------------------------+------------------------+
```
```
+-----------+---------+-------------------------+
| Benchmark | cpython | rustpython-final        |
+===========+=========+=========================+
| fannkuch  | 354 ms  | 3.64 sec: 10.26x slower |
+-----------+---------+-------------------------+
```

use static reference for AsMapping / AsSequence

---

Lib/test/test_float.py
Lib/test/test_index.py
Lib/test/test_int.py
stdlib/src/math.rs
vm/src/buffer.rs
vm/src/builtins/complex.rs
vm/src/builtins/float.rs
vm/src/builtins/int.rs
vm/src/function/number.rs
vm/src/protocol/mod.rs
vm/src/protocol/number.rs
vm/src/stdlib/mod.rs
vm/src/stdlib/warnings.rs
vm/src/types/slot.rs
vm/src/vm/vm_ops.rs

Implement Number Protocol

---

benches/benchmarks/nbody.py

500 is too small to measure performance

increase nbody benches argument

---

Lib/test/test_sys.py
vm/src/stdlib/sys.rs
vm/src/vm/interpreter.rs
vm/src/vm/mod.rs

Added `sys.is_finalizing()` but could not enable test_sys::SysModuleTest.test_is_finalizing. RustPython have to implement module destruction to enable the TC.

feat(sys): add `sys.is_finalizing()`

---

stdlib/src/array.rs
vm/src/builtins/list.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/bytesinner.rs
vm/src/iter.rs
vm/src/lib.rs
vm/src/sequence.rs
vm/src/stdlib/collections.rs

PyExactSizeIterator

---

extra_tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

Fix itertools chain

---

Lib/test/test_dictviews.py
vm/src/builtins/dict.rs

fixed test_dict_mixed_keys_items in test_dictviews.py

fix test_dictviews::test_dict_mixed_keys_items

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

Add itertools.compress.__reduce__

---

vm/src/builtins/type.rs
vm/src/function/protocol.rs
vm/src/object/core.rs
vm/src/protocol/buffer.rs
vm/src/protocol/mapping.rs
vm/src/protocol/number.rs
vm/src/protocol/sequence.rs

Fix infinite hang of pip #3670

Fix slot call deadlock

---

.github/workflows/ci.yaml
vm/src/stdlib/posix.rs

disable schedparam from musl

---

Lib/test/test_io.py

During investigating [issue](https://github.com/RustPython/RustPython/issues/3826) also update test as usual.

test: update test_io.py to 3.10

---

.github/workflows/ci.yaml

Switch clippy to stable

---

vm/src/stdlib/itertools.rs

Fix rustfmt and clippy warnings

---

Lib/argparse.py
Lib/test/test_argparse.py

This also updates the corresponding test file.

Update argparse to CPython 3.10

---

.github/workflows/ci.yaml
vm/src/stdlib/builtins.rs
vm/src/vm/compile.rs
vm/src/vm/mod.rs

I wish freebsd is similar enough to openbsd #1945

fix --no-default-features build and freebsd CI

---

whats_left.sh

run whats_left.sh with --features=ssl

---

Lib/test/test_types.py
vm/src/builtins/union.rs

type-type subclass identifying

Fix is_unionable type_type check

---

Lib/test/test_itertools.py
vm/src/builtins/complex.rs

Implementation based on #3507.

Implement Number protocol for PyComplex

---

Lib/test/test_grammar.py
parser/src/lexer.rs

Fix https://github.com/RustPython/RustPython/issues/3760

Fix multiline lexer bug

---

.github/workflows/ci.yaml
.github/workflows/cron-ci.yaml

Abandon `actions-rs` actions

---

parser/src/lexer.rs

Fix #3760 
Related PR: https://github.com/RustPython/RustPython/pull/3874

Fix multiline string bug

---

vm/src/builtins/set.rs

`SetIterable` was a set object but acting like `PosArgs` to be passed as argument.
Instead of it, `AnySet` is a simple `PyObjectRef` wrapper.

SetIterable -> AnySet

---

vm/src/builtins/singletons.rs

Implement Number protocol for PyNone

---

vm/src/builtins/dict.rs
vm/src/builtins/mappingproxy.rs
vm/src/builtins/type.rs

- Use PyMappingProxy to make dict and return
- Add a property called mapping to dict.rs. Its return type -> PyMappingProxy

Add a mapping property

---

derive/src/pyclass.rs

This pull request is from https://github.com/RustPython/RustPython/pull/3904#issuecomment-1186551766. It tries to unify naming of elements referring to getset to `GetSet`.
It was a reply of my question and it's one vote of one maintainer. It may need discussion between maintainers 🤔 
Feel free to discuss it even if this pull request closed or become to stay while long time. 🙏🏻 .

Unify elements referring to getset to `GetSet`

---

Lib/test/test_types.py
vm/src/builtins/mappingproxy.rs

Add MappingProxy's get method implementation handling missing key

---

Lib/test/test_dataclasses.py
Lib/test/test_enum.py
Lib/test/test_types.py
vm/src/builtins/mappingproxy.rs

Implement missing methods to `MappingProxy`

---

Lib/test/test_array.py
stdlib/src/array.rs

Fix #3938 
update array.index for optional range, start and stop

update array.index for optional range

---

stdlib/src/array.rs
vm/src/builtins/list.rs
vm/src/builtins/tuple.rs
vm/src/sequence.rs
vm/src/stdlib/collections.rs

@daeun503 @falsetru could you review this PR?

Refactor repetive optional range pattern to OptionalRangeArgs

---

Lib/test/test_set.py
vm/src/builtins/set.rs

Fix set test_merge_and_mutate

---

.github/workflows/ci.yaml

turn on --installp-pip test

---

Lib/test/test_copy.py
Lib/test/test_range.py
vm/src/builtins/range.rs

Fix range attributes type

---

Lib/test/test_float.py
common/src/hash.rs
vm/src/builtins/complex.rs
vm/src/builtins/float.rs

Fix `float` and `complex`'s incorrect hash value when using with `nan`

---

Cargo.lock
Lib/test/test_htmlparser.py
Lib/test/test_re.py
extra_tests/snippets/stdlib_re.py
vm/Cargo.toml

fix #3829 
fix #3544 
fix #2793

Fix sre-engine wrong repeat context used when multiple max_until recusion

---

Lib/test/test_types.py
vm/src/builtins/union.rs
vm/src/protocol/object.rs

Resolve `test_types::UnionTests::test_instancecheck, test_bad_instancecheck,test_bad_subclasscheck`

Fix `instancecheck`, `subclasscheck` of `UnionType`

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

Add `itertools.starmap.__reduce__`

---

Lib/test/test_types.py
vm/src/builtins/union.rs

This pull request resolves #3851.

Correct union hash

---

Lib/test/test_types.py
vm/src/builtins/union.rs

Resolve `test_types::UnionTests::test_or_types_operator`.

Update cmp of `PyUnion`

---

examples/generator.rs
examples/package_embed.rs
parser/build.rs
src/lib.rs
src/main.rs
stdlib/src/posixsubprocess.rs
vm/src/vm/compile.rs
vm/src/vm/interpreter.rs
vm/src/vm/mod.rs

replace exit with Exitcode

---

Cargo.lock
Cargo.toml
Lib/bz2.py
stdlib/Cargo.toml
stdlib/src/bz2.rs
stdlib/src/lib.rs

pretty much copy and pasted from `csv.rs`.

add bz2 from CPython 3.10.5

---

Cargo.toml

enable lto for release build

---

Lib/test/test_marshal.py
vm/src/builtins/dict.rs
vm/src/dictdatatype.rs
vm/src/stdlib/marshal.rs

The previous design didn't support recursive

redesign marshal

---

Lib/test/test_marshal.py
vm/src/stdlib/marshal.rs

a few more marshal

---

vm/src/stdlib/io.rs

Fix _TextIOBase.encoding impl

---

Lib/test/test_ucn.py
Lib/test/test_univnewlines.py

skipped test is related to https://github.com/progval/unicode_names2/issues/6

Add test_ucn from CPython 3.10.5

---

Lib/test/test_types.py
vm/src/builtins/union.rs

Resolve `test_types::UnionTests::test_union_parameter_chaining`

Fix making union parameters

---

vm/src/builtins/union.rs

Refactor making union parameters 

---

Lib/test/test_exceptions.py
bytecode/src/lib.rs
compiler/src/compile.rs
compiler/src/error.rs
compiler/src/snapshots/rustpython_compiler_core__compile__tests__if_ands.snap
compiler/src/snapshots/rustpython_compiler_core__compile__tests__if_mixed.snap
compiler/src/snapshots/rustpython_compiler_core__compile__tests__if_ors.snap
compiler/src/snapshots/rustpython_compiler_core__compile__tests__nested_double_async_with.snap

before:
```
0 SetupLoop            (13)
>>     1 LoadFast             (0, a)
2 JumpIfFalse          (12)
3 LoadFast             (0, a)
4 SetupWith            (9)
5 Pop
6 Continue             (1)
7 PopBlock
8 EnterFinally
>>     9 WithCleanupStart
10 WithCleanupFinish
11 Jump                 (1)
>>    12 PopBlock
>>    13 LoadConst            (None)
14 ReturnValue
```
after:
```
2           0 SetupLoop            (13)
>>    1 LoadFast             (0, a)
2 JumpIfFalse          (12)
3           3 LoadFast             (0, a)
4 SetupWith            (9)
5 Pop
4           6 Continue             (1)
7 PopBlock
8 EnterFinally
>>    9 WithCleanupStart
10 WithCleanupFinish
11 Jump                 (1)
>>   12 PopBlock
>>   13 LoadConst            (None)
14 ReturnValue
```

enhance dis output to print line numbers

---

Lib/test/test_pickle.py
Lib/test/test_pickletools.py
Lib/test/test_typing.py
Lib/typing.py
extra_tests/snippets/builtin_type.py
vm/src/builtins/type.rs

Implemente type __qualname__ setter

---

compiler/porcelain/src/lib.rs
vm/src/bytesinner.rs
vm/src/macros.rs
vm/src/object/ext.rs
vm/src/protocol/object.rs
vm/src/stdlib/thread.rs
vm/src/vm/mod.rs

to prevent #3986 to use Display trait

No Display trait for PyObject

---

.github/workflows/ci.yaml

I need time to check if the failure is our bug or rust regression.

set CI toolchain to 1.62.1

---

whats_left.py

This pull request resolves #3996.
This pull request introduces `--doc` option in `whats_left.py` script. You can run it like `./whats_left.py --doc --signature`.
----
ps. Currently, it seems some bugs to get document (`inspect.getdoc`, `inspect._finddoc`) but I think it isn't related to this feature.
ps. 🔼 About the above issue, it seems `__slots__` implementation issue 🤔 (e.g. `_SpecialForm.__doc__`)

Check `__doc__` difference also in whats_left

---

vm/src/stdlib/pwd.rs

The refactored contents while developing the grp module are also reflected in the pwd module.

Refactor: pwd module

---

.github/workflows/ci.yaml
Lib/test/test_os.py
vm/src/stdlib/pwd.rs

#4053 
This is intended change in Rust

Use stable rust again

---

Cargo.lock
Lib/fnmatch.py
Lib/ntpath.py
Lib/test/test_fnmatch.py
Lib/test/test_ntpath.py
vm/Cargo.toml
vm/src/stdlib/nt.rs

Add nt._path_splitroot and update ntpath

---

Lib/unittest/result.py
Lib/unittest/test/test_result.py
vm/src/builtins/traceback.rs
vm/src/import.rs
vm/src/suggestion.rs

Update `traceback.tb_next` to be writable.

---

Cargo.lock
vm/Cargo.toml
vm/src/stdlib/sre.rs

Refactor to update sre-engine to 0.4.1

---

Lib/http/__init__.py
Lib/http/client.py
Lib/http/cookiejar.py
Lib/http/cookies.py
Lib/http/server.py
Lib/test/test_http_cookiejar.py
Lib/test/test_http_cookies.py
Lib/test/test_httplib.py
Lib/test/test_httpservers.py
Lib/test/test_urllib.py
common/src/lib.rs
common/src/windows.rs
vm/Cargo.toml
vm/src/stdlib/winapi.rs

close #4001
close #3925 by including its all commits

feat: _winapi.GetModuleFileName

---

parser/build.rs

better error message for #4117

panic when parser build failed

---

extra_tests/custom_text_test_runner.py
extra_tests/jsontests.py
vm/src/dictdatatype.rs

- Try fixing jsontest?
- Fix occasional race condition in dictdatatype

fix cron ci 2

---

vm/src/builtins/code.rs
vm/src/builtins/frame.rs
vm/src/frame.rs
vm/src/warn.rs

Update warning module https://github.com/RustPython/RustPython/issues/4013

Update warning setup_context

---

Lib/test/test_math.py
stdlib/src/math.rs

`math.exp2` return 2 raised to the power x.
* Python codes are copy-pasted from CPython.
- https://github.com/python/cpython/pull/29829
- [Python documentation](https://docs.python.org/3.11/library/math.html#math.exp2)

Add `math.exp2` implemented in cpython 3.11

---

compiler/parser/Cargo.toml
compiler/parser/build.rs

maybe related to #4166 and #4117

temporary fix of lalrpop build

---

vm/src/builtins/dict.rs
vm/src/vm/context.rs
vm/src/vm/mod.rs
vm/src/warn.rs

Update warning module https://github.com/RustPython/RustPython/issues/4013

Update warning warn_explicit

---

vm/src/builtins/function.rs
vm/src/frame.rs

Fix https://github.com/RustPython/RustPython/issues/4088 and refactor function `repr()`

Update function `__qualname__` and `repr`

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

add takewhile.__reduce__

---

Cargo.lock
jit/Cargo.toml
jit/src/instructions.rs
jit/src/lib.rs

👋 Hey,
I was playing around with this project and noticed the cranelift version is quite a bit out of date. This PR updates it to the latest version.

Update JIT Cranelift version

---

vm/src/function/getset.rs
vm/src/object/core.rs
vm/src/protocol/object.rs

This PR fixes compile error when using `vm-tracing-logging` feature is on
- https://github.com/RustPython/RustPython/discussions/4162

Fix compile error when using `vm-tracing-logging` is on

---

vm/src/builtins/code.rs

Hello there!
I started working on issue #4022  and was just wondering whether this is the right place to implement the replace() function.

<code object>::replace()

---

compiler/parser/src/lexer.rs
compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_f_string.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_f_string_concat_3.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_string_triple_quotes_with_kind.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_f_string_concat_1.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__parse_u_f_string_concat_2.snap
compiler/parser/src/string.rs

Start string location at kind or quote prefix

---

compiler/ast/asdl_rs.py
compiler/ast/src/ast_gen.rs
compiler/ast/src/constant.rs

I'm finding this useful for some automatic code generation applications.

Make AST nodes Clone-able

---

Lib/test/test_enum.py
Lib/test/test_float.py
vm/src/builtins/float.rs

Fixed return type for fromhex class method of float subclass.

Fix class method of a float subclass

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

Hi!
Here is a solution proposal for `reduce` and `setstate` functions for `zip_longest` (#3611).

Add reduce and setstate for zip_longest

---

Lib/test/test_pickle.py
Lib/test/test_pickletools.py
vm/src/builtins/builtinfunc.rs
vm/src/builtins/function.rs

Add method.__reduce__

---

Lib/test/test_opcodes.py
vm/src/builtins/type.rs
vm/src/types/slot.rs

Fix test_default_annotations_exist in test_opcodes

Add annotations for type

---

Lib/test/test_ast.py
vm/src/stdlib/ast.rs

Add `_fields` attribute to ast and remove expectedFailure

Add `_fields` attribute to ast

---

Cargo.lock
Lib/test/test_math.py
Lib/test/test_statistics.py
stdlib/Cargo.toml
stdlib/src/math.rs

Part of #1671
My plan is to extend this to log() and log10() in the next PR — I wanted to see how you felt about the approach, first. Let me know what you think.

Allow log2() to work on large integers

---

Lib/test/test_marshal.py
vm/src/stdlib/marshal.rs

Added to marshal to support StopIteration type and remove expectedFailure

Add `StopIteration` type to marshal

---

jit/src/instructions.rs
jit/tests/float_tests.rs

👋 Hey,
This PR Implements float comparisons in the JIT.

Implement float comparisions in JIT

---

jit/src/instructions.rs

The duplication with JitType is a bit unfortunate, but this is a big
ergonomics improvement when working on the compiler itself.
This will also allows us to define types that are internal to the
compiler and shouldn't leak to other code via the JitType

Make JitValue an enum

---

vm/src/stdlib/itertools.rs

```bash
>>>>> from itertools import combinations
>>>>> c = combinations([1,2,3,4], 2)
>>>>> c.__reduce__()
(<class 'itertools.combinations'>, ((1, 2, 3, 4), 2))
```

Add itertool.combinations.__reduce__ method

---

compiler/parser/src/lexer.rs

I added following test in `test_numbers`.
* octal
* exponent

Add test in test_numbers

---

DEVELOPMENT.md

#4294
I changed bytecode path from `bytecode/src` to `compiler/core/src`.

Change bytecode path

---

DEVELOPMENT.md

File structure has changed in https://github.com/RustPython/RustPython/commit/a05a09390ef858f10907fde8cd92d225d077c238.
So I fixed source code path in `DEVELOPMENT.md`.

Fix `DEVELOPMENT.md`

---

Lib/test/test_ast.py
compiler/parser/python.lalrpop
compiler/parser/src/parser.rs
compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_boolop_and.snap
compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_boolop_or.snap

Fix `ExprKind::BoolOp` location

---

vm/src/frame.rs

I added the following functions in `ExecutingFrame`.
* `jump_if`
* `jump_if_or_pop`

Refactor `ExecutingFrame`

---

vm/src/py_serde.rs

fix typo in `py_serde`

---

compiler/parser/src/string.rs

A follow-up for #4324. Refactors the code a bit.

A follow-up for #4324

---

Lib/test/test_symtable.py
compiler/codegen/src/symboltable.rs
vm/src/stdlib/symtable.rs

#4350
I fixed the code to make `test_local` pass.

make `test_local` pass

---

compiler/parser/python.lalrpop
compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_lambda.snap

Fixes the location of `BinOp`.

Fix the location of `BinOp`

---

stdlib/src/ssl.rs

probably missed in a previous pr.

Fix build error for ssl on android.

---

vm/src/vm/thread.rs

If I understand it correctly, the current vm is not required to be the same vm that the pyobject is created except the __del__ slot.
The current vm should match the vm provided by function argument that for now always getting from enter_vm function.
Is this the right appoarch?
@youknowone @coolreader18

Store Current VirtualMachine Pointer in LocalKey

---

compiler/parser/python.lalrpop
compiler/parser/src/parser.rs
compiler/parser/src/snapshots/rustpython_parser__parser__tests__slice.snap

This PR fixes the location of `Slice`.

Fix `Slice` location

---

Lib/test/test_string_literals.py
vm/src/stdlib/builtins.rs

Solved by removing preceding whitespaces, tabs, and newlines for evals only. Fixes #4364

Fix eval doesn't work correctly

---

compiler/parser/src/fstring.rs

A minor refactoring I found in #4343 that can simplify the code. `expression` in `FStringParser.parse_formatted_value` currently contains `{}`, but it doesn't have to.
```python
f"a {b} c"
^^^
expression contains { and }, requires slicing when parsed
```
```python
f"a {b} c"
^
expression doesn't contain { and }, doesn't require slicing when parsed
```

Refactor `FStringParser.parse_formatted_value`

---

Lib/test/test_named_expressions.py

Update test_named_expressions.py to CPython 3.11

---

compiler/parser/src/fstring.rs

Refactors `FStringParser` to simplify https://github.com/RustPython/RustPython/pull/4343.

Refactor `FStringParser`

---

Cargo.lock
Cargo.toml
src/lib.rs

Fix be silent even with no file using stdin

---

extra_tests/snippets/stdlib_itertools.py
vm/src/stdlib/itertools.rs

Related to #3611
Implement and add tests for the reduce function of islice.

Implement islice.__reduce__

---

compiler/parser/python.lalrpop
compiler/parser/src/snapshots/rustpython_parser__context__tests__assign_named_expr.snap
compiler/parser/src/snapshots/rustpython_parser__parser__tests__parse_named_expression_generator_comprehension.snap
compiler/parser/src/snapshots/rustpython_parser__with__tests__with_statement.snap

Fix `NamedExpr` location

---

compiler/parser/src/string_parser.rs

This PR removes unreachable code in `compiler/parser/src/string_parser.rs` to simplify the code.

Remove unreachable code in `compiler/parser/src/string_parser.rs`

---

compiler/parser/src/string_parser.rs

This PR merges match arms in `parse_formatted_value` that perform the same operation to simplify the code.

Merge match arms in `StringParser.parse_formatted_value`

---

compiler/parser/src/error.rs
compiler/parser/src/string_parser.rs

Improves error conversion in `string_parsers.rs`.

Improve error conversion in `string_parsers.rs`

---

compiler/parser/src/string_parser.rs

Removes repetitive `to_string` in `parse_escaped_char`.

Remove repetitive `to_string` in `parse_escaped_char`

---

compiler/parser/src/lexer.rs

Updates the implementation of `CharWindow` in `compiler/parser/src/lexer.rs` to allow slicing.

Update `CharWindow` in `compiler/parser/src/lexer.rs` to allow slicing

---

compiler/codegen/src/symboltable.rs
compiler/core/src/location.rs
compiler/parser/src/error.rs
compiler/parser/src/string_parser.rs

Adds `with_col_offset` and `with_row_offset` to `Location` for conveniece.

Add `with_col_offset` and `with_row_offset` to `Location` for conveniece

---

Lib/test/test_list.py
extra_tests/snippets/builtin_list.py
vm/src/builtins/list.rs

#4315
I added comparison between index and list size in `PyList.remove`.

Fix `PyList.remove`

---

src/shell.rs

Improved the fix for the continuing problem in the shell

---

compiler/parser/src/lexer.rs
compiler/parser/src/string_parser.rs
compiler/parser/src/token.rs

Simplifies string check in `Lexer.lex_identifier`.

Simplify string check in `Lexer.lex_identifier`

---

Lib/ctypes/__init__.py
Lib/ctypes/_aix.py
Lib/ctypes/_endian.py
Lib/ctypes/macholib/README.ctypes
Lib/ctypes/macholib/__init__.py
Lib/ctypes/macholib/dyld.py
Lib/ctypes/macholib/dylib.py
Lib/ctypes/macholib/fetch_macholib
Lib/ctypes/macholib/fetch_macholib.bat
Lib/ctypes/macholib/framework.py
Lib/ctypes/util.py
Lib/ctypes/wintypes.py

I newly added `Lib/ctypes` because it was missing. imported from CPython 3.11 branch.
#4247

add Lib/ctypes from cpython 3.11

---

Lib/test/test_float.py
vm/src/builtins/float.rs

I've fixed the error message of ValueError.
With this fix, following test now pass.
* `test_error_message` in `test_float.py`

Fix error message

---

Lib/test/test_float.py
common/src/float_ops.rs
extra_tests/snippets/builtin_float.py

I've fixed float modulo operation.
With this fix, following test now pass.
* `test_float_mod` in `test_float.py`

Fix float mod

---

Lib/test/test_dataclasses.py
vm/src/builtins/function.rs

fix https://github.com/RustPython/RustPython/issues/4473

use qualname in `TypeErrors` for functions

---

compiler/parser/src/lexer.rs

Removes the new line handler window and moves the checks inside the lexer. This is slightly more complex but it does mean we don't check each source character twice (once during the NewLineHandler and once during the proper lexing phase. This does result in an 7-8% speed-up on my machine.
I've also gone ahead and documented most I could in the file.

Remove NewLineHandler, move handling inline.

---

vm/src/sliceable.rs

used by #3755
@coolreader18 I am worrying if you had a reason to choose that form. Could you check it?

wrap_index without abs

---

stdlib/src/sqlite.rs

Fixed: https://github.com/RustPython/RustPython/issues/4493

Fix aarch64 compatibility for sqlite.

---

vm/src/builtins/code.rs

Add co_freevars to code object

---

vm/src/builtins/code.rs

Add co_cellvars to code object

---

Lib/test/test_future.py

that occurred after the last two PRs were merged.

Fix unexpected success in test_future.

---

common/src/bytes.rs
compiler/ast/src/constant.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/bytesinner.rs
vm/src/exceptions.rs

Make common::repr throw error instead of panic

---

Lib/graphlib.py
Lib/test/test_graphlib.py

This PR is no-brainer copy of graphlib from cpython v3.11.2

Copy graphlib module from cpython

---

vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/list.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/builtins/union.rs
vm/src/protocol/sequence.rs
vm/src/stdlib/collections.rs

Fix sequence mul types and add AsNumber for PyUnion

---

extra_tests/snippets/stdlib_os.py
vm/src/stdlib/posix.rs

Implementation for os.pathconf_names  resolves #4494

Pathconf names

---

vm/src/builtins/range.rs
vm/src/builtins/tuple.rs

Partially brought from #3460 
cc @TeamTamoad

Prepare to implement hash for tuple

---

vm/src/builtins/code.rs

Add co_nlocals to code object

---

compiler/parser/python.lalrpop
compiler/parser/src/parser.rs
compiler/parser/src/snapshots/rustpython_parser__parser__tests__variadic_generics.snap

See https://peps.python.org/pep-0646/#args-as-a-type-variable-tuple.

Allow type variable tuple for *args

---

Lib/locale.py
Lib/test/support/__init__.py
Lib/test/support/import_helper.py
Lib/test/support/os_helper.py
Lib/test/support/script_helper.py
Lib/test/support/socket_helper.py
Lib/test/support/testresult.py
Lib/test/support/threading_helper.py
Lib/test/support/warnings_helper.py
Lib/test/test_locale.py
Lib/test/test_support.py
Lib/test/test_utf8_mode.py

Update test.support from CPython 3.11.2

---

vm/src/builtins/bytearray.rs

Closes https://github.com/RustPython/RustPython/issues/4573

Implement Number Protocol for `PyByteArray`

---

vm/src/stdlib/sys.rs

add wasm32-wasi as wasi in sys.platform

---

README.md

attach links to images

---

extra_tests/snippets/stdlib_os.py
vm/src/stdlib/posix.rs

#4494
I don't know the reason but it seems fixed for macos already.

posix.pathconf_names

---

Cargo.lock
Cargo.toml
compiler/parser/Cargo.toml
compiler/parser/src/snapshots/rustpython_parser__string__tests__backspace_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__bell_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__carriage_return_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__character_tabulation_with_justification_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__delete_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__escape_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__form_feed_alias.snap
compiler/parser/src/snapshots/rustpython_parser__string__tests__hts_alias.snap
compiler/parser/src/string.rs
stdlib/Cargo.toml
vm/Cargo.toml

see also #4572
we can temporarily go with this because unicode_names2 will work with this interface in future.
closes #4566

Another temporary fix for #4566 

---

Lib/antigravity.py

Hey guys, first time contributing, so sorry in advance if I'm missing something.
- Moved from here: https://github.com/python/cpython/blob/3.11/Lib/antigravity.py
- Found no tests, but I tested it manually, and it seems ok.

feat(antigravity): update to 3.11

---

Lib/argparse.py
Lib/test/test_argparse.py

- Imported lib from: https://github.com/python/cpython/blob/3.11/Lib/argparse.py
- Imported test from: https://github.com/python/cpython/blob/3.11/Lib/test/test_argparse.py
Ran the tests and seemed ok
```
RUSTPYTHONPATH=Lib cargo run --release Lib/test/test_argparse.py 
Updating git repository `https://github.com/youknowone/unicode_names2.git`
Finished release [optimized] target(s) in 0.84s
Running `target/release/rustpython Lib/test/test_argparse.py`
(...)
Ran 1698 tests in 5.036s
OK
```

feat(argparse): update to 3.11

---

Lib/test/test_locale.py
Lib/test/test_types.py
stdlib/src/lib.rs
stdlib/src/locale.rs

This PR is to add localeconv function to locale module.
#3850

Add localeconv function to locale module

---

.github/workflows/ci.yaml
Lib/sysconfig.py
Lib/test/test_sysconfig.py

Closes #4589 (which most likely applied for all OS's). At some point it seems this change was removed from sysconfig by accident, this adds it back and also adds a check to the CI to make sure its caught in the future.
edit: Removed in #4569 which I also approved :smile:

Fix ensurepip install issues

---

Lib/configparser.py
Lib/test/test_configparser.py

- Lib: https://github.com/python/cpython/blob/3.11/Lib/configparser.py
- Test: https://github.com/python/cpython/blob/3.11/Lib/test/test_configparser.py
Test
```
RUSTPYTHONPATH=Lib cargo run --release Lib/test/test_configparser.py
Updating git repository `https://github.com/youknowone/unicode_names2.git`
Finished release [optimized] target(s) in 0.92s
Running `target/release/rustpython Lib/test/test_configparser.py`
...
Ran 343 tests in 1.312s
OK (skipped=5)
```

feat(configparser): update to 3.11

---

Lib/test/__init__.py

Add Lib/test/__init__.py

---

vm/src/builtins/set.rs
vm/src/builtins/type.rs

Closes https://github.com/RustPython/RustPython/issues/4618

Implement Number Protocol for `PyType`, `PySet` and `PyFrozenSet`

---

Lib/test/test_locale.py
stdlib/src/locale.rs

This PR is made to add `strcoll` and `strxfrm` function to `locale` module

Add strxfrm and strcoll to locale mod

---

vm/src/builtins/str.rs

Inspired by #3903.
Unblocks something in #4461.
c.f. #3244.

Add number protocol for PyStr

---

Lib/test/test_binascii.py
stdlib/src/binascii.rs

New PR for #4374. Still working on figuring out how to get the error messages to match, but wanted to get this up to at least run against CI and see what else I'm missing. I think the general direction should be okay.

Implement `strict_mode` keyword for `binascii.a2b_base64()`

---

compiler/parser/src/parser.rs
compiler/parser/src/snapshots/rustpython_parser__parser__tests__match_as_identifier.snap
compiler/parser/src/soft_keywords.rs

Will close https://github.com/charliermarsh/ruff/issues/3337 in Ruff.

Treat match and case as soft keywords in lambda assignments

---

Lib/test/test_bigmem.py

Update test_bigmem from cpython 3.11.2

---

Lib/test/exception_hierarchy.txt

> @fanninpm(#4624) One thing: since this references a file named exception_hierarchy.txt, it would make sense if it could also be brought up to date.
I didn't realize this file needed to be updated.

Update Lib/test/exception_hierarchy.txt from CPython 3.11.2

---

Lib/test/test_bool.py

Update test/test_bool from cpython 3.11.2

---

Lib/test/test_buffer.py

Update test/test_buffer from CPython 3.11.2

---

vm/src/builtins/dict.rs

Closes https://github.com/RustPython/RustPython/issues/4643

Implement Number Protocol for `PyDict`

---

vm/src/builtins/complex.rs

It was not converting int/float to complex.
I found it during testing #4615 , thanks @xiaozhiyan

Fix AsNumber for PyComplex bugs

---

Lib/test/test_zlib.py

Update test/test_zlib.py from CPython 3.11.2

---

derive-impl/src/pyclass.rs

use case: https://github.com/RustPython/RustPython/commit/fb818c85dd3b0e1a2ee591073562eb84c76802e0

Add extend_slot support for protocol traits

---

Lib/test/test_weakset.py

Update test/test_weakset.py from CPython 3.11.2

---

Lib/test/test_userstring.py

Update test/test_userstring.py from CPython 3.11.2

---

Lib/contextlib.py
Lib/test/test_contextlib.py

Update contextlib.py and test_contextlib from CPython 3.11.2

---

vm/src/builtins/complex.rs
vm/src/builtins/float.rs
vm/src/builtins/int.rs
vm/src/types/slot.rs

Refactor with AsNumber::number_downcast_exact

---

stdlib/src/locale.rs

Fixes #4661
Signed-off-by: Kaan Karakaya <yusufkaan142@gmail.com>

Remove strict type to allow cross compiling

---

Lib/test/test_userdict.py
Lib/test/test_userlist.py

In the case of test_userdict.py file only white space is different.
#4564

Update test/test_userlist.py and test_userdict.py from CPython 3.11.2

---

Lib/test/test__osx_support.py

- `_osx_support.py` remains unchanged

Update test__osx_support.py from CPython 3.11

---

Lib/test/test_array.py
stdlib/src/array.rs
vm/src/function/argument.rs

Add init for array.rs

---

Lib/test/test_unpack.py

Update test/test_unpack.py from CPython 3.11.2

---

Lib/test/test_unicodedata.py

Update test_unicodedata from CPython 3.11.2

---

Lib/test/test_compile.py
vm/src/builtins/code.rs

Add co_stacksize to code objects

---

stdlib/src/array.rs
stdlib/src/bisect.rs
stdlib/src/math.rs
stdlib/src/zlib.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/int.rs
vm/src/builtins/list.rs
vm/src/builtins/range.rs
vm/src/builtins/slice.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/convert/try_from.rs
vm/src/function/mod.rs
vm/src/function/number.rs
vm/src/object/payload.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/io.rs

apply ArgIndex

---

stdlib/src/ssl.rs

Solve the problem of unmatched types

---

pylib/build.rs

remove *.pyc during rustpython-pylib build

---

Lib/test/test_unicode_file_functions.py

Update test_unicode_file_functions.py from CPython 3.11.2

---

src/shell/helper.rs
vm/src/builtins/builtin_func.rs
vm/src/builtins/classmethod.rs
vm/src/builtins/descriptor.rs
vm/src/builtins/function.rs
vm/src/builtins/getset.rs
vm/src/builtins/property.rs
vm/src/builtins/staticmethod.rs
vm/src/builtins/str.rs
vm/src/builtins/super.rs
vm/src/builtins/type.rs
vm/src/cformat.rs
vm/src/convert/try_from.rs
vm/src/frame.rs
vm/src/protocol/mapping.rs
vm/src/protocol/number.rs
vm/src/protocol/object.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/operator.rs
vm/src/stdlib/sys.rs
vm/src/types/slot.rs
vm/src/vm/method.rs
vm/src/vm/mod.rs
vm/src/vm/vm_object.rs
vm/src/vm/vm_ops.rs

alt work of #4737 without descr_get

method calls to take &PyObject

---

Lib/test/test_pwd.py

#4564 Update test from  `test_pwd` cpython 3.11.2

update test from test_pwd cpython 3.11.2

---

Lib/test/test_array.py

#4564 update test_array.py from Cpython

Update test_array.py from Cpython v3.11.2

---

Lib/test/test_sort.py

#4564 marked failed case expected failure

updated test_sort from cpython 3.11.2

---

Lib/glob.py
Lib/test/test_glob.py

Update glob.py and test/test_glob.py from CPython v3.11.2

---

Lib/test/test_getopt.py

update test_getopt.py from cpython 3.11.2

update test_getopt.py from cpython 3.11.2

---

Lib/test/test_eof.py

#4564 Add test_eof.py from Cpython v3.11.2 with expectedFailure

Add test_eof.py from Cpython v3.11.2

---

Lib/test/test_bytes.py

Update test_bytes.py from CPython v3.11.2

---

Lib/test/test_complex.py

update test_complex.py from cpython 3.11.2
#4564

update test_complex.py from cpython 3.11.2

---

Lib/test/test_math.py

update test_math.py from python 3.11.2
#4564

update test_math.py from cpython 3.11.2

---

Lib/random.py
Lib/test/test_random.py
vm/src/builtins/int.rs

Fix int.from_bytes and Update random.py and test/test_random.py from CPython v3.11.2

---

Lib/test/test_listcomps.py

update test_listcomps.py from cpython 3.11.2
#4564

update test_listcomps.py from cpython 3.11.2

---

Lib/test/test_cmath.py

update test_cmath.py from cpython 3.11.2

update test_cmath.py from cpython 3.11.2

---

Lib/test/test_dict.py

#4564 updated test_dict.py from CPython v3.11.2

Update test_dict.py from CPython v3.11.2

---

Lib/test/test_deque.py

#4564 updated `test_deque.py` from CPython v3.11.2

updated test_deque.py from CPython v3.11.2

---

Lib/base64.py
Lib/test/test_base64.py
vm/src/builtins/int.rs

I also added default parameters to to_bytes to fix tests that failed.

make int.to_bytes arguments optional and update base64.py and test_base64.py from CPython v3.11.2

---

Lib/test/test_print.py

#4564 added new test file and marked TODOs

added test_print.py and marked TODOs

---

vm/src/builtins/int.rs
vm/src/builtins/str.rs
vm/src/object/ext.rs

disallowing subclass is a repeatitive pattern

Fix str.__str__ and PyRef::into_exact_or for int() or str() pattern

---

Lib/test/test_fileinput.py
vm/src/stdlib/io.rs
vm/src/stdlib/sys.rs
vm/src/vm/setting.rs

https://github.com/RustPython/RustPython/issues/4662

Add encoding="locale" support for TextIOWrapper

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml

Reenable redox ci

---

.github/workflows/ci.yaml
Lib/test/test_os.py

#3960 for test_os
In addition removed test_iter from platform dependant tests.

test_os windows failed test handling

---

vm/src/function/buffer.rs

Buffer arguments as PyObject

---

Lib/test/test_sysconfig.py
stdlib/src/mmap.rs
stdlib/src/socket.rs

Hi,
cargo build && test, all tests pass:
```
Running unittests src/lib.rs (target/debug/deps/rustpython-2c061bc00c2f70a2)
running 1 test
Hello
Hello
test tests::test_run_script ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.38s
Running unittests src/main.rs (target/debug/deps/rustpython-f9242e878d797bdd)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests rustpython
running 1 test
test src/lib.rs - (line 8) - compile ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s
```
Please review my patch.
Thanks,
Leslie Zhai

Add loongarch64 support

---

derive-impl/src/lib.rs
derive-impl/src/pyclass.rs
derive-impl/src/util.rs
derive/src/lib.rs
extra_tests/snippets/builtin_exceptions.py
vm/src/builtins/type.rs
vm/src/class.rs
vm/src/exceptions.rs
vm/src/macros.rs
vm/src/protocol/callable.rs
vm/src/stdlib/io.rs
vm/src/types/slot.rs
vm/src/vm/method.rs
vm/src/vm/vm_object.rs
vm/src/vm/vm_ops.rs

@sobolevn would you review this PR?

Merge define_exception into pyexception

---

common/src/format.rs
test.py
vm/src/builtins/bool.rs

Closes #4939
Probably more to do but im gonna let the action runner help me.

Format d bool support

---

stdlib/src/array.rs
stdlib/src/csv.rs
stdlib/src/pystruct.rs
stdlib/src/sqlite.rs
vm/src/builtins/asyncgenerator.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/coroutine.rs
vm/src/builtins/dict.rs
vm/src/builtins/enumerate.rs
vm/src/builtins/filter.rs
vm/src/builtins/generator.rs
vm/src/builtins/iter.rs
vm/src/builtins/list.rs
vm/src/builtins/map.rs
vm/src/builtins/memory.rs
vm/src/builtins/range.rs
vm/src/builtins/set.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/builtins/zip.rs
vm/src/stdlib/collections.rs
vm/src/stdlib/io.rs
vm/src/stdlib/itertools.rs
vm/src/stdlib/os.rs
vm/src/types/slot.rs
wasm/lib/src/js_module.rs

Implement PyObject_SelfIter to  actually share same function

---

Cargo.lock
Cargo.toml
compiler/src/lib.rs
examples/hello_embed.rs
examples/mini_repl.rs
src/shell.rs
stdlib/src/dis.rs
vm/src/compiler.rs
vm/src/eval.rs
vm/src/import.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/symtable.rs
vm/src/vm/compile.rs
vm/src/vm/interpreter.rs
vm/src/vm/mod.rs
vm/src/vm/vm_new.rs

Remove compiler_core::CompileError

---

Cargo.lock
Cargo.toml
compiler/codegen/src/compile.rs
compiler/codegen/src/symboltable.rs
vm/src/stdlib/ast/gen.rs

https://github.com/RustPython/Parser/pull/11
#4930

 Refactor ast to hold data as seperated type

---

vm/src/bytesinner.rs

Fix repr(bytearray) in debug

---

vm/src/exceptions.rs

Added `__reduce__` method for `ImportError` #3611.

Implemented __reduce__ method for the ImportError exception

---

Lib/test/test_types.py
vm/src/builtins/namespace.rs

Added `__reduce__` method for `types.SimpleNamespace` #3611.

Implemented __reduce__ method for types.SimpleNamespace

---

Lib/test/test_weakref.py
vm/src/builtins/weakproxy.rs
vm/src/protocol/number.rs
vm/src/stdlib/builtins.rs

weakref.__reversed__ fixed

---

extra_tests/snippets/syntax_del.py
vm/src/frame.rs

Attempt at addressing #4910 .
Maybe should also add a test?

Check variables in local scope in DeleteFast

---

Lib/_dummy_thread.py
Lib/test/test_builtin.py
Lib/test/test_fcntl.py
Lib/test/test_httpservers.py
Lib/test/test_os.py
Lib/test/test_pty.py
Lib/test/test_support.py
Lib/test/test_tempfile.py
Lib/test/test_threading.py
Lib/test/test_uuid.py
Lib/test/tf_inherit_check.py
vm/src/stdlib/thread.rs

Refer: https://github.com/RustPython/RustPython/issues/4971

Add fork support functions

---

Cargo.lock
Cargo.toml
compiler/codegen/src/compile.rs
compiler/codegen/src/symboltable.rs
compiler/src/lib.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/ast/gen.rs

https://github.com/RustPython/Parser/pull/59

new ast layout for arguments

---

vm/src/vm/setting.rs

Part of the solution for #4988

Added constructor for Settings called with_path

---

extra_tests/snippets/stdlib_os.py
vm/src/stdlib/thread.rs

Remove unecessary unsafe, remove generated file in extra_snippets.

---

Lib/test/test_compile.py
Lib/test/test_runpy.py
vm/src/stdlib/builtins.rs
vm/src/stdlib/os.rs

Fix test_path_like_objects

---

Lib/heapq.py
Lib/imghdr.py
Lib/ipaddress.py
Lib/linecache.py
Lib/netrc.py
Lib/nntplib.py
Lib/ntpath.py
Lib/nturl2path.py
Lib/numbers.py
Lib/pprint.py
Lib/test/test_ipaddress.py
Lib/test/test_netrc.py
Lib/test/test_ntpath.py
Lib/test/test_numeric_tower.py
Lib/test/test_pprint.py
Lib/test/test_urllib.py
Lib/test/test_zipfile.py

Update more libraries from 3.11

---

.github/workflows/ci.yaml
extra_tests/snippets/stdlib_sys.py
extra_tests/snippets/syntax_non_utf8.py
vm/src/stdlib/sys.rs
vm/src/vm/mod.rs
vm/src/vm/setting.rs

Hi!
Here is a solution proposal for issue #5010.

Add `get_int_max_str_digits` and `set_int_max_str_digits` in `sys`.

---

Lib/test/test_cmd_line.py
src/settings.rs
vm/src/stdlib/sys.rs
vm/src/vm/mod.rs
vm/src/vm/setting.rs

resolves #5019. Welcoming feedback on best practices because I was unsure how to correctly do error handling and default values

add int_max_str_digits input from command line

---

.github/workflows/ci.yaml
scripts/update_asdl.sh

The latest version of this script is at https://github.com/RustPython/Parser/blob/main/scripts/update_asdl.sh — the version here does not work

Delete stale ASDL update script

---

vm/src/vm/mod.rs

Hi!
Here is a solution proposal to #4988 (error message part).

Path error message

---

Lib/code.py
Lib/test/test_code.py

Update test_code.py code.py from CPython v3.11

---

vm/src/stdlib/itertools.rs

added __reduce__ method for itertools.permutations

---

Lib/hashlib.py
Lib/test/test_hashlib.py

feat: update test_hashlib fro CPython3.11

---

vm/src/stdlib/imp.rs

related: https://github.com/RustPython/RustPython/issues/5056

feat: Implement _imp._frozen_module_names

---

Lib/difflib.py
Lib/test/test_difflib.py

related: https://github.com/RustPython/RustPython/issues/4564

update test_difflib from CPython3.11.2

---

Cargo.lock
Cargo.toml
benches/execution.rs
common/Cargo.toml
compiler/Cargo.toml
compiler/codegen/Cargo.toml
compiler/core/Cargo.toml
derive-impl/Cargo.toml
derive/Cargo.toml
jit/Cargo.toml
pylib/Cargo.toml
stdlib/Cargo.toml
vm/Cargo.toml
wapm.toml
wasm/lib/Cargo.toml

test 0.3.0 release target
fix #4793

Update parser & Release 0.3.0

---

Cargo.lock
vm/Cargo.toml

Bump is-macro crate from 0.2 ⇒ 0.3

Bump is-macro crate from 0.2 ⇒ 0.3

---

Cargo.lock
compiler/core/Cargo.toml

Bump lz4_flex version

---

Lib/ftplib.py
Lib/test/test_ftplib.py

Update ftplib to CPython 3.11.5

---

pylib/build.rs

Retry to fix win_lib_path again

---

.github/workflows/ci.yaml

The installation path actually seems to be changed time by time

retry windows ci openssl fix

---

jit/src/instructions.rs
jit/tests/bool_tests.rs
jit/tests/int_tests.rs

In JIT, Implemented more comparison operations for boolean types, and added tests
1. Verified with CPython implementation
2. Added necessary Tests

Implemented compare operation for boolean types in JIT engine

---

vm/src/builtins/object.rs
vm/src/protocol/object.rs

Hi!
Here is a solution proposal regarding the addition of PyObject_Dir to ByObjectRef (#3244).

implement PyObject_Dir for ByObjectRef

---

Lib/test/test_itertools.py
vm/src/stdlib/itertools.rs

Implemented __reduce__,  __setstate__ methods in product object of python itertools
1) Uncommented expected failure annotation and ran tests
Issue:
#3611

[VM] Object pickling implementation for product object (python itertools) 

---

vm/src/protocol/object.rs
vm/src/stdlib/builtins.rs

Hi!
Here is a solution proposal regarding the addition of PyObject_GetAIter to PyObject (#3244).

implement PyObject_GetAIter for PyObject

---

vm/src/protocol/object.rs

Hi!
Here are proposed implementations for PyObject_Type and PyObject_TypeCheck related to issue (#3244 ).

implement PyObject_Type and PyObject_TypeCheck

---

stdlib/Cargo.toml
vm/Cargo.toml

stdlib doesn't compile on Windows MSVC x64 otherwise.

Add missing 'sysinfoapi' feature for winapi

---

Lib/test/test___all__.py

Add a new test file Lib/test/test___all__.py 
I don't see test___all__.py file so I copied this from cpython version 3.12

Add Lib/test/test___all__.py

---

Cargo.lock
Lib/test/test_atexit.py
Lib/test/test_locale.py

I don't know if the update of Cargo.lock is important so I included it.

Update test__locale.py and test_atexit.py from CPython v3.12

---

common/src/str.rs
vm/src/stdlib/os.rs

const `str::is_ascii` and `OsStr::as_encoded_bytes`!

Use new 1.74 features

---

Lib/test/test_bigaddrspace.py
Lib/test/test_bigmem.py
Lib/test/test_bool.py
Lib/test/test_bufio.py
Lib/test/test_c_locale_coercion.py
Lib/test/test_class.py
Lib/test/test_cmath.py

Would you plz tick the boxes in issue #5104 ? Thank you!

Update test files from CPython v3.12.0

---

Cargo.lock
Cargo.toml

Fix #5120 for main branch side

Fix malachite-bigint version

---

Lib/abc.py
Lib/argparse.py
Lib/base64.py
Lib/bdb.py
Lib/bisect.py
Lib/test/support/asynchat.py
Lib/test/support/asyncore.py
Lib/test/test_abc.py
Lib/test/test_argparse.py
Lib/test/test_base64.py
Lib/test/test_bdb.py
Lib/test/test_bisect.py
Lib/test/test_bz2.py
Lib/test/test_file.py

Update libraries and test files from CPython v3.12

---

stdlib/Cargo.toml
vm/Cargo.toml

clean up winapi features

---

Cargo.lock
stdlib/Cargo.toml
stdlib/src/multiprocessing.rs
stdlib/src/select.rs
stdlib/src/socket.rs
stdlib/src/ssl.rs
vm/Cargo.toml
vm/src/stdlib/errno.rs
vm/src/stdlib/msvcrt.rs
vm/src/stdlib/nt.rs
vm/src/stdlib/os.rs
vm/src/stdlib/signal.rs
vm/src/stdlib/sys.rs
vm/src/stdlib/time.rs
vm/src/stdlib/winreg.rs
vm/src/windows.rs

Windows sys

---

Lib/test/test_abc.py
Lib/test/test_dataclasses.py
vm/src/builtins/object.rs

Fix abc error messages

---

vm/src/types/slot.rs

Fix typo in slot.rs

---

Lib/calendar.py
Lib/test/test_calendar.py

Update `calendar.py` and `test_calendar.py`  from CPython v3.12

---

.github/workflows/ci.yaml
Cargo.toml
stdlib/vcpkg.json

Fix Windows CI

---

compiler/codegen/src/compile.rs

better symboltable error message

---

Lib/test/test_operator.py

This PR for a `operator` module.
* `operator.py` doesn't need to be updated
* `Lib/test/test_operator.py` needs an update (this PR)

Update Lib/test/test_operator.py to 3.12

---

Lib/pprint.py
Lib/test/test_pprint.py

This PR for a ``pprint.py`` module
* ``pprint.py`` needs an update
* ``test_pprint.py`` needs an update

Update ``Lib/pprint.py`` and ``Lib/test/test_pprint.py`` to 3.12

---

Lib/cgitb.py

This PR for a ``cgitb.py`` module
* ``cgitb.py`` needs an update
* ``test_cgitb.py`` doesn't need to be updated

Update ``Lib/cgitb.py`` to 3.12

---

Lib/colorsys.py
Lib/test/test_colorsys.py

This PR for a ``colorsys.py`` module
``Lib/colorsys.py`` needs an update
``Lib/test/test_colorsys.py`` needs an update

Update ``Lib/colorsys.py`` and ``Lib/test/test_colorsys.py`` to 3.12

---

Lib/test/libregrtest/main.py

There seems to have been a bug in the libregrtest code which unloaded modules between tests. The previous state was calculated using `sys.modules.keys()`, which is actually a mutable object that is updated as the underlying `sys.modules` is updated. The result was that modules were not unloaded between tests, which is the root cause for `test_unittest` failing when run after `test_import` and `test_importlib`.
This code is copied from 3.12. Ideally all of `libregrtest` should probably be updated as it seems wildly out of date, but that's a lot more work.

Properly unload modules between tests

---

common/src/static_cell.rs
common/src/str.rs
vm/src/builtins/memory.rs
vm/src/stdlib/os.rs

clippy was just updated and has a few minor issues with the code base. This should get CI passing again.

Implement new clippy lints

---

Lib/test/test_re.py

cherry-pick python/cpython#117616

Require cpu resource to test_search_anchor_at_beginning

---

vm/src/vm/interpreter.rs
vm/src/vm/mod.rs
vm/src/vm/vm_object.rs

if users want simple panic, Result::expect could be used.

always print exceptions when panic by expect_pyresult

---

Cargo.lock
Cargo.toml
stdlib/Cargo.toml
vm/Cargo.toml

Update a few deps

---

Lib/test/test_hashlib.py
stdlib/src/lib.rs
stdlib/src/sha256.rs
stdlib/src/sha512.rs
vm/src/class.rs

Also adding error message for #5210 less confusing

Fix _sha512 support

---

Lib/genericpath.py
Lib/os.py
Lib/posixpath.py
Lib/test/test_genericpath.py
Lib/test/test_os.py
Lib/test/test_posix.py
Lib/test/test_posixpath.py

test_os is not fully updated because it depends on async comprehension, which we don't implement yet.

Update os/posix/posixpath from CPython 3.12.2

---

Lib/test/test_exception_group.py
Lib/test/test_pickle.py
vm/src/exceptions.rs
vm/src/stdlib/builtins.rs

Add bare ExceptionGroup

---

Lib/pickle.py
Lib/pickletools.py
Lib/test/pickletester.py
Lib/test/test_pickle.py
Lib/test/test_pickletools.py
Lib/test/test_socket.py
Lib/test/test_types.py

pickletester is not fully updated 
Fix test errors of #5200

Update pickle from CPython 3.12.3

---

Lib/test/test_asyncgen.py
Lib/test/test_grammar.py
compiler/codegen/src/compile.rs
vm/src/frame.rs

following up #2513 #2999 
closes #2999 
partially resolving #2510 
Thank you for your effort @aaronclong and @HyeockJinKim 
Many other bugs (#5273 #5275 #5270) were related to this issue, so it had to be not easy to solve it.

Async for comprehension

---

README.md

Fix wasmer example

---

vm/src/stdlib/mod.rs
vm/src/stdlib/signal.rs

Add const-only signals for wasm32

---

vm/src/stdlib/sys.rs
vm/src/vm/thread.rs

sys.get_coroutine_origin_tracking_depth

---

vm/src/stdlib/sys.rs
vm/src/vm/thread.rs

sys.{get,set}_asyncgen_hooks

---

Cargo.lock
vm/Cargo.toml
wasm/lib/src/convert.rs

Wasm bindgen warning

---

derive-impl/src/pyclass.rs
stdlib/src/socket.rs
vm/src/builtins/asyncgenerator.rs
vm/src/builtins/builtin_func.rs
vm/src/builtins/bytearray.rs
vm/src/builtins/bytes.rs
vm/src/builtins/coroutine.rs
vm/src/builtins/descriptor.rs
vm/src/builtins/dict.rs
vm/src/builtins/frame.rs
vm/src/builtins/generator.rs
vm/src/builtins/getset.rs
vm/src/builtins/list.rs
vm/src/builtins/memory.rs
vm/src/builtins/namespace.rs
vm/src/builtins/range.rs
vm/src/builtins/set.rs
vm/src/builtins/str.rs
vm/src/builtins/tuple.rs
vm/src/class.rs
vm/src/protocol/buffer.rs
vm/src/stdlib/collections.rs
vm/src/stdlib/io.rs
vm/src/types/slot.rs

#5286 DISALLOW_INSTANTIATION flag will be useful to show better error message later

DefaultConstructor impls Constructor; Unconstructible is not anymore

---

Lib/test/test_os.py

working with `unittest.IsolatedAsyncioTestCase`

Update test_os from CPython v3.12.3

---

Lib/test/test_contextlib.py
compiler/codegen/src/compile.rs

As well as some mild formatting. 
Fix #4060

Adding generator_stop to compile_future_features

---

Lib/test/test_context.py

reported in https://github.com/RustPython/RustPython/pull/5325#issuecomment-2115841636

skip flaky test in test_context

---

vm/src/builtins/type.rs

See also original patch in #5324

Reduce rc ops from best_base

---

README.md

OpenSSL3 in README

---

Cargo.toml

Fix https://github.com/RustPython/RustPython/issues/5182#issuecomment-2120072410

feature ssl-vendor implies ssl

---

Cargo.lock
Cargo.toml

upgrade unicode_names2

---

.cspell.json
Lib/test/test_descr.py
vm/src/builtins/descriptor.rs
vm/src/builtins/getset.rs
vm/src/function/method.rs
vm/src/vm/context.rs

__objclass__

---

Lib/codecs.py
Lib/test/test_codecs.py

This is my first time contributing to open source. If there is anything that needs changed, please let me know.

Update codecs and test_codecs from cpython v3.12.4

---

vm/src/builtins/descriptor.rs
vm/src/builtins/type.rs

Fix #5349
cc @moreal 
Any suggestion for proper fix is appreciated

temp fix slot member_count

---

Cargo.toml
common/Cargo.toml
compiler/Cargo.toml
compiler/codegen/Cargo.toml
compiler/core/Cargo.toml
derive-impl/Cargo.toml
derive/Cargo.toml
jit/Cargo.toml
pylib/Cargo.toml
stdlib/Cargo.toml
vm/Cargo.toml
vm/sre_engine/Cargo.toml
wasm/lib/Cargo.toml

Mark rust-version 1.78

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
stdlib/Cargo.toml
stdlib/src/dis.rs
vm/Cargo.toml
vm/src/stdlib/time.rs
vm/src/vm/vm_object.rs
wasm/lib/Cargo.toml
wasm/wasm-unknown-test/Cargo.toml
wasm/wasm-unknown-test/README.md
wasm/wasm-unknown-test/src/lib.rs

originated from, and close #4875 
also  merge and close #4211

recreating wasmbind patch

---

Lib/test/test_exception_hierarchy.py
Lib/test/test_subprocess.py
stdlib/src/posixsubprocess.rs
vm/src/exceptions.rs
vm/src/function/protocol.rs
vm/src/stdlib/posix.rs

Fills in most of what was missing in posixsubprocess, so gids, groups, uids, etc are properly handled now.

Improve posixsubprocess

---

stdlib/build.rs
stdlib/src/ssl.rs

This is the version redox has in their package repository. Closes #5182

Fix build with openssl1

---

vm/src/sequence.rs
vm/src/vm/mod.rs

Fixes #1750 
Based on #1779 which seems to be abandoned.

Handle MemoryError for sequences

---

wasm/lib/src/lib.rs

Resolve clippy error
close #5429

Change deprecated type PanicInfo to PanicHookInfo

---

vm/src/stdlib/time.rs

Remove time.daylight  from freebsd

---

Cargo.lock
Cargo.toml
Lib/test/test_calendar.py
Lib/test/test_cmd_line.py
Lib/test/test_gzip.py
Lib/test/test_httpservers.py
Lib/test/test_repl.py
src/interpreter.rs
src/lib.rs
src/settings.rs
src/shell.rs
vm/Cargo.toml
vm/src/function/argument.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/imp.rs
vm/src/stdlib/io.rs
vm/src/stdlib/sys.rs
vm/src/vm/compile.rs
vm/src/vm/mod.rs
vm/src/vm/setting.rs

Part of this is taken from #5414.

Miscellaneous cli-related parity fixes

---

extra_tests/snippets/stdlib_os.py
vm/src/stdlib/os.rs
vm/src/stdlib/posix.rs

Move os.system from posix.rs to os.rs

---

Lib/test/support/testcase.py
Lib/test/test_float.py

re-open PR for update test_float.py copied from CPython v3.12.7
#5104

Update test float from c python v3.12.7

---

Lib/test/test_fstring.py

Update test_fstring.py from CPython v3.12.7

Update fstring from v3.12.7

---

Lib/contextlib.py
Lib/test/test_contextlib.py

Implements changes in the `contextlib` library to match CPython 3.12

Update contextlib from CPython 3.12

---

.github/workflows/release.yml
scripts/release-wapm.sh
vm/src/stdlib/signal.rs

Rename wasi target to wasm32-wasip1

---

Lib/test/support/__init__.py
Lib/test/test_zlib.py
stdlib/src/zlib.rs
vm/src/vm/vm_new.rs

After this is merged a few GZip tests are unblocked.

Update zlib from 3.12.6 and _ZlibDecompressor implementation

---

Lib/logging/__init__.py
Lib/logging/config.py
Lib/logging/handlers.py
Lib/smtplib.py
Lib/test/support/__init__.py
Lib/test/support/smtpd.py
Lib/test/test_logging.py
Lib/test/test_smtplib.py
Lib/test/test_smtpnet.py

Turns out logging tests were not being tested, this pr adds them too. This also adds smtplib because that is needed for logging tests

Update Logging to 3.12.7

---

vm/src/vm/vm_new.rs

The Expected payload... error in  #5476 is common pitfall for new comers. This panic will help not to forget actually add the Constructor.

Add better panic for abnormal downcast error

---

Cargo.lock
Cargo.toml

https://github.com/RustPython/malachite-bigint/pull/7

Pin malachite versions to avoid API incompatibility

---

extra_tests/snippets/stdlib_subprocess.py

fix windows subprocess test

---

vm/Cargo.toml
vm/src/stdlib/time.rs

Extend time compat for windows

---

.github/workflows/ci.yaml

Test colorize on CI

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
common/src/hash.rs
stdlib/Cargo.toml
stdlib/src/random.rs
stdlib/src/uuid.rs
vm/Cargo.toml
vm/src/import.rs
vm/src/stdlib/os.rs
wasm/lib/.cargo/config.toml
wasm/lib/Cargo.toml
wasm/wasm-unknown-test/.cargo/config.toml
wasm/wasm-unknown-test/Cargo.toml
wasm/wasm-unknown-test/src/lib.rs

`getrandom` is kinda messy now, but hopefully malachite removes its transitive dependency on `getrandom 0.2` soon and things can get simpler.

Update rand to 0.9

---

Cargo.lock
extra_tests/snippets/builtins_ctypes.py
vm/Cargo.toml
vm/src/stdlib/ctypes.rs
vm/src/stdlib/ctypes/array.rs
vm/src/stdlib/ctypes/base.rs
vm/src/stdlib/ctypes/function.rs
vm/src/stdlib/ctypes/library.rs
vm/src/stdlib/ctypes/pointer.rs
vm/src/stdlib/ctypes/structure.rs
vm/src/stdlib/ctypes/union.rs

Successor to #5519
The following works now (I've added it to `extra_tests`):
```python
i = c_int(42)
f = c_float(3.14)
assert i.value == 42
assert f.value == 3.14
```

_ctypes pt. 2

---

Lib/test/ieee754.txt
Lib/test/test_math.py
common/src/float_ops.rs
stdlib/src/math.rs
vm/src/builtins/float.rs

Still work in progress..commits will get messy until I fix everything.
Edit: Part of https://github.com/RustPython/RustPython/issues/5104

Updating test_math.py to CPython 3.12.9

---

stdlib/Cargo.toml

Update puruspe version to 0.4.0

---

.github/workflows/cron-ci.yaml

Update the csv for website what's left

---

extra_tests/snippets/stdlib_math.py

Add extra tests for issue

---

Lib/gzip.py
Lib/test/test_gzip.py
Lib/test/test_zlib.py
derive-impl/src/pymodule.rs
stdlib/src/zlib.rs

Best reviewed ignoring whitespace. Updating gzip turned out to fix test_gzip failures :]

Fix a bunch of zlib tests & update gzip.py to Python 3.13

---

vm/src/stdlib/ctypes.rs
vm/src/stdlib/ctypes/structure.rs

- `addressof`
- Parts of `Structure`

_ctypes addressof and Structure

---

.github/workflows/ci.yaml
wasm/demo/package-lock.json

Fixes #2086 and upgrade a few dependencies. Also allows for manual triggering of the workflow.

Actions caching for nodejs

---

.github/workflows/release.yml

Publish demo on weekly release

---

.github/workflows/cron-ci.yaml

Adds column name as per https://github.com/RustPython/rustpython.github.io/pull/80

Fix module.csv generation in cron ci

---

.github/workflows/cron-ci.yaml

Fix extra newline in module.csv generation in cron ci

---

Lib/_android_support.py
Lib/_apple_support.py
Lib/_ios_support.py

- `_android_support`
- `_apple_support`
- `_ios_support`

Add os support modules

---

stdlib/src/overlapped.rs

Replace pyattr(once) to constant

---

.github/workflows/cron-ci.yaml

The column name is "module", not "modules".

Fixed whats left

---

extra_tests/snippets/stdlib_sys.py
vm/src/stdlib/sys.rs

The `build` field is still somewhat wrong though.

partially fix sys.getwindowsversion()

---

Lib/statistics.py
Lib/test/test_statistics.py

This reverts commit ff970b0e1c8f51d2ccc292e4c405511c0ea3eb69.

Revert "Update statistics to 3.13.2 (#5592)"

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
Lib/test/test_grammar.py
compiler/codegen/src/compile.rs
compiler/src/lib.rs
src/shell.rs
vm/src/stdlib/ast.rs
vm/src/stdlib/ast/constant.rs
vm/src/stdlib/ast/expression.rs
vm/src/stdlib/ast/other.rs
vm/src/stdlib/ast/string.rs
vm/src/vm/vm_new.rs
wasm/lib/src/convert.rs

Update to ruff_python_parser 0.11

---

Cargo.lock
Cargo.toml
Lib/tkinter/__init__.py
Lib/tkinter/__main__.py
Lib/tkinter/colorchooser.py
Lib/tkinter/commondialog.py
Lib/tkinter/constants.py
Lib/tkinter/dialog.py
Lib/tkinter/dnd.py
Lib/tkinter/filedialog.py
Lib/tkinter/font.py
Lib/tkinter/messagebox.py
Lib/tkinter/scrolledtext.py
Lib/tkinter/simpledialog.py
Lib/tkinter/ttk.py
stdlib/Cargo.toml
stdlib/src/lib.rs
stdlib/src/tkinter.rs

Feature-gated because tk had to be installed in a not-very-easy manner to work on windows.

_tkinter pt. 1

---

Lib/ctypes/__init__.py
extra_tests/snippets/builtins_ctypes.py
vm/src/stdlib/ctypes.rs
vm/src/stdlib/ctypes/array.rs
vm/src/stdlib/ctypes/base.rs
vm/src/stdlib/ctypes/function.rs
vm/src/stdlib/nt.rs

This PR tries to do the following:

_ctypes pt. 4

---

.cspell.json
derive-impl/src/pystructseq.rs
derive/src/lib.rs

Add #[pystruct(skip)]

---

Cargo.lock
derive-impl/src/from_args.rs
derive/Cargo.toml
stdlib/src/binascii.rs
stdlib/src/faulthandler.rs
stdlib/src/hashlib.rs
stdlib/src/mmap.rs
stdlib/src/pystruct.rs
stdlib/src/select.rs
stdlib/src/socket.rs
stdlib/src/sqlite.rs
stdlib/src/ssl.rs
stdlib/src/zlib.rs
vm/src/anystr.rs
vm/src/builtins/int.rs
vm/src/builtins/list.rs
vm/src/stdlib/builtins.rs
vm/src/stdlib/codecs.rs
vm/src/stdlib/io.rs
vm/src/stdlib/os.rs
vm/src/stdlib/posix.rs
vm/src/stdlib/signal.rs
vm/src/stdlib/sre.rs
vm/src/stdlib/thread.rs
vm/src/stdlib/winreg.rs

Make FromArgs default field take an expression, not a string literal

---

Lib/doctest.py

expected to be resolved by #5443

try IncrementalNewlineDecoder in doctest

---

Lib/test/test_audit.py

This test is currently noop because RustPython does not have sys.audit?

Added test_audit from 3.13.2

---

.github/workflows/ci.yaml
common/src/linked_list.rs
src/lib.rs
src/settings.rs
src/shell.rs
stdlib/src/pystruct.rs
vm/src/builtins/mod.rs
vm/src/dict_inner.rs
vm/src/function/builtin.rs
vm/src/import.rs
vm/src/lib.rs
vm/src/object/core.rs
vm/src/object/traverse.rs
vm/src/prelude.rs
vm/src/protocol/buffer.rs
vm/src/protocol/object.rs
vm/src/readline.rs
vm/src/suggestion.rs
vm/src/version.rs
vm/src/vm/interpreter.rs
vm/src/vm/mod.rs
vm/src/vm/vm_ops.rs
wtf8/src/lib.rs

Also adds doc build to CI to prevent future warnings from cropping up.

Fix doc warnings

---

stdlib/src/lib.rs
stdlib/src/suggestions.rs
vm/src/suggestion.rs

Add _suggestions module

---

.cspell.dict/python-more.txt
Lib/_pyrepl/__init__.py
Lib/_pyrepl/__main__.py
Lib/_pyrepl/_minimal_curses.py
Lib/_pyrepl/_threading_handler.py
Lib/_pyrepl/commands.py
Lib/_pyrepl/completing_reader.py
Lib/_pyrepl/console.py
Lib/_pyrepl/curses.py
Lib/_pyrepl/fancy_termios.py
Lib/_pyrepl/historical_reader.py
Lib/_pyrepl/input.py
Lib/_pyrepl/keymap.py
Lib/_pyrepl/main.py
Lib/_pyrepl/mypy.ini
Lib/_pyrepl/pager.py
Lib/_pyrepl/reader.py
Lib/_pyrepl/readline.py
Lib/_pyrepl/simple_interact.py
Lib/_pyrepl/trace.py
Lib/_pyrepl/types.py
Lib/_pyrepl/unix_console.py
Lib/_pyrepl/unix_eventqueue.py
Lib/_pyrepl/utils.py
Lib/_pyrepl/windows_console.py
Lib/site.py
vm/src/stdlib/sys.rs

- Adds `sys._baserepl`
- Adds `_pyrepl` module
- Temporarily patches `site` module to add a needed function.

Add _pyrepl

---

Lib/test/support/__init__.py
Lib/test/test_csv.py
Lib/test/test_decimal.py
Lib/test/test_struct.py
Lib/test/test_unicode.py

`test/support/__init__.py` is good up till line 754.

Update struct to 3.13.3 and update parts of test.support

---

Cargo.lock
Cargo.toml
common/Cargo.toml
stdlib/Cargo.toml
stdlib/src/select.rs
vm/Cargo.toml

Straightforward upgrade of radium, criterion, which, rustix, system-configuration, and libz-rs-sys.

Miscellaneous deps upgrades

---

Lib/test/test___all__.py
Lib/test/test_android.py

Add more independent tests at 3.13.3

---

stdlib/src/lib.rs

Renames the module init from suggestions to _suggestions.
My bad

Fix _suggestions module init

---

stdlib/src/mmap.rs

When running test_mmap without release, it fails with a safety violation. This is because `File::from_raw_fd` is called from an invalid fd (the one from python). Instead, to fix this while avoiding TOCTOU, use `fstat` from the `nix` crate instead
```
test_bad_file_desc (test.test_mmap.MmapTests.test_bad_file_desc) ... fatal runtime error: IO Safety violation: owned file descriptor already closed
zsh: abort      cargo run -- -m test test_mmap -v
```

Fix mmap aborting with invalid fd in debug mode

---

Lib/colorsys.py
Lib/graphlib.py
Lib/linecache.py
Lib/pprint.py
Lib/queue.py
Lib/sched.py
Lib/test/test_heapq.py
Lib/test/test_linecache.py
Lib/test/test_pprint.py
Lib/test/test_queue.py
Lib/test/test_sched.py

- pprint
- colorsys
- queue
- linecache
- sched
- heapq
- graphlib
These have been batched since I didn't change any code. Everything is directly from cpython.

Update some libraries to 3.13.3

---

stdlib/src/overlapped.rs

Needed for regrtest upgrades.
Usage here: https://github.com/python/cpython/blob/4f18916c5c28321f363e85ee7ef3ee29bbf79d8e/Lib/test/libregrtest/win_utils.py#L37

More overlapped implementation

---

.cspell.dict/rust-more.txt
Cargo.lock
Cargo.toml
Lib/test/test_math.py
stdlib/Cargo.toml
stdlib/src/math.rs

Might be lower quality, but better compatibility
Repository: https://github.com/RustPython/pymath

Replace puruspe to pymath

---

Cargo.lock
Cargo.toml
stdlib/Cargo.toml

No breaking changes from them (that affect our code at any rate).

Bump dependencies

---

Lib/codeop.py
src/shell.rs

This makes it possible to define functions/classes interactively.

Support multiline function/class definitions in REPL and InteractiveConsole

---

Lib/test/test_math.py

Enable test_mtestfile

---

.cspell.dict/rust-more.txt
stdlib/src/compression/bz2.rs
stdlib/src/compression/generic.rs
stdlib/src/compression/mod.rs
stdlib/src/compression/zlib.rs
stdlib/src/lib.rs

Follow up to #5709. File structure is based on #5717, hopefully it should be mostly compatible.

Split out common compression routines into separate file

---

Cargo.lock
Cargo.toml
common/Cargo.toml

Add radium patch to fix CI

---

Cargo.lock
jit/Cargo.toml
jit/src/instructions.rs

Specifically: `Pop`, `Swap`, and `Nop`

Bump cranelift to 0.119 and add more instructions to JIT

---

.devcontainer/DOCKERFILE
.devcontainer/devcontainer.json

I adapted this configuration from deno: https://github.com/denoland/deno/blob/main/.devcontainer/devcontainer.json.

Dev container update

---

Lib/_collections_abc.py
extra_tests/snippets/stdlib_typing.py

Callable __or__ patch
