- vm/src/pyobject.rs
Implement list and tuple print to [elements.str()]  and {elements.str()}
Though parser doesn't support tuple yet.
> add pretty print to list and tuple

- vm/src/bytecode.rs
Implement Debug for CodeObject so that instructions is print in separate lines.
> add pretty Debug implementation for CodeObject

- src/main.rs
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
> Add bool constant

- parser/src/lexer.rs
This PR adds more tests for different EOL characters on Windows, Mac and Linux. It then also implements some fixes for EOL characters in comments and multi-line strings.
Sorry if the code is not perfect, but this is actually the first Rust code I have ever written...
> Add support for Windows/Mac EOL characters in lexer

- parser/src/python.lalrpop
For example, `cargo run -- -c 'print("a"); print("b")'`.
> Enable semi-colon separated statements

- vm/src/frame.rs
The Locals line in the Frame Object output is now, for example:
Locals: {"num": RefCell { value: [PyObj int 9] }, "f": RefCell { value: [PyObj function] }}
(Note that in cases where the inner values of the PyObjectRefs are unexpected, I simply output to the log and continue; potentially we should panic instead, but I wasn't sure if that was appropriate in a trace log.)
> Output locals mapping in trace logging

- vm/src/compile.rs
This means that breaks within while loops function correctly (as they have a block that they can reference to work out where to jump to).
This fixes running `tests/snippets/loop.py`:
```
$ cargo run -- tests/snippets/loop.py && echo worked
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
Running `target/debug/rustpython tests/snippets/loop.py`
thread 'main' panicked at 'No block to break / continue', vm/src/vm.rs:146:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
$ cargo run -- tests/snippets/loop.py && echo worked
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
Running `target/debug/rustpython tests/snippets/loop.py`
worked
```
> Emit a SetupLoop instruction during while loop compilation

- vm/src/objbool.rs
- vm/src/objlist.rs
- vm/src/objtuple.rs
- vm/src/vm.rs
This doesn't update the string `unimplemented!()` because that would conflict with my other PR.
> Add more information to unimplemented! panics

- parser/src/parser.rs
- src/main.rs
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/vm.rs
The interpreter should interate a list of expressions and/or statements,
and print the results of any expressions that do not return none.
Eval should fail (should eventually be Syntax Error) if it gets a
statement.
Still need to implement continuation lines.
```is_none``` doesn't belong in main, but I'm not sure where to put it (or if there's a better implementation). The ```is``` method on vm is private and wouldn't work anyway because None isn't a singleton yet.
> Interpreter improvements

- tests/snippets/3.1.3.2.py
- vm/src/lib.rs
- vm/src/objlist.rs
- vm/src/objsequence.rs
- vm/src/objtuple.rs
This moves the list slicing logic in to a separate function, and calls that function from the tuple code. The one thing I'm unsure about is whether `objlist.rs` is the appropriate place for this (though I'm not sure where would be better; suggestions welcome!).
> Implement stepped slicing for tuples

- parser/src/lexer.rs
lex_comment doesn't consume the newlines, (correctly) leaving them to
the regular newline parsing.  As such, it shouldn't call self.new_line,
or we end up double-counting lines.
> Don't double-count newlines in comments

- vm/src/builtins.rs
- vm/src/vm.rs
This adds a macro which can be called by rust functions to check that the arguments they have been given are of the correct type. (It also decomposes the args.args elements in to the identifiers that are passed in, removing another bit of boilerplate.)
We're using `char`s to indicate the expected type here because enum variants can't easily be referred to and/or compared.
This was inspired by CPython's Argument Clinic. I attempted to go all the way and unwrap the internal types of kinds (i.e. i32, Vec<...> etc.) but the type-checker defeated me. Rust macros also can't write/rewrite function signatures, which is another way in which this differs from Argument Clinic.
> Add a macro for builtins argument checking

- vm/src/builtins.rs
- vm/src/objbool.rs
- vm/src/objfloat.rs
- vm/src/objint.rs
- vm/src/objlist.rs
- vm/src/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- vm/src/vm.rs
Currently, all users of the *_type attributes on PyContext have to
immediately clone the pointer before they can use it; this pushes that
cloning in to getters to reduce the clone-clutter across the codebase.
> Implement getters for PyContext types

- Cargo.lock
- parser/src/ast.rs
- parser/src/parser.rs
- parser/src/python.lalrpop
- tests/snippets/func_defaults.py
- vm/Cargo.toml
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/lib.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
This allows defaults to be specified at function definition:
```py
def func(pos, defaulting="default"):
return pos, defaulting
assert 1, 2 == func(1, 2)
assert 1, "default" == func(1)
```
> Add support for function argument defaults

- tests/snippets/basic_types.py
- vm/src/objbool.rs
- vm/src/objfloat.rs
- vm/src/objint.rs
- vm/src/objlist.rs
- vm/src/objstr.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
In this pull request I implemented an example of the direction we should take. Please comment your ideas. The idea is to use isinstance more and more to test for certain types, and no longer test on PyObjectKind. Also this adds the methods `__add__` and friends to the builtin types.
> Alternative operator implementation based on typ instead of kind

- tests/snippets/json_snippet.py
- vm/src/objdict.rs
- vm/src/objlist.rs
- vm/src/objsequence.rs
- vm/src/stdlib/json.rs
We can currently only construct instances of string subclasses, so
that's the only code path that is actually tested.
Fixes #91.
> Rework json.dumps to support subclasses

- vm/src/import.rs
- vm/src/stdlib/mod.rs
- vm/src/vm.rs
This means we only have to load the modules once at startup.
Fixes #90.
> Store Rust stdlib modules on VirtualMachine and lazily-load them

- tests/snippets/bools.py
- vm/src/objbool.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
A surprising edge case of python that I'd forgotten about. Let's us delete some code.
> Bool is a subclass of int, so doesn't need a special kind.

- tests/snippets/strings.py
- vm/src/builtins.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objtype.rs
- vm/src/objbool.rs
- vm/src/vm.rs
Fixes issue #79 .
```
Welcome to the magnificent Rust Python 0.0.1 interpreter
>>>>> ["a", "b", "can't"]
['a', 'b', 'can\'t'] 
```
> Implement Repr

- tests/snippets/json_snippet.py
- vm/src/pyobject.rs
And so PyContext grows ever bigger. I wish there was somewhere better to put these, but there isn't at the moment.
Fixes: #132
> Add true_value and false_value to context.

- src/main.rs
- vm/src/builtins.rs
- vm/src/compile.rs
- vm/src/eval.rs
- vm/src/exceptions.rs
- vm/src/import.rs
- vm/src/lib.rs
* Raises `ModuleNotFoundError` when the module is not found.
* Raises `ImportError` when the module cannot be read. Rare case. Probably what CPython does.
* Raises `SyntaxError` when the file cannot be compiled.
* Raises whatever error when an exception is raised during executing the module's code.
* Fix multiline comments on Windows (was a `\r\n` thing).
* Keep collecting lines when an empty line is pressed but the code is still incomplete.
* Implemented using `sys.ps`, but stopped because modules dont have attributes yet.
> Improve behavior wrt errors during import

- tests/snippets/builtin_ord.py
- vm/src/builtins.rs
Implements builtin [ord](https://docs.python.org/3/library/functions.html#ord).
> builtin ord basic implementation. Fixes #151

- vm/src/builtins.rs
Addresses issue #152. Currently, they only work for integers and use the `PyObject::cmp` method from the `Ord` trait.
> Add max and min builtins

- .gitignore
- Cargo.toml
- README.md
- src/main.rs
Hi. I am not really sure about the dependency politics for this project. Is it to depend on the less possible external dependencies, or is it ok to use something like [https://github.com/kkawakam/rustyline](rustyline)?
If rustyline is ok, then this PR brings a repl history, and navigation. Some further steps would be required to have an awesome repl, but it seems that rustyline natively offers some of them. An awesome repl would probably have:
- syntax highlighting for the code
- syntax highlighting for the tracebacks
- history stored in some XDG repository
- code completion
If that's ok for you, I can create issues for those features.
Also, I do not really know how to test a feature like this. Maybe send some input to the binary, and expect some output?
> Basic repl based on rustyline

- src/main.rs
This fixes the way multi-line commands display when looking in the repl history.
> Minor repl fix

- .travis.yml
Once this is merged, let's change the "Source" in the RustPython/website repo from gh-pages to master branch
> Push website to the master branch to simplify website development

- vm/src/vm.rs
- wasm/Cargo.toml
- wasm/src/lib.rs
- wasm/src/wasm_builtins.rs
@rmliddle @windelbouwman would you mind reviewing this code?
I'm not sure what's the best way to allow different version of `print` builtin function. I add the `builtins` argument to VM's `new()`, so we can inject different version of builtin implementation to it. But maybe I need to use builder pattern or a Trait for that. What your thoughts on this?
This is how it works, we can build more interesting webpage demo on top of it.
> Mapping Python print to JavaScript console.log

- wasm/Cargo.lock
- wasm/Cargo.toml
- wasm/app/index.html
- wasm/app/index.js
- wasm/build.sh
- wasm/src/lib.rs
- wasm/src/wasm_builtins.rs
I was planning to put the getting element and setting value part in JS, because it's more of a way of representation then the core logic. But it turns out the `wasm-pack` tool we are using doesn't officially support loading external JS file for Rust to call (see https://github.com/rustwasm/wasm-pack/issues/240
). So I push the code to a branch for future reference: https://github.com/RustPython/RustPython/tree/wasm-output
Instead I let Rust code directly access the DOM API to manipulate the textarea value. 
Also I noticed that the `Cargo.lock` was checked-in before, so I commit it as well.
> [WASM] Print STDOUT to textarea on the demo page

- parser/src/lexer.rs
- tests/snippets/indentation.py
This allows the parser to handle tabs and spaces. Currently it
requires that spaces come after any tabs, which is slightly more
strict than python3. It also requires that neighboring indentation
levels have either both more spaces and tabs or less spaces and
tabs so that tab size can't make perception of indentation
differ from what the parser interprets.
I didn't opt to implement PartialOrd on IndentationLevel because I
wasn't sure that the comparison logic would meet the logical
requirements for that trait. One could easily switch to having it
implement PartialOrd though. This would necessitate switching to
manually implementing PartialEq so that it's behavior 'matches'.
It's unclear from the docs what 'matches' exactly means so for
now I'm avoiding implementing the traits.
> Handle mixed spaces and tabs.

- tests/snippets/list.py
- vm/src/obj/objlist.rs
Implements `__mul__` for lists so that it is possible to do things like
```
s = [1, 2,] * 3
s == [1, 2, 1, 2, 1, 2]
```
This is literally the first rust I've written (that isn't adventofcode) so hopefully it isn't too horrific.
(Hopefully) fixes https://github.com/RustPython/RustPython/issues/232
> Implements __mul__ for lists

- tests/snippets/dict.py
- vm/src/obj/objdict.rs
e.g.
```py
dict(a=2, b=3) == {'a': 2, 'b': 3}
dict({'a': 2, 'b': 3}, b=4) == {'a': 2, 'b': 4}
dict([('a', 2), ('b', 3)]) == {'a': 2, 'b': 3}
```
> Make `dict()` work like it does in cpython

- vm/src/builtins.rs
- vm/src/frame.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
This required going through and changing all the instances of `format!("{:?}", py_obj_ref)` to `format!("{}", py_obj_ref.borrow())`, because I implemented it as the `fmt::Display` formatter and `RefCell` doesn't implement `fmt::Display`, so the values need to be borrowed to get the `PyObject`.
> Format exceptions nicely (no more RefCell { value: .. }!)

- vm/src/exceptions.rs
- vm/src/stdlib/json.rs
Also, I noticed that in exceptions.rs a String was being allocated for every new exception type being added to the ExceptionZoo, so I changed that to just be a string literal. I assume that at one point `create_type` took an `&String` instead of an `&str`?
> Have the json ser/de functions throw an exception instead of panicking

- vm/src/obj/objbytes.rs
Tiny change to make things most consistent with python:
Previous Behaviour:
```python
>>>>> b = b'abc'
>>>>> b
b'\x61\x62\x63'
```
Python 3:
```python
>>> b = b'abc'
>>> b
b'abc'
```
> Bytes representation changed from hex to utf-8

- .travis.yml
Now if you push to the `release` branch, the deployment will run on every test suite. So all of them fails. We only want `publish documentation` to deploy to `RustPython/docs` and `WASM online demo` to release to `RustPython/demo`. 
I can't seem to find a way to put the deployment as a post-build step for just one test suite, so I use this ugly environment variable to limit that. 
Also here is a sample of a failed build: https://travis-ci.org/RustPython/RustPython/builds/476271838
> Limit the deployment only to the specific build job

- .travis.yml
I was stupid to forgot to add spaces around the equals signs in the previous PR #250 .
Clearly if you do `$FOO=true`, it is always evaluated as true in bash's `if [[ ... ]]` condition. ([Reference](https://stackoverflow.com/questions/4977367/why-equal-to-operator-does-not-work-if-it-is-not-surrounded-by-space))
I tested in a branch and now it seems to skip the deployment step properly: https://travis-ci.org/RustPython/RustPython/builds/478033185
> Fix the deploy condition for missing spaces around equals sign

- src/main.rs
- vm/src/builtins.rs
- vm/src/frame.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/ast.rs
- vm/src/stdlib/json.rs
- vm/src/stdlib/keyword.rs
- vm/src/stdlib/re.rs
- vm/src/stdlib/string.rs
- vm/src/stdlib/time_module.rs
- vm/src/stdlib/tokenize.rs
- vm/src/stdlib/types.rs
- vm/src/stdlib/weakref.rs
- vm/src/sysmodule.rs
This'll especially be useful in `main.rs`, which was cloning the entire source of the file it loaded :smiley:
> Remove unnecessary to_string conversions

- tests/snippets/buffered_reader.py
- tests/snippets/builtin_open.py
- tests/snippets/os_open.py
- tests/snippets/os_static.py
- vm/src/builtins.rs
- vm/src/obj/mod.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objmemory.rs
- vm/src/pyobject.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/os.rs
Start on some methods on the io Classes related to File-IO:  FileIO, BufferedReader/Writer and TextIOWrapper Classes and the open builtin.
Follows (approximately) the CPython implementation.
TextIOWrapper - BufferedReader/Writer - FileIO
Where open returns the TextIOWrapper or Buffered Type depending on the mode parameters. 
Some related implementation from the os module, memoryview and minor changes to bytes and byte array types.
[open](https://docs.python.org/3/library/functions.html#open) builtin at this stage only supports first two parameters: file and mode
> File-IO: IO Module and Open Builtin

- tests/snippets/list.py
- tests/snippets/tuple.py
- vm/src/obj/objlist.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objtuple.rs
This allows for `(1, 2) * 3`. The python documentation states that multiplying by a negative number should result in an empty sequence (https://docs.python.org/3.7/library/stdtypes.html#common-sequence-operations, Note 2). `3 * (1, 2)` doesn't seem to work as the reverse operators don't seem to work at the moment(even after adding \_\_rmul\_\_ method).
> Add tuple.__mul__

- .gitignore
- vm/src/vm.rs
For operators that can don't have a reverse method, passing in default method as the fourth parameter.
> Use call_or_unsupported for operators.

- Cargo.lock
- Cargo.toml
- src/main.rs
Awesome talk at FOSDEM! This is my first rust PR so please let me know what could be improved.
I've used the [xdg crate](https://docs.rs/xdg/2.2.0/xdg/struct.BaseDirectories.html) to find the appropriate place to save the readline history file. I'm not sure if we care about Window support here?
Also, it seems that crate does not accept a Path struct but only a string, so I had to unwrap it into a string. Seems like that should be added to xdg at some point.
> Use XDG paths to store Python history

- vm/src/exceptions.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/os.rs
Prefer runtime errors over panic in some common situations for file IO
```
>>>>> open('missing.txt')
File <unknown>, line 0, in <module>
FileNotFoundError: No such file or directory: missing.txt
>>>>> f = open('no-write.txt', 'w')
File <unknown>, line 1, in <module>
PermissionError: Permission denied: no-write.txt
```
Commit Summary
- Raise common errors on file open
- Add FileNotFoundError
- Add PermissionError
- Minor idomatic clean ups
> Better error handling for file io

- vm/src/exceptions.rs
Reordered the Exception Zoo wherever possible.  In the case of the definitions, there is some dependence on their order of initialization, because of sub-classing.  In this case, I sorted first by location in the dependency hierarchy, and secondly by their alphabetic position.
I don't believe this change is easily testable (or needs it beyond, compilation), however please let me know if I can add any useful tests.
> Alphebetize exception related code

- tests/snippets/basic_types.py
- tests/snippets/bools.py
- vm/src/obj/objint.rs
The new method, `int.conjugate()`, just returns a clone of the `int`.
However, this method is _also_ used by the `bool` type and in that case returning a clone doesn't match CPython.
CPython does:
```Python
>>> type(True.conjugate())
<class 'int'>
```
A couple options (open to others!):
- Implement `bool.conjugate()` independently
- Cast the return type to `int` in `int.conjugate()`
Happy to implement that to, but would love some feedback.
> Add .conjugate() method to int type

- vm/src/obj/objsequence.rs
Also an out of bounds index now raises an IndexError rather than a ValueError
> Fix panic on out of bounds negative index (addresses #295)

- vm/src/compile.rs
I found these while reading through the source code and wondered whether they're necessary or not. As it turns out, they're not and we can safely remove them, reducing visual clutter and making the code easier to understand :)
> Remove unnecessary dereferences/references in compiler

- tests/snippets/index_overflow.py
- vm/src/obj/objsequence.rs
- vm/src/obj/objstr.rs
Fixes panics from #276 adding error handling and returning an error _"IndexError: cannot fit 'int' into an index-sized integer"_ similar to [the error from cpython](https://github.com/python/cpython/blob/master/Objects/abstract.c#L1336-L1338).
> Add error handling for objsequence and objstr index overflow (addresses #276)

- tests/snippets/strings.py
- vm/src/obj/objstr.rs
Hi!
I've found current `str.__len__` returns the number of bytes instead of the number of characters as follows.
```
$ python3
>>> len("あ")
1
$ cargo run
>>>>> len("あ")
3
```
I've changed `str.__len__`  and added a few tests to cover this case.
> Use the number of characters instead of bytes for str.__len__

- tests/snippets/import.py
- vm/src/builtins.rs
- vm/src/import.rs
```
> from math import unknown
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
File <unknown>, line 1, in <module>
ImportError: cannot import name 'unknown'
```
> raise ImportError in import list

- vm/src/builtins.rs
- vm/src/compile.rs
- vm/src/format.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/pystruct.rs
This replaces all the occurrences of the <collection>.len() == 0
with the <collection>.is_empty() and the occurrences of the
<collection>.len() > 0 with the !<collection>.is_empty()
Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
> Fixed the 'len_zero' clippy warnings

- vm/src/frame.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/ast.rs
- vm/src/vm.rs
This replaces all the occurrences of the Struct {field: _} with the Struct { .. }.
Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#unneeded_field_pattern
> Fixed the 'unneeded_field_pattern' clippy warnings

- vm/src/compile.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/ast.rs
- vm/src/stdlib/io.rs
This replaces all the occurrences of &<dynamic collection><T> with the &[T].
Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
> Fixed the 'ptr_arg' clippy warnings

- vm/src/obj/objbool.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objgenerator.rs
- vm/src/obj/objint.rs
- vm/src/obj/objiter.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objmemory.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objsuper.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
This replaces all the occurrences of the 'let ref var = another_var' with the 'let var = &another_var'
Relevant clippy warning: https://rust-lang.github.io/rust-clippy/master/index.html#toplevel_ref_arg
> Fixed the 'toplevel_ref_arg' clippy warning

- tests/snippets/math.py
- vm/src/stdlib/math.rs
Implemented float conversion for functions in `math` module
> Float Conversion for #211

- tests/snippets/basic_types.py
- vm/src/obj/objcomplex.rs
> repr() of complex numbers is compliant with cpython

- src/main.rs
Issue here was due to xdg struct being unix dependent.
Windows builds appear to now success after this change.
Closes #313 (and #349)
> Fixes build on Windows

- tests/snippets/bools.py
- tests/snippets/numbers.py
- tests/snippets/tuple.py
This PR removes all tests that deal with the `__doc__` as per [this comment](https://github.com/RustPython/RustPython/pull/327#issuecomment-461577440)
> tests: Removed tests for the __doc__

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
According to #352
I added tu methods to `floats` the `__truediv__` and `__mul__`. And also I change a little bit, and with this changes you can run the code below. But it's works really slow.
```python
#!/usr/bin/env python3
w = 50.0
h = 50.0
y = 0.0
while y < h:
x = 0.0
s = ''
while x < w:
Zr, Zi, Tr, Ti = 0.0, 0.0, 0.0, 0.0
Cr = 2*x/w - 1.5
Ci = 2*y/h - 1.0
i = 0
while i < 50 and Tr+Ti <= 4.0:
Zi = 2*Zr*Zi + Ci
Zr = Tr - Ti + Cr
Tr = Zr * Zr
Ti = Zi * Zi
i = i+1
if Tr+Ti <= 4.0:
s += '*'
else:
s += '.'
x = x+1
print(s)
y = y+1
```
> Add floats.{__truediv__, __mul__}

- tests/snippets/builtin_open.py
- tests/snippets/os_open.py
- vm/src/builtins.rs
Currently we panic if we pass a file path that does not exist to `open()`. This seems to be because we assume `os::os_open` doesn't fail and just blindly unwrap it.
I've added a few tests and I've made it bubble up the `ValueError` that `os::os_open` throws. I also removed the `HashSet` as this seemed redundant for only 4 elements.
> Improve test coverage of os.open/open

- tests/snippets/numbers.py
- vm/src/builtins.rs
- vm/src/obj/objint.rs
Implements `__ceil__`, `__floor__`, `__round__`, `__trunc__`, `__index__`, `__int__` for int
**TODO:** calling `round` with parameter should check if the value is convertible to `int` and fail otherwise:
x = 10
x.__round__("") # => 10
x.__round__("") # => 'str' object cannot be interpreted as an integer
> int type: rounding, index, trunc, int (#304)

- tests/snippets/builtin_range.py
- vm/src/obj/objrange.rs
> Implement range.count

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
Fix the comaring with non float types:
```
1.0 < 1
1.0 <= 1
1.0 > 1
1.0 >= 1
```
Rais 
```
TypeError: argument of type <class 'float'> is required for parameter 2 (other) (got: <class 'int'>)
```
> float.{__lt__, __le__, __ge__, __gt__} fix comparing with non float type

- tests/snippets/builtin_complex.py
- tests/snippets/object.py
- vm/src/frame.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objset.rs
- vm/src/obj/objtuple.rs
- vm/src/vm.rs
Fixes #419.
- Updated `VirtualMachine::call_or_unsupported` to fallback on a returned `NotImplemented` value, rather than catching `NotImplementedError`.
- Updated `objint` and `objfloat` binary ops to return `NotImplemented` instead of raising `NotImplementedError` or raising `ValueError` directly.
- Factored out `ValueError` construction from `VirtualMachine::call_or_unsupported` as the TODO suggested.
- Use `call_or_unsupported` on eq/ne operations
> Use NotImplemented in binary operations

- src/main.rs
- vm/src/format.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objmap.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- wasm/lib/src/lib.rs
This PR fixed the last batch of the simple clippy warnings.
The remaining warnings deal with the basic types representation and API, which potentially introduces breaking changes, therefore they will be dealt with in the separate PRs
> Fixed several clippy warnings

- tests/snippets/ints.py
- vm/src/obj/objint.rs
Int to float comparisons (where int is left operand) currently raise `TypeError`.
```
>>>>> 1 > 1.0
TypeError: argument of type <class 'int'> is required for parameter 2 (other) (got: <class 'float'>)
```
This updates int comparison methods to return `NotImplemented` for non-ints.
> Fix int to float comparison

- tests/snippets/builtin_callable.py
- tests/snippets/weakrefs.py
- vm/src/builtins.rs
Unfortunately, due to object model, it's a far cry from CPython's oneliner `return x->ob_type->tp_call != NULL;` :(
> Fix callable(), add tests.

- parser/src/ast.rs
- parser/src/lexer.rs
- parser/src/parser.rs
- parser/src/python.lalrpop
- parser/src/token.rs
- tests/snippets/fstrings.py
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/frame.rs
- vm/src/stdlib/ast.rs
This adds initial support for f-strings. String interpolation is tricky because it is essentially embedding a mini-language inside of the main one, with its own set of rules. There are two approaches to dealing with this that I know of: modal lexers and invoking the parser recursively. I tried both, and the latter worked out a lot better (although not without some weirdness).
Things that work:
- f-strings inside f-strings
- sets inside f-strings
- escaping with {{ and }}
- graceful handling of syntax errors inside f-string (thanks to the undocumented but extremely useful lalrpop fallible rules feature, i.e. `=>?`)
Things missing:
- format specs (e.g. `f"{1/3:.2}"`)
- reporting the specific syntax error (#464 should help with this)
- probably more that I didn't think of
> Initial support for f-strings (i.e. strings with interpolated expressions)

- parser/src/parser.rs
- tests/snippets/fstrings.py
- Fixes edge case where nested fstring contained escaped unmatched parenthesis
- Avoids generating empty string ast nodes
- Several more tests
> Fix f-string edge case and add more tests

- tests/snippets/floats.py
- tests/snippets/ints.py
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- Implements the above four r-methods for ints and floats
- Removes support for floats from int methods to match cpython, now that they can fallback to the r-methods
- Fixes a few cases where type errors were raised instead of returning `NotImplemented`
> Add {int,float}.{__radd__,__rsub__,__rmul__,__rtruediv__}

- tests/snippets/set.py
- vm/src/obj/objset.rs
Currently when we do `set([[]])` we will panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RefCell { value: [PyObj instance] }', src/libcore/result.rs:1009:5
```
Now we will raise;
```py
TypeError: unhashable type
```
> set raises TypeError when unhashable element is passed in creation

- vm/src/macros.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objenumerate.rs
- vm/src/obj/objfilter.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objmap.rs
- vm/src/obj/objmemory.rs
- vm/src/obj/objnone.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objsuper.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objzip.rs
This basically unrolls the typechecking loop, moving type checks to assignment time, and moving argument count check to a single check at the beginning of the function. Expected number of args can be deduced by macro magic.
Advantages:
- avoids allocating a vector of expected_args on every function call
- doesn't repeatedly check for argument count
- optimizer-friendly (arguments without type requirements can have the type check branches completely removed)
- functions with 1-2 args generate less code (I checked that the binary size reduced).
- arguably more readable
Disadvantages:
- can generate more code for functions with a lot of args. (this can probably be reduced more by moving the error creation block to a separate function)
Let me know if I missed anything.
> Refactor arg_check macro

- tests/snippets/division_of_big_ints.py
- vm/src/builtins.rs
- vm/src/obj/objint.rs
- vm/src/obj/objstr.rs
- wasm/lib/src/wasm_builtins.rs
Fixes #459.
Also I changed the `objstr::get_value_as_ref` function to `objstr::borrow_value`. I think it is a better name for a function extracting ref to the inner value.
> big Integers division

- tests/snippets/builtin_divmod.py
- tests/snippets/builtin_format.py
- tests/snippets/builtin_hex.py
- tests/snippets/builtin_max.py
- tests/snippets/builtin_min.py
- tests/snippets/builtin_open.py
- tests/snippets/builtin_ord.py
- tests/snippets/builtin_range.py
- tests/snippets/builtin_slice.py
- tests/snippets/division_by_zero.py
- tests/snippets/division_of_big_ints.py
- tests/snippets/floats.py
- tests/snippets/func_defaults.py
- tests/snippets/list.py
- tests/snippets/membership.py
- tests/snippets/printing.py
- tests/snippets/set.py
- tests/snippets/stdlib_os.py
- tests/snippets/test_bitwise.py
- tests/snippets/testutils.py
- Move `assert_raises` to testutils
- Add optional message argument, with reasonable default
- Reverse order of expr and exception type for readability
- Lambda argument no longer takes parameter
- Convert applicable snippets to use `assert_raises`
> Reuse and improve ergonomics of assert_raises utility

- tests/snippets/control_flow.py
- vm/src/compile.rs
- vm/src/frame.rs
Fixes #498.
A few different issues were at play here:
1. When a block was popped, values from its execution were left on the stack. The value stack is now truncated to the level it was at prior to entering the block.
2. The for-loop iterator was being pushed to the value stack _before_ entering the loop block.
3. Breaking from loops was actually popping the block twice, first in the `Break` instruction, and then in the `PopBlock` instruction it jumped to. This probably went unnoticed because the `PopBlock` instruction didn't consider it an error when the block stack was empty, so things still worked for top-level loops.
> Fix infinite loop when breaking from nested for loop

- tests/snippets/control_flow.py
- vm/src/frame.rs
Fixes #490 
This one was pretty simple. `unwind_loop` popped the block stack until and _including_ the loop block. This is what `break` wants but not `continue`.  It now stops short of the loop block, and the `Break` instruction pops it explicitly.
> Fix continue statement

- tests/snippets/bytearray.py
- vm/src/obj/objbytearray.rs
Fix the issue:
```
>>>>> a = bytearray([400])
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
```
Python:
```
>>> a = bytearray([400])
ValueError: byte must be in range(0, 256)
```
> Add checking if value more then 255 in bytearraya

- parser/src/ast.rs
- vm/src/compile.rs
- vm/src/error.rs
- Match cpython error messages for invalid assign and delete statements, rather than printing the `Debug` representation of the target node
- Replace redundant `SyntaxErr` variant with `InvalidBreak` and `InvalidContinue`
> Compile error message cleanup

- tests/snippets/ints.py
- vm/src/obj/objint.rs
This PR adds a behavior that apparently exists in Python3
```
>>> a = 1
>>> a.imag
0
>>> a.real
1
>>> 
```
> Added real/imag attributes to int type.

- tests/snippets/testutils.py
Changed syntax in testutils.py that is introduced in 3.6 to a backwards compatible version
> Backwards compitability for python 3.5 to run tests.

- src/main.rs
- vm/src/stdlib/os.rs
This PR hides the file io behind `cfg` attributes so that RustPython can compile to a `std` without file descriptors.
> Allow compiling VM for wasm32-unknown-unknown

- wasm/demo/src/main.js
- wasm/lib/src/lib.rs
Also, the demo checks if the error it catches is a WASM `RuntimeError` and displays the correct error nicely.
> [WASM] Make panic errors available from JS

- tests/snippets/stdlib_socket.py
- vm/src/pyobject.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/socket.rs
This is an initial work on an implementation of a socket module. I wanted to get some first input on my design.
You can try the code by opening a server with `nc` for example `nc -l 127.0.0.1 -p 8080` and doing the following:
```py
>>>>> import socket
>>>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>>>> s.connect("127.0.0.1:8080")
>>>>> s.send(b'aaaa')
>>>>> s.close()
```
What I wanted is to use the [`std::net`](https://doc.rust-lang.org/std/net/index.html) high level socket handlers. By saving the initial socket creation flags I can choose the correct connection object at each function.
> socket module

- wasm/demo/src/index.ejs
Right now, on https://rustpython.github.io/demo, all of the `option`s have the `selected` attribute, so it goes with the last one, `mandelbrot`, which takes a long time to run and freezes the page. I'd recommend merging this to `release` so that that issue gets fixed in "production" ASAP.
Edit: it actually does run `fibonacci` first, but shows `mandelbrot` as selected, since the default snippet in the textarea is separate from the `select`, but it's still an issue.
> [WASM] Fix snippet selector's default selection

- vm/src/obj/objbool.rs
- vm/src/obj/objint.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objstr.rs
- vm/src/pyobject.rs
First off, this is _far_ from being complete, but I wanted to share it early to see if this is a direction we actually want to go in before continuing.
The idea is to apply the ["extractor pattern"](https://actix.rs/#extractors) used by Rust web frameworks such as actix to native/rust python functions, so that the function signature determines things such as type checking, conversions to and from python objects, etc.
For example, a function that adds two ints would currently look like this:
```rus
fn add(vm: &mut VirtualMachine, args: PyFuncArgs) -> PyResult {
arg_check!(
vm,
args,
required = [(a, Some(vm.ctx.int_type())), (b, Some(vm.ctx.int_type())]
);
Ok(vm.ctx.new_int(get_value(a) + get_value(a)))
}
```
This isn't _bad_, but it's a lot for such a simple function, and for more complex …
> Use "extractor" pattern for native functions

- Cargo.lock
- wasm/lib/Cargo.toml
It was removed from `lib.rs` in #532, I just forgot to remove it from the manifest.
> Remove the console_error_panic_hook crate from Cargo.toml

- vm/src/pyobject.rs
Sort of what I was talking about in #535 and #536, just not as drastic of a change. This would allow outside crates to store whatever data they'd like in a PyObject, e.g. a `js_sys::Promise` as I talked about in the issue, or if someone was embedding RustPython in their program they could wrap their structs using this.
> Add AnyRustValue payload variant

- wasm/demo/snippets/mandelbrot.py
- wasm/lib/src/browser_module.rs
I also modified `mandelbrot.py` to use request_animation_frame as I discussed in [#528](https://github.com/RustPython/RustPython/pull/528#issuecomment-466670440).
> [WASM] Add requestAnimationFrame to browser module

- vm/src/stdlib/io.rs
Fixes #557.
I wanted to test it somehow, but I am not sure how and whether I really should. Other modules are not tested for being imported once, and this one needs opening (ie. creating) a file (which is not portable to wasm, and litters user’s filesystem).
> fix io module being initialized multiple times

- tests/snippets/list.py
- vm/src/builtins.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objsequence.rs
Covers the basic feature set:
- `key` argument
- `reverse` argument
- does work with only `__lt__` defined
- checks for attempts of list modification in the same way that CPython does
Algorithm: quicksort. Can be replaced with something better in the future.
Didn't do:
- handling comparator doing weird stuff, not-total order
- strict type checks for arguments and key_func return type (CPython does them)
- probably some other obscure behavior compatibility
> Add list.sort, sorted()

- tests/snippets/ints.py
- vm/src/obj/objint.rs
fix for https://github.com/RustPython/RustPython/issues/556
> add overflow errors for int shifts.

- parser/src/fstring.rs
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/lib.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objgenerator.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/socket.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/lib.rs
I'm planning on working on more, but there are some that I'm not sure about:
```
warning: large size difference between variants
--> vm/src/pyobject.rs:1251:5
|
1251 | /     Frame {
1252 | |         frame: Frame,
1253 | |     },
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
help: consider boxing the large fields to reduce the total size of the enum
|
1252 |         frame: Box<Frame>,
|                ^^^^^^^^^^
```
There are a few of ^these, and I don't know what the tradeoff would be between size/box performance. I'll probably do it, it'll just take a lot of refactoring.
```
warning: the function has a cyclomatic complexity of 33
--> vm/src/compile.rs:150:5
|
150 | /     fn compile_statement(&mut self, …
```
> Fix a bunch of clippy lints

- src/main.rs
- vm/src/builtins.rs
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/eval.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/lib.rs
- vm/src/obj/objframe.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
- wasm/lib/src/vm_class.rs
It's a refactor that got big!
I set out to remove the Scope variant because it's not a python object type (you can never get a python object for a scope). Along the way I cleared up naming quite a bit, deleted the StoreLocals instruction, and got rid of a bunch of code.
> Remove Scope variant from PyObject.

- vm/src/builtins.rs
- vm/src/macros.rs
- vm/src/obj/objsuper.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
Also moves the real versions to the vm. 
This is a followup PR to #554 that resolves post-merge review comments
> Only use real isinstance/issubclass for built-ins

- vm/src/function.rs
- vm/src/pyobject.rs
Some examples:
```
Welcome to the magnificent Rust Python 0.0.1 interpreter
>>>>> str.endswith()
TypeError: Expected at least 2 arguments (0 given)
>>>>> '1234'.endswith(4)
TypeError: Expected type <class 'str'>, not <class 'int'>
>>>>> '1234'.endswith('4', 0, 4, 'extra')
TypeError: Expected at most 4 arguments (5 given)
```
> Improve error messages and add docs for new native function machinery

- tests/snippets/test_exec.py
- vm/src/builtins.rs
- vm/src/frame.rs
- vm/src/macros.rs
- vm/src/vm.rs
One case I couldn't handle is that the following is valid in CPython.
```
>>>>> exec("print(x)", None, {'x': 2})
TypeError: argument of type <class 'dict'> is required for parameter 2 (globals) (got: <class 'NoneType'>)
```
```arg_check!``` needs to allow None and treat it as if the optional argument wasn't passed. I don't know what other builtins have this behaviour.
> Proper construction of scope for exec/eval.

- Cargo.lock
- Cargo.toml
- wasm/lib/Cargo.toml
In #602, I meant to change the version of `/wasm/lib/Cargo.toml` but I changed `/Cargo.toml`. This PR fixes that.
> Fix Cargo.toml versions

- tests/snippets/bools.py
- vm/src/frame.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objnone.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- vm/src/vm.rs
This cleans up all of the attempts to identify None based on its payload.
I went through a few iterations here:
1. PyUnit - wasn't what I wanted. Py* is for converting the payload to/from rust, and you never want to do this when there isn't a payload.
2. AnyRustValue { value: Box::new(()) } - seems silly to box up unit. (I guess eventually PyObjectPayload becomes simply ```Option<Box<dyn std::any::Any>>```?)
3. NoPayload - could be called None but we already had bugs due to payload None and python None being different it seems better to be explicit.
> Unit payload

- vm/src/obj/objstr.rs
- vm/src/pyobject.rs
- Renamed to `OptionalArg`, the more I looked at it, the more the name `OptArg` bothered me
- No longer is a wrapper around `Option`, but its own enum. Trying to make it act like an `Option` via `Deref` just led to unintuitive errors.
- Helper to convert to `Option` for obvious reasons
(side note: the reason we don't just use `Option<T>` here is because it will later serve as a value that may be (python) `None`)
> Improvements to OptionalArg extractor

- tests/snippets/types_snippet.py
- vm/src/obj/objfunction.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
Fixes #583
Moves the \_\_class\_\_ property to object, so lookup of it works properly, this matches CPython. Also to make lookup work the property has to have a \_\_set\_\_ method, at this point it always raises an exception.
> Fix __class__

- vm/src/pyobject.rs
Since `PyObjectPayload2` is required to be `Debug`, might as well use that impl for `<PyObjectPayload as Debug>::fmt()`.
> Have AnyRustValue actually format with its own Debug impl

- vm/src/obj/objdict.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
Move attribute dict out to PyObject. This doesn't give us anything yet, but is necessary for subclasses of basic types.
> Py object dict

- tests/snippets/stdlib_socket.py
- vm/src/builtins.rs
- vm/src/stdlib/socket.rs
Change many socket errors to OSError with indicative error message. For example:
```py
>>>>> import socket
>>>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>>>> s.connect(("127.0.0.1", 1))
OSError: Connection refused (os error 111)
```
> Socket OSError

- tests/snippets/builtin_open.py
- vm/src/stdlib/io.rs
This allows the following:
```python
with open('README.md') as fp:
fp.read()
```
This does not close the file, as there's no close method yet. See #547 .
Fixes #648
> Make IOBase a context manager

- vm/src/frame.rs
- vm/src/obj/mod.rs
- vm/src/obj/objbuiltinfunc.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objgenerator.rs
- vm/src/obj/objiter.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objset.rs
- vm/src/obj/objtuple.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
Based on #642 to avoid conflicts.
This is far from ideal because there should actually be a distinct iterator type for each iterable, and the obvious name conflicts with the `PyIterator` extractor. I'm punting on these issues for now, and will straighten things up once the payload conversion is done.
> Convert iterator to Any payload

- tests/snippets/class.py
- tests/snippets/property.py
- vm/src/function.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
Followup to #619, migrates property to the newer style and unify property like objects by:
* making data descriptors an actual property, removing the need for an extra class. 
* making any property created from rust, which only has a getter(any use of vm.new_property) a readonly property. This means they can be overridden by the instance dict, hopefully leading to more consistent behavior.
* changes member descriptors to be properties
> Unify property like objects

- src/main.rs
- tests/snippets/test_exec.py
- vm/src/builtins.rs
- vm/src/eval.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/macros.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objmodule.rs
- vm/src/pyobject.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/weakref.rs
- vm/src/vm.rs
- wasm/lib/src/vm_class.rs
Restructure Scope (again) so I can separate globals and locals properly. Scope now has a narrow interface so we can make further changes more easily.
I can now enable the broken tests in test_exec.
There's also the beginnings of a new AttributeProtocol that I plan on merging with the existing one.
> Scope globals locals

- vm/src/obj/mod.rs
- vm/src/obj/objweakref.rs
- vm/src/pyobject.rs
- vm/src/stdlib/re.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/weakref.rs
Promote weakref to be a core type by moving it out of its stdlib module and into the obj module. This is required to implement weakref callbacks, which I will redo in a followup PR. This was originally implemented as part of the outdated #488 PR.
Also, I have migrated the weakref type to use the 'any' payload and new style functions.
I built this on top of #635, so I could use PyRef::new_with_type.
> Move weakref object type to obj module

- vm/src/builtins.rs
- vm/src/obj/objenumerate.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objslice.rs
- vm/src/obj/objtuple.rs
- vm/src/vm.rs
Things still to do: currently constructing a new PyInt from a BigInt clone()s it, which causes unnecessary allocations.
>  Convert most objint functions to new args style

- vm/src/obj/objdict.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/types.rs
Further moves towards using PyClassRef for types more broadly.
It's bringing in more use of the FromPyObjectRef trait that we want to drop, but they I think they should all start to go away in the next phase.
One thing (I think) we're missing is ```PyTuple<PyClassRef>``` so we can handle conversion of PyClassRef inside other structures.
> Pyclassref protocols

- Cargo.toml
This makes the release build noticeably faster (~50% faster on random microbenchmarks) while increasing the binary size slightly (less than 10% on x86).
It's a question to wasm guys on whether it's acceptable (as AFAIK this option was added specifically for wasm). If not, a per-target config would be needed.
> Use default opt-level for release builds.

- vm/src/exceptions.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
Also drops Default for PyObject.
> Remove Option from PyObject.typ; Refactor type hierarchy initialization.

- vm/src/obj/objproperty.rs
- vm/src/pyobject.rs
This removes the requirement that properties need to be symmetric.
As discussed in #665, it's useful for properties to be asymmetric, to provide more appropriate error messages and the ability for 'get' to return a value but 'set' to take a reference.
> Remove type parameter from PropertyBuilder

- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
They weren't necessary at all, I don't know why I added them.
> Remove the `Rc`s around the WASM global HashMaps

- vm/src/frame.rs
- wasm/demo/src/main.js
- wasm/lib/src/vm_class.rs
Eventually we should use [`sys.displayhook`](https://docs.python.org/3/library/sys.html#sys.displayhook), but this is fine for now.
> Use compile::Mode::Single for the demo terminal

- vm/src/frame.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objweakref.rs
- vm/src/pyobject.rs
Various refactors to avoid direct use of PyObject and put things through the into_ref interface.
> Prefer pyvalue into ref

- .gitignore
- Cargo.lock
- Cargo.toml
- derive/Cargo.toml
- derive/src/lib.rs
- vm/Cargo.toml
- vm/src/builtins.rs
- vm/src/function.rs
- vm/src/lib.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objstr.rs
Based on #693 to avoid merge conflict.
I decided to convert this because it hits a lot of edge cases and thus helps to validate the model of the new args style.
In addition to converting to the new style, this also fixes a couple bugs:
- `Args` was swallowing the first keyword argument after it finished slurping the remaining positional args.
- `print` was accepting arbitrary / unknown keyword arguments, they are now rejected 
Note:
`KwArgs` is _only_ for functions that accept arbitrary keyword arguments, (i.e. `**kwargs` in python). For functions that accept _specific_ named arguments, a rust struct with an appropriate `FromArgs` implementation must be created. ~~This means some boilerplate right now, but is still cleaner / less error-prone than doing it in the function itself, and will …
> Convert print() builtin to new args style

- vm/src/builtins.rs
- vm/src/exceptions.rs
- vm/src/frame.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
Refactor into new style declarations.
Now contains changes to vm.to_str and vm.to_repr to make them return PyStringRefs too.
> Objdict refactor

- tests/snippets/attr.py
- tests/snippets/property.py
- tests/snippets/testutils.py
- vm/src/builtins.rs
- vm/src/frame.rs
- vm/src/obj/objmodule.rs
- vm/src/obj/objnone.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objproperty.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
Fixes the following:
- setattr() now calls \_\_setattr\_\_ and implemented object.\_\_setattr\_\_
- Fix \_\_getattr\_\_ getting called with the class instead of the instance
- Fix hasattr catching non-AttributeError exceptions
- Added default paramter to getattr
- object() had a dict
- property not returning itself for class bindings
> Various fixes for getattr/setattr/hasattr

- tests/snippets/class.py
- vm/src/builtins.rs
- vm/src/vm.rs
This is a basic implementation that I think should be good enough for ```__super__``` to work.
This should be passed through to the metaclass to allow some more advanced trickery, but I think this is good enough. There's a more optimal implementation than a whole dictionary just for this, which we can sort when we come to optimise local variables.
> Add __class__ cell to method scopes.

- parser/src/ast.rs
- parser/src/parser.rs
- parser/src/python.lalrpop
- src/main.rs
- vm/src/builtins.rs
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/function.rs
- vm/src/lib.rs
- vm/src/macros.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/re.rs
- vm/src/stdlib/types.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
The biggest change in this is that I changed the representation of varargs in the bytecode and AST from `Option<Option<_>>` to its own enum in commit ab53883. I sorta jury-rigged it into the lalrpop file because I'm not too familiar with how it functions, so feel free to give critique for that.
> Fix a bunch of clippy lints (again)

- vm/src/builtins.rs
- vm/src/exceptions.rs
- vm/src/frame.rs
- vm/src/obj/objstr.rs
- vm/src/pyobject.rs
- vm/src/stdlib/dis.rs
- vm/src/vm.rs
A stand-alone piece of my AttributeProtocol work.
I don't know if an equivalent of ```IntoPyObjectRef``` can be pieced together from the existing function machinery, but I couldn't see how.
> Introduce IntoPyStringRef to make vm.get_attribute more usable.

- vm/src/obj/objlist.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
Previously used the target's `Debug` impl which leads to surprising results.
(Also, to avoid implementing `Display` for `PyTuple` and `PyList`, I corrected the comparison methods on these to return `NotImplemented` instead of formatting and raising their own errors.)
> Fix the Display impl for PyRef

- vm/src/sysmodule.rs
- vm/src/vm.rs
This allows for VirtualMachine to be immutable. This is a first work into the direction that VirtualMachine is immutable.
This enables a few things:
- Store a virtualmachine reference into each python object (a sort of handle). This would reduce the amount of VirtualMachine passing around.
- Share the VirtualMachine accross threads in a memory safe way.
> Put RefCell around frames member of VirtualMachine.

- vm/src/builtins.rs
- vm/src/function.rs
- vm/src/obj/objnone.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objtype.rs
- vm/src/vm.rs
Introduce objtype::get_class_attr as the internal interface for access to attributes where we need to bypass the full attribute chain. Use this interface in place of the attribute protocol where this low level access is needed.
I'd like to eventually make these functions private, perhaps by moving call_method, etc to ```PyClassRef``` but I don't think we can do this yet.
> Class get attr 2

- vm/src/obj/objint.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- vm/src/vm.rs
This is the first in a series of PRs that prepare for the merging of `PyRef` and `PyObjectRef` (so that the latter is an alias for `PyRef<dyn PyObjectPayload>` and the payload type of a `PyRef` is statically guaranteed).
This removes the obsolete `FromPyObjectRef` trait and replaces it with a `downcast` method (that will eventually be moved to `PyRef` and have a very different implementation).
> Remove FromPyObjectRef, replace with downcast

- vm/src/stdlib/io.rs
- vm/src/stdlib/socket.rs
Moves to using `into_ref{,_with_type}` instead of `PyObject::new` since we are moving away from the latter (and its existence is blocking my `PyRef` work). Also changes from panicking to raising an `Overflow` error if `socket.socket` is called with an int that doesn't fit in an `i32` (via `TryFromObject`).
@palaviv I think you wrote most of `socket.rs`, could you review this?
> Some socket and io cleanups

- vm/src/function.rs
- vm/src/obj/objrange.rs
- renames `end` field of `PyRange` to `stop` to match python
- removes usages of deprecated `PyObject::new`
- cleans up convoluted range constructor by introducing a simple technique for function overloading
> Range cleanups

- vm/src/obj/objrange.rs
- vm/src/obj/objslice.rs
- vm/src/pyobject.rs
Note: I intentionally implemented `TryFromObject` only for an `Either` of two `PyRef`s rather than any two types than implement `TryFromObject`. This is because doing the latter would pointlessly allocate an error object whenever the argument was type `B`. By restricting this to `PyRef`s, we can just try to downcast, which is a lot cheaper. 
Example of the error messages this returns:
```
>>>>> range(10).__getitem__('')
TypeError: must be int or slice, not str
```
> Introduce Either extractor and convert range.__getitem__

- vm/src/frame.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objgenerator.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/dis.rs
- vm/src/stdlib/json.rs
- vm/src/stdlib/types.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
Following on from my previous PRs, this removes unnecessary uses of `PyObjectRef` in `type_new_class` function and in the areas around the code/frame object.
> Use specific PyRef where possible - code object/type_new_class

- vm/src/builtins.rs
- vm/src/function.rs
- vm/src/obj/objsuper.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
I was going to do `.on` for events, but I realized that it would require (a) a different class for every single possible Event subclass, or (b) a `PyJsValue` class with `__getattr__`, which I'm going to do but in a separate PR.
I also fixed that issue from before with importing the `json` module - `builtins.__import__` tried to get the current frame, and if there wasn't anything on the stack it just failed because `vm.current_frame()` used `frames[idx]` which panics instead of `.get(idx)` which returns a result in the case of an invalid index.
> [WASM] Add PyDocument and PyElement classes to browser

- tests/snippets/builtin_range.py
- vm/src/frame.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objenumerate.rs
- vm/src/obj/objint.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objsequence.rs
- Converts range to new args style
- Changes representation to hold `PyIntRef`s instead of `BigInt`s
- Removes a _lot_ of unnecessary cloning
- Introduces `as_bigint()` to `PyInt` and makes the latter's value field private
> Convert range to new args style

- vm/src/builtins.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/import.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objmodule.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/ast.rs
- vm/src/stdlib/json.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
Sorry, this is a bit of monster (especially as I had to change most of AST).
This is the controversial change I've been working towards:
After this:
* Instances (including modules) use real dictionaries for their attributes.
* Classes keep their attributes in a hidden PyAttributes.
We should create fewer dictionaries generally.
> Attributes and dictionaries

- vm/src/builtins.rs
- vm/src/exceptions.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/macros.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objint.rs
- vm/src/obj/objiter.rs
- vm/src/obj/objnone.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objset.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objsuper.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- vm/src/vm.rs
- wasm/lib/src/wasm_builtins.rs
- Rename to `class` to mirror python `__class__`
- Reduce to one variant
- Remove `objtype::get_type_name`
> Clean up type protocol

- Cargo.lock
- parser/Cargo.toml
- parser/build.rs
- parser/src/token.rs
Seems like removal of lalrpop-snap in the new version will improve build times a tiny little bit.
> Upgrade lalrpop

- derive/src/lib.rs
- tests/snippets/ints.py
- vm/src/builtins.rs
- vm/src/function.rs
- vm/src/obj/objint.rs
To achieve this I anhanced FromArgs derive proc macro to support positional arguments. Positional-only arguments have the #[positional] attribute in front of it's field and while keyword-only arguments have #[keyword] attribute in front of it's field.
> Use new style args for int.__new__

- tests/snippets/decorators.py
- vm/src/compile.rs
Previously, the defaults and decorator function was around the wrong way on the stack, so it tried to call the defaults as if they were the decorator.
> Fix decorator on functions with defaults

- tests/snippets/dict.py
- vm/src/builtins.rs
- vm/src/dictdatatype.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objsuper.rs
- vm/src/pyobject.rs
- vm/src/stdlib/json.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
- wasm/lib/src/convert.rs
Finally remove DictProtocol, and clean up a bunch of other dict things.
I've come to the conclusion that ```ItemProtocol``` on ```PyDictRef``` must do the same thing as the version on ```PyObjectRef```.
* It's way too surprising if ```dict.get_item``` and ```dict.as_object().get_item``` are different.
* I haven't found any cases where it's correct to bypass the overridden ```__getitem__```, so the only thing left is the performance boost where we know it's a base dictionary because we just created it. In that case it's clearer to call ```inner_getitem``` explicitly. (We should optimise attribute access first though.)
> Dict protocols

- vm/src/stdlib/os.rs
Currently I did not added tests. I want to move all the files tests to a system temp directory. I will need to add the following in order to do that:
- Add `os.getenv` to get windows `%TEMP%`
- Add `os.sep` for correct path building in windows and linux.
I will these two features and then add to `testutils` a context manager of temp folder and move the tests to use that folder.
> Add os.{mkdir, mkdirs, rmdir, listdir}

- vm/src/builtins.rs
- vm/src/exceptions.rs
This is required for importing of the warnings module, which is a dependency of unittest.
> Add builtin warning classes

- vm/src/function.rs
- vm/src/obj/objfloat.rs
This allows the first argument to a function to be a shared reference to a type implementing `PyValue` _as a special case_. This is useful because it allows calling python methods from rust without consuming or cloning the reference. Eventually, it would be ideal to support shared references in _any_ position, but that is significantly more complex to accomplish due to a combinatorial explosion of trait impls required.
> Allow first argument to be a shared ref to a python value

- tests/snippets/list.py
- vm/src/obj/objlist.rs
- vm/src/pyobject.rs
after working on #783 it felt wrong to leave `list.__setitem__` broken in that it could not do slice assignment.
ref #251
I tried to work off the [CPython list code](https://github.com/python/cpython/blob/master/Objects/listobject.c) for this and I think I assessed all the special cases. It was a bit hard to follow as it's all done with `memmove` in C.
I've added a large number of test snippets in hopes of covering all the use cases of list assignment and checking for correct behavior, but it would probably be a good idea for someone to double check my work on that.
I've tried to use fairly optimal modifications of the underlying `Vec` by relegating most of the work to `Vec.splice` except for stepped slices. I trust Rust's internals to be smarter than me.
stepped slices use a zipped iter …
> implement  list.__setitem__ with slice and int indexing

- derive/src/pyclass.rs
- vm/src/obj/objint.rs
I have come to the conclusion that it is impossible to write clean code for a macro implementation.
> Change #[pymethod(property)] to #[pyproperty]

- parser/src/lexer.rs
- tests/snippets/bytes.py
- vm/src/obj/mod.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objbytes.rs
It's the start to refactor bytes and  bytearray like #765 .
- only bytes for now (no bytearray) with new style method
- What to do with byteinner ? change the name ? remove a differet file and put everything in bytes.rs
- tests added
- I struggled with the iterator, I don't know if it can be send to byteinner.rs or not.
- the `__new__` method has been rewritten to deal with more cases, but it's quite horrible to read. interested in ideas to refactor this one. there are many possibilities with various error message so ...
- `b"éùà"` passes now but it shouldn't. I'm not sur where to fix it.
> refactor bytes

- vm/src/dictdatatype.rs
- vm/src/frame.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objmodule.rs
- vm/src/obj/objobject.rs
- vm/src/stdlib/json.rs
- wasm/lib/src/browser_module.rs
Simplify iteration of dictionaries from rust code.
> Implement IntoIterator for PyDictRef.

- tests/snippets/builtin_dir.py
- vm/src/obj/objdict.rs
- vm/src/obj/objobject.rs
On master:
```
>>>>> dir(lambda: 1)
["'str' object", ...
```
This was introduced when we got non-string dictionary keys. We now fail in a slightly different way than CPython but it's a an obscure enough edge case that I don't think it matters:
```
>>> a.__dict__[9] = 2
>>> dir(a)
TypeError: '<' not supported between instances of 'str' and 'int'
```
vs
```
>>>>> a.__dict__[9] = 2
>>>>> dir(a)
TypeError: Attribute is not a string: "9"
```
> Fix dir bug - not including object attributes correctly.

- Lib/_collections_abc.py
- Lib/os.py
- tests/snippets/stdlib_os.py
- vm/src/stdlib/mod.rs
- vm/src/stdlib/os.rs
I tried using only the low level calls (`getenv`, `setenv`, `putenv`) but python `os.getenv` read only from the `os.environ`.
I copied `_collection_abc.py` from Cpython and commented out the code that did not work yet.
In `os.py` I copied only the parts related to `_Environ` and commented out the unsupported code as well.
> Add os.environ

- tests/snippets/try_exceptions.py
- vm/src/exceptions.rs
- vm/src/frame.rs
You can now do:
```py
try:
raise ZeroDivisionError
except ZeroDivisionError as ex:
raise NameError from ex
```
and the output is:
```py
File tests/snippets/try_exceptions.py, line 131, in <module>
ZeroDivisionError: No msg
The above exception was the direct cause of the following exception:
File tests/snippets/try_exceptions.py, line 133, in <module>
NameError: No msg
```
> Add exception cause

- tests/snippets/bytes.py
- tests/snippets/strings.py
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objstr.rs
Add bytes.center
fix str.center
add some tests
introduce `is_byt`e to get value of a byte object : byte or byterray.
I'cant get out of a clone() in this function. maybe you have an idea ?
Should follow in another  PR : is_bytes_like : which basically would do the same thing, including memory view.
also added a get_value() to PyBytes as convenient way to deal with PyBytes Value in other function. Id'l like it be also added to byterray when refactoring it with PyByteInner.
> add capitalize bytes.center + fix str.center

- derive/src/pyclass.rs
Building from anything but the root crate currently fails with:
```
error[E0599]: no method named `expect` found for type `std::result::Result<std::vec::Vec<syn::attr::NestedMeta>, syn::attr::Meta>` in the current scope
--> derive/src/pyclass.rs:42:49
|
42 |                 let nesteds = meta_to_vec(meta).expect(
|                                                 ^^^^^^
|
= note: the method `expect` exists but the following trait bounds were not satisfied:
`syn::attr::Meta : std::fmt::Debug`
error[E0599]: no method named `expect` found for type `std::result::Result<std::vec::Vec<syn::attr::NestedMeta>, syn::attr::Meta>` in the current scope
--> derive/src/pyclass.rs:74:49
|
74 |                 let nesteds = meta_to_vec(meta).expect(
|                                                 ^^^^^^ …
```
> Fix sub-crate compilation

- vm/src/obj/objstr.rs
The existing implementation didn't actually title-case, it just naively capitalized the first letter of each word. Also note that this is _still_ not 100% on-par with cpython because it doesn't handle unicode titlecase characters, e.g. digraphs that consist of an uppercase and a lowercase letter. It looks like rust used to support this on nightly [but removed it because they couldn't add corresponding methods on strings without a `unicode-segmentation` dependency](https://github.com/rust-lang/rust/issues/26555). I'll see if I can extract that support into its own crate.
Also note that I added the tests as _rust_ unit tests; this is getting significantly less painful with recent refactors and I think we should do it more.
> str: improve {is,}title impl and add tests

- Lib/_collections_abc.py
- vm/src/builtins.rs
- vm/src/eval.rs
- vm/src/import.rs
- vm/src/obj/objclassmethod.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objobject.rs
- vm/src/pyobject.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/thread.rs
- vm/src/stdlib/types.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
Split from #824 as requested. These are the changes to RustPython itself to support importing and running unittest.
The changes are:
- Ability to do an absolute import of a non-top-level module. i.e. import unittest.case. This isn't implemented properly but is a hack to get importing of those to happen.
- Add function.__call__
- Add io.IOBase.flush
- Add skeleton _thread module
- Expose types.MethodType
- Add fake sys.intern and sys.warnoptions
- Make classmethod have a dict by default.
> RustPython changes for #824

- tests/snippets/try_exceptions.py
- vm/src/bytecode.rs
- vm/src/compile.rs
- vm/src/exceptions.rs
- vm/src/frame.rs
This PR add support for reraise:
```py
>>>>> try:
.....     raise NameError
..... except:
.....     raise
..... 
File <stdin>, line 4, in <module>
File <stdin>, line 2, in <module>
NameError: No msg
```
And exception context:
```py
>>>>> try:
.....     raise ZeroDivisionError
..... except ZeroDivisionError as ex:
.....     raise NameError
..... 
File <stdin>, line 2, in <module>
ZeroDivisionError: No msg
During handling of the above exception, another exception occurred:
File <stdin>, line 4, in <module>
NameError: No msg
```
> Exception reraise and context

- vm/src/macros.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objellipsis.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objslice.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/keyword.rs
- vm/src/stdlib/math.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/pystruct.rs
- vm/src/stdlib/random.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/time_module.rs
- vm/src/stdlib/tokenize.rs
- vm/src/sysmodule.rs
These changes make it possible to successfully call the exported macros from outside the `rustpython_vm` crate.
> Make macros comply fully with Rust 2018

- tests/snippets/stdlib_os.py
Should we add a `cfg` to not put `unsetenv` into `os` if on Windows?
> Fix os.unsetenv test for windows

- tests/snippets/import.py
- tests/snippets/import_mutual1.py
- tests/snippets/import_mutual2.py
- vm/src/import.rs
This fixes an infinite loop when importing mutual depending modules.
> Support mutual importing modules.

- derive/src/error.rs
- derive/src/lib.rs
- derive/src/pyclass.rs
I copied `error.rs` from wasm-bindgen because it seemed like a very
good system, and I think that the MIT license is all in place for that?
> Target rustpython_derive errors at specific source spans

- tests/snippets/stdlib_os.py
- vm/src/stdlib/os.rs
Currently support `name, path, is_dir, is_file`.
I will add `stat` and `symlink` support in separate PRs.
> Add os.scandir

- README.md
`cargo run tests/snippets/whats_left_to_implement.py` -> `./whats_left.sh`
> Fix README not to refer moved file

- tests/snippets/stdlib_os.py
- vm/src/stdlib/os.rs
This is only a limited part of `os.stat`. The windows implementation is missing `st_ino`, `st_dev` and `st_nlink` as they are not yet implemented in `std::os::windows::fs::MetadataExt`.
I have tested the results against Cpython on my machine but I am not sure how to test it in the CI. The windows code is not tested yet so I will let the CI test it.
> Add os.stat

- tests/snippets/strings.py
- vm/src/obj/objstr.rs
The bug is that the `"string".rpartition("not in")` should equal `('', '', 'string')` not `('string', '', '')`, which it was.
> Fix rpartition bug

- vm/src/stdlib/json.rs
Prevent crash from call to json.loads. Use `vm.get_attribute` to get the attribute `json.JSONDecodeError` instead of `get_item`.
> Fix json.loads

- Lib/os.py
- tests/snippets/stdlib_os.py
Add some missing contants:
- `os.curdir`
- `os.pardir`
- `os.extsep`
- `os.linesep`
- `os.altsep`
- `os.pathsep`
> Add constants to os module

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
Added `__rfloordiv__`, `__divmod__`, `__rdivmod__` and `__rpow__`
> PyFloat overflow handling + missing methods

- vm/src/import.rs
- wasm/lib/src/browser_module.rs
This is initial work on #659.
This allowed you to do:
```py
def f():
import test
print(test.func())
import browser
browser.load_module("test", "http://localhost:8080/test.py").then(f)
```
when test.py is:
```py
def func():
return "testing"
```
> Add browser.load_module

- tests/snippets/try_exceptions.py
- vm/src/frame.rs
This solution come to fix the following problem:
```py
def g():
try:
1/0
except ArithmeticError:
return 5
try:
g()
raise NameError
except NameError as ex:
assert ex.__context__ == None
```
When we exit an except with `return` or `yield` we need to pop the exception from the exception stack.
> Except block

- tests/not_impl_gen.py
This is so that in e.g. #358 , bool methods that are inherited from int aren't displayed. But methods that have are currently implemented as inherited from int, but should instead be reimplemented with special behavior, are displayed.
>  Include reimplemented methods in whats_left.sh, and skip inherited methods

- tests/snippets/bytearray.py
- tests/snippets/bytes.py
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objbytes.rs
- vm/src/stdlib/io.rs
This is a rewrite of bytearray with pybyteinner.
Everything is the same as in #847 , except :
- some refactoring for eq, gt, ge, le, lt and add to DRY
- adapt clear, pop and append (which where already here)
Actual issues : 
- I'm struggling with  get_value and get_value_mut. For now i'm just using a public `inner` and call directly `borrow` or `borrow_mut` (see changes in io.rs). I need some help on it.
- the return type of `append`...
> rewrite pybytearray with pybyteinner

- Lib/_collections_abc.py
The hack was introduced in #829, but is unnecessary since #905.
> Revert mappingproxy hack

- vm/src/stdlib/os.rs
Avoids warn when building on Windows.
> Define `os_unix_stat_inner` only when required

- Lib/posixpath.py
- tests/snippets/sysmod.py
- vm/src/sysmodule.rs
For #958.
Currently support:
- linux
- windows
- android
- macos
> Add sys.platform

- vm/src/exceptions.rs
- vm/src/function.rs
- vm/src/import.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objtuple.rs
- vm/src/stdlib/json.rs
- vm/src/stdlib/socket.rs
- vm/src/vm.rs
- wasm/lib/src/convert.rs
I didn't find any reason to have a shared `get_elements`, mostly since a direct check on `type in (tuple, list)` is done anyways before the call.
Removing the RefCell, the API now won't allow returning both a normal reference and a `Ref`, so if we want to keep this API then some larger change has to be made.
> Remove RefCell from tuple

- vm/src/function.rs
Addressing review comment from here https://github.com/RustPython/RustPython/pull/993
> Simplify PyFuncArgs get_kwarg/get_optional_kwarg with cloned()

- tests/snippets/frozen.py
- vm/src/frozen.rs
- vm/src/import.rs
- vm/src/lib.rs
- vm/src/vm.rs
As part of #958 we need to be able to import frozen modules. This is not the same as in Cpython as we do not compile the code and marshal it. I think that can wait for a later stage.
> Support frozen modules

- tests/snippets/strings.py
- vm/src/obj/objstr.rs
- Used `str::repeat` instead of manually building the result string
- Rewritten the int type check to return error at the beginning of the
method
- Replaced the `unwrap` calls with the single `unwrap_or`
> objstr: Refactored the 'mul' method

- Cargo.lock
- parser/Cargo.toml
- parser/src/ast.rs
- parser/src/lexer.rs
- tests/snippets/stdlib_marshal.py
- vm/Cargo.toml
- vm/src/bytecode.rs
- vm/src/pyobject.rs
- vm/src/stdlib/marshal.rs
- vm/src/stdlib/mod.rs
This adds the marshal module with support for `loads` and `dumps`.
No support for `load` and `dump` for now.
I just added Serde's `Serialize` and `Deserialize` to `bytecode::CodeObject` (and all the needed sub structs).
The marshal module just uses `bincode` to encode and decode the `CodeObject`.
> Add support for marshal with loads and dumps

- tests/snippets/stdlib_itertools.py
- vm/src/stdlib/itertools.rs
After https://github.com/RustPython/RustPython/pull/965.
After this branch, `Lib/reprlib.py` is importable, which leaves only `collections.namedtuple`  (Itself requiring lots of stuff) and we can use `Lib/functools.py` :)
> itertools islice

- vm/src/sysmodule.rs
The motivation for this is so that we could `export RUSTPYTHONPATH=${rustpython_checkout}/Lib` in our dev environments, and then not have to worry about having to do `PYTHONPATH=$PWD/Lib cargo run` or worrying about a permanently set PYTHONPATH with the RustPython `Lib` directory messing something up for python programs. If anyone has come up with a better way of managing this in their dev environment I'd be interested in hearing it.
> Check RUSTPYTHONPATH as well as PYTHONPATH env variables

- parser/src/ast.rs
- vm/src/builtins.rs
- vm/src/dictdatatype.rs
- vm/src/frame.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objint.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/pyhash.rs
- vm/src/pyobject.rs
- vm/src/stdlib/ast.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/socket.rs
- vm/src/symboltable.rs
- vm/src/vm.rs
`identity_conversion` warnings are false-positives https://github.com/rust-lang/rust-clippy/issues/4133, should disappear in 1.36. 
I'm not sure what to do with others, lots of them are for the `PyFloat` object methods which uses macros, so I'm not positive about `&self` -> `self` change suggested by the lint.
> Fix most of clippy warnings

- vm/src/obj/objmemory.rs
The memoryview skeleton did not correctly assign the "obj" attribute;
The "obj" attribute was assigned to the memoryview class and not the memryview object,
leading to a funny bug that can be reproduced as follows:
```python
m1 = memoryview(b'1234')
m2 = memoryview(b'abcd')
print(m1.obj)
```
the result would be the value inside `m2` instead that of `m1`
> Fix memoryview.obj misimplementation.

- tests/snippets/warnings.py
- vm/src/stdlib/mod.rs
- vm/src/stdlib/warnings.rs
This is just a the `_warnings` module and a `warn` method without implementation so I can continue with #958.
> Add _warnings

- vm/Cargo.toml
- vm/src/stdlib/mod.rs
It was causing a build error due to some `libc` functions that aren't available on android.
> Disable the pwd module on android

- tests/snippets/strings.py
- vm/src/format.rs
- vm/src/obj/objstr.rs
From: https://gitter.im/rustpython/Lobby?at=5cfa898ebf4cbd167c484cf0
As the Python docs, when a `{!r}` occur, it runs `__repr__` over the argument before applying the `:` rules. The current implementation of `{!a}` is not correct, as simple acts as `!r`.
> Feature: str.format accepting !r, !s and !a

- vm/src/builtins.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/obj/objiter.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/math.rs
- vm/src/vm.rs
1. Make raising `TypeError` from `get_method()` more explicit by splitting it into two methods: one that raises `TypeError` if there's no method, and one that's not (for some cases, like `__missing__` method for dict). 
2. If it's acceptable for method to be absent (`__missing__`, `__iter__` for iterators and others), do not raise `TypeError`. 
(note that if `__get__` descriptor raises an exception, it still gets propagates as before)
3. Make error messages more consistent with CPython. 
4. Add `exc_type` to `info!` exception logging.
> Cleanup get_method() error handling

- compiler/src/bytecode.rs
- compiler/src/compile.rs
- compiler/src/symboltable.rs
- parser/src/ast.rs
- parser/src/python.lalrpop
- vm/src/frame.rs
Currently when doing `from module import a,b,c,d,e` we would call `vm.import` one time for each symbol. This change the parser so we will call `vm.import` once for all symbols.
> Import all from_list in one call

- tests/snippets/strings.py
- vm/src/cformat.rs
- vm/src/format.rs
- vm/src/lib.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
This is a WIP on `str % tuple` formatting.
Currently on the parser itself is available for reviewing, I will be happy to take your comments and improve it.
Example usage:
```rust
let format_string = match CFormatString::from_str("Hello, My name is %s and I'm %d years old. My favorite hex number is %#08x") {
Ok(fmt) => fmt,
Err(_) => { panic!("got an error") }
};
println!("{:?}", format_string.format_parts);
```
will output:
```
[(0, Literal("Hello, My name is ")), (18, Spec(CFormatSpec { mapping_key: None, flags: (empty), min_field_width: None, precision: None, format_type: String(Str), format_char: 's' })), (20, Literal(" and I\'m ")), (29, Spec(CFormatSpec { mapping_key: None, flags: (empty), min_field_width: None, precision: None, format_type: Number(Decimal), format_char: 'd' })), …
```
> Printf-style formatting

- parser/Cargo.toml
- parser/src/lexer.rs
- tests/snippets/strings.py
support Unicode literal as same as CPython #1025 
- support Unicode literal `\x` with 2 digits
- support Unicode literal `\u` with 4 digits
- support Unicode literal `\U` with 8 digits
> support unicode literal

- compiler/src/bytecode.rs
- compiler/src/compile.rs
- derive/src/compile_bytecode.rs
- src/main.rs
- vm/src/builtins.rs
- vm/src/eval.rs
- vm/src/frame.rs
- vm/src/frozen.rs
- vm/src/import.rs
- vm/src/obj/objcode.rs
- vm/src/stdlib/imp.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/vm_class.rs
Reverts RustPython/RustPython#1037. See https://github.com/RustPython/RustPython/pull/1037#issuecomment-504101074
> Revert "Make CodeObject.source_path an Option<String>", just add a parameter to import_codeobj

- derive/src/compile_bytecode.rs
- derive/src/pyclass.rs
- vm/src/lib.rs
- vm/src/pyobject.rs
- vm/src/stdlib/mod.rs
- wasm/lib/src/browser.py
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/js_module.rs
- wasm/lib/src/lib.rs
- wasm/lib/src/vm_class.rs
- wasm/lib/src/wasm_builtins.rs
Attempt number 2, after #848. Here's the design for this implementation:
- `_js` module - contains the `JsValue` class which wraps a `wasm_bindgen::JsValue` and provides methods like `get_prop()`, `set_prop()`, and `typeof()`.
- `_window` - provides a single export, a `JsValue` wrapping `window`. Can be disabled by the JS code using `rustpython_wasm`.
- `browser` - a (eventually) Python frozen module that imports `window` from `_window` and uses it to provide all the functionality that the `browser` native module does now.
- (eventually) `jslib` - a frozen module that provides a JsProxy similar in functionality to the `JsValue` discussed in #808 among some other things (like a Promise wrapper).
Closes #808.
> [WASM] Add a JsValue class

- Lib/collections/__init__.py
- Lib/collections/abc.py
- Lib/difflib.py
- Lib/functools.py
- Lib/linecache.py
- Lib/warnings.py
- Lib/weakref.py
- vm/src/stdlib/weakref.rs
The big blocker for the next set of modules (`logging`, `traceback`)
requires `re`, so I think someone should try implementing that in full
(using CPython's `re.py`, preferably). I'll open an issue for that.
> Add CPython library modules needed for unittest

- tests/snippets/stdlib_io.py
- vm/src/stdlib/io.rs
The following changes are part of the efforts to enable `.pyc` files.
This change allow the following:
- Receive open fd descriptor as `name` parameter.
- Accept ByteArray as input to write.
- Ignore chars after first char in mode.
> Improve FileIO

- vm/src/stdlib/imp.rs
This PR and #1067 are the last things needed for supporting `.pyc` files. You can now change `sys.dont_write_bytecode` to false.
This improve the import time significantly. for example:
```py
import time
start = time.time()
import os
print(time.time() - start)
```
without `__pycahce__`: 0.272 [sec]
with `__pycache__`: 0.114 [sec]
*in release
> Add empty _imp._fix_co_filename

- tests/snippets/stdlib_os.py
Fix TestWithTempDir test that comapre `os.getcwd()` and `tmpdir`.
`os.getcwd()` returns the result of resolving the symbolic link. But `tmpdir`
absolute path. Testing fails on Mac because the `/tmp` directory is a symbolic
link. Comparing the results of resolving `tmpdir` will pass the test. But
RustPython does not implement `os.lstat`, so it does not pass, but in CPython The
test passes.
> Fix TestWithTempDir test to pass on Mac

- tests/snippets/ellipsis.py
- vm/src/builtins.rs
Currently, only "..." works for Ellipsis type.
This PR will fix the RustPython to work correctly on this code.
```python
a = Ellipsis
b = ...
a is b
```
> Add "Ellipsis" for Ellipsis

- tests/snippets/json_snippet.py
- tests/snippets/math_basics.py
- vm/src/py_serde.rs
Related to #1087.
Changes:
* serialize positive ints fitting inside `u64`,
* do not crash when ints do not fit in either `u64` or `i64`,
* let `Deserializer` accept non-string keys in maps – requirement for string keys is json-specific and json deserializer raises an error here anyway, in general both Python and deserializers might support non-string dict keys,
* uncomment old class inheritance tests for serialization,
* forward `&str` visitor to `string` visitor, since it needs an owned string anyway, no need to duplicate the logic,
* change `Visitor` impl functions order to match the one in the trait definition.
> improve (de)serialization: no crash on BigInts, non-string map keys

- vm/src/vm.rs
I actually passed the `locals` as `globals`. Fixed that and now I pass both.
> Fix locals and globals in call to __import__

- tests/snippets/ints.py
- vm/src/obj/objint.rs
Extracted `inner_mod` function and used in `int.__mod__` and `int.__rmod__`
and also added test snippets of `int.__mod__` and `int.__rmod__`.
> Implement int.__rmod__

- compiler/src/compile.rs
- tests/snippets/if_expressions.py
Otherwise provided test snippet fails with `Unsupported method __call__` because vm tries to make a `__call__`on the value returned from expression.
> Do not pollute stack when if-expression condition evaluated to False

- tests/snippets/exceptions.py
- tests/snippets/import.py
- vm/src/exceptions.rs
`importlib` sets those attributes in some places. 
```
cargo run -- -c "from collections import unknown"
```
for relevant failure on the current master.
> Add name, path, msg attributes to ImportError

- tests/not_impl_gen.py
I kept getting the following error:
```py
File "not_impl_gen.py", line 99, in <module>
output=open(f"snippets/whats_left_{name}.py", "w"),
File "not_impl_gen.py", line 77, in gen_modules
pkgutil.iter_modules(),
File "not_impl_gen.py", line 74, in <lambda>
if mod.name not in ("this", "antigravity")
File "/usr/lib/python3.6/turtle.py", line 107, in <module>
import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'
```
> Allow skipping of unknown modules in whats_left.sh

- vm/src/import.rs
- vm/src/vm.rs
Previously the traceback was:
```py
File "/tmp/a.py", line 3, in <module>
import b
File "_frozen_importlib", line 1093, in __import__
File "_frozen_importlib", line 1014, in _gcd_import
File "_frozen_importlib", line 991, in _find_and_load
File "_frozen_importlib", line 975, in _find_and_load_unlocked
File "_frozen_importlib", line 686, in _load_unlocked
File "_frozen_importlib", line 677, in _load_unlocked
File "_frozen_importlib", line 671, in _load_unlocked
File "_frozen_importlib_external", line 778, in exec_module
File "_frozen_importlib", line 219, in _call_with_frames_removed
File "/tmp/b.py", line 1, in <module>
1/0
ZeroDivisionError: 'integer division by zero'
```
Now it is:
```py
File "/tmp/a.py", line 3, in …
```
> Remove importlib frames from traceback

- compiler/src/error.rs
- parser/src/error.rs
- parser/src/lexer.rs
- src/main.rs
- wasm/lib/src/vm_class.rs
Before the message was:
```py
SyntaxError: 'Got unsupported token(s) at line 0'
```
And now it is:
```py
SyntaxError: 'Got unexpected token \t at line 4 column 25'
```
> Pass more information in user defined parse error

- bytecode/src/lib.rs
- compiler/src/lib.rs
- derive/src/lib.rs
- parser/src/lib.rs
- vm/src/lib.rs
I randomly came across [this crate](https://docs.rs/adapton/0.3.30/adapton/) on docs.rs, and I had no idea that you were able to put logos in rustdoc! I figured we should put our derpy logo there. :smiley:
> Add #![doc(html_logo_url = ...)] to crates

- tests/snippets/builtin_complex.py
- vm/src/obj/objcomplex.rs
Currently, hash(3.1-4.2j) or hash(3.1+4.2j) is crashed due to
overflow error on RustPython.
This patch will fix this issue.
> complex: Fix hash function to work correctly

- .gitignore
- Cargo.lock
- Cargo.toml
- DEVELOPMENT.md
- README.md
- src/main.rs
- vm/src/frame.rs
- vm/src/macros.rs
I added some documentation to `README.md`, but essentially it now by default outputs a `flamescope.json` file, which you can upload to https://speedscope.app to view profiling information in a *much* nicer viewer than the html that flame outputs. I authored the `flamescope` crate, so if there are any problems that come up I can quickly fix them.
[Here's](https://www.speedscope.app/#profileURL=https://gist.githubusercontent.com/coolreader18/4d601fb73b9382a5c217f3ce9efcf849/raw/9b98b5814c110cd32e90fb9c3e73f3a598a0c9da/flamescope.json) a demo of speedscope with a RustPython profiling output.
> Add an speedscope output format for profiling 

- Lib/collections/__init__.py
- Lib/collections/_defaultdict.py
- Lib/pprint.py
Ok, so I did it in Python because I encountered a ton of broken/fragile class machinery when I tried to do it in Rust: subclassing a built-in class but also being a `PyValue` itself weirdness, inconsistency with CPython in how `__new__` vs `__init__` works (it was calling `__new__` with arguments intended for `__init__`, and I still had to work around that in Python), and the final straw, `__missing__` not being detected from `dict.__getitem__`, while `__missing__` did work in Python. In any case `defaultdict` being a native class is mostly just an implementation detail, and there's really no reason why it can't be implemented in Python. We can look at all that at some point later, but we're *really* close to unittest and I'm focusing on that at the moment.
> Add defaultdict to collections; add pprint.py

- Lib/argparse.py
- Lib/collections/__init__.py
- Lib/gettext.py
- vm/src/sysmodule.rs
It turns out there actually wasn't actually a problem with relative
imports, it's just that when I was trying to import `unittest` I'd run
into an error with `sys.base_prefix`, and then once I monkey patch that
I ran it again, and something about the error in the middle of the
import process made me run into the `cannot import name 'result'` error.
Definitely an incompatibility, but more of an edge case than a really
critical issue.
The next native module after this for unittest is `signal`.
> Add argparse and gettext modules

- compiler/src/compile.rs
- compiler/src/symboltable.rs
- crawl_sourcecode.py
- parser/src/ast.rs
- parser/src/fstring.rs
- parser/src/parser.rs
- parser/src/python.lalrpop
- vm/src/stdlib/ast.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/symtable.rs
- Add location attribute to expression nodes in AST.
- Change symboltable to use flags for symbols.
This paves the way for more thorough checking of symbols, in order to emit the right bytecodes when accessing a symbol.
Also, the AST expression nodes now have proper line number information.
> Add location to expressions.

- .travis.yml
- tests/snippets/bools.py
- tests/snippets/builtins_module.py
- tests/snippets/delete.py
- tests/snippets/dismod.py
- tests/snippets/test_exec.py
- tests/snippets/try_exceptions.py
These tests focus on Python syntax errors and undefined names.
Also capitalize first words and brand names.
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
On the test selection, this PR does not focus on "_style violations_" (the majority of [flake8 error codes](https://lintlyci.github.io/Flake8Rules) that [__python/black__](https://github.com/python/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script …
> Travis CI: Lint Python code with flake8

- tests/snippets/stdlib_io.py
- vm/src/stdlib/io.rs
Seekable API is not yet implemented.
Apparently, this PR is not a perfect implementation of seekable but we can fill the rest of implementation in the future.
> stdlib.io: Implement seekable()

- Cargo.lock
- Cargo.toml
- derive/Cargo.toml
- derive/src/compile_bytecode.rs
- derive/src/lib.rs
- vm/Cargo.toml
- vm/src/frozen.rs
- vm/src/lib.rs
- wasm/lib/src/browser_module.rs
As discussed in #1142.
Adding the current `Lib` folder increase the executable by 5MB. I would like to add this to the demo so it will support python stdlib.
I wanted to allow specifying the location of the stdlib dir with a compilation flag but could not find out how to do that. @coolreader18 any suggestions?
> Allow stdlib freeze

- tests/snippets/tuple.py
- vm/src/pyobject.rs
Yeah, not all that big of an optimization, but it seemed dumb to be allocating a new `Rc` for something that's essentially empty.
> Add empty tuple optimization

- wasm/lib/Cargo.toml
As discussed in #1142. We did not reach a conclusion there if we should make this the default. I can remove the default if we will decide against this.
> freeze stdlib in WASM

- .travis.yml
[`cargo-sweep`](https://github.com/holmgr/cargo-sweep)
The `before_cache` lifetime script now runs this:
```
if command -v cargo; then
! command -v cargo-sweep && cargo install cargo-sweep
cargo sweep -i
cargo sweep -t 15
fi
```
It first checks that there is rust/cargo installed, as our flake8 script doesn't install the rust toolchain. It then installs cargo-sweep if it isn't already, and removes artifacts from old versions of the rust toolchain and those that are more than 15 days old (by mtime). I'm not sure if that's a good measurement, it might be better if it were longer or shorter.
> Use cargo-sweep to manage travis caches

- vm/src/dictdatatype.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objint.rs
- vm/src/obj/objsuper.rs
- vm/src/pyhash.rs
- vm/src/pyobject.rs
This add support for indexing the dictionary by string. So instead of creating a PyStringRef, we now can use rust's String type to index a dict.
> Implement dictionary indexing by trait.

- Lib/__importlib_util.py
- Lib/runpy.py
- src/main.rs
- vm/src/stdlib/re.rs
Now, if you just stick theses lines in `unittest/__main__.py`:
```py
sys.stdout = open("/dev/stdout", "w")
sys.stderr = open("/dev/stderr", "w")
```
then you're able to run `rustpython -m unittest --help` and get unittest's cli's usage!
>  Use runpy to run modules with -m

- compiler/src/compile.rs
I ran into this in `unittest/runner.py`, which has this code:
```py
(run, run != 1 and "s" or "", timeTaken)
```
It was duplicating the False from the `!=` expression but not popping it off the stack, so when BuildTuple was called it included that original False as the first element of the tuple.
> Fix compilation of nested boolean operations

- compiler/src/compile.rs
Reverts RustPython/RustPython#1225
> Revert "Fix compilation of nested boolean operations"

- tests/snippets/stdlib_os.py
In very rare situations this is not true - sometimes "older" PID can be reused.
> Remove assert os.getppid() < os.getpid()

- vm/src/obj/objstr.rs
suggested by @coolreader18 in #1262
> Simplify error formatting of str.__mod__ method.

- vm/src/stdlib/zlib.rs
Fixed deprecated syntax warning.
> fixed deprecated inclusive range syntax '...' to '..='

- benchmarks/test_benchmarks.py
Right now ```pytest``` does not show correct name/filename of the bench:
```
test_benchmarks.py::test_bench[args0-/usr/bin/python]
test_benchmarks.py::test_bench[args0-../target/release/rustpython]
test_benchmarks.py::test_bench[args1-/usr/bin/python]
test_benchmarks.py::test_bench[args1-../target/release/rustpython]
```
This PR:
```
test_benchmarks.py::test_bench[nbody.py-cpython]
test_benchmarks.py::test_bench[nbody.py-rustpython]
test_benchmarks.py::test_bench[mandelbrot.py-cpython]
test_benchmarks.py::test_bench[mandelbrot.py-rustpython]
```
> Add nicer test names for benchmarks

- src/main.rs
- vm/src/dictdatatype.rs
- vm/src/frame.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objstr.rs
- vm/src/py_serde.rs
- vm/src/pyobject.rs
- vm/src/scope.rs
- vm/src/stdlib/errno.rs
- vm/src/vm.rs
I finally got some idea that works in short circuiting the get_item_option for the case of strings. For example, this happens with the load_name opcode.
Idea is to short circuit the get_item logic and prevent several things from happening:
- Creation of the `KeyError`. Simply check for `None` or `Some`.
- Creation of a PyString when we lookup values by `str`.
> Increase performance for get_item_option.

- .travis.yml
- vm/src/stdlib/os.rs
- nix-rust/nix mentioned that this feature should be implemented
based on opendirectoryd. However, CPython implemented it based on getgroups(2)
for apple macOS.
So I ported the code from nix-rust/nix and it works well.
- Add apple macOS tests for travis CI.
ref0: https://github.com/nix-rust/nix/blob/500036a206188dc8f57bf95a7c61616db417038e/src/unistd.rs#L1320
ref1: https://github.com/python/cpython/blob/c4cacc8c5eab50db8da3140353596f38a01115ca/Modules/posixmodule.c#L6852
fix: #1295
> use getgroups(2) for apple macos.

- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- tests/snippets/try_exceptions.py
- vm/src/frame.rs
This implements finally execution when an exception is raised and when code returns in a try statement.
- The unwind blocks function is cleaned up.
Note that the design deviates from cpython. In CPython, the reason for entering the finally clause is remembered on the value stack. I chose to use the blockstack instead.
> Refactor block stack unwinding to enable finally execution.

- src/main.rs
- vm/src/frame.rs
- vm/src/import.rs
- vm/src/obj/objmodule.rs
- vm/src/stdlib/io.rs
- vm/src/vm.rs
This change decreases the time when importing a module which is already in `sys.modules`. If you will run the following script:
```py
import time
start = time.time()
import io
mid = time.time()
import io
end = time.time()
print(mid - start)
print(end - mid)
```
Before the change you will get:
```
0.0029745101928710938
0.00000667572021484375
```
After the change:
```
0.002993345260620117
0.000006198883056640625
```
```
```
> Delay from_list tuple create in import

- vm/src/scope.rs
I hoped this change will increase the speed a little by accessing the last element without iterating but
from checking the benchmarks this does not have an effect on the speed.
Before:
```
--------------------------------------------------------------------------------------------- benchmark: 4 tests ---------------------------------------------------------------------------------------------
Name (time in ms)                             Min                 Max                Mean             StdDev              Median                IQR            Outliers      OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Use LinkedList in scope locals

- vm/src/obj/objlist.rs
Clone other to prevent borrow error
when self iadd to itself from list
Fixes #1351
> Clone other to prevent borrow error

- compiler/src/symboltable.rs
- tests/snippets/global_nonlocal.py
If the scope depth is less than 2,
a syntax error occurs in nonlocal.
> nonlocal generate syntax error

- vm/Lib/_bootstrap_external.py
- vm/src/obj/objstr.rs
This mainly affects the module type repr on Windows, it would do something like `<module x from 'C:\\...\\RustPython\\Lib/importlib/__init__.py'>`. This fixes that and corrects it to `<module x from 'C:\\...\\RustPython\\Lib\\importlib\\__init__.py'>`, along with in general being more accurate code to what the CPython version was doing in a CPython-accurate environment.
> Fix importlib path separators

- tests/snippets/builtin_range.py
- vm/src/obj/objrange.rs
Fixed `get` function and `slice` function for range type
to prevent overflow problem, negative value problem
Fixes #1363
> Fixed calculation for range

- vm/src/builtins.rs
- vm/src/obj/objbool.rs
The purpose of the change is to differentiate between function that accept `Boolean` arguments (`True`, `False`) and function that accept "bool like" arguments that can be converted to bool by using `__bool__` or `__len__`. For example the builtin function `all` can get any "bool like" objects in its iterator for example `all([True,[1] ])` while doing `[1,2,3].sort(reverse=[1])` will result in a `TypeError`.
If anyone has a better suggestion then `PyBoolLike` for the struct name I would love that as I could not think of a better name...
> Add IntoPyBool

- .gitattributes
Right now, the language statistics for the repository say that it's ~75% Python, despite that being mostly the stdlib (which we didn't really write). This adds a git attribute to mark the `Lib` directory as ["vendored"](https://github.com/github/linguist#vendored-code), so it doesn't count towards the repository statistics.
> Fix Github language statistics to make this a Rust project again

- compiler/src/symboltable.rs
- tests/snippets/global_nonlocal.py
Fix Global symbol to prevent syntax error
when global declaration for same variable in function.
Fixes #1353
> Fix global declaration error in the function

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
Hi, I just noticed that the behavior of float.__repr __ is different between Python and RustPython. 
Python 3
```
>>> -0.0
-0.0
>>> float(-0.0)
-0.0
```
RustPython 
```
>>> -0.0
0.0
>>> float(-0.0)
0.0
```
On Python 3, __repr __ call on -0.0 returns -0.0, whereas on RustPython, it returns 0.0, without negative sign. I made a simple fix for that.
> Fix __repr__ return value for -0.0

- vm/src/obj/objfloat.rs
Ignore whitespace
```
>>>>> float('   -12345\n')
ValueError: could not convert string to float: '   -12345
'
```
```
>>>>> float('   -12345\n')
-12345.0
```
Fixed: #1391
> Fix the ValueError for whitespace in float()

- vm/src/sysmodule.rs
Check https://docs.python.org/3/library/sys.html#sys.implementation
> name is the implementation’s identifier, e.g. 'cpython'. The actual string is defined by the Python implementation, but it is guaranteed to be lower case.
> Change sys.implementation.name to only has lowercase

- tests/snippets/builtin_range.py
- vm/src/builtins.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objsequence.rs
* Adds several new tests to ```tests/snippets/builtin_range.py```
* Fixes 2 bugs in range slicing behavior
* Does some refactoring
This implementation is basically [0] and [1] combined and translated to Rust.  There might be a better way to do it, but I went with just copying the CPython algorithm for the time being, since the way negative steps are handled with slices is counter-intuitive and really tricky.
[0]  https://github.com/python/cpython/blob/530f506ac91338b55cf2be71b1cdf50cb077512f/Objects/rangeobject.c#L297-L334
[1] https://github.com/python/cpython/blob/bed4817d52d7b5a383b1b61269c1337b61acc493/Objects/sliceobject.c#L368-L511
See: https://github.com/RustPython/RustPython/issues/1373
> Fix range slicing behavior

- tests/snippets/ints.py
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objint.rs
- vm/src/stdlib/pystruct.rs
- wasm/lib/Cargo.toml
- wasm/lib/src/convert.rs
Change base type from u32 to i32
After result
```
>>>>> print(int(' 1 ', base=-1))
ValueError: int() base must be >= 2 and <= 36, or 0
```
Fixed: #1405
> Fix int type casting error with negative base value

- tests/snippets/exit.py
- vm/src/builtins.rs
- vm/src/exceptions.rs
After #1343, RustPython could not provide builtin exit() properly.
> Fix exit()

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
Copy the same pattern used by int()
closes #1421
> Allow float() to be called without an argument

- tests/snippets/builtin_format.py
- vm/src/format.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/ast.rs
- vm/src/stdlib/unicodedata.rs
- wasm/lib/src/browser_module.rs
Hi! This patch is an attempt to fix #1379 
References
* https://www.python.org/dev/peps/pep-3101/
* https://github.com/python/cpython/blob/v3.7.4/Python/formatter_unicode.c#L219-L225
> Enable Zero-padding with Format Strings

- tests/.gitignore
When execute `pytest` local, sometimes generate .cache folder to tests folder.
Add .cache/ to tests/.gitignore prevent wrong commit.
> Add .cache/ to tests/.gitignore

- parser/src/lexer.rs
- tests/snippets/ints.py
Generate syntaxError at integer starting with 0,
not zero
Fixes #1422
> Generate SyntaxError at integer starting with 0

- tests/snippets/ints.py
- vm/src/obj/objint.rs
Add new struct to fix int argument keyword error in `int.from_bytes` and `int.to_bytes`
Also Change ValueError to OverflowError like cPython
fixed: #1427
> Fix error in int.from_bytes and int.to_bytes

- tests/snippets/stdlib_os.py
- vm/src/stdlib/os.rs
Added several changes to achieve better compatibility with CPython [[doc](https://docs.python.org/3/library/os.html#os.scandir)]:
* Make ```path``` an optional arg, set ```"."``` default argument,
* Implement missing methods:
* context manager - ```__enter__```, ```__exit__```
* ```close```.
> os.scandir refinement

- derive/src/pyclass.rs
- vm/src/sysmodule.rs
- vm/src/version.rs
Return the version of Python that we attempt to be compatible with, not
the version numbers of the RustPython interpreter itself.
closes #1396
> Change sys.version* attributes to return the Python version

- Lib/_sre.py
- Lib/argparse.py
- Lib/re.py
- Lib/sre_compile.py
- Lib/sre_constants.py
- Lib/sre_parse.py
- Lib/textwrap.py
- vm/src/obj/objmappingproxy.rs
- vm/src/obj/objnamespace.rs
- vm/src/pyobject.rs
- vm/src/stdlib/array.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/re.rs
So it turns out that [`_sre.py`](https://github.com/nikhaldi/_sre.py) actually is fairly compatible with Python 3's `re`. The `re` and `sre_*` python modules are taken from Python 3.0, but I may be able to use the Python 3.6 ones, I haven't tried yet. I kept the Rust `re` module, but I renamed it to `regex_crate`; I'm not sure if that's a good name or what we should do with it in general.
> Add the _sre module

- tests/snippets/bools.py
- tests/snippets/floats.py
- tests/snippets/ints.py
- vm/src/obj/objbool.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
Reverts RustPython/RustPython#1444. Apparently `int(x=...)` [is a bug in and of itself](https://github.com/RustPython/RustPython/issues/1440#issuecomment-537757189) which was fixed in CPython 3.7.
> Revert "Fix argument keyword error in int/float/bool.__new__"

- Cargo.lock
- compiler/Cargo.toml
- compiler/src/compile.rs
For codes like `f(a=1, b=2, **c)`, emit less BuildMap bytecodes.
Before: LoadConst a, LoadConst 1, BuildMap 1, LoadConst b, LoadConst 2, BuildMap 1, LoadName c, BuildMapUnpack 3
After: LoadConst a, LoadConst 1, LoadConst b, LoadConst 2, BuildMap 2, LoadName c, BuildMapUnpack 2
> Optimize BuildMap bytecode emission

- tests/snippets/memoryview.py
- vm/src/obj/objmemory.rs
#1394
Hash value of memoryview should be hash value of the wrapped object.
```python3
hash(memoryview(b'abcdef')) == hash(b'abcdef')
```
And currently ```memoryview.__hash__()``` returns hash value of itself as below.
https://github.com/RustPython/RustPython/blob/162ff58f1667328da3777a33981c80d363f1df26/vm/src/obj/objobject.rs#L59-L61
So I made it to call ```__hash__()``` of ```obj_ref```.
> Fix #1394 Memoryview hash problem

- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- tests/snippets/function_args.py
- vm/src/frame.rs
This may look hacky but it exactly mirrors how CPython works. That `{**x, **y}` is not an error got tested by #932.
Fix #1419
> Raise TypeError for duplicate keyword arguments

- tests/snippets/sysmod.py
- vm/src/builtins.rs
- vm/src/exceptions.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
Partial solution of #1374
I made a small change to check recursion depth before push the frame and then raise error instead of run until segmentation fault occurs.
But it seems there is still a problem. RustPython occurs segmentation fault on 700 (debug) ~ 2600 (release) recursive calls while cpython is fine until 15000. This is the reason that I set default limit lower than cpython.
If there is any inappropriate changes, please let me know. Thank you.
> Add RecursionError

- tests/snippets/memoryview.py
- vm/src/obj/objmemory.rs
- vm/src/stdlib/mod.rs
#1003 
Now memoryview object can only be constructed from (memoryview|bytes|bytearray|array.array) and its subclasses.
Am I missing any bytes-like objects that should be able to construct memoryview?
> Fix #1003 Construct memoryview from bytes-like obejcts

- tests/snippets/ints.py
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objlist.rs
Add logic to check array.array byte like object
After apply this patch, We can handle array.array byte like object
Fixed: #1437
> Add logic to check array.array byte like object

- vm/src/vm.rs
closes #1416.
Changed only `vm.rs` file, and the other files were just auto-formatted with `cargo fmt`
> fix error message for __call__ for non-callable objects

- tests/snippets/global_nonlocal.py
- vm/src/builtins.rs
- vm/src/obj/objdict.rs
Return copy of locals so that local variables
does not change even if locals() values is changed
Fixes #1356
> locals() return copy of locals dictionary

- Cargo.lock
- parser/Cargo.toml
- parser/src/error.rs
This allows reporting the correct location for EOF error instead of the default.
> Update lalrpop to 0.17

- vm/src/exceptions.rs
- vm/src/lib.rs
This should allow me to .. show users errors.
I've left `print_exception` ignoring the error, as this is what `println!` does. I'd be happy for it to return the error.
> print_exception can print to places that aren't stdout

- parser/src/lexer.rs
- tests/snippets/floats.py
Take only numbers not `_` after `.`
Fixes #1498
> Take only numbers after `.`

- tests/snippets/attr.py
- vm/src/obj/objtype.rs
Implement delattr for type object
```
>>>>> class C:
.....   x = 10
..... 
>>>>> del C.x
AttributeError: 'type' object has no attribute 'x'
>>>>> C.x
10
```
```
>>>>> class C:
.....   x = 10
.....
>>>>> del C.x
>>>>> C.x
AttributeError: C has no attribute 'x'
```
Fixed: #1404
> Implement delattr for type object

- tests/snippets/stdlib_os.py
- vm/src/stdlib/os.rs
* Add `os_system` and accompanying Python attribute `os.system` to `os.rs`
* Tested/ working on *Nix (MacOS) only.  Not tested on Windows. 
* Accepts Python `str` argument, but not `bytes or os.PathLike object`
> Add os.system

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
For most cases uses rust's round function to round via:
`round(number, decimals) = round(number * 10^decimals) / 10^decimals`
* skips rounding if rounding would not affect digits within double precision (also covers cases where the above implementation would overflow the f64 exponent)
* also handles arbitrarily negative values for `decimals`
> Implement round(number, digits) for digits != 0

- whats_left.sh
Simply adds RUSTPYTHONPATH to whats_left.sh to avoid setting it explicitly for running the script.
As a newcomer, while I ran the script, I didn't recognize setting RUSTPYTHONPATH for the error below.
So, I think it's good to add RUSTPYTHONPATH for convinence.
```
===== MODULES =====
File "tests/snippets/whats_left_modules.py", line 8, in <module>
import os
ModuleNotFoundError: No module named 'os
```
> Add RUSTPYTHONPATH to whats_left.sh to run the script without setting an environment variable

- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- compiler/src/output_stream.rs
- src/shell.rs
- src/shell/readline.rs
- src/shell/rustyline_helper.rs
- vm/src/frame.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objfunction.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
I changed `FunctionOpArg` to `CodeFlags`, which is basically the same but is stored inside `CodeObject`. This also means that we don't have to have `enter_function` return the flags for `MakeFunction`; it can just apply them to the `CodeObject` it pushes onto the stack.
> Clean up the REPL and CodeFlags

- tests/snippets/stdlib_math.py
- vm/src/stdlib/math.rs
- Implement `math.isclose()` function with test case
- Add `IsCloseArgs` struct for `keyword_only` arguments: `rel_tol`, `abs_tol`
- Change order of test case on `math_module.py` for readability
> Update isclose module of math

- Lib/_sitebuiltins.py
Opens the files on initialization and attaches to `sys.std{in,out,err}`
- It respects what already exists if any
- Otherwise it opens de UNIX standard files
Caveats:
- May be not on the proper place
- Is open to discussion on what codec, or if should be opened as bytes
- Can be also done in Rust side
> `sys.std{in,out,err}` implemented in the most simple way

- vm/src/obj/objbytearray.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objstr.rs
- vm/src/pyobject.rs
- vm/src/stdlib/binascii.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/re.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/time_module.rs
- vm/src/stdlib/zlib.rs
This change is mainly changes of `PyIntRef` to primitives types. I will do other type in a different PR as this became a very large change...
> Use primitives directly

- vm/src/dictdatatype.rs
Dict resizing is working by removing all None entries, and filling up indices map from scratch
Frequency of resizing should be adjusted, I guess. Maybe it'll be useful to trigger it more often, it's hard to say without somewhat realistic benchmark
Addresses: #1531 
Benchmark: 
```python
a = {0: 1}
for i in range(10000):
del a[0]
a[0] = 1
```
Results: 
```
$ time ./target/release/rustpython-master test.py
real    0m3,316s
user    0m3,312s
sys     0m0,004s
$ time ./target/release/rustpython test.py
real    0m0,062s
user    0m0,055s
sys     0m0,008s
$ time python3 test.py
real    0m0,023s
user    0m0,015s
sys     0m0,008s
```
> Implement dict resizing

- Cargo.lock
- tests/snippets/stdlib_struct.py
- vm/Cargo.toml
- vm/src/stdlib/pystruct.rs
Changed most of the pack_* function to be built with a macro.
In addition before this change this was allowed in RustPython and not in CPython:
```py
struct.pack('<IH', "14", 12)
```
> pystruct refactor

- tests/snippets/class.py
- vm/src/obj/objtype.rs
This set `__doc__` as None if it is not included in attribute
while making new instance of type.
In cpython if there is no docstring in class definition,
`__doc__` attribute will be None. So RustPython should follow it.
Partially solves #1523 
This only fixes class definition.
> objtype: Set __doc__ as None if not included 

- tests/not_impl_gen.py
When executing `./whats_left.sh`,
you may see several warning messages at beginning as follows
```
not_impl_gen.py:69: DeprecationWarning: the formatter module is deprecated
return set(dir(__import__(name))) if name not in ("this", "antigravity") else None
not_impl_gen.py:69: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
return set(dir(__import__(name))) if name not in ("this", "antigravity") else None
not_impl_gen.py:69: DeprecationWarning: the macpath module is deprecated in 3.7 and will be removed in 3.8
return set(dir(__import__(name))) if name not in ("this", "antigravity") else None
```
This fix will stop showing those messages
> Ignore deprecated module warning in a test script

- tests/snippets/bytes.py
- vm/src/obj/objbyteinner.rs
fix the bug on replacing bytes with different length
issue #1560
> bytes.replace: replacing bytes w/ diff len

- compiler/src/peephole/optimizations.rs
- tests/snippets/floats.py
In cpython, "1.0 / 0.0" raises ZeroDivisionError
```
>>> 1.0 / 0.0
ZeroDivisionError: float division by zer
```
but RustPython doesn't
```
>>>>> 1.0 / 0.0
inf
```
This is because they emits different byte codes.
```
$ echo "1.0 / 0.0" > zero-div.py
$ python -m dis zero-div.py
1           0 LOAD_CONST               0 (1.0)
2 LOAD_CONST               1 (0.0)
4 BINARY_TRUE_DIVIDE
6 POP_TOP
8 LOAD_CONST               2 (None)
10 RETURN_VALUE
$ cargo run --example dis zero-div.py
zero-div.py:
0 LoadConst            (inf)
1 Pop
2 LoadConst            (None)
3 ReturnValue
```
This commit stops optimization for zero division case
to generate same byte codes.
> Fix wrong const optimization for "1.0 / 0.0" case

- README.md
The readme has instructions for cloning and testing the repo and for installing with wapm, but it's always nice to have copy-able cargo install instructions
> add cargo install instructions to README

- tests/not_impl_gen.py
Ignore python module which cannot be imported and print error message thereof
I am not sure the reason, but I have a problem with import `pyopenvdb`.
This does not really matter to block `whats_left.sh`, so I propose to ignore error and print error message as following.
```
!!! pyopenvdb skipped because ImportError: /usr/lib64/libjemalloc.so.2: cannot allocate memory in static TLS block
```
> test.not_impl_gen ignore py module w/ import error

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
- Python `float.fromhex` can handle string of float and hex without `.`
- For example `0.0`, `-0.0`, `0x0p0`, `-0x0p0`
- Add test case mantioned
> Improve  float.fromhex module of objfloat

- compiler/src/compile.rs
- tests/snippets/function.py
In cpython, if there is no docstring declared in function definition,
the `__doc__` attribute of the function is None.
So this implements the behavior.
Fix #1523
> Set docstring of function as None if not declared

- tests/snippets/strings.py
- vm/src/obj/objstr.rs
#1575 distinguish between 'cased' and 'non-cased' characters
use unic::ucd::is_cased function to ignore non-cased character
> Fix issue #1575 distinguish between 'cased' and 'non-cased' characters

- Lib/_rp_thread.py
- Lib/_threading_local.py
- Lib/threading.py
- tests/snippets/test_threading.py
`_rp_thread.py` populates `_thread` missing attributes with `_dummy_thread` implementations. This allows `threading.py`  from CPython to be imported.
Copied from CPython:
- `_threading_local.py`: Verbatim
- `threading.py`: One line change `import _rp_thread`
It needs `sys.stdout` to work, so may be needed to merge #1514 before testing this one.
> `threading` support via dummy implementation

- tests/snippets/floats.py
- vm/src/obj/objfloat.rs
- Refactoring previous PR #1552
- Embrace hexadecimal without `0x`, `.`, `p`
- Embrace variety of `nan`, `inf` case
- Enhance test case based on cpython
- TODO: Still fromhex can't catch overflow error and accept closest to `min`, `max`, `0`, `1` case isn't handled
> Improve float.fromhex module representation case

- tests/snippets/class.py
- vm/src/obj/objfunction.rs
- vm/src/obj/objtype.rs
Currently the method return the attributes of the `PyMethod` object. This changes the attributes of the wrapped function to be returned.
In addition removed the change in #1550 after #1580.
> Return function attributes in method

- compiler/src/compile.rs
- compiler/src/error.rs
- compiler/src/symboltable.rs
- parser/src/location.rs
- vm/src/vm.rs
visualize syntax error with caret diagnostics, when the statement is provided
Fix issue #1513 
The result will show as following.
```
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> a ! b
SyntaxError:
a ! b
↑
Got unexpected token !
>>>>>
```
I am not sure how to implement the test for the python error message if someone knows about this, please kindly tell me, thanks.
> Provide caret diagnostics for SyntaxError

- tests/snippets/exceptions.py
- vm/src/exceptions.rs
In CPython the BaseException initialize `__traceback__`, `__cause__`, `__context__` and `__suppress_context__` in `__new__` and not in `__init__`.
Do you think this attributes should be members of `PyBaseException`?
> Separate BaseException to __init__ and __new__

- wasm/lib/README.md
- wasm/lib/src/lib.rs
- wasm/lib/src/vm_class.rs
Fix issue #1610 
The print function of wasm will be
- `console.log` by default or when giving undefined or "console"
- a dumb function when giving `null`
- the function when giving a function
> Set default stdout of wasm to `console.log`

- compiler/src/error.rs
When you compile a multi-line statement this will now print only the problematic line.
> Fix caret diagnostics for mutiple lines

- tests/snippets/stdlib_itertools.py
- vm/src/stdlib/itertools.rs
This pull request implements `itertools.zip_longest` in Python standard library, related with #1361.
> Implement itertools.zip_longest

- tests/snippets/stdlib_hashlib.py
- vm/src/stdlib/hashlib.rs
Example case in [the documentation][1]:
```py
>>> hashlib.sha224(b"Nobody inspects the spammish repetition").hexdigest()
'a4337bc45a8fc544c03f52dc550cd6e1e87021bc896588bd79e901e2'
```
[1]: https://docs.python.org/3.6/library/hashlib.html#hash-algorithms
> Add an optional data parameter for predefined constructors of hashlib

- vm/src/obj/objbool.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/vm.rs
- `objint::get_float_value` -> `objfloat::from_int_value` because objint::get_float_value is only used in objfloat
- `PyInt::cmp`, `PyInt::int_op`, `PyInt::general_op` to make it simple
> Refacter objint

- vm/src/obj/objbool.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objint.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
FIrst 2 commits are included in other PR (#1626). So please check only the last commit.
We use this common pattern a lot:
```rust
if objtype::isinstance(&obj, &vm.ctx.T_type()) {
let v = obj.payload::<T>().unwrap();
...
} 
```
By adding a new method `PyObject::payload_if_subclass`, this pattern is reduced to
```rust
if let Some(v) = obj.payload_if_subclass::<T>(vm) {
...
}
```
> PyObject::payload_if_subclass to reduce common pattern

- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- compiler/src/symboltable.rs
- parser/src/ast.rs
- parser/src/error.rs
- parser/src/fstring.rs
- tests/snippets/fstrings.py
- vm/src/frame.rs
This allows:
```py
spec = "0>+#10x"
f"{16:{spec}}"
```
> Support expression in f-strings spec

- wasm/demo/src/main.js
- wasm/lib/src/lib.rs
- wasm/lib/src/vm_class.rs
- wasm/tests/test_exec_mode.py
- Expose `pyEval`, `pyExec`, `pyExecSingle` in wasm module
This PR also fix #1612
> Support eval and exec mode in wasm

- Lib/test/libregrtest/__init__.py
- Lib/test/libregrtest/cmdline.py
- Lib/test/libregrtest/main.py
- Lib/test/libregrtest/refleak.py
- Lib/test/libregrtest/runtest.py
- Lib/test/libregrtest/runtest_mp.py
- Lib/test/libregrtest/save_env.py
- Lib/test/libregrtest/setup.py
- Lib/test/libregrtest/utils.py
- Lib/test/libregrtest/win_utils.py
- Lib/test/regrtest.py
- Lib/test/support/__init__.py
- Lib/test/test_bool.py
- vm/src/stdlib/faulthandler.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/time_module.rs
- vm/src/sysmodule.rs
This change include many different changes that allows us to run the CPython test using `libregtest`. After the change you can do:
```
cargo run --release Lib/test/regrtest.py
== RustPython 3.5.0alpha (heads/run-unittests-dirty:cba70133, Dec 28 2019, 10:23:15) [rustc 1.40.0]
== cwd: /tmp/test_python_19746
== CPU count: 4
== encodings: locale=UTF-8, FS=utf-8
Run tests sequentially
0:00:00 [1/1] test_bool
test_bool passed
== Tests result: SUCCESS ==
1 test OK.
Total duration: 293 ms
Tests result: SUCCESS
<SystemExit object at 0x5571b65f8a10>
```
This change is based on the change in #1625.
> Run unittests

- vm/src/stdlib/socket.rs
For #1176.  Just added each of those functions to `vm/src/stdlib/socket.rs`, mostly by cheating off of the `htonl` implementation.
> Add htons, ntohl, and ntohs to socket.rs

- src/main.rs
- tests/snippets/stdlib_collections.py
- vm/src/exceptions.rs
- vm/src/function.rs
- vm/src/lib.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objiter.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/py_serde.rs
- vm/src/sequence.rs
- vm/src/stdlib/collections.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/subprocess.rs
- vm/src/vm.rs
- their members are now private (removed TODO)
- refactor cmp functions
- PyListRef impls -> PyList
- Fix deque bug for self comparison
- SimpleSeq impl for cell ref so that the code now are looks like more common rust
> Refactor list, tuple and collections.deque

- vm/src/frame.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objstr.rs
- vm/src/py_serde.rs
- vm/src/stdlib/csv.rs
- vm/src/stdlib/imp.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/pystruct.rs
- vm/src/stdlib/subprocess.rs
- vm/src/stdlib/tokenize.rs
- vm/src/vm.rs
because the previous naming gives unclear performance estimation to
users especially comparing to `objstr::borrow_value`.
I also suggest one of below:
1. Rename `objstr::borrow_value` -> `objstr::get_value` as current expectation.
2. Rename `get_value`s of non-copying types into `borrow_value` and `clone_value`. For now, there are `bytes`, `int`, `range` and `tuple`.
> objstr::get_value -> objstr::clone_value

- Cargo.lock
- Cargo.toml
- derive/Cargo.toml
- derive/src/lib.rs
- vm/Cargo.toml
- vm/src/lib.rs
`proc-macro-hack` is sort of a pain to deal with (based on the nested cargo features that were removed by this), and with Rust 1.40 [function-like macros can generate `macro_rules!`](https://github.com/rust-lang/rust/pull/64035), so this is pretty easy to implement ourselves (`proc-macro-hack` does something with a custom derive on an enum and stringifying and reparsing the input stream).
> Don't use proc-macro-hack; use our own slightly-less-hacky hack

- vm/src/exceptions.rs
- vm/src/function.rs
- vm/src/obj/objproperty.rs
- vm/src/pyobject.rs
- vm/src/stdlib/os.rs
Suggestion from #1644
Not sure this is what we want - because I thought VM param is designated constraint not to confuse plain functions with python functions until now.
> Allow to skip VM param for IntoPyNativeFunc functions

- .travis.yml
- tests/Pipfile
- tests/snippets/math_basics.py
https://docs.python.org/3/whatsnew/3.8.html#other-language-changes
> For integers, the three-argument form of the pow() function now permits the exponent to be negative in the case where the base is relatively prime to the modulus. It then computes a modular inverse to the base when the exponent is -1, and a suitable power of that inverse for other negative exponents.
> Travis CI: Matrix -> jobs and Python 3.6 to 3.8

- tests/snippets/stdlib_select.py
`'win' in sys.platform` returns true on MacOS, since it's platform string is [`"darwin"`](https://docs.python.org/3/library/sys.html#sys.platform). This was likely not intended, since the check seems to be testing for a windows platform, and was the only test error on a clean master build for me.
> Improve test check for windows platform

- README.md
We just created badges for WAPM packages, so projects that are published there can use them.
It will appear in the README like this:
[![WAPM package](https://wapm.io/package/rustpython/badge.svg?style=flat&nocache)](https://wapm.io/package/rustpython)
Hope you find it useful! :)
> Added WAPM badge

- benchmarks/benchmarks/strings.py
- benchmarks/test_benchmarks.py
- tests/snippets/strings.py
- vm/src/obj/objstr.rs
I noticed that the string iterator looped over all or parts of the characters twice for each call to `__next__`. Made an attempt to remove both of them and only keep the current byte position, which should change string iteration an O(n) operation instead of O(n²).
Master (but with this branch's benchmark test):
```
(rustpython_benchmarks) benchmarks (master) $ (cd .. && cargo build --release) && pytest -k "strings.py"
<skipped>
------------------------------------------------------------------------------------------------ benchmark: 2 tests -----------------------------------------------------------------------------------------------
Name (time in ms)                            Min                   Max                  Mean             StdDev                Median                IQR …
```
> String performance

- parser/src/error.rs
- parser/src/lexer.rs
- tests/snippets/funky_syntax.py
- tests/snippets/invalid_syntax.py
Currently when we had a line continuation all lines numbers after were shifted by one. For example:
```py
a = "aaaa" + \
"bbbb"
1/0
```
Would say the exception was in line 2 instead of 3.
> fix line continuation parsing

- Lib/test/test_compare.py
- vm/src/vm.rs
This PR solves `test_ne_low_priority` by implementing `PyObject_RichCompare` to `vm._cmp`.
> Fix comparison operator

- README.md
- examples/hello_embed.rs
- examples/mini_repl.rs
I'm sure examples like these were left out because you can just comb through the source, the documentation, pyckitup, etc. and figure out how everything works, and while that's definitely the case (I mean, I just did exactly that) doing so is quite time consuming, so I hope that I can leave these tutorials as breadcrumbs for anyone else who's interested in embedding RustPython into their applications.
I can say that personally I encountered RustPython a couple months back, and because there were no examples like these I simply assumed that embedding RustPython into Rust applications wasn't possible/feasible, and that it was meant simply to be a standalone application. Examples like these and the note in the README should make it much clearer to interested passerby that RustPython is not …
> Add examples showcasing how to embed RustPython in Rust applications

- Cargo.lock
- derive/Cargo.toml
- derive/src/compile_bytecode.rs
- vm/Cargo.toml
- vm/src/lib.rs
- vm/src/vm.rs
```once_cell``` is generally considered to be superior to ```lazy_static``` nowadays since it doesn't require a macro and has some extra flexibility.  The ongoing proposal to add lazy initialization to the stdlib basically copies the ```once_cell``` API.
https://github.com/rust-lang-nursery/lazy-static.rs/issues/111
https://github.com/rust-lang/rfcs/pull/2788
> Replace lazy_static! macro with once_cell

- .github/workflows/ci.yaml
This will decrease the CI time from ~25 min to ~18 min. The github actions [quotas](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits) are 20 concurrent builds (5 macOS) so I think this should be OK.
> Split rust test and snippets in github actions

- vm/src/pyobject.rs
- vm/src/types.rs
My plan I had in #1411 didn't work out because I failed to account for `PyClassRef` and `Rc<PyObject<PyClass>>` not being the same size due to the former being a trait object, so I went with using raw trait object manipulation.
cc @silmeth
> Purge all UB from init_type_hierarchy

- Cargo.lock
If you haven't updated to Rust 1.41 yet, you might want to do so, as I don't think this lockfile format is backwards-compatible.
> Ugrade dependencies and update lockfile format

- src/main.rs
Fixes #1742 
This PR changes the exit code to 0 if it overflows by replacing an `unwrap()` call with `unwrap_or(0)`. Let me know what you think @coolreader18!
> Fallback exit code to 0 in case of overflow

- .github/workflows/ci.yaml
- wasm/demo/package.json
This should speed up WASM testing, as Rust actually compiles to wasm fairly quickly (and I think the time it takes to run the wasm tests is mostly rustpython_wasm setting itself up), and it will also fix the horrible performance issue that's on the demo page right now, as we've got a (38 MB!) debug build running in production.
> Have wasm/demo's "test" npm script build the demo in release mode

- tests/snippets/builtin_complex.py
- vm/src/obj/objcomplex.rs
This pull request adds support for `__pos__` to the VM's complex number type, `PyComplex`.
```python3
>>>>> +1j                     
Traceback (most recent call last):   
TypeError: Unsupported method: __pos__
>>>>> 
```
```python
>>>>> +1j                     
1j
>>>>> 
```
> Add __pos__ to PyComplex

- tests/snippets/ints.py
- vm/src/obj/objint.rs
This pull request adds support for `as_integer_ratio` to the VM's integer number type, `PyInt`.
```python
>>>>> (10).as_integer_ratio()        
Traceback (most recent call last):                                             
AttributeError: 'int' object has no attribute 'as_integer_ratio'
>>>>> 
```
```python
>>>>> (10).as_integer_ratio()
(10, 1)
>>>>> 
```
> Add as_integer_ratio to PyInt

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
Gitpod is a really neat tool that allows you to pop into a build environment for a project to play around with what how it works; I've been using it to develop RustPython while away from my main computer and I figured I'd add explicit support for it to the project.
> Add gitpod configuration

- Cargo.lock
- Lib/random.py
- vm/Cargo.toml
Adds the `wasm-bindgen` feature to rand/getrandom, and makes the `os` module optional for the `random` module.
> Make _random work on wasm

- parser/src/error.rs
- parser/src/fstring.rs
Reopened the pull request due to unusual git behaviour. 
This pull request addresses #1770.
It correctly handles != inside of f strings, as well as f"{!a}" not returning an EmptyExpression error.
This also adds an error for conversion flags not being followed by brace characters, which would otherwise be a token error, unlike the Python implementation.
It also changes the print out for UnopenedRbrace / UnclosedLbrace to correctly print braces instead of brackets.
I've also included tests for expected brace characters and not equals operations inside of braces, as well as the expected EmptyExpression errors for f"{!a}".
> Update f-string errors, handle != in f-string.

- vm/src/frame.rs
This fixes a panic when a function receives kwargs which are not a dict: addresses #1780
> Raise TypeError when kwargs are not dict.

- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- compiler/src/peephole.rs
- parser/src/error.rs
- parser/src/function.rs
- parser/src/lexer.rs
- parser/src/location.rs
- parser/src/parser.rs
- parser/src/python.lalrpop
- vm/src/frame.rs
It's only 2 `usize`s and it gets passed around a lot, the `clone()`ing just makes the code more verbose.
> Make ast::Location implement Copy

- Lib/test/string_tests.py
- Lib/test/test_bytes.py
- vm/src/obj/objbyteinner.rs
- `Lib/test/test_bytes.py` from CPython 3.8.2
- Fix `bytes.split` for 32bit+ int maxsplit
- Fix empty needle crash for `bytes.__contains__`
> fix bytes bugs and add test_bytes.py 

- vm/src/obj/objmemory.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/types.rs
The main motivator for this is to make the type hierarchy creation simpler and less error prone; this removes the trait object hack, including a few questionable transmutes.
> Make PyObject.typ a Rc<PyObject<PyClass>>

- benchmarks/bench.rs
- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- compiler/src/error.rs
- derive/src/compile_bytecode.rs
- examples/dis.rs
- tests/snippets/function.py
- tests/snippets/invalid_syntax.py
- vm/src/import.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objframe.rs
- vm/src/obj/objfunction.rs
- vm/src/vm.rs
- wasm/demo/src/index.js
- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
- wasm/tests/test_demo.py
- wasm/tests/test_inject_module.py
This allows for strict privacy for WASM modules, which is important in an environment like the browser, where most of the time you're running code on someone else's computer. The idea for this method would be to write a wrapper module around some possibly security-sensitive functions that you pass from js, and then allow arbitrary code to access that module. For [robot rumble](https://github.com/chicode/robot-rumble) (the successor to codingworkshops, the code learning platform), it might be used like:
```js
// vm.injectModule(name, source, imports?, strict_private?)
vm.injectModule(
"robots",
`
__all__ = ["export"]
def export(...): runRobot(...)
`,
{ runRobot: () => { ... } },
true,
);
// later
vm.exec(userCode);
```
We don't want user code arbitrarily calling the `runRobot` function, so …
> Add a better injectModule method to WASM

- Cargo.lock
- vm/Cargo.toml
As discussed in #1823. I would suggest revisiting this once our testing matrix is larger.
> Use vendored version of openssl

- Cargo.lock
- Lib/_collections_abc.py
- Lib/test/test_unicode.py
- bytecode/Cargo.toml
- bytecode/src/bytecode.rs
- compiler/src/compile.rs
- tests/.gitignore
- tests/custom_text_test_runner.py
- tests/jsontests.py
- vm/src/format.rs
- vm/src/obj/objcode.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objstr.rs
>  Add json output for CPython tests

- Lib/pathlib.py
- Lib/test/test_pathlib.py
- vm/src/stdlib/io.rs
- vm/src/stdlib/os.rs
This change add `pathlib` and changes many `os` method to support path like objects.
Many of the tests fail because Rust does not support `Cstring` with `nul`. Not sure how to bypass that. Would appreciate suggestion on how to solve this.
> Add Pathlib

- .github/workflows/cron-ci.yaml
As @mireille-raad requested in #1671. Successful run [here](https://github.com/RustPython/RustPython/runs/581687268?check_suite_focus=true).
> Add a cron job to push jsontest data to the website

- parser/src/fstring.rs
- tests/snippets/fstrings.py
This PR contains the following changes for fstring:
so far f"{'42'!s:10}" rose a parsing error as a '}' was expected after a conversion flag.This is fix now.
I implemented the self documenting fstrings in rustpython, as introduced with python 3.8. I.e., the following syntax is now allowed:
>>> foo="bar"
>>> f"{foo=}"
foo=bar
>>> f"{2*21=}"
2*21=42
...
Also combination with conversion flags and format specs are supported.
Open: the behaviour when the type of the expression is a string is so far not conform to cpython, thus those are temporarily modified or skipped. 
Imported the tests for  selfdocumentign fstrings from cpython to rustpython.
> The any key/p38 self documenting fstrings

- vm/src/stdlib/os.rs
As title, sync function is available in UNIX only.
> add support for sync func in os module

- Lib/test/test_math.py
- vm/src/stdlib/math.rs
This PR implements the bpo-39648 and bpo-39479, which are planned for CPython 3.9.
This change extends the math module to implement a lcm (least common multiple) function analog to the gcd. Further both functions are extended to take an arbitrary number of int arguments.
The kind of args is in accordance to the 3.9.a6 cpython implementation, although this style of parameters is quite uncommon in the math module; in similar cases iterables are used as arguments. Maybe this changes before release.
Further, I imported the test_math.py module from CPython and skipped all failing tests (unluckily there are plenty of them)
Whats missing: cpython also accepts object arguments having index implemented, this seems so far not be finalized in the reference. Thus I defer the implementation.
replace …
> Implement Py3.9 LCM and GCD

- parser/src/error.rs
- parser/src/lexer.rs
- src/shell.rs
Return EOF Error to get the next line after` \\ `in the shell.
Closes #1928
> EOF after `\\` raise EOF Error

- Lib/test/string_tests.py
- tests/snippets/strings.py
- tests/snippets/testutils.py
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbyteinner.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objstr.rs
- vm/src/obj/pystr.rs
This PR implements and tests the new string functions introduced by Python 3.9 to remove prefixes and suffixes. This change is defined in PEP616. Now it is possible to do:
s='foobarfoo'
t=s.removeprefix('foo')
print(t.removesuffix('foo'))
'bar'
Clean replacement of #1903
> Implement Python 3.9 style string functions: removeprefix and removesuffix PEP616

- Lib/test/test_decorators.py
- Lib/test/test_types.py
- parser/src/python.lalrpop
Implement the in Python 3.9 introduced generalized decorators
So far it was only allowed:
>>> @foo
>>> def fct():
or 
>>> @bar()
>>> def fcd():
now it is also possible to use generic expressions lile
>>> @foo_arr[42]
>>> def fct():
or
>>> @foo_arr[42].baz.wrap
>>> def fct():
The implementation of the grammar is in accordance to the reference grammar, with required changes, e.g., as named expressions are not supported by rustpython.
This change is fully backward compatible and thus does not harm the compatibility with older python versions.
> Implement Py39 generalized decorators (PEP 614)

- vm/src/builtins.rs
- vm/src/import.rs
- vm/src/stdlib/imp.rs
- vm/src/stdlib/signal.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/js_module.rs
- wasm/lib/src/vm_class.rs
In preparation for threading; we want to keep some properties of the vm consistent across threads, so I'm moving the ones that should be into an `Arc`.
> Move some vm fields to an Arc-wrapped struct

- README.md
Had issues installing with 1.40.0 which the readme implies could work. Thanks @youknowone realized it was out of date, thought I'd update to reflect that.
> update rust version in readme

- vm/src/vm.rs
This should make debugging vm initialization problems easier.
> Initialize the vm with imports from _io instead of io

- Lib/re.py
- Lib/test/libregrtest/main.py
- Lib/test/test_decorators.py
- Lib/test/test_long.py
- Lib/test/test_math.py
- Lib/test/test_named_expression.py
- Lib/test/test_scope.py
- tests/snippets/fstrings.py
- vm/src/obj/objint.rs
Implement an efficient bitcount method directly for the type int. Bitcount sometimes refered as population count returns the number of 1 in an int of arbitrary length. In the implementation always the absolute value is takes.
This PR also includes the test from CPytohn for long.
https://bugs.python.org/issue29882
> Implement bitcount for int (Py310 BPO-29882)

- vm/src/lib.rs
I'd like to have access to local py script variables after execution embedded script like that:
```Rust
let frame = Frame::new(code_obj, scope).into_ref(&vm);
vm.frames.borrow_mut().push(frame.clone());
let result = frame.run(&vm);
//Access locals here !!!
let locals = frame.scope.get_locals();
vm.frames.borrow_mut().pop();
```
> make "frame" module public

- vm/src/function.rs
Remove `clippy::many_single_char_names`
No idea about remaining warnings of `clippy::redundant_field_names`
> Fix clippy warning

- Lib/test/test_named_expression.py
- compiler/src/symboltable.rs
- pdc.sh
Improved scoping and error handling. All tests besides of three are passing now.
Now the error handling in comprehensions is improved. Now the following errors are detected and reported:
rebinding of iterator var
>>> [i:=0 for i in range(0)]
>>> [i for i:=0 in range(5)]
using named expressions in iterator definition
>>> [i for i in (k:=range(5))]
> Py3.8 Named expression completion - error handling and scoping

- Cargo.lock
- Lib/test/test_bool.py
- Lib/test/test_unicode.py
- vm/Cargo.toml
- vm/src/obj/objstr.rs
- vm/src/stdlib/unicodedata.rs
This new behavior matches the Python documentation https://docs.python.org/3/library/stdtypes.html#str.isspace.
> Fix str.isspace to support unicode space characters

- derive/src/pyclass.rs
- vm/src/dictdatatype.rs
- vm/src/exceptions.rs
- vm/src/frame.rs
- vm/src/macros.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objcoroinner.rs
- vm/src/obj/objenumerate.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objmappingproxy.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/sequence.rs
- vm/src/stdlib/array.rs
- vm/src/stdlib/collections.rs
- vm/src/stdlib/csv.rs
- vm/src/stdlib/hashlib.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/random.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/ssl.rs
- vm/src/stdlib/winreg.rs
- vm/src/stdlib/zlib.rs
- vm/src/types.rs
- vm/src/vm.rs
All of the benefits of `parking_lot::Mutex` over the std one are listed in its
[readme](https://github.com/Amanieu/parking_lot#features), but the ones that apply
to us are copied here:
* Mutex and Once only require 1 byte of storage space, while Condvar and RwLock only require 1 word of storage space. On the other hand the standard library primitives require a dynamically allocated Box to hold OS-specific synchronization primitives. The small size of Mutex in particular encourages the use of fine-grained locks to increase parallelism.
* less allocation is always good for performance, especially when all PyObjects are allocated and most require Mutexes
* Uncontended lock acquisition and release is done through fast inline paths which only require a single atomic operation.
* good, since a …
> Switch to using parking_lot::Mutex instead of std::sync::Mutex

- tests/not_impl_gen.py
```
===== MODULES =====
[2020-07-13T14:46:47Z ERROR rustpython] Failed reading file 'tests/snippets/whats_left_modules.py': InvalidData
```
I discovered a issue when launching `./whats_left.sh` fails to read modules. Turns out it was because of non-ASCII path, so I created this small fix to solve this.
The issue is only confirmed on a Windows 10 machine with non-unicode codepage.
> Fix file reading failure in non-ascii path on `not_impl_gen.py`

- Lib/fractions.py
- Lib/test/test_fractions.py
- derive/src/pymodule.rs
- vm/src/builtins.rs
Importing `fractions.py` required getting `divmod.__name__`. I achieved this by converting most of the `builtin` module to be declared with `#[pymodule]`, and then changed the proc macro to use `new_function_named`. As a consequence a lot more builtin functions now will have `__name__` and `__module__` correctly set.
> Add fractions.py

- Lib/test/test_grammar.py
- compiler/src/compile.rs
Set annotation for other type function args.
```python        
def f(a, b: 1, c: 2, d, e: 3 = 4, f: int = 5, /, *g: 6, h: 7, i=8, j: 9 = 10,
**k: 11) -> 12: pass
self.assertEqual(f.__annotations__,{'b': 1, 'c': 2, 'e': 3, 'f': int, 'g': 6, 'h': 7, 'j': 9, 'k': 11, 'return': 12})
```
> Set annotation for function args

- vm/src/obj/objbyteinner.rs
- vm/src/stdlib/array.rs
- vm/src/stdlib/os.rs
- Test case `BaseTest.test_cmp` in `Lib/test/test_array.py` is failing because there are no compare method of array.
- `BaseTest.test_cmp` is still failing after this PR because multiply methods of array are not implemented.
> Implement lt, le, gt, ge method of array

- Cargo.lock
- Lib/test/test_pwd.py
- bytecode/Cargo.toml
- parser/Cargo.toml
- vm/Cargo.toml
- vm/src/obj/objint.rs
- vm/src/stdlib/pwd.rs
Removing the `pwd` dependency removes about 6 transitive dependencies, including failure-derive and synstructure. This should improve our compile time a fair bit.
> Update the pwd module

- vm/src/stdlib/array.rs
Implement remove method of array (vm/src/stdlib/array.rs)
I didn't uncommented TODO because there are still error with another problem.
```
======================================================================
ERROR: test_remove (__main__.UnsignedShortTest)
File "Lib/test/test_array.py", line 953, in test_remove
self.assertRaises(ValueError, a.remove, self.outside)
AttributeError: 'array' object has no attribute 'remove'
```
```
======================================================================
ERROR: test_remove (__main__.UnsignedShortTest) …
```
> Implement remove method of array

- Lib/test/test_subclassinit.py
- vm/src/function.rs
- vm/src/obj/objobject.rs
- vm/src/obj/objtype.rs
This implements `__init_subclass__` from [PEP 487](https://www.python.org/dev/peps/pep-0487/).
Closes #1346. Partially fixes issue  #356.
> Implementation of __init_subclass__

- vm/src/sysmodule.rs
[Documentation](https://docs.python.org/3/c-api/init_config.html#c.PyConfig.base_executable)
With this, the venv module can display its help screen, though it doesn't work.
> Add _base_executable variable to sys module

- tests/snippets/stdlib_os.py
- vm/src/stdlib/os.rs
Hello all,
I am trying to implement the chown function for the os module (https://docs.python.org/3/library/os.html#os.chown), because of issue #1175 .
I am a new contributor and I'd like to have feedback on this first take at the implementation. It is not finished yet but I have a few questions and I wanted to be sure that I am going in the good direction.
As of now, the chown function works properly given that you invoke rustpython with root permissions. I can successfully change uid and gid of a file, or use -1 to preserve them. I am having a few issue with the path to file, it does not seem yet to accept unix shorthands like ~ (FileNotFound error, might come from nix lib, need to investigate).
I have not tested dir_fd and _follow_symlink yet since I am not sure how to handle these …
> Implementation of chown, lchown and fchown for the os module

- derive/src/pyclass.rs
- derive/src/pymodule.rs
- derive/src/util.rs
- vm/src/pyhash.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/pwd.rs
- vm/src/stdlib/time_module.rs
- vm/src/version.rs
Just implemented 'rustpython_vm::version::VersionInfo::repr' method, and added as value of property 'sys.version_info'.
It's now works, but refactoring is required.
Fix #1448
> implemented __repr__ method in impl_pyclass_sequence

- vm/src/sysmodule.rs
Before, sys.executable returned a relative path, unlike what the [documentation](https://docs.python.org/3/library/sys.html#sys.executable) says. This makes sys.executable return an absolute path.
> Fixed bug where sys.executable returned an absolute path instead of a relative path

- Lib/test/test_builtin.py
- vm/src/obj/objfloat.rs
Floating point modulo operation is different between python and rust.
> fix a divmod bug

- tests/snippets/stdlib_os.py
- vm/src/sysmodule.rs
This PR fixes #1996.
>In Windows 8.1 and Windows 10, the GetVersion and GetVersionEx functions have been deprecated. In Windows 10, the VerifyVersionInfo function has also been deprecated. While you can still call the deprecated functions, if your application does not specifically target Windows 8.1 or Windows 10, the functions will return the Windows 8 version (6.2). - [Targeting your application for Windows](https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1)
* Since Windows 8.1 and later versions return 6.2 for non-manifested application, for now, this function will report the Windows version as 6.2 on modern systems. This can be fixed by adding a manifest with `embed_resource` crate.
* `platform_version` returns the result from …
> Implement `sys.getwindowsversion` 

- vm/src/stdlib/os.rs
panic message has following typo: "Uknown file type"
fixed to "Unknown file type"
> os.rs - Minor typo fix for panic! macro

- Lib/test/test_iter.py
- Lib/test/test_itertools.py
- vm/src/obj/objiter.rs
- vm/src/pyobject.rs
- vm/src/stdlib/itertools.rs
The test `TestBasicOps.test_groupby` is still failing due to a general pickling bug.
For #1983
Closes #1361 (this is the last itertools function to be implemented)
> Add itertools.groupby

- vm/src/stdlib/os.rs
This PR adds os.execv for unix systems which is a part of #1992
Uses nix::unistd::execv for implementation.
Would appreciate any help on line 1203 - temporary value referencing in closure while converting CString to &CStr
> os.execv implementation for unix systems

- Lib/test/test_fractions.py
- vm/src/obj/objfloat.rs
Fix #1986 
**Before:**
- RustPython
`>>>>> float.__rpow__(0.5, -2)`
`NaN`
**After:**
- RustPython
`>>>float.__rpow__(0.5, -2)`
`(0.00000000000000008659560562354934+1.4142135623730951j)`
- CPython 3.85
`>>> float.__rpow__(0.5, -2)`
`(8.659560562354934e-17+1.4142135623730951j)`
> Fix #1986 which (-2) ** 0.5 yields NaN.

- Lib/test/test_array.py
- vm/src/stdlib/array.rs
I changed return type to `Option` because when a parameter is None, `$t::try_from_object(vm, obj)` cause `TypeError` unlike CPython. But I'm not sure the way to compare value is good way.
```
======================================================================
ERROR: test_remove (__main__.UnsignedShortTest)
File "Lib/test/test_array.py", line 955, in test_remove
self.assertRaises(ValueError, a.remove, None)
File "/home/clemado1/workspace/RustPython/Lib/unittest/case.py", line 746, in assertRaises
context = None
File "/home/clemado1/workspace/RustPython/Lib/unittest/case.py", line 743, in assertRaises
return context.handle('assertRaises', args, kwargs)
File …
```
> Allow None parameter for remove, index, count method of array

- vm/src/frozen.rs
I don't use windows machine for RustPython, so please check if this is really helpful when you actually missed the step.
> Windows build note for failing part

- Lib/test/test_sys_executable.py
- vm/src/sysmodule.rs
Currently, sys.executable calls [`std::env::current_exe`](https://doc.rust-lang.org/std/env/fn.current_exe.html). With current_exe, it is platform defined if it follows symlinks. However, from my testing sys.executable never follows symlinks in CPython. This behavior is important in certain cases, e.g [this](https://github.com/BolunThompson/RustPython/blob/51c9e8824a1305d1e670700aa0904825656c921e/Lib/test/test_venv.py#L327) test only passes if symlinks aren't followed. 
This changes sys.executable to not follow symlinks.
> Fixed bug where sys.executable may follow symlinks

- Lib/test/support/__init__.py
- Lib/test/test_venv.py
- Lib/venv/__init__.py
- Lib/venv/__main__.py
- Lib/venv/scripts/common/Activate.ps1
- Lib/venv/scripts/common/activate
- Lib/venv/scripts/nt/activate.bat
- Lib/venv/scripts/nt/deactivate.bat
- Lib/venv/scripts/posix/activate.csh
- Lib/venv/scripts/posix/activate.fish
This is the venv module from CPython. If called without the --without-pip flag, it errors because the pip module isn't supported yet.
> Add venv module

- vm/src/exceptions.rs
Is there any reason exceptions currently write to stdout?
A related change would have the REPL stuff (e.g `>>> `) be written to stderr too, like CPython.
> Write exceptions to stderr instead of stdout 

- vm/src/stdlib/msvcrt.rs
This allows to start running CPython test suites on Windows, although some cases are still failing.
> Implement msvcrt.SetErrorMode

- Lib/test/test_dis.py
- vm/src/stdlib/dis.rs
Currently, the dis function from the dis module can only take functions to decompile. This changes it so that strings, when passed to dis, are compiled then disassembled.
This also includes tests for the dis module.
> Change dis.dis to take strings to decompile

- Lib/test/test_string.py
- Lib/test/test_unicode.py
- vm/src/format.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/string.rs
- Adds support for: `"{a.attr}".format(...)` and `"{l[0]}".format(...)`
- Also, adds the couple of underlying functions behind `string.Formatter`
For #1983
> Add support for indexing and attribute access inside format strings

- Lib/test/test_zipimport.py
- Lib/test/test_zlib.py
- vm/src/stdlib/zlib.rs
Fixed a couple of bugs with zlib decompression, and shared the core decompression routine between `zlib_decompress`, `Decompress.decompress`, and `Decompress.flush`.
> Fix zlib decompression

- vm/src/stdlib/os.rs
`target_is_directory` parameter is required for `symlink` function.
https://docs.python.org/3/library/os.html#os.symlink
> Add target_is_directory parameter for symlink function

- Cargo.lock
- Cargo.toml
- Lib/test/test_json/test_tool.py
- derive/src/compile_bytecode.rs
- derive/src/lib.rs
- src/main.rs
- vm/pylib-crate/Cargo.toml
- vm/pylib-crate/src/lib.rs
- vm/src/lib.rs
This should make sure that even if installed from crates.io, rustpython has access to the python standard library,
and it also allows access to the stdlib even when `-I` is passed, since the lib location is a `./configure` option
in CPython rather than it always assuming that PYTHONPATH will be set.
> Use pylib as a dependency of the rustpython binary in order to get a Lib path

- derive/src/pyclass.rs
- vm/src/dictdatatype.rs
- vm/src/format.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/obj/objbool.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objfloat.rs
- vm/src/obj/objgetset.rs
- vm/src/obj/objint.rs
- vm/src/obj/objmappingproxy.rs
- vm/src/obj/objmemory.rs
- vm/src/obj/objnone.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtuple.rs
- vm/src/pyobject.rs
- vm/src/stdlib/array.rs
- vm/src/stdlib/csv.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/ssl.rs
- vm/src/stdlib/string.rs
- vm/src/sysmodule.rs
This separation removes a lot of unnessessary unwrapping.
> Separate IntoPyObject and IntoPyResult

- vm/src/exceptions.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/posixsubprocess.rs
- vm/src/stdlib/pwd.rs
- vm/src/stdlib/select.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/ssl.rs
- vm/src/stdlib/thread.rs
- vm/src/stdlib/winreg.rs
This trait make possible converting rust errors to python errors in idiomatic form.
I accidently mixed up a bit of os module edits but didn't fix the commits to be splited again. Let me know if i'd better to split them again.
> IntoPyException

- common/src/hash.rs
- vm/src/dictdatatype.rs
- vm/src/obj/objint.rs
- vm/src/obj/objstr.rs
- vm/src/vm.rs
Creating a new PR from #2035 due to crash.
Do anyone know why changing str hash function causes crash?
> DictKey for str shares same hash with PyString

- Lib/test/test_builtin.py
- common/src/hash.rs
In cpython, the hash values of str and bytes were the same, so the rustpython was modified the same.
> Fix problems with different hash values for str and bytes

- Lib/test/test_tuple.py
- vm/src/obj/objtuple.rs
Fix `objtuple.rs` `fn tp_new()` so that return cloned object when a parameter is tuple object.
```python
def test_constructors(self):
t0_3 = (0, 1, 2, 3)
t0_3_bis = tuple(t0_3)
self.assertTrue(t0_3 is t0_3_bis) # to pass this test
```
> Fix objtuple.tp_new so that return cloned when a parameter is tuple

- vm/src/obj/objstr.rs
- vm/src/stdlib/os.rs
This PR implements `os.execv` via MSVCRT's `_wexec`, which is used in CPython too.
> Implement os.execv on Windows

- Lib/test/test_module.py
- vm/src/obj/objmodule.rs
**Before**
- CPython 3.7.4
```python
>>> import sys
>>> ModuleType = type(sys)
>>> ModuleType.__new__(ModuleType)
<module '?'>
>>> ModuleType("new_module_name")
<module 'new_module_name'>
```
- RustPython
```python
>>>>> ModuleType.__new__(ModuleType)
TypeError: Expected at least 2 arguments (1 given)
>>>>> ModuleType("new_module_name")
<module 'new_module_name'>
```
**After**
- RustPython
```python
>>>>> ModuleType.__new__(ModuleType)
<module '?'>
>>>>> ModuleType("new_module_name")
<module 'new_module_name'>
```
> Fix module.__new__ to give uninitialized object.

- vm/src/stdlib/winreg.rs
https://docs.python.org/3.8/library/winreg.html#winreg.OpenKeyEx
It looks like it's just an alias for OpenKey.
> Add OpenKeyEx

- Lib/test/test_exceptions.py
- Lib/test/test_threadedtempfile.py
This patch allows running CPython tests fully on Windows. It doesn't fix failing tests yet.
> Disable certain CPython tests on Windows

- derive/src/pyclass.rs
- derive/src/pymodule.rs
- derive/src/util.rs
- vm/src/stdlib/dis.rs
- vm/src/stdlib/faulthandler.rs
- vm/src/stdlib/functools.rs
- vm/src/stdlib/json.rs
- vm/src/stdlib/keyword.rs
- vm/src/stdlib/marshal.rs
- vm/src/stdlib/multiprocessing.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/posixsubprocess.rs
- vm/src/stdlib/select.rs
- Fix duplicated attribute checker for pyclass/pymodule
- `pyattr` for values from const and calcaulated (from function)
- py* macro doesn't allow mismatched item type
- pymodule inject `__module__` field of member class
- `pyattr` can explicitly create attribute for `pyclass` in `pymodule`
- if function or method require similar work, it can be expanded.
- worked on a few modules with upper features
> Enhance pyclass/pymodule

- vm/src/obj/objint.rs
- vm/src/obj/objtuple.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
This make PyRef to be 0 cost, though I'm not sure how much that `expect()` in `PyRef::deref` was actually being optimized away.
> Make it a safety invariant that PyRef<T>.obj has a payload of T

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
Used `nix::unistd::execve` for execution.
Changes demonstrated at #2100 is applied for this execve as well.
I'm not quite sure whether the use of downcast() in the context is appropriate or not, but anyway it seems to work.
Any improvements or suggestions are welcome.
nix::unistd::execve 
https://docs.rs/nix/0.9.0/nix/unistd/fn.execve.html
Python3 os.execve 
https://docs.python.org/3/library/os.html#os.execve
```
cargo run -- -c 'import os;os.execve("/usr/bin/env", ["/usr/bin/env"], {"foo":"bar", "baz":"qux"})'
Finished dev [unoptimized + debuginfo] target(s) in 0.40s
Running `target/debug/rustpython -c 'import os;os.execve("/usr/bin/env", ["/usr/bin/env"], {"foo":"bar", "baz":"qux"})'`
foo=bar
baz=qux
```
Any null-embedded character throws ValueError
Overlapping codes in os.execv and …
> Implement os.execve for unix system

- vm/src/stdlib/itertools.rs
1) fix index error (refer to [CPython](https://github.com/python/cpython/blob/fa5d7251987c70a9c5d58b59a0b36ac9287eaafa/Modules/itertoolsmodule.c#L3258))
```
test_permutations (__main__.TestBasicOps) ... thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', vm/src/stdlib/itertools.rs:1420:42
```
2) fix overflow error in debug mode when r > n
> Fix index and overflow error in itertools

- vm/src/stdlib/os.rs
after merging #2101, test_os.py just crashes without any message. By examining test_execve_invalid_env, it turned out that the initial implementation does not throw ValueError when an equal character `=` exists in the environment variable name. This PR fixes this issue.
```
> cargo run Lib/test/test_os.py
Finished dev [unoptimized + debuginfo] target(s) in 21.27s
Running `target/debug/rustpython Lib/test/test_os.py`
.sssssssssssssssss.s.s..xs..sxxx.xssxs..x.s...xsss.sxxssxxssssssssssssssssssss....x.Tested current directory length: 872
.x.xxxx..s.xxs...ss.Traceback (most recent call last):
OverflowError: Int value cannot fit into Rust u32
x.s......ssssssssssssssssssssssssssss...sssxss....ss.s.....x.......x..s.sssssssss.sssxsssssssssssssxsxs...ssssssssssss …
```
> check '=' character in environment variable name in os.execve to pass test_os.py

- tests/snippets/builtin_complex.py
- vm/src/obj/objcomplex.rs
`Complex64::from_str()` was used to parse a complex number from a string, but its implementation is quite different from how python's complex() should work.
For example, it cannot parse `"(1+2j)"`, `"J"`, or `"1_000"` - it throws `ValueError`.
The new function `objcomplex::parse_str()` handles parentheses correctly, allows capital `J`, and uses `float_ops::parse_str()` to parse float numbers.
I copied some tests from `test_complex.py` into snippets and made them work.
> Implement objcomplex::parse_str() to replace Complex64::from_str()

- Lib/test/test_itertools.py
- vm/src/stdlib/itertools.rs
I fixed panic caused by attempt to subtract with overflow.
But `test_permutations` and `test_product_pickling` still have error at `self.pickletest`.
> Fix panic in itertools pruduct

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/cell.rs
- jit/Cargo.toml
- jit/src/instructions.rs
- jit/src/lib.rs
- tests/snippets/jit.py
- tests/test_snippets.py
- vm/Cargo.toml
- vm/src/obj/objfunction.rs
Proof of concept for a JIT(just in time) compiler, that compiles python functions down to native code.
This uses https://github.com/bytecodealliance/wasmtime/tree/main/cranelift to do the heavy lifting of generating the native code.
Currently this can successfully compile the following:
```python
def foo():
a = 9_223
return 10 + a
```
As a proof of concept, this has very limited functionality:
- only handles functions that take no arguments and return an integer
- only handles a very limited set of bytecodes
- aborts if operations overflow
> Proof of concept JIT compiler

- Lib/test/test_bytes.py
- vm/src/bytesinner.rs
Few changes were made to pass `test_constructor_type_errors`:
- Use the correct arguments: `[source[, encoding[, errors]]]`
- If either `encoding` or `errors` is present when `source` is NOT a string, raise `TypeError`
- If `encoding` is NOT present when `source` is a string, raise `TypeError`
- Do not allow iterable of non-ints
- `bytes(["0"])` should raise TypeError
- However, `objint::to_int` was used originally, allowing iterable of strings or floats as an argument
- `vm.extract_elements::<PyIntRef>(&obj)` uses `TryFromObject` internally, so only `int` objects are allowed now
> Handle TypeErrors in bytes() & bytearray()

- Cargo.lock
- Lib/test/test_builtin.py
- Lib/test/test_sort.py
- vm/Cargo.toml
- vm/src/builtins.rs
- vm/src/obj/objlist.rs
- vm/src/stdlib/random.rs
Closes #1072, closes #2151, and closes #578 
Timsort implementation in RustPython/rust-timsort, forked from notriddle/rust-timsort
> Stable sort

- vm/src/frame.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbytes.rs
- Use `payload_is` function
- Change some "as->to" conversions to "into" (may reduce unnecessary copying)
> Fix minor things

- .github/workflows/ci.yaml
- Cargo.lock
- README.md
- jit/Cargo.toml
- jit/src/instructions.rs
- jit/src/lib.rs
- tests/snippets/jit.py
This allows us to call the jitted functions based on a runtime computed signature, without having to enumerate all possible signatures.
> Use libffi to call jitted functions.

- Cargo.lock
- Lib/test/test_sys.py
- common/Cargo.toml
- common/src/hash.rs
- src/main.rs
- vm/src/bytesinner.rs
- vm/src/dictdatatype.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objstr.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/vm.rs
I didn't add test_hash b/c it expects strings are in the "unicodeobject" format, which is a union of `Vec<u8>|Vec<u16>|Vec<u32>`. Since that's not our actual internal string format, replicating it would require an allocation on every hash, which I felt was too heavy.
> Use siphash24 + PYTHONHASHSEED

- Lib/test/test_array.py
- tests/snippets/stdlib_array.py
- vm/src/stdlib/array.rs
I just cleared out the git commits, sorry I am new of doing the PR.
Maybe I had miss something but as my throught, At PyArray setitem() we can not just simply call something like self.borrow_value_mut().setitem_by_slice(obj) because if [self] is referring to the same object as [obj] than we can not borrow obj anymore as it is borrowed mut by [self].
The alternate is we have to check if [self] and [obj] is refering to the same object before we doing the borrow, if it is we clone our self otherwise we pass a ref to the next function. But I did not get any idea to do so, the [self] is &PyArray and the [obj] is PyObjectRef.
> Implement array setitem by slice

- vm/src/bytesinner.rs
Problems occur when byte values are 12, 14, and 15.
> Troubleshooting displaying bytes in the wrong hexadecimal number in certain cases.

- Lib/calendar.py
- Lib/test/test_calendar.py
- Update `calendar.py` from CPython 3.8.5
- Add `test_calendar.py`
- Skip `test_option_encoding` that caused error 
```
======================================================================
FAIL: test_option_encoding (__main__.CommandLineTestCase)
File "Lib/test/test_calendar.py", line 831, in test_option_encoding
stdout = self.run_ok('--encoding', 'utf-16-le', '2004')
File "Lib/test/test_calendar.py", line 794, in run_ok
return assert_python_ok('-m', 'calendar', *args)[1]
File "/home/clemado1/workspace/RustPython/vm/pylib-crate/Lib/test/support/script_helper.py", line 157, in assert_python_ok
return _assert_python(True, *args, **env_vars)
File …
```
> Update calendar.py and Add test_calendar.py from CPython 3.8.5

- Cargo.lock
- Lib/test/test_baseexception.py
- jit/src/instructions.rs
- jit/src/lib.rs
- tests/snippets/jit.py
- vm/Cargo.toml
- vm/src/builtins.rs
- vm/src/exceptions.rs
- vm/src/obj/objfunction.rs
- vm/src/obj/objfunction/jitfunc.rs
To jit functions that have arguments, the type of the arguments needs to be known when it's compiled. this PR uses the annotations to determine the type of the arguments.
> Support arguments in jitted functions

- vm/src/builtins.rs
- vm/src/function.rs
- vm/src/pystr.rs
The reference of `Fn` object also implements `Fn`.
Passing refs will solve the ownership problem with recursive calls, so the `Checker` struct can be removed.
> Pass function refs to single_or_tuple_any

- vm/src/obj/objint.rs
- vm/src/pyobject.rs
- vm/src/stdlib/array.rs
`PyValue::into_object` was first introduced here: https://github.com/RustPython/RustPython/pull/2079
It was originally intended to be used in `into_ref_with_type`.
However, the definition of `PyValue` has changed, and `into_object` is not used anywhere.
I also renamed `into_simple_object` to `into_object`
> Remove PyValue::into_object & Rename PyValue::into_simple_object to PyValue::into_object

- vm/src/stdlib/os.rs
The error message was lazily copy-pasted when i implemented it. this PR fixes the typos
> Fix error message typo at execve

- DEVELOPMENT.md
autoconf, automake, and libtool are required as an external dependencies on macOS.
This PR adds the guide at DEVELOPMENT.md
After Rust update, I've experienced errors regarding the compilation of [libffi-sys](https://crates.io/crates/libffi-sys), and after some trial and error, installing automake and libtool solved the problem for me.
> Add macOS development requirements.

- .github/workflows/ci.yaml
Fairly recently we removed passing `--all` when running clippy/tests on CI as the wasm crate can't handle be compiled with the threading feature, but that caused rust tests that aren't in the root crate to not be run on CI.
Split from #2187 
cc @coolreader18
> Run tests/clippy on all crates

- vm/src/builtins.rs
- vm/src/lib.rs
- vm/src/macros.rs
- vm/src/obj/objtype.rs
- vm/src/obj/objweakref.rs
- vm/src/pyobject.rs
- vm/src/pyobjectrc.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/weakref.rs
- vm/src/sysmodule.rs
- vm/src/types.rs
- vm/src/vm.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
Split `__del__` unrelated part from #2128 
this patch will be base of any kind of drop implementation
> PyObjectRc: thin wrapper for PyObjectRef inner Rc

- wasm/notebook/package.json
- wasm/notebook/src/index.ejs
- wasm/notebook/src/index.js
- wasm/notebook/src/style.css
- wasm/notebook/webpack.config.js
This PR is for a new example under the `wasm` directory. Inspired by iodide, a Mozilla Project https://alpha.iodide.io/ (now abandoned).
This example re-uses the code from `wasm/demo` and adds a basic import code functionality from `api.github.com`
Here is how it looks like:
Here is how the import works:
Here are the url for test imports (can be anything public as long as it uses the github api url):
https://api.github.com/repos/RustPython/RustPython/contents/wasm/demo/snippets/asyncbrowser.py
https://api.github.com/repos/RustPython/RustPython/contents/wasm/demo/snippets/fetch.py
Here is how the notebook looks like after fetching
Then code execution 
Changes:
- Removed xterm
- Changed the output from a text area to an HTML element (so later on, I can toy with adding markdown, graphs or …
> new wasm example: notebook inspired by alpha.iodide.io

- Cargo.lock
- derive/Cargo.toml
- derive/src/compile_bytecode.rs
- derive/src/lib.rs
- examples/freeze/main.rs
- examples/mini_repl.rs
- jit/Cargo.toml
- jit/src/lib.rs
- jit/tests/common.rs
- jit/tests/float_tests.rs
- jit/tests/int_tests.rs
- jit/tests/lib.rs
- jit/tests/misc_tests.rs
- vm/pylib-crate/src/lib.rs
- vm/src/frozen.rs
- vm/src/obj/objfunction.rs
- wasm/lib/src/browser_module.rs
This add a test utility macro `jit_function`, which allows declaring jitted python functions inside rust test functions. Example:
```rust
let add = jit_function! { add(a:i64, b:i64) -> i64 => r##"
def add(a: int, b: int):
return a + b
"## };
```
The above define the python function `add`, which is compiled to bytecode at compile time. That bytecode is then jitted into native code at runtime(we could also do this a compile time in the future). The return value of the macro is a lambda with the signature `fn(i64, i64) -> i64`.
As part of that I refactored `py_compile_bytecode` into two different macros `py_compile` and `py_freeze`.
> Add Jit integration tests

- vm/src/pyobject.rs
it will not make any actual difference but it makes more sense.
ture_value and false_value also is PyIntRef
> int_cache_pool holds PyIntRef instaed of PyObjectRef

- Lib/test/test_dict.py
- common/src/cell.rs
- vm/src/dictdatatype.rs
- vm/src/obj/objdict.rs
- vm/src/obj/objset.rs
```
❯ hyperfine -L X norm,opt './rustpython-{X} pystone.py 50000'    
Benchmark #1: ./rustpython-norm pystone.py 50000
Time (mean ± σ):     14.349 s ±  0.561 s    [User: 14.295 s, System: 0.010 s]
Range (min … max):   13.580 s … 14.982 s    10 runs
Benchmark #2: ./rustpython-opt pystone.py 50000
Time (mean ± σ):     9.385 s ±  0.193 s    [User: 9.308 s, System: 0.016 s]
Range (min … max):   8.986 s … 9.623 s    10 runs
Summary
'./rustpython-opt pystone.py 50000' ran
1.53 ± 0.06 times faster than './rustpython-norm pystone.py 50000'
```
Based on this python version of the data structure (ran through lib2to3): https://code.activestate.com/recipes/578375/
I chose pystone to benchmark this because there aren't many stdlib or even builtins calls, it's just loops, `Load`/`StoreName`s, and …
> Make dict repr more efficient (50% faster!)

- derive/src/pystructseq.rs
- vm/src/exceptions.rs
- vm/src/obj/objbytearray.rs
- vm/src/obj/objbytes.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objrange.rs
- vm/src/obj/objsequence.rs
- vm/src/obj/objtuple.rs
- vm/src/obj/objtype.rs
- vm/src/pyobject.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/pystruct.rs
- Reuse empty tuple singleton
- Remove typecheck from objsequence::get_item
- tuple internal uses `Box<[PyObjectRef]>` instead of vec
> tuple optimization

- wasm/notebook/package.json
- wasm/notebook/src/index.ejs
- wasm/notebook/src/index.js
- wasm/notebook/src/parser.js
- wasm/notebook/src/sample.txt
- wasm/notebook/src/style.css
- wasm/notebook/webpack.config.js
This PR is to add features onto the rustpython notebook.
You can still run pure python code there, but now there is the **option** to divide your content and add markdown and math blocks. There is a sample on `sample.txt` in this repo.
Here is a math block and how it renders.
Here is a sample python code ;p 
Code blocks are marked by `%%` + `keyword`. 
I re-used the parser code from iodide. It is on [this link](https://github.com/iodide-project/iodide/blob/master/src/editor/iomd-tools/iomd-parser.js).
The parser takes the content of the code editor and can look for any keyword. It returns an object with the different chunks, each chunk has these properties.
```json
{
"chunkContent": "\nprint(\"Javascript called. It wants its DOM elements back.\")\n",
"chunkType": "py",
"chunkId": …
```
> rustpython notebook, add markdown and math support

- Cargo.lock
- Lib/json/__init__.py
- Lib/json/decoder.py
- vm/Cargo.toml
- vm/src/stdlib/mod.rs
- vm/src/stdlib/serde_json.rs
I made it optional because there were like 25 errors for `test_json` when using
serde_json, so I think it's best to apply it specifically for when there's a
lot of json data, e.g. importing altair which loads the vega schema, or maybe
for the `custom_text_test_runner`, if that still takes a really long time to
`json.dump`
> Make serde_json an optional optimization for the json module

- wasm/demo/src/index.ejs
I couldn't find full documentation for the browser module anywhere where users could be pointed at but was able to scratch up some basic functionality by reading the related python and Rust code as well as using using `dir(browser)` in the RustPython demo.
Need for this came from the fact that I was running scripts that used the builtin `input()` function. Browsers don't have `stdin` that could be plugged in nicely to support `input()` command but I was able to monkey patch it in the end with:
```
import browser
input = browser.prompt
```
which worked just fine with my use cases. Just documenting the fact that the module exists can already save good amount of time from others.
> Document browser module availability in WASM Demo 

- derive/src/util.rs
I got this when I did:
```rust
#[pyattr]
use super::foo::BAR as BAZ;
```
So I think it makes sense not to panic here
> Don't panic on #[pyattr] use foo::bar::baz;

- derive/src/from_args.rs
- derive/src/pymodule.rs
- vm/src/anystr.rs
- vm/src/builtins.rs
- vm/src/bytesinner.rs
- vm/src/function.rs
- vm/src/obj/objcomplex.rs
- vm/src/obj/objint.rs
- vm/src/obj/objlist.rs
- vm/src/obj/objproperty.rs
- vm/src/obj/objstr.rs
- vm/src/stdlib/binascii.rs
- vm/src/stdlib/collections.rs
- vm/src/stdlib/faulthandler.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/math.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/posixsubprocess.rs
- vm/src/stdlib/pystruct.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/ssl.rs
- vm/src/stdlib/thread.rs
- vm/src/stdlib/warnings.rs
- vm/src/stdlib/winapi.rs
- vm/src/stdlib/zlib.rs
- wasm/lib/src/browser_module.rs
- wasm/lib/src/js_module.rs
I don't think the `FromArgOptional` trait is the perfect solution to combining
`optional` and `default`, but I think it's ok.
> Make the FromArgs derive less verbose

- bytecode/src/bytecode.rs
This is so that a frozen module tree can be represented as a single bytestring, specifically for [`RustPython/pyckitup`](https://github.com/RustPython/pyckitup)
> Add derive(Serialize, Deserialize) to FrozenModule

- Cargo.lock
- derive/src/pyclass.rs
- vm/src/builtins/mod.rs
- vm/src/exceptions.rs
- vm/src/function.rs
- vm/src/stdlib/os.rs
- wasm/lib/Cargo.toml
- wasm/lib/src/browser.py
- wasm/lib/src/browser_module.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/js_module.rs
cc @phorward
Main relevant changes:
- Move `Promise` to the `_js` module
- Rename `JsValue`/`JsError` to `JSValue`/`JSError` to fit with Python naming conventions
- If an exception bubbles up to js and it's a `JSError`, throw the jsvalue inside it
- `browser.jsclosure -> JSClosure`
```py
class JSClosure:
value: Optional[JSValue]
destroyed: bool
detached: bool
destroy(self)
detach(self) -> JSValue
```
`JSClosure.destroy()` decreases the refcount of the inner python function that gets called, and makes the js function uncallable. `JSValue.detach()` makes it so the inner function never gets dropped. If anyone has any API critiques, I'd love to hear them; I'm not really sure if having `destroyed` and `detached` completely orthogonal to each other is the best way to do things.
> Update the browser module

- Lib/stat.py
stat.py of CPython 3.8 is same with the latest.
stat.py of CPython 3.7 slightly differ with CPython 3.8.
This change removes stat module from whats_left.sh result.
> Update stat.py with CPython 3.8 version

- .github/workflows/ci.yaml
- vm/src/stdlib/socket.rs
Fixes #2241
As I said on the issue:
> std::net::ToSocketAddrs does its job. host: "localhost" result: Ok(IntoIter([[::1]:5555, 127.0.0.1:5555]))
> Then get_addr() just reads the first one (which is IPv6 on my system).
> -> We then pass this IPv6 address to an IPv4 socket <-
> So get_addr() just need to be aware of PySocket::family and to filter incompatible IPs
I'm not a fan of `IpAddrFmt` but it's the cleanest way I found to do this.
I also removed `RUSTPYTHON_NO_IPV6` since it's no longer necessary :)
> socket: resolve addresses according to socket family (ipv4/6)

- extra_tests/snippets/floats.py
- vm/src/format.rs
Before this change, format(1e16) returns '10000000000000000.0' in RustPython while CPython 3.7 returns '1e+16'.
After this change, format(1e16) returns '1e+16' in RustPython too.
> Fix default format(float) result when the number is too big

- Lib/test/test_struct.py
- vm/src/stdlib/array.rs
- vm/src/stdlib/pystruct.rs
This is sort of a big lump change, and there aren't necessarily tests to prove it, since there aren't any tests in `test_struct.py` that verify the native ordering -- even though there's padding now and correct alignment/size, the tests that I unskipped aren't related to that :disappointed: . Still, I think this is cleaner then it was before; there's an enum for the codes now, and finding the `pack()` function for a code is a bit cleaner now and respects endianness/architecture
> Update pystruct + array

- common/src/lock/cell_lock.rs
- vm/src/builtins/bytearray.rs
- vm/src/builtins/bytes.rs
- vm/src/builtins/memory.rs
- vm/src/byteslike.rs
- vm/src/stdlib/array.rs
- vm/src/stdlib/io.rs
@qingshi163 could you take a look at this?
`rustpython` built without threading was panicking with `deadlock: tried to upgradably+sharedly lock a CellRwLock twice` in `ByteArray::get_options()`. The changes in memory.rs are because I thought it was a legit deadlock but it turned out to just be a type in `cell_lock.rs`, and I made the Buffer type for bytearray a separate type that stores the options directly in it, to avoid some overhead with the RwLock inside of `PyByteArray`
> Fix cell_lock, remove the RwLock<BufferOptions> from bytearray

- Lib/test/test_builtin.py
- Lib/test/test_complex.py
- vm/src/builtins/complex.rs
- vm/src/builtins/float.rs
I forgot to fully change some functions when I refactored the math. This just resolves some obvious bugs - python overflow semantics are very inconsistent.
> Fix float power and complex division

- vm/src/stdlib/os.rs
Use oct number like in CPython fileutils.c instead of decimal number leading zero. (e.g.: 0666 -> 0o666)
> Fix os.stat().st_mode error in windows

- .github/workflows/ci.yaml
- Cargo.lock
- vm/Cargo.toml
- vm/src/builtins/code.rs
- vm/src/builtins/dict.rs
- vm/src/builtins/object.rs
- vm/src/builtins/pystr.rs
- vm/src/builtins/pytype.rs
- vm/src/builtins/weakref.rs
- vm/src/bytesinner.rs
- vm/src/pyobject.rs
- vm/src/pyobjectrc.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/pystruct.rs
- vm/src/stdlib/weakref.rs
- vm/src/sysmodule.rs
- vm/src/types.rs
You can see a lot of the rationale for this in the comment at the top of `pyobjectrc.rs`. Here's the benchmark info:
```
Benchmark #1: ./rustpython-norm benchmarks/pystone.py 50000
Time (mean ± σ):      6.282 s ±  0.198 s    [User: 6.247 s, System: 0.016 s]
Range (min … max):    5.911 s …  6.542 s    10 runs
Benchmark #2: ./rustpython-opt benchmarks/pystone.py 50000
Time (mean ± σ):      4.887 s ±  0.171 s    [User: 4.866 s, System: 0.008 s]
Range (min … max):    4.687 s …  5.283 s    10 runs
Summary
'./rustpython-opt benchmarks/pystone.py 50000' ran
1.29 ± 0.06 times faster than './rustpython-norm benchmarks/pystone.py 50000'
```
> Manually implement a vtable for PyObjectRef

- ast/src/location.rs
- parser/src/fstring.rs
Since we are already adding parentheses, we don't need to trim(), this also improves location information for `f'{  b  }`!
> PEP 498 compatibility: parenthesized expressions for f-strings

- src/lib.rs
- src/main.rs
A possible replacement for native extension modules for the moment.
> Give the `rustpython` crate a library component

- wasm/notebook/src/index.ejs
- wasm/notebook/src/style.css
This PR adds responsive layout to `wasm/notebook` on phone and ipad/tablets.
The notebook looked decent/good on phone and iPad (especially when the iPad is flipped horizontally).  Since I think those devices would be mostly used for reading code, not writing it, imho the layout is good enough for now (It can be better on phones tho). 
Here are some screenshots from tests on real devices. There is a problem with Chrome on Android (will open an issue).
needs fixing, will create an issue.
> wasm/notebook: mobile and tablet responsive layout

- Cargo.lock
- bytecode/Cargo.toml
- bytecode/src/bytecode.rs
- compiler/Cargo.toml
- compiler/src/compile.rs
- compiler/src/error.rs
- compiler/src/lib.rs
- jit/src/instructions.rs
- jit/tests/common.rs
- src/lib.rs
- vm/src/builtins/frame.rs
- vm/src/builtins/module.rs
- vm/src/builtins/object.rs
- vm/src/builtins/pystr.rs
- vm/src/builtins/traceback.rs
- vm/src/builtins/tuple.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/import.rs
- vm/src/pyobject.rs
- vm/src/pyobjectrc.rs
- vm/src/vm.rs
This reduces the size of the Instruction enum from 56 bytes to 16 bytes, which should help with memory usage as well as a (very) slight performance boost:
```
Benchmark #1: ./rustpython-norm benchmarks/pystone.py 50000
Time (mean ± σ):      3.655 s ±  0.119 s    [User: 3.637 s, System: 0.007 s]
Range (min … max):    3.522 s …  3.853 s    10 runs
Benchmark #2: ./rustpython-opt benchmarks/pystone.py 50000
Time (mean ± σ):      3.624 s ±  0.074 s    [User: 3.601 s, System: 0.008 s]
Range (min … max):    3.557 s …  3.783 s    10 runs
Summary
'./rustpython-opt benchmarks/pystone.py 50000' ran
1.01 ± 0.04 times faster than './rustpython-norm benchmarks/pystone.py 50000'
```
The instructions I changed were either a) flattening an inner enum, like `CallFunction { CallType } -> …
> Optimize the size of Instruction

- vm/src/builtins/make_module.rs
> Arguments to builtin.compile() can be named

- extra_tests/generator/not_impl_modules_footer.txt
I was wondering why `whats_left` says the entire `collections` module isn't implemented yet. It's because both `libdir` and `name` are `bytes`, when you format them into a string, you get a invalid path with `b''` in it.
> Fix whats_new.sh not finding libraries that are directories

- Lib/site.py
- Lib/sysconfig.py
- Lib/test/test_builtin.py
- Lib/test/test_pow.py
- README.md
- derive/src/from_args.rs
- extra_tests/snippets/math_basics.py
- vm/src/builtins/int.rs
- vm/src/builtins/make_module.rs
- vm/src/stdlib/sysconfigdata.rs
- vm/src/sysmodule.rs
- vm/src/version.rs
- wasm/lib/README.md
Python 3.5 is pretty old at this point, and I think we generally try to keep up with the latest features (e.g. assignment expression, self-documenting fstrings), so I think it makes sense to say we're 3.9. I put 3.8 in the READMEs because I don't think we have full 3.9 compatibility yet and 3.8 is more used, but I'm not really sure if that makes a difference :shrug:
> Declare ourselves as Python 3.9

- bytecode/src/lib.rs
- derive/src/compile_bytecode.rs
- examples/freeze/main.rs
- vm/pylib-crate/src/lib.rs
- vm/src/frozen.rs
- vm/src/vm.rs
So instead of `hashmap! { "a" => decode(b"....."), "b" => decode(b"......") }`, it's just `decode(b"<map>")`
release binary sizes:
|        | default | freeze-stdlib |
| :----- | ------: | ------------: |
| master | 18296   | 29908         |
| libmap | 18292   | 24832         |
My hunch on this was that putting all the data in the same buffer gives lz4 more opportunity to deduplicate, and I'm pretty sure that's what made the difference in binary size.
> Serialize entire frozen hashmap to bytes

- common/src/float_ops.rs
- extra_tests/snippets/strings.py
The previous implementation truncated all decimal powers of 10.0 below 1 million (by default) to 1, because it cut away any
combination of trailing 0's and .'s. 
(Powers of 10.0 beginning with 1000000.0 are formatted to an exponential format and thus not affected by the bug.)
My fix now checks whether the number string to truncate represents a floating point value at all and if that is the case, truncation stops at the decimal point.
(The check whether there is a decimal point in the string to truncate is necessary as `format!("{:.*}", precision, magnitude)` with `precision==0` does return strings without a decimal point; truncating those is fatal)
> Fix formatting of decimal powers below 1 million

- .github/workflows/cron-ci.yaml
This PR fixes #2400.
I added a new job that runs the `whats_left.sh` script 
```bash
chmod +x ./whats_left.sh
./whats_left.sh > whats_left.temp
```
Then after cloning the website and cd-ing into it, it does:
``` bash
git clone git@github.com:RustPython/rustpython.github.io.git website
cd website
[ -f ./_data/whats_left.temp ] && cp ./_data/whats_left.temp ./_data/whats_left_lastrun.temp
cp ../whats_left.temp ./_data/whats_left.temp
git add ./_data/whats_left_lastrun.temp
git add ./_data/whats_left.temp
```
which translates to:
- check if website/_data/whats_left.temp exits (on the first run it won't)
- make a copy of that to a "lastrun" file
- the goal is to have the last run and the what's left now, so we can do a diff then show what has been recently finished (kind of a basic "tada"-log …
> add a github workflow to save whats left to the website repo

- Cargo.lock
- wasm/lib/Cargo.toml
- wasm/lib/src/lib.rs
- wasm/lib/src/vm_class.rs
cc @satyajeetkolhapure
To add your own modules, you should make your own crate that depends on
```toml
[lib]
crate-type = ["cdylib", "rlib"]
rustpython_wasm = { git = "https://github.com/RustPython/RustPython", branch = "wasm-hooks" }
rustpython_vm = { git = "https://github.com/RustPython/RustPython", branch = "wasm-hooks" }
wasm-bindgen = "0.2"
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```
Then your lib.rs should look like:
```rust
pub use rustpython_wasm::exports::*;
use wasm_bindgen::prelude::*;
use rustpython_vm::VirtualMachine;
#[wasm_bindgen(start)]
fn init() {
rustpython_wasm::add_init_func(init_vm);
}
fn init_vm(vm: &mut VirtualMachine) {
vm.add_frozen(rustpython_vm::py_freeze!(dir = "deps"));
}
```
`deps/` should be a directory next to your Cargo.toml, with a …
> Add a way to inject modules to rustpython_wasm

- Cargo.lock
- vm/Cargo.toml
- vm/src/builtins/memory.rs
- vm/src/py_io.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/select.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/zlib.rs
This gets basic `requests` functionality working:
```sh
$ mkdir deps
$ pip install -t deps requests
<snip>
$ cd deps
$ rustpython
```
```py
>>>>> import requests
>>>>> res = requests.get("http://httpbin.org/get")
>>>>> res.json()
{'args': {}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.25.1', 'X-Amzn-Trace-Id': 'Root=1-600ce51d-187d27d01dae14c54f63f539'}, 'origin': '99.104.70.102', 'url': 'http://httpbin.org/get'}
```
I spent a lot of time debugging this, but I think the key thing that stopped it from hanging forever in `SocketIO.readinto` was fixing `_io` to use `as_contiguous` instead of `obj_bytes`, which wasn't taking the range of a memoryview into account, as well as changing a `>` to a `>=` in `_io`.
> Fix BufferedReader over a SocketIO to properly read the right amount

- vm/src/pyobject.rs
On CPython `import os; print(os.stat('.'))` will print 
```
os.stat_result(st_mode=16877, st_ino=11403492, st_dev=64769, st_nlink=69, st_uid=1001, st_gid=1001, st_size=4096, st_atime=1612956818, st_mtime=1612952241, st_ctime=1612952241)
```
and on RustPython
```
os.stat_result(st_mode: 16893, st_ino: 4277, st_dev: 64769, st_nlink: 22, st_uid: 1001, st_gid: 1001, st_size: 4096, __st_atime_int: 1612992970, __st_mtime_int: 1612816814, __st_ctime_int: 1612816814, st_atime: 1612992970.2450392, st_mtime: 1612816814.5084808, st_ctime: 1612816814.5084808, st_atime_ns: 1612992970245039341, st_mtime_ns: 1612816814508480761, st_ctime_ns: 1612816814508480761)
```
Is this formatting used for some other object?
> format PyStructSequence with = instead of :

- Lib/test/test_pathlib.py
- Lib/test/test_platform.py
- Lib/test/test_py_compile.py
- Lib/test/test_random.py
- Lib/test/test_set.py
- Lib/test/test_slice.py
- Lib/test/test_tuple.py
- Lib/test/test_types.py
- Lib/test/test_unicode.py
- Lib/test/test_unicode_file.py
- Lib/test/test_unicode_file_functions.py
- Lib/test/test_unicode_identifiers.py
- Lib/test/test_unicodedata.py
- Lib/test/test_zlib.py
I grep'd the codebase for this regular expression: `@unittest\.skip.[\"']TODO: RUSTPYTHON[^ :;,]`, and ran every test that was associated with it. If it errored, I put the error in the skip reason. Otherwise, I un-skipped it. (This was initially tested on Manjaro, so some breakage on Windows and macOS is to be expected. That's why I'm initially marking this as draft.)
> Cleanup skipped tests

- extra_tests/not_impl_gen.py
because of #2410 checking them adds a lot of noise
> Skip checking builtin signatures in whats_left

- Lib/test/test_posix.py
- bytecode/src/lib.rs
- compiler/src/ir.rs
- vm/src/stdlib/os.rs
Implement `os.getgrouplist`.
Ref #1175 
Looks like we don't have [test_posix.py](https://github.com/python/cpython/blob/49926cf/Lib/test/test_posix.py) to check `os.getgrouplist`. Do we want to copy it from `CPython`?
> Implement os.getgrouplist

- .github/workflows/ci.yaml
- jit/src/lib.rs
- src/lib.rs
- vm/src/lib.rs
- wasm/lib/src/convert.rs
- wasm/lib/src/vm_class.rs
See rust-lang/rust-clippy#6726
> Allow clippy::unnecessary_wraps lint, and rename "to_js" to "into_js"

- vm/src/stdlib/signal.rs
`swap` seems to be pretty slow, it took 5.66% of the time in my microbenchmarks. After the optimization, `check_signals` would only take 0.29% of the time. (from flamegraph).
> Optimize check_signals

- Lib/test/test_math.py
- vm/src/stdlib/math.rs
Previously the `math.floor` and `math.ceil` functions did not work on subclasses of `float` or on types that implemented the `__float__` method. This change brings the `floor` and `ceil` implementations closer to the [cpython](https://github.com/python/cpython/blob/0837f99d3367ecf200033bbddfa05d061ae9f483/Modules/mathmodule.c#L1194) [versions](https://github.com/python/cpython/blob/0837f99d3367ecf200033bbddfa05d061ae9f483/Modules/mathmodule.c#L1257).
> Fix `math.floor` and `math.ceil` functions to match cpython behavior

- vm/src/frame.rs
```
Benchmark #1: ./rustpython-norm benchmarks/pystone.py
Time (mean ± σ):      2.794 s ±  0.160 s    [User: 2.783 s, System: 0.006 s]
Range (min … max):    2.597 s …  3.056 s    10 runs
Benchmark #2: ./rustpython-opt benchmarks/pystone.py
Time (mean ± σ):      2.749 s ±  0.103 s    [User: 2.738 s, System: 0.005 s]
Range (min … max):    2.577 s …  2.897 s    10 runs
Summary
'./rustpython-opt benchmarks/pystone.py' ran
1.02 ± 0.07 times faster than './rustpython-norm benchmarks/pystone.py'
```
cc @pca006132
> Don't use atomics as much for lasti

- Lib/test/test_itertools.py
- vm/src/stdlib/itertools.rs
I make `itertools.accumulate` follow the latest signature `itertools.accumulate(iterable[, func, *, initial=None])`, and split the tests on `accumulate` into two parts.
Now, only `pickletest`s fail.
```
test_accumulate (__main__.TestBasicOps) ... ok
test_accumulate_pickle (__main__.TestBasicOps) ... expected failure
```
> Follow the latest `itertools` module

- vm/src/builtins/pytype.rs
- vm/src/function.rs
- vm/src/vm.rs
This would improve the performance for method calls a bit:
Microbenchmark:
```python
s = 0
for i in range(1000000):
s += 1
```
Result:
```
Benchmark #1: ./rustpython-master test.py
Time (mean ± σ):     870.1 ms ±   8.1 ms    [User: 867.4 ms, System: 2.5 ms]
Range (min … max):   858.6 ms … 884.0 ms    10 runs
Benchmark #2: ./rustpython-opt test.py
Time (mean ± σ):     857.7 ms ±   7.1 ms    [User: 853.8 ms, System: 3.3 ms]
Range (min … max):   841.8 ms … 866.0 ms    10 runs
Summary
'./rustpython-opt test.py' ran
1.01 ± 0.01 times faster than './rustpython-master test.py'
------
Benchmark #1: ./rustpython-master-nothreading test.py
Time (mean ± σ):     520.8 ms ±   6.6 ms    [User: 517.9 ms, System: 2.7 ms]
Range (min … max):   512.6 ms … 530.6 ms    10 runs
Benchmark #2: …
```
> Optimize method call performance

- .github/workflows/cron-ci.yaml
I noticed that the GitHub action for pushing `whats_left.sh` data to the website repo is broken.
I switched to using git add -A instead and I updated the commit message.
> fix github action for what is left data

- Cargo.lock
- Cargo.toml
- src/shell/helper.rs
- vm/Cargo.toml
- vm/src/readline.rs
Fixes [the parsing of multiple lines into the REPL](https://github.com/RustPython/RustPython/issues/2406).
Updates RustyLine to version 8.0.0 and turns off [bracketed paste](https://docs.rs/rustyline/8.0.0/rustyline/config/struct.Builder.html#method.bracketed_paste) to do so. The respective test is currently marked as ignored due to an [issue ](https://github.com/kkawakam/rustyline/issues/504)with RustyLine.
> 2406 parse multiple lines REPL

- Lib/test/test_fileio.py
- Lib/test/test_with.py
- bytecode/src/lib.rs
- compiler/src/compile.rs
- compiler/src/ir.rs
- vm/src/builtins/builtinfunc.rs
- vm/src/builtins/function.rs
- vm/src/builtins/getset.rs
- vm/src/builtins/iter.rs
- vm/src/builtins/make_module.rs
- vm/src/builtins/object.rs
- vm/src/builtins/property.rs
- vm/src/builtins/pytype.rs
- vm/src/builtins/weakproxy.rs
- vm/src/cformat.rs
- vm/src/format.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/macros.rs
- vm/src/pyobject.rs
- vm/src/pyobjectrc.rs
- vm/src/slots.rs
- vm/src/stdlib/io.rs
- vm/src/stdlib/thread.rs
- vm/src/vm.rs
Sort of a follow-up to #2476
Benchmarks (without `threading`):
```
Benchmark #1: ./rustpython-norm benchmarks/pystone.py
Time (mean ± σ):      2.699 s ±  0.124 s    [User: 2.678 s, System: 0.004 s]
Range (min … max):    2.452 s …  2.870 s    10 runs
Benchmark #2: ./rustpython-opt benchmarks/pystone.py
Time (mean ± σ):      2.366 s ±  0.120 s    [User: 2.349 s, System: 0.007 s]
Range (min … max):    2.141 s …  2.581 s    10 runs
Summary
'./rustpython-opt benchmarks/pystone.py' ran
1.14 ± 0.08 times faster than './rustpython-norm benchmarks/pystone.py'
```
> Add optimized method lookup to avoid creating intermediate method objects

- .github/workflows/cron-ci.yaml
The first half of #2396:
- run benchmarks
- restructure the folders and rename the generated SVG's to simplify displaying them
- upload/commit the generated data to [RustPython/rustpython.github.io](https://github.com/RustPython/rustpython.github.io)
The second half (actually displaying the data) will be implemented in [RustPython/rustpython.github.io](https://github.com/RustPython/rustpython.github.io).
I considered moving the `restructure generated files` 'run' to a separate script file to add some comments, but I decided that that was not 'worth' the extra file. Be sure to let me know if people have a different opinion on this.
The for loop renames files as follows: `./execution/mandelbrot.py/report/violin.svg` -> `./execution/mandelbrot.py.svg`.
> Run benchmarks in CI

- Lib/test/support/script_helper.py
Before this patch, you need to set PYTHONHOME to run the test suite.
Now it will automatically detect whether you need environment for your interpreter.
> Add os in detect requires environment script

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
This PR would like to add support for `os.fwalk` which need 
`{open, stat} <= supports_dir_fd and {listdir, stat} <= supports_fd` 
So I add support for dir_fd and fd for each functions.
In listdir, I use same approach as make_path to add support_fd.
Noted that, test coverage doesn't increase due to the lack of 3rd argument in `os.symlink`.
> os: Add support for fd and dir_fd in `listdir`, `stat`, `fstat`

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
From [python doc](https://docs.python.org/3/library/os.html?highlight=os%20symlink#os.symlink),
`os.symlink(src, dst, target_is_directory=False, *, dir_fd=None)`
which means that `target_is_directory` is a positional argument.
> Fix os.symlink 3rd argument

- vm/src/stdlib/os.rs
Add `os.getloadavg()` by using [systemstat](https://github.com/unrelentingtech/systemstat)
> os: add getloadavg

- Lib/test/test_py_compile.py
I don't know if this has to do with the operating system or the architecture. Does anyone have an Intel Mac running Big Sur that can test this patch's effectiveness?
> Add extra check in test_py_compile for Big Sur and/or Apple Silicon

- Cargo.lock
- derive/src/from_args.rs
- derive/src/pystructseq.rs
- vm/build.rs
- vm/src/byteslike.rs
- vm/src/lib.rs
- vm/src/macros.rs
- vm/src/pyobject.rs
- vm/src/stdlib/fcntl.rs
- vm/src/stdlib/mod.rs
- vm/src/stdlib/os.rs
- vm/src/stdlib/pwd.rs
- vm/src/stdlib/resource.rs
- vm/src/stdlib/select.rs
- vm/src/stdlib/signal.rs
- vm/src/stdlib/socket.rs
- vm/src/stdlib/sysconfigdata.rs
- vm/src/stdlib/termios.rs
- vm/src/stdlib/time_module.rs
- vm/src/sysmodule.rs
- vm/src/vm.rs
Now IPython fully works:
```
$ rustpython -m pip install ipython
$ rustpython -m IPython
/home/coolreader18/.local/lib/rustpython3.9/site-packages/IPython/core/history.py:226: UserWarning: IPython History requires SQLite, your history will not be saved
warn("IPython History requires SQLite, your history will not be saved")
Python 3.9.0alpha (heads/coolreader18/moduless-dirty:3f79daf1, Apr 15 2021, 09:45:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: x = 1
In [2]: x
Out[2]: 1
In [3]: import color
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[... skipping hidden 1 frame] …
```
> Add some os-related modules and improve stdlib_inits

- Lib/test/test_optparse.py
This tests a module that has been [deprecated since Python 3.2](https://www.python.org/dev/peps/pep-0389/#deprecation-of-optparse). However, it's still in the standard library as of CPython 3.8.
> Add test_optparse from CPython 3.8

- vm/src/stdlib/os.rs
> os: Put `UtimeArgs` behind cfg gate

- Lib/test/test_os.py
- vm/src/stdlib/io.rs
- vm/src/stdlib/os.rs
Following code used to fail due to the way used to define
os.open in rust. To fix this, we need to use `FromArgs`
to define `struct OpenArgs {...}`.
```
f = os.open(path=__file__, flags=os.O_RDONLY, mode=0o777, dir_fd=None)
```
Noted that the original `open` is now rename to `rust_open`
and is also exported. The only usage of `rust_open` is only in `io.rs`.
> os: Fix `open` keyword arguments

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
Pass `FileTests.test_symlink_keywords` in `test_os.py`
> os: symlink use `FromArgs` for arguments

- .github/workflows/ci.yaml
This PR will incrementally determine exactly which tests must be skipped on the macOS CI run. Submitting as draft until everything is narrowed down.
> Unskip more macOS tests in CI

- compiler/src/symboltable.rs
- parser/src/lexer.rs
- vm/src/builtins/complex.rs
- vm/src/builtins/dict.rs
- vm/src/builtins/function.rs
- vm/src/frame.rs
- vm/src/function.rs
- vm/src/py_serde.rs
- vm/src/pyobject.rs
- vm/src/stdlib/itertools.rs
- vm/src/stdlib/ssl.rs
Clippy warnings fixed:
- [`inconsistent_struct_constructor`](https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor)
- [`manual_flatten`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_flatten)
- [`manual_map`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_map)
> Fix Clippy warnings introduced in Rust 1.52

- Lib/test/test_subprocess.py
As observed in #2652, various tests failed around the time when #2645 and #2647 were both merged into the master branch. Submitting this as draft because I can't reproduce the `test_os` failure on my machine.
> Fix CI failures with test_subprocess and/or test_os

- Lib/test/test_os.py
- Lib/test/test_pathlib.py
- vm/src/stdlib/os.rs
Change `perform_on_metadata` to fit python document and tests.
From [`os.DirEntry.is_dir()`](https://docs.python.org/3/library/os.html?highlight=direntry#os.DirEntry.is_dir)
> Return True if this entry is a directory or a symbolic link pointing to a directory;
> return False if the entry is or points to any other kind of file, or if it doesn’t exist anymore.
> ...
> This method can raise OSError, such as PermissionError, but FileNotFoundError is caught and not raised.
> os: Fix `DirEntry` is_file and is_dir function

- Lib/test/test_os.py
- Lib/test/test_posix.py
- vm/src/stdlib/os.rs
From `listdir(path)` to `listdir(path='.')`
> os: argument in listdir should be optional

- Lib/test/test_bisect.py
Kept the same structure (as also described in [PEP 399](https://www.python.org/dev/peps/pep-0399/)) in order to easily be able to plug in a future rust implementation of bisect.
No changes other than removing statements dealing with the C accelerator module (and importing module directly for now). All tests locally pass.
> Add tests file for the bisect module.

- vm/src/macros.rs
Wrong values passed for `__name__` and `__module__` for functions built with `named_function`.
> Fix arguments passed to make_funcdef.

- vm/src/builtins/builtinfunc.rs
Note a discrepancy: in the [Reference manual](https://docs.python.org/3/reference/datamodel.html), it is stated that `__self__` for builtins should return `None`. This is what I've currently done.
On the other hand, `CPython` currently returns the module the function is defined in. 
If the module is to be returned, what's the best way to do it? Yank it from the `globals` using the module name?
> Add `builtin.__self__`.

- Lib/dbm/__init__.py
- Lib/dbm/dumb.py
- Lib/test/test_dbm.py
- Lib/test/test_dbm_dumb.py
just the Python implementation. `_dbm` and `_gdbm` will have to be re-implemented in Rust
> Add dbm from CPython 3.8

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
Make openpty return non-inheritable file descriptors
> os: Fix openpty test

- Lib/test/test_operator.py
- vm/src/iterator.rs
- vm/src/stdlib/operator.rs
Essentially, by making `length_hint` take a `default` argument instead of returning an `Option`.
> Handle NotImplemented return from length_hint.

- vm/src/builtins/function.rs
Fix small mistake. Bound methods of builtins (which still don't have `__qualname__` set) were repr'ed with `?` because of this.
CPython differentiates between bound methods for Python classes and bound methods for builtins and the `repr` for one uses `__qualname__` while for the other `__name__`. Doubt this discrepancy is of much concern, though.
> Fallback to __name__ if __qualname__ isn't available.

- Lib/test/test_range.py
- vm/src/builtins/range.rs
which caused the test failure.
> Fix miscalculation when reversing a range.

- Lib/test/test_os.py
- vm/src/stdlib/os.rs
1. `lstat` support `dir_fd` parameter
2. Change error message for fspath to match unittest
> Fix tests in os

- Lib/test/test_builtin.py
- vm/src/builtins/singletons.rs
`__new__` simply returns the singleton. While `bool(NotImplemented)` already returned `True`, it is added since it will need to raise a warning in the future.
> Add new and bool for NotImplemented.

- vm/src/builtins/tuple.rs
The `empty_tuple` was currently only returned if an empty tuple was created with literal syntax (via the `BuildTuple` instruction) or if passed explicitly to `tuple` i.e `tuple(())`. This PR makes `tuple(iterable)`, where `iterable` is empty, also return `empty_tuple`.
> Make tuple(empty_iterable) return empty_tuple

- Lib/test/test_builtin.py
- vm/src/builtins/make_module.rs
`vars` raises a `TypeError` if `__dict__` doesn't exist on the supplied object.
> Fix test_vars in test_builtins.

- Lib/test/test_range.py
- vm/src/builtins/range.rs
In short:
1. Added fallback for when item isn't found via `index/count/contains`, iterate through the range and invoke `__eq__` with every element.
2. Contains has a fast lane only for exact ints. Subclasses should fall back to normal slow iteration described in 1.
3. Use similar logic as cpython/ironpython when calculating new start,stop,step in `__reverse__`. There's some corner cases current approach doesn't cover. (see `reversed(range(-2, -1, -3))` for an example)
4. `is_empty` just invokes `length`.
All in all, 5 more tests should now pass.
> Fix a number of range issues.

- Lib/operator.py
- Lib/test/test_operator.py
There was an inconsistent implementation issue between C and Python versions from CPython.
The regression did not happen until the CPython user doesn't use _operator module.
But since RustPython only uses pure Python implementation, the implementation should be updated.
ref: https://bugs.python.org/issue44558
> Lib: Update operator.py to follow CPython's implementation

- Cargo.lock
- vm/Cargo.toml
- vm/src/stdlib/os.rs
Implement pathconf and fpathconf using libc::pathconf.
os.pathconf_names is not implemented.
> os: Implement (f)pathconf

- Lib/test/test_posix.py
- vm/src/stdlib/os.rs
`getgroups` is already implement in rust, just wrap the function to let it be used in python.
> os: Implement getgroups

- vm/src/stdlib/os.rs
On musl-libc-based targets, libc::copy_file_range is not provided, but libc::syscall and libc::SYS_copy_file_range are supported. This pull request use them instead of libc::copy_file_range.
> Change `os.rs` to build on musl libc

- extra_tests/not_impl_gen.py
In this PR I simply modified the `not_impl_gen.py` script to ignore all of the modules listed in [PEP 594](https://www.python.org/dev/peps/pep-0594/#deprecated-modules) as "dead batteries". While that PEP is still a draft, some form of it is likely to be accepted eventually.
My main intention here was to just take some things off the TODO list that are probably less important. This change takes 11 modules off the list and a total of 74 items (in terms of lines of output). Of course there are still ~2760 items left. :joy: 
This is just a suggestion! This change doesn't preclude implementing these modules--indeed some of the modules on the list are already implemented. But I don't think people should invest too much time or effort in fixing or maintaining code that isn't being maintained in …
> Suggestion: remove PEP 594 "dead batteries" from whats_left.sh

- Lib/test/test_set.py
- vm/src/builtins/set.rs
- vm/src/pyobject.rs
This covers creating an empty frozenset through Python code. Modules implemented in rust could still use `from_iter` (as `ssl` does) and end up with an empty frozenset which isn't the singleton.
> Make `frozenset(empty_iterable)` return a singleton.

- Lib/test/test_iter.py
- Lib/test/test_iterlen.py
- Lib/test/test_list.py
- vm/src/builtins/iter.rs
- vm/src/builtins/list.rs
An iterator should be able to know when it has been exhausted. Certain iterations through the iterator and pickling currently require this, a number of test cases could be fixed.
The approach uses an `AtomicCell` as was done in `PyCallableIterator`, it just packages the cases in an enum to make it publicly available. If any other approaches seem better, please share!
Minimal application of it, if the changes are agreeable, I can add PRs for the other types.
> Fix iteration issues, pickling by marking iterators as exhausted.

- Lib/test/test_math.py
- vm/src/stdlib/math.rs
Matches CPython behavior.
For example, `math.exp(1e6)` raises `OverflowError` in cpython, but the previous RustPython implementation just returned `inf`.
> math: raise OverflowError when result is infinite

- vm/src/stdlib/os.rs
Most recent PR removed the `TryFromObject` implementation for `CString` which was used in another PR that was added before it. This uses `PyStrRef` to do the same thing and should fix the error.
> Fix failure -- use PyStrRef to extract String.

- Cargo.lock
- Lib/plistlib.py
- Lib/test/test_platform.py
- Lib/test/test_pyexpat.py
- vm/Cargo.toml
- vm/src/stdlib/mod.rs
- vm/src/stdlib/pyexpat.rs
Many python libraries, for example `plistlib`, use `expat` to parse xml.
This is a very initial implementation for the `pyexpat` module using `xml-rs` as the actual xml parser. 
This fixes `plistlib`, which allows running `platform.mac_ver()` - now we can install pip on Macs!
I would like to get some feedback about this before I add more error handling and other missing features.
> Initial implementation of pyexpat

- Lib/test/test_iter.py
- Lib/test/test_iterlen.py
- Lib/test/test_tuple.py
- vm/src/builtins/tuple.rs
Fixes a couple of issues with `tuple` iterator by adding these methods.
> Add __length_hint__, __setstate__, __reduce__ for tuple iterator.

- DEVELOPMENT.md
(the old link leads to a 404 page)
> Fix LALRPOP book link in development guide

- Lib/test/test_itertools.py
- vm/src/stdlib/itertools.rs
Specifically:
- an implementation of `repr`.
- an implementation for `reduce`
- a fix for the arguments, namely, allowing named arguments for `object` and `times`
- fixing `length_hint` to return `TypeError` if `times` is missing, that way `operator.length_hint` returns a default.
> Add fixes for itertools.repeat

- Lib/test/test_itertools.py
- vm/src/stdlib/itertools.rs
Fixes test for `islice` and also un-blocks doctest for `itertools` to finally be able to run. Also fixes acceptable values for `start`, `step` and `stop` to be in the range `0 <= value <= sys.maxsize` when they previously were in range `0 <= value <= usize::MAX`.
> Fix arguments for islice. 3 args are allowed.

- Lib/test/list_tests.py
- Lib/test/test_bytes.py
- vm/src/builtins/bytearray.rs
- vm/src/builtins/bytes.rs
- vm/src/builtins/list.rs
- vm/src/builtins/pystr.rs
- vm/src/builtins/tuple.rs
- vm/src/bytesinner.rs
- vm/src/sliceable.rs
This pull request adds the following changes:
- Refactors owner_type argument in PySliceableSequence's indexing functions into a separate PySliceableSequenceOwner trait
- Makes setitem tests in list_tests.py, test_bytes.py files work
> Refactor sequence owner name into trait

- extra_tests/not_impl_gen.py
As I (very slowly) progress toward making an actual contribution, I wanted to propose a tweak to `whats_left.sh`. In its current form, the script uses `dir` to crawl the modules and this means that there is some redundant output from items defined somewhere else. A big culprit is `__loader__` (see #2732) but there are others. In total this shaves 388 (redundant) lines from the output. The `missing_items` and `mismatched_items` go down but I think that was because they overcounted before.
Another thing I noticed in the output is that for some entries, RustPython is actually _better_ than the CPython implementation. Many of the entries in `operator` have a signature, where the CPython version returns `None`. I'm not sure it makes sense to include those in the output but that's a separate …
> Use inspect.getmodule to prevent redundant output in whats_left.sh

- extra_tests/not_impl_gen.py
In #2760 I introduced a regression. Sometimes RustPython will have an object defined in a different module from the one CPython defines it in. This is probably fine (implementations can be different) as long as the code is working (which this script doesn't test anyway).
For example, CPython's `posix` module defines its own `chdir`, `cpu_count`, etc. In RustPython the implementations are coming from `os.py` (maybe actually in `os.rs`?). Or for instance, CPython `sys.stderr` has no module defined (`getmodule` returns `None`) but RustPython will return `_io`. In these cases I think we'd want to count those as implemented, even though the code location is different.
So, this just adds an option `keep_other` to the scanning code. When in CPython, the script only keeps members from the module …
> Further tweaking whats_left: allow differing implementation

- extra_tests/snippets/builtin_type.py
- vm/src/builtins/builtinfunc.rs
- vm/src/builtins/pytype.rs
Previously `type.__module__` was returning `<getset descriptor>`.
It happend because this code:
```rust
#[pyproperty(magic)]
fn module(&self, vm: &VirtualMachine) -> PyObjectRef {
// TODO: Implement getting the actual module a builtin type is from
self.attributes
.read()
.get("__module__")
.cloned()
.unwrap_or_else(|| vm.ctx.new_str("builtins"))
}
```
was able to find `__module__` in `self.attributes`. But, it was the method `#[pyproperty(magic)] fn module` definition itself.
The same happened to `__qualname__` as well.
I've added a simple test to ensure that it is now correct.
Closes #2310
> Fixes `type.__module__` issue, refs #2310

- vm/src/stdlib/io.rs
For some reason I was having an error from `clippy` locally:
It was quite annoying, so I have fixed it:
> Fixes clippy on macos

- .github/workflows/ci.yaml
- .github/workflows/cron-ci.yaml
- Updates `actions/setup-python`
- Uses `v2` instead of `master` for `actions/checkout`
All other versions are fine 👍
> GitHub Actions housekeeping

- Lib/test/list_tests.py
- Lib/test/test_set.py
- vm/src/builtins/dict.rs
- vm/src/builtins/list.rs
- vm/src/builtins/set.rs
This moves the initialization from the arguments into `__init__`. `dict` already did this, this just fixes the behavior for `list` and `set`.
> Initialize with init for mutable builtins.

- vm/src/slots.rs
This pull request resolves #2800 by fixing the message format of the error raised by `hash` built-in function.
After this pull request, the message will have compatibility with CPython implementation and will have more rich information about error. 😎 
You can check the changes by executing below lines at [the current master branch commit](https://github.com/RustPython/RustPython/commit/53b8067acd1af79c2081e9eb56586fa8955749fd) and [this pull request HEAD commit](https://github.com/RustPython/RustPython/commits/fcfc15778d5937b7626ac39d2239a9eabfb85769).
```python
hash(dict())
hash(set())
```
> Fix unhashable type error message

- Lib/test/test_keyword.py
- vm/src/stdlib/keyword.rs
there was one todo in test_keyword.py
before: s was PyStrRef, it failed to handle None
after: convert s to PyObjectRef and add None check
> add iskeyword None check
